### ISSUE TITLE
Socket.io warnings

### ISSUE THREAD

**Issue by 0x80** [chentsulin/electron-react-boilerplate#10]
I'm seeing all these warnings. And they also appear in the browser console. Any idea what's causing this? I think this is just the develop branch, not the master...

WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/bufferutil in /Users/me/Development/myapp/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib
 @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js 8:19-57

WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/bufferutil in /Users/me/Development/myapp/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib
 @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js 10:19-57

WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/validation in /Users/me/Development/myapp/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib
 @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js 8:19-57

WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/validation in /Users/me/Development/myapp/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib
 @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js 10:19-57
webpack: bundle is now VALID.

**Comment by chentsulin** [comment]
There are some problem with `webpack-dev-server` 1.8 and `ws`, I will update it to fix this.

**Comment by 0x80** [comment]
:+1:

**Comment by chentsulin** [comment]
It seems that `wepback-dev-server` rely on a old verion `ws` v0.4.31 and it has some try catch code in `BufferUtil.js` to let it works for somehow.

```js
try {
  module.exports = require('../build/Release/bufferutil');
} catch (e) { try {
  module.exports = require('../build/default/bufferutil');
} catch (e) { try {
  module.exports = require('./BufferUtil.fallback');
} catch (e) {
  console.error('bufferutil.node seems to not have been built. Run npm install.');
  throw e;
}}}
```

In my opinion, maybe it's not a issue, just a warning because this try catch flow usage.

**Comment by chentsulin** [comment]
I finally figure out this is a issue with webpack `target: 'atom'` and `engine.io-client`, and it breaks react-hot now.

See Automattic/engine.io-client#376, webpack-dev-server#191

**Comment by 0x80** [comment]
thanks for investigating!

**Comment by asfktz** [comment]
it is possible to disable react hot somehow until it fixed?

**Comment by chentsulin** [comment]
`webpack --watch` with `npm start` will works. But should refresh manually using `Cmd + R`.

**Comment by haustraliaer** [comment]
Hmmm I'd honestly rather have some warnings flash up than forego hot reloading... is this an option? Or do you think the issue will be resolved quite soon?

Or perhaps I can just use an older release of this boilerplate?

**Comment by chentsulin** [comment]
Hot reload should be fixed in 0.2.9.

But using target `web` maybe not be a good enough solution. Let's keep tracing issues between webpack and socket.io here.

**Comment by t1mmen** [comment]
@chentsulin, I overwrote my 0.2.8 `make-webpack-config.js` with the one from 0.2.9, but I'm getting the following error:

```
[19438:0817/122219:INFO:CONSOLE(744)] "Uncaught TypeError: Cannot read property '_currentElement' of null", source: webpack:///./~/react/lib/ReactCompositeComponent.js? (744)
```

Reverting back to the old `make-webpack-config.js` makes the error go away. Ideas?

**Comment by chentsulin** [comment]
"Uncaught TypeError: Cannot read property '_currentElement' of null"

It's most likely a React issue or issue with react-hot-load. And not everything in flux is hot-reloadable, so sometime you should do a full refresh in your  browser.

**Comment by haustraliaer** [comment]
I got it working again by using:

```
npm run hot-dev-server
HOT=1 electron .
```
I had to remove `NODE_ENV=development` from the start command.

**Comment by chentsulin** [comment]
close via #35
