### ISSUE TITLE
IDEA: CLI tool

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1000]
Would be nice if we could have some kind of CLI tool that can:

- [ ] Install the boilerplate
- [ ] Perform upgrades/migration
- [ ] Simple code mods (flow => typescript migration)

(these are just ideas. feel free to comment your own ideas)

**Comment by akshaygarg834** [comment]
For CLI commander js can be used.
[https://github.com/tj/commander.js](url)

But how ? In main or renderer process ? Would it work after packaging ?

**Comment by amilajack** [comment]
This would be an npm package

**Comment by develar** [comment]
@amilajack Consider to use [electron-webpack](https://github.com/electron-userland/electron-webpack) under the hood. electron-vue will soon move to electron-webpack for easy update. e.g. there is preset https://www.npmjs.com/package/electron-webpack-vue and this project can also move all code from user project to some preset like `electron-webpack-react`.
