### ISSUE TITLE
Text Editor Not Appearing In Chromium Window

### ISSUE THREAD

**Issue by Superraptor** [chentsulin/electron-react-boilerplate#1006]
Sorry for posting again, but I'm having trouble again on my Windows 10 machine and there really isn't an error that I can see this time... Essentially after running `npm run hot-updates-server` and `npm run start-hot-renderer` concurrently, the following window pops up:

![image](https://cloud.githubusercontent.com/assets/8202717/26337240/5764a7c0-3f45-11e7-86e5-9e9600b10ae5.png)

From tutorials and other images I have seen, shouldn't there be like a text editor of some sort in the window? I'm sure this is because I forgot to install something, but I'm not sure what exactly... Any help much appreciated! Thanks!

**Comment by amilajack** [comment]
Click on the x on the top right. Those are the developer tools.

**Comment by Superraptor** [comment]
Okay... I did that and now it's just empty:

![image](https://cloud.githubusercontent.com/assets/8202717/26337383/3d4ad7b4-3f46-11e7-94f6-e45d8226f2ed.png)

**Comment by amilajack** [comment]
>  shouldn't there be like a text editor of some sort in the window?

Click the two arrows that look like `>>` and you should see a `sources` option. Click that. I would recommend going over some devtool tutorials.

**Comment by Superraptor** [comment]
Thanks for the quick responses! I looked over the `sources` options, but couldn't find anything that looked like the text editor I saw in the tutorial at https://blog.jscrambler.com/building-expense-application-electron-react/

I'm basically looking for the black text editor in between the dev tools and the viewer (below right is picture as shown on the website and below left is what I get when running it as it is currently installed).

![image](https://cloud.githubusercontent.com/assets/8202717/26337648/1e8f79a4-3f48-11e7-89b3-2445fc169059.png)

**Comment by amilajack** [comment]
Ohh I see. That screenshot is outdated. Redux dev tools come in a new tab. Look for the redux tab after clicking the `>>` button

**Comment by amilajack** [comment]
<img width="1078" alt="screen shot 2017-05-22 at 8 59 59 pm" src="https://cloud.githubusercontent.com/assets/6374832/26337987/a32dfb66-3f31-11e7-9930-304bdebe17d5.png">

**Comment by Superraptor** [comment]
YES YES YES! Works perfectly! Thank you so much!!!!
