### ISSUE TITLE
builder win-x64 .msi

### ISSUE THREAD

**Issue by Mrxdh** [chentsulin/electron-react-boilerplate#1013]
current config
`build : {
   "win": {
      "target": [
        "nsis"
      ]
    }
}`

but i set config

`build : {
   "win": {
          "title": "My awesome app",
          "version": "2.28.999.1",
          "noMsi": false,
          "msi": true,
          "authors": "Author"
        }
  }`
        
hint

`Error: Config is invalid:
{
  "win": [
    {
      "noMsi": "Unknown option",
      "iconUrl": "Unknown option",
      "title": "Unknown option",
      "version": "Unknown option",
      "publisher": "Unknown option"
    },
    "Invalid option object"
  ]
}
    at /Users/xiedonghao/Developer/git/kuban-desktop/node_modules/electron-builder/src/util/readPackageJson.ts:153:11`

**Comment by amilajack** [comment]
Your electron-builder config is incorrect. See the electron-builder docs to correct this

**Comment by Mrxdh** [comment]
How do I generate .msi programs, examples?        current version

**Comment by amilajack** [comment]
Here's the [docs](https://github.com/electron-userland/electron-builder/wiki/Options) for the electron-builder options. I should note that msi is deprecated in favor of nsis. The default config is optimal.

**Comment by Mrxdh** [comment]
oh，Thank You （= v =）
