### ISSUE TITLE
Modals PR offer

### ISSUE THREAD

**Issue by mtompkins** [chentsulin/electron-react-boilerplate#1017]
Modals with React / Electron can be a challenge when you don't want to break the React schema, especially if you need to have many of them in a Line-of-Business app.
Modals with React / Redux can be even harder... throw Thunk in the mix and until you get comfortable you can really endure some pain.

I've "extended" the base boilerplate with a Modal approach and I am happy to offer you a PR if you'd like to include it in your boilerplate. If so, lmk and I'll fork, include it and offer a PR.

**Comment by amilajack** [comment]
Would be nice if you could show a small example of what this PR brings. I'm not 100% sure what you mean just yet.

**Comment by mtompkins** [comment]
https://github.com/mtompkins/WIP.git

**Comment by amilajack** [comment]
I think it would be better if you could abstract those components to a separate library and then we should add a guide on adding integration with the separate library
