### ISSUE TITLE
Download with axios not working.

### ISSUE THREAD

**Issue by akshaygarg834** [chentsulin/electron-react-boilerplate#1021]
```js
axios({
  method:'get',
  url:'http://bit.ly/2mTM3nY',
  responseType:'stream'
})
.then(function(response) {
  response.data.pipe(fs.createWriteStream('ada_lovelace.jpg'))
});
```

[https://github.com/mzabriskie/axios#axiosrequestconfig](url)

This is the example for downloading a file using axios. (See the URL)
Not working in electron but works perfectly on separately on simple js file. Using this in electron shows this 

The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType.
xhr.js:177 XHR finished loading: GET "http://bit.ly/2mTM3nY".
SignIn.js?d9b0:124 Uncaught (in promise) TypeError: response.data.pipe is not a function

**Comment by amilajack** [comment]
Just made an [example for you](https://github.com/amilajack/erb-axios-example) that shows using axios with electron-react-boilerplate.

See this commit for all the changes made to the boilerplate to add axios.

**Comment by akshaygarg834** [comment]
In example you gave you just add axios as dependency and put that example in index.js.
In my project I did same thing in different file. It still shows this error.

The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType.
xhr.js:177 XHR finished loading: GET "http://bit.ly/2mTM3nY".
SignIn.js?d9b0:124 Uncaught (in promise) TypeError: response.data.pipe is not a function

**Comment by amilajack** [comment]
Can you show the whole stack trace? That would be helpful

**Comment by akshaygarg834** [comment]
[Violation] Avoid using document.write().
dev-server.js:49 [HMR] Waiting for update signal from WDS...
only-dev-server.js:66 [HMR] Waiting for update signal from WDS...
index.js:11 console.trace
./app/index.js @ index.js:11
__webpack_require__ @ bootstrap 398c9fc…:659
fn @ bootstrap 398c9fc…:85
20 @ bundle.js:17147
__webpack_require__ @ bootstrap 398c9fc…:659
(anonymous) @ bootstrap 398c9fc…:708
(anonymous) @ bootstrap 398c9fc…:708
xhr.js:138 The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType.
dispatchXhrRequest @ xhr.js:138
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
xhr.js:177 XHR finished loading: GET "http://bit.ly/2mTM3nY".
dispatchXhrRequest @ xhr.js:177
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
index.js:9 Uncaught (in promise) TypeError: response.data.pipe is not a function
    at index.js:9
    at <anonymous>
(anonymous) @ index.js:9
client?e4ca:41 [WDS] Hot Module Replacement enabled.

**Comment by amilajack** [comment]
Are you importing axios from the renderer process?

**Comment by akshaygarg834** [comment]
Yupp ! In index.js only i did import.

**Comment by amilajack** [comment]
I see. The main process does not have access to the DOM so you will not be able to use any XHR-based API. [Do this instead](https://github.com/mzabriskie/axios/pull/234#issuecomment-212735740).
