### ISSUE TITLE
Flow rasies "Required module not found" error

### ISSUE THREAD

**Issue by talha131** [chentsulin/electron-react-boilerplate#1024]
I get this error when using material-ui. material-ui library works fine otherwise. It's just the flow that raises this error.

To reproduce, clone this repository. Add material-ui to `./package.json`. Here is a snippet from mine

```json
  "dependencies": {
    "electron-debug": "^1.1.0",
    "font-awesome": "^4.7.0",
    "history": "^4.6.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-hot-loader": "3.0.0-beta.6",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0",
    "material-ui": "^0.17.0",
    "react-bootstrap-table": "^3.3.7",
    "source-map-support": "^0.4.15"
  },
```

Add this line to `Counter.js`

```js
import AppBar from 'material-ui/AppBar';
```

If flow is enabled, it will produce following error,

> file: 'file:///Users/talha/Repos/electron-react-boilerplate/app/components/Counter.js'
severity: 'Error'
message: 'material-ui/AppBar (Required module not found)'
at: '4,20'
source: 'flow'

<img width="693" alt="screen shot 2017-05-29 at 17 00 13" src="https://cloud.githubusercontent.com/assets/1094724/26549526/e91a8d54-4492-11e7-9eee-dd12969d169b.png">

Perhaps `.flowconfig` needs some tweaking. Any idea how can I fix this error?

**Comment by talha131** [comment]
I added this line to my `.flowconfig` and it fixed the issue

```js
declare module 'material-ui' {
   declare var exports: 'material-ui';
}
```

Got answer from [here](https://stackoverflow.com/a/39454079/177116).

Still it would be great if @amilajack can shed some light on it.

Also, if this tip is added to Readme it will definitely help beginners like me.

**Comment by amilajack** [comment]
@talha131 Not every module has flow definitions. In cases where flow requires definitions and they cannot be found, it throws an error. The only way to get around this is to add the `declare module` lines to the `flow-typed` dir. [See this](https://github.com/chentsulin/electron-react-boilerplate/tree/master/flow-typed) as an example

**Comment by talha131** [comment]
Thanks a lot @amilajack. This fixed the issue. 

For anyone else, facing same or similar issue. I added `./flow-typed/material-ui_vx.x.x.js`. Then I wrote in the file

```js
declare module 'material-ui' {
  declare module.exports: any;
}

declare module 'material-ui/AppBar' {
  declare module.exports: any;
}

declare module 'material-ui/CircularProgress' {
  declare module.exports: any;
}

declare module 'material-ui/Subheader' {
  declare module.exports: any;
}

declare module 'material-ui/RaisedButton' {
  declare module.exports: any;
}
```

You have to declare sub-modules separately.

**Comment by OutThisLife** [comment]
Can also do this in flowconfig:

```
[ignore]
.*/node_modules/(?!(styled-components|react|next|memory-cache|next-routes|prop-types|webpack|redux|express))/*.
```
