### ISSUE TITLE
Sample for using different windows / dialogs

### ISSUE THREAD

**Issue by derwaldgeist** [chentsulin/electron-react-boilerplate#1026]
First of all: thanks for this great boilerplate. Tought me a lot about how to setup an Electron app with React.

However, I am missing a sample for using this in combination with separate browser windows that have to communicate with with the main process via IPC. In my case, I am implementing an options dialog. In plain vanilla Electron this means that the dialog has its own HTML, CSS and JavaScript files. How does this work in combination with Webpack? Does the "one bundle output" still make sense, and how have things to be strung together to make a multi-window / multi-process app work?

I have to admit that I am somewhat new to Webpack and the complexity of the boilerplate already caused me some headaches to understand. :-)

**Comment by amilajack** [comment]
I'll get around to making a simple fork of the boilerplate demoing this.

**Comment by derwaldgeist** [comment]
@amilajack That would be awesome! Thanks.

**Comment by Slapbox** [comment]
@derwaldgeist I believe the first thing you need to do is add the files you need to the `files` array in your top level package.json. For example I played around with an `auth.html` window.

That should get it packaged when you build for production in my experience.

```
    "files": [
      "dist/",
      "includes/",
      "node_modules/",
      "app.html",
      "auth.html",
      "main.js",
      "main.js.map",
      "package.json"
    ],
```


**Then in your main.development.js:**

```
ipcMain.on('auth-window', (arg) => {
  createNewAuthWindow();
});

function createNewAuthWindow() {
authWindow = new BrowserWindow({
    show: true,
    width: 400,
    height: 560,
    resizable: false,
    frame: true,
    skipTaskbar: false,
    alwaysOnTop: true,
    useContentSize: false,
    webPreferences: {
      zoomFactor: 1,
      allowRunningInsecureContent: false,
      nodeIntegration: true,
    }
  });

  authWindow.loadURL(`file://${__dirname}/auth.html`);
  
}
```

Hope this helps!

**Comment by derwaldgeist** [comment]
Thanks for sharing this. Will look into it!

**Comment by Slapbox** [comment]
You're welcome! Let me know how it goes! If it doesn't work for you I'll poke around to see if I missed a piece.

**Comment by Telemakhos** [comment]
Did you guys have success with this?

**Comment by Slapbox** [comment]
Yes I'm doing it with the method I laid out above.

No one has reported back if this works for them. There is not question that my solution works. The only question is, did I post every piece of it up here.

If someone could report back regarding their success or failure to implement it would be helpful to everyone reading. I'll figure out what I missed if people have trouble.

This works though. I am using it. Works in production too, at least as of 40 days ago. I haven't updated the boilerplate recently, but I imagine this still works and will continue to work.

**Comment by mtompkins** [comment]
If a demo is ever constructed to demonstrate the above, it would also be great if consideration were given on how to create a BrowserWindow from the renderer side so that it packages properly (e.g. an invisible window that does CPU intensive calc's so as not to lock the main or primary renderer threads).

**Comment by amilajack** [comment]
@derwaldgeist [responded](https://github.com/chentsulin/electron-react-boilerplate/issues/1095#issuecomment-311227831) to https://github.com/chentsulin/electron-react-boilerplate/issues/1095. Would recommend looking at it
