### ISSUE TITLE
Add additional loader fails

### ISSUE THREAD

**Issue by mtompkins** [chentsulin/electron-react-boilerplate#1029]
(This could quite easily be me ..)
Added `raw-loader` to the boilerplate so I can handle `.pem` certificate files.
Inline, the following works:
`import cCA from 'raw-loader!../certs/ca-cert.pem';`

So I tried to move handling it to webpack config as:
`webpack.config.base.js`

```js
...
module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          cacheDirectory: true
        }
      }
    },
    // Add PEM handling
    {
      test: /\.pem?$/,
      exclude: /node_modules/,
      use: {
        loader: 'raw-loader'
      },
    }
    ]
  },
...

```
However, this doesn't work resulting in: 
_... You may need an appropriate loader to handle this file type._

Thanks for any help.

**Comment by amilajack** [comment]
Just a guess: try adding the [module-bind](https://github.com/webpack-contrib/raw-loader#cli) in your package.json npm script for the `start-renderer-dev` and `build-renderer` scripts (I'm assuming that this is the renderer process that you're importing from)

**Comment by mtompkins** [comment]
Thank you for the thoughts.

Is the approach not to make changes to the `webpack.config.base.js` but to do it at the effective CLI call as you've referenced in the boilerplate? My understanding is you either use one or the other.

**Comment by amilajack** [comment]
Make the changes in the CLI npm script in the `package.json`, not the webpack config itself

**Comment by mtompkins** [comment]
OK Thanks. If that's the case I'll continue to inline the loader.

**Comment by praveen-zluri** [comment]
@amilajack When adding `--module-bind json-loader` or `--module-bind js=json-loader` to the `start:renderer` script, the webpack-cli throws: `[webpack-cli] Error: Unknown option '--module-bind'`.

Basically, my requirement is that I want to use json-loader but I also have secrets.json, queries.json which I want to exclude. Is there any way to acheive this?
