### ISSUE TITLE
npm run start-hot not working on Windows 10

### ISSUE THREAD

**Issue by timc3** [chentsulin/electron-react-boilerplate#103]
When running the `npm run start-hot` it shows the Welcome to Electron screen telling me where to execute my code.

**Comment by neighborhood999** [comment]
hey @timc3！you can try `set HOT=1 && set NODE_ENV=development && electron .`

**Comment by jhen0409** [comment]
@neighborhood999 the cross-platform env should be work by #100.

@timc3 I run `start-hot` is worked on Windows 7, no Welcome to Electron screen. Maybe the `.` path is not work on Windows 10? but I haven't machine of Windows 10. :\

**Comment by neighborhood999** [comment]
@jhen0409 Sorry. I misunderstanding timc3 problem！
yesterday, I got this error message:
```
...
fs.js:585
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
...
```
then, i asked C.T.Lin, it's solved.

**Comment by WMeldon** [comment]
For whatever reason, changing the command to ```"command": "electron ./"``` was what fixed this for me.

**Comment by timc3** [comment]
WMeldon actually has the solution (though I did upgrade all my devDependancies). Works on both OS X and Windows 10.

**Comment by Semigradsky** [comment]
The same issue on Windows 10. Maybe update the README or package.json?

**Comment by Chandu** [comment]
@WMeldon : +1.  Your solution works for me (Windows 10).

**Comment by Smurf-IV** [comment]
Now appears to be broekn in Windows 8.1
```
D:\electron-react-boilerplate-master>npm run start-hot

> electron-react-boilerplate@0.7.1 start-hot D:\electron-react-boilerplate-maste
r
> cross-env HOT=1 NODE_ENV=development electron ./

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\electron-react-boilerplate-ma
ster\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
etc...
```

**Comment by chentsulin** [comment]
Reinstall packages maybe solve your problem
```
rm -rf node_modules
npm install
```

**Comment by luistest** [comment]
@chentsulin Your soulution works for me.
