### ISSUE TITLE
cannot use babel-core function in main process (production mode)

### ISSUE THREAD

**Issue by rsaccon** [chentsulin/electron-react-boilerplate#1030]
I am using a babel-core function in the main process, (for the purpose of turning external  .jsx files into .js files), this works fine in development mode, but with the packaged app I get the following error:

```
Uncaught Exception:
ReferenceError: Unknown plugin "transform-react-jsx" specified in "base" at 0, attempted to resolve relative to "/"
    at 
...
```

how can i make sure that `babel-core` module dependency is also fulfilled in the packaged app ?

My current code (simplified):
```
import { transform } from 'babel-core';
...
const outJS = transform(inJSX, {
  plugins: ['transform-react-jsx']
}).code;
...
```

**Comment by amilajack** [comment]
You can move all the `babel-*` devDeps to deps in `./package.json`.

If that doesn't work, try [changing this line](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.main.prod.js#L16) to be:

```js
entry: ['babel-core', 'babel-polyfill', './app/main.dev'],
```

**Comment by rsaccon** [comment]
OK, thanks, well, it looks like my problem is somewhere else, the build process throws some exceptions `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` (but then still continues to package the app).

**Comment by amilajack** [comment]
That means that the node heap doesn't have enough memory. Run node with the flag `--max_old_space_size=4096` to allocate 4GB to the heap

**Comment by rsaccon** [comment]
oh yeah, now things look better, thanks a lot again
