### ISSUE TITLE
IDEA: I would like to make a todo list app as a default example, using react apollo

### ISSUE THREAD

**Issue by erick2014** [chentsulin/electron-react-boilerplate#1032]
The idea is to implement a simple todo app using react, redux and react apollo, in order to fetch data from a graphql server. This will be used by new incomers as starter example

**Comment by amilajack** [comment]
What is react appolo?

**Comment by erick2014** [comment]
@amilajack http://dev.apollodata.com/react/

**Comment by amilajack** [comment]
We're only going to be removing tooling from now. The more tooling we add, the more difficult it is for beginners to start using the project.
