### ISSUE TITLE
Any way to use 'yarn add' without immediately rebuilding the DLL?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1034]
Adding and removing tiny packages has begun to take several minutes for me as my project has grown. Is there anything I can do to not rebuild until I'm done making package changes, or is this yarn itself doing it?

It ends off with:

     npm run build-dll exited with code 0

**Comment by amilajack** [comment]
Try `npm install some-dep --ignore-scripts`. The `--ignore-scripts` could have unexpected side affects. A better solution for you would probably be to create a separate script that looks something like this:

```js
// postinstall.js
if (process.env.arv.includes('--no-build-dll')) return
execSync('npm run build-dll')
```

**Comment by Slapbox** [comment]
Thanks very much @amilajack. For anyone else who comes across this, I'm using Yarn and the `--ignore-scripts` flag seems apply for it as well.

I'll report back with my results. Thanks again as always!

**Comment by Slapbox** [comment]
Works great!

**Comment by talha131** [comment]
@amilajack I suggest we should add such questions and their resolution to the wiki of this project. What do you think?

**Comment by amilajack** [comment]
@talha131 good idea. I'll make a FAQ section. Ideally, we can incorporate those questions and answers into the video tutorial series

**Comment by talha131** [comment]
> I'll make a FAQ section.

I suggest you should leave these low hanging fruits for rest of the community. You are already inundated with too many non trivial requests and issues.

**Comment by amilajack** [comment]
Good call. I actually don't have permission to enable read/write permissions to the public. That's up to @chentsulin. Also would be awesome if @chentsulin could add you as a collaborator

**Comment by talha131** [comment]
@amilajack It seems wiki is open for editing to all, not just the contributors.

See this page that I just added

https://github.com/chentsulin/electron-react-boilerplate/wiki/Tool-Tips

Secondly, how about we keep tips about tools like npm, yarn, git, flow to "Tool-Tips" instead of FAQ? I think this categorization is better than pilling everything into FAQ.

**Comment by amilajack** [comment]
I think that would be better once our FAQ becomes larger.

**Comment by vikr01** [comment]
[I've updated the FAQ](https://github.com/chentsulin/electron-react-boilerplate/wiki/FAQ#how-do-i-skip-building-the-dll-immediately-after-an-npm-install). It now mentions using `.yarnrc` to make `ignore-scripts` happen permanently (for all or specific commands).
