### ISSUE TITLE
NPM script to generate new components

### ISSUE THREAD

**Issue by diegohaz** [chentsulin/electron-react-boilerplate#1037]
Hey, guys.

I'm working on a project that helps people to generate new components on their projects following their conventions no matter how they structure the project.

I'm trying to apply it on some boilerplates so I can be sure that it works on most structures.

I just want to know if it's desirable to have a `yarn component` script (or something like that) to handle that. I can submit a small PR. 🎉

**Comment by amilajack** [comment]
What are some other projects that are using this? This has been discussed before in an issue regarding plopfiles. Would recommend looking at that issue.

**Comment by diegohaz** [comment]
Thank you for the quick reply, @amilajack. Could you link to that issue, please? I couldn't find it.

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate/pull/843

**Comment by diegohaz** [comment]
The project I'm working on is this: https://github.com/diegohaz/generact

Regarding to your question, there's no projects using it yet (I just made it public), except two of mine ([ARc](https://github.com/diegohaz/arc) and another private one).

Actually, there's no need to include it here as people could just run `npm install -g generact` and `generact`. It would be just a convenience npm script for those using the boilerplate. That's why I'm asking if that's desirable.

I'm currently trying to make it work properly with `electron-react-boilerplate` structure and similar (have a look at https://github.com/diegohaz/generact/issues/2).

**Comment by diegohaz** [comment]
Finally, it's working for `electron-react-boilerplate` 🎉
![image](https://cloud.githubusercontent.com/assets/3068563/26830709/1c87d710-4aa0-11e7-95ce-57eaf45f4f95.png)
![image](https://cloud.githubusercontent.com/assets/3068563/26830750/3aafbc80-4aa0-11e7-9854-36771d6ceecf.png)
![image](https://cloud.githubusercontent.com/assets/3068563/26830781/569388be-4aa0-11e7-94e4-139c96e6efdc.png)

**Comment by amilajack** [comment]
Maybe you can write a tutorial on this. That would be welcome. Create a fork of the boilerplate that demos generact. See https://github.com/chentsulin/electron-react-boilerplate/issues/968 for the discussion on guides.

**Comment by amilajack** [comment]
Project wiki's in this project are editable to anyone. Feel free to create the guide there

**Comment by amilajack** [comment]
Closing this because this probably wont get added to the boilerplate at this moment
