### ISSUE TITLE
cannot find electron-remote module

### ISSUE THREAD

**Issue by akshaygarg834** [chentsulin/electron-react-boilerplate#1040]
I installed electron-remote using 

> yarn add electron-remote

When I am trying to import it it shows this error.

Cannot find module './node_modules/electron-remote/lib/remote-event-browser.js'

Besides this I installed glamor axios which are working fine

**Comment by amilajack** [comment]
Electron remote is a native dependency. Remove it from your `./package.json` and add it to your `./app/package.json`

**Comment by amilajack** [comment]
[This section](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure) fully documents this issue

**Comment by aguynamedben** [comment]
👍Thanks for answering this. This also confused me. I was trying a bunch of different stuff (move code from main process to renderer, etc.). I didn't realize that was a native dependency because it looks mostly like the source is JavaScript.
