### ISSUE TITLE
npm - install-app-deps failure (courtesy notification)

### ISSUE THREAD

**Issue by mtompkins** [chentsulin/electron-react-boilerplate#1041]
You can review the issue and close this accordingly.

https://github.com/electron-userland/electron-builder/issues/1626

**Comment by amilajack** [comment]
I've actually been experiencing this issue with the boilerplate as well. I assumed it was an issue with my computer. Will close this after it gets resolved.

**Comment by mtompkins** [comment]
That was my initial suspicion as well, that it was local to my dev environment and caused me to do a batch of reinstalling / maintenance. This is one of the reasons I posted it here.

What is really worth noting is the extreme encouragement to move away from `npm` . It feels like upstream `electron-builder` may not support it much longer . . .

**Comment by amilajack** [comment]
@mtompkins have you found the latest working version of `electron-builder`?

**Comment by mtompkins** [comment]
Not sure what you mean exactly. 
As per 18.6.1 and using `yarn` things are working if that helps.

**Comment by amilajack** [comment]
Hmm interesting. For some reason I'm experiencing this issue still.

**Comment by mtompkins** [comment]
With yarn or NPM?

**Comment by amilajack** [comment]
yarn

**Comment by mtompkins** [comment]
... and I take it you did an @18.6.1?

**Comment by amilajack** [comment]
I'm on `18.6.2`

**Comment by mtompkins** [comment]
I haven't tried that version - give 18.6.1 a try?

**Comment by develar** [comment]
Obsolete in any case since electron-builder 19.x `electron-builder install-app-deps` is a recommended way now.
