### ISSUE TITLE
What is exactly native dependency?

### ISSUE THREAD

**Issue by talha131** [chentsulin/electron-react-boilerplate#1042]
From #1040 

> Electron remote is a native dependency. Remove it from your ./package.json and add it to your ./app/package.json

From [docs](https://github.com/chentsulin/electron-react-boilerplate#module-structure)

> If the module is native to a platform or otherwise should be included with the published package (i.e. bcrypt, openbci), it should be listed under dependencies in ./app/package.json.

Can you please elaborate what is native dependency?

For example, I added `material-ui` and `redux-form` to `./app/package.json`. Because my published application uses them.

But it generated [Refs Must Have Owner Warning](https://facebook.github.io/react/warnings/refs-must-have-owner.html)

>  Warning:
> addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded.

I kept getting this error until I moved all my react dependencies to the `./package.json`

```json
    "material-ui": "^0.17.0",
    "react-bootstrap-table": "^3.3.7",
    "react-motion": "^0.4.7",
    "react-swipeable-views": "^0.10.7",
    "react-tap-event-plugin": "^2.0.1",
    "react-treebeard": "^1.1.4",
    "redux-form": "^6.5.0",
```

So what is native dependency? Doc says

> otherwise should be included with the published package

I think I would want to include redux-form or material-ui in the published package, right? 

I am confused here. I would appreciate some clarification. Thanks

**Comment by amilajack** [comment]
### What is a native dependency?
Good question. A native dependency is any dependency that requires compilation of C++. Sometimes for performance benefits, some modules are written partially in C++ and make calls directly to the node runtime (v8). These kinds of modules, however, require to be compiled on the users computer upon installation. These dependencies that need to be compile are referred to as "native dependencies" because they rely on code that is compiled on the machine.

### How does this affect webpack?
Webpack was issues bundling native dependencies. I'm not sure why this is but I suspect this issue has to do with how some modules have dynamic require statements:

```js
const foo = 'bar'
const baz = 'loo'

require(foo + baz) // webpack many not be able to resolve this.
```

I will get in touch with the webpack team to find out more about why this issue exists and how we can resolve it. Currently, `./app/node_modules` are bundled in production, which is terrible for app size and performance.

**Comment by talha131** [comment]
Thank you @amilajack. Really appreciate how you go extra mile in helping us.

Can you shed some light on second part of the question. (I am sorry my original question didn't make the second part clear.)

### Part 2

The [doc suggests](https://github.com/chentsulin/electron-react-boilerplate#module-structure)

> If the module is native to a platform or **otherwise should be included with the published package** (i.e. bcrypt, openbci), it should be listed under dependencies in ./app/package.json.

I added material-ui and redux-form to `./app/package.json`. Because my published application uses them. I assume these should be **included with the published app**, right?

But it generated [Refs Must Have Owner Error](https://facebook.github.io/react/warnings/refs-must-have-owner.html)

>    Warning:
    addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded.

I kept getting this error until I moved all my react modules to the `./package.json`

```json
    "material-ui": "^0.17.0",
    "react-bootstrap-table": "^3.3.7",
    "react-motion": "^0.4.7",
    "react-swipeable-views": "^0.10.7",
    "react-tap-event-plugin": "^2.0.1",
    "react-treebeard": "^1.1.4",
    "redux-form": "^6.5.0",
```

On the other hand, non react modules are working fine inside `./app/package.json`


```json
    "moment": "^2.17.1",
    "password-generator": "^2.1.0",
    "pg-promise": "^5.5.6",
    "serial-number": "^1.2.0",
    "xlsx": "^0.8.3",
    "zxcvbn": "^4.4.2"
```

[moment](https://momentjs.com/) for example has no compiled code. It works fine inside `./app/package.json`.

But placing react modules in `./app/package.json` throws error.

1. Why does placing react modules in `./app/package.json` throw error but not for other js modules like moment?
1. What does doc mean from "...otherwise should be included with the published package"? 
    1. Modules like material-ui they should be included in the published package?
    1. If so, they why do I get ref error?
1. I get it what are native modules and that they should be placed inside `./app/package.json`. What other modules should be placed inside `./app/package.json`

Thanks for your time and effort.

**Comment by amilajack** [comment]
> I added material-ui and redux-form to ./app/package.json. Because my published application uses them. I assume these should be included with the published app, right?

> A native dependency is any dependency that requires compilation of C++/C

I'm pretty sure `material-ui` and `redux-form` do not need to be compiled to machine code. They are intended to run inside of the browser. They aren't written in C/C++. Here's a decent way of determining  if a package needs to be added to `./app/package.json`: go to that project's gihtub page. If you can see that it is written in C/C++ or it depends on any code that is written in C/C++, move it to `./app/package.json`. Its very unlikely that react/front-end code in general has bindings to C/C++.

### Recommendation
Here's what I do for my personal projects
* By default, add everything to `./package.json`. If you get errors that have some error like `cannot find module x`, try moving the dependency that errors to the `./app/package.json`.
* Add all dependencies that are `require()`'d or `import`'d in your app to `dependencies` of `./package.json`. These dependencies will be bundled in development to make hot module reloading fast in large apps.
* Add all tooling to `devDependencies` of `./package.json`. Some examples are `eslint`, `webpack`, `babel`, and all their related plugins. These packages will not be bundled in the DLL.

### Examples
* Here's examples of things that would go in the `depencencies` of `./app/package.json`: [node-postgres](https://github.com/brianc/node-postgreshttps://github.com/brianc/node-postgres), [node-fibers](https://github.com/laverdet/node-fibers), [node-mongodb-native](https://github.com/mongodb/node-mongodb-native), etc. Don't add an

* `devDepencencies` of `./package.json`: `eslint`, `webpack`, `babel`, and all their related plugins
* `devDepencencies` of `./package.json`: `react`, `redux`, `moment`, `jQuery`, `bootstrap`, etc

**Comment by mlukasch** [comment]
How do I build native modules for electron

**Comment by amilajack** [comment]
@mlukasch This is handled for you actually. See the the `postinstall` script in `./app/package.json`

**Comment by mlukasch** [comment]
@amilajack Thanks. Didnt realize that there 2 packgae.json-files. So the one in app/package.json is solely for native modules then such as chokidar?

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate#module-structure

**Comment by amilajack** [comment]
> So the one in app/package.json is solely for native modules then such as chokidar?

I'm not sure if chokidar is a native dependency. But if it is, then add it to `dependencies` of `./app/package.json`

**Comment by amilajack** [comment]
Also I should note that none of the dependencies inside of `./app/package.json` are touched by webpack. Webpack has issues with native dependencies (i'm not sure why). Because of this, none of those dependencies are minified or bundled. So your `./app/node_modules` are included in your production app.

**Comment by talha131** [comment]
> @talha131 also sorry for the late response on this. Expect a followup video tutorial on this if I have time sometime soon.

No need to be sorry. You are already doing a superb job. 

Now I have a better understand of how and where to put modules in the `package.json`.

I have used your answer in this thread to create a new wiki page. Have a look if you get time

https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure

**Comment by amilajack** [comment]
> I have used your answer in this thread to create a new wiki page. Have a look if you get time

That's awesome! Thank you so much. Would appreciate a PR that would mention that wiki in the readme. Maybe we can remove some of the previous documentation in the readme that may have been confusing.

**Comment by amilajack** [comment]
Also we should probably find a way to notify users about the two `package.json` structure. I've found out that a lot of users aren't aware of it. Maybe if we can add something like this to the [install section of the readme](https://github.com/chentsulin/electron-react-boilerplate#install):

> ⚠️ **Please read [this section](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure) before installing any dependencies** ⚠️

**Comment by amilajack** [comment]
Also I think we should add an 'overview'/TL;DR section to that wiki. Maybe something like:

If you are trying to install a native dependency, install it to `./app/package.json`:
```bash
cd app
npm install --save my-native-dep
```

**Comment by talha131** [comment]
> Would appreciate a PR that would mention that wiki in the readme.

See [here](https://github.com/chentsulin/electron-react-boilerplate/pull/1048)

> Also I think we should add an 'overview'/TL;DR section to that wiki. Maybe something like:

See [here](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure/_compare/f100ccfafefe1496cac870e8f39c0442cae3640e...c66c1996ef94e2a128b34a08b60376951f895605)

**Comment by aguynamedben** [comment]
I'm learning too that Webpack has complicated and confusing issue with dynamic requires (i.e. your example of `require(foo + bar)`. I also ran into a similar issue in [node-migrate](https://github.com/tj/node-migrate/issues/126), which is a module that relies on dynamic requires to run JavaScript/ES6 migration code (`require(path.join(migrationsDirectory, file))`).

I'm wondering if dynamic requires might also be the core issue going on with electron-remote in #1040.

Is it fair to say...
> A "native module" is anything written in C/C++ that must be packaged with the app, but because of unclear issues with Webpack you should also add packages to app/package.json if they rely on dynamic import statement.
?

Just curious. Also, I don't have a good mind map of all the moving parts in the JS traspiling ecosystem, but I think if modules, Babel, Webpack start using the new dynamic imports(), everything will "just work"? (in some pipe-dream future?)
