### ISSUE TITLE
execFile error

### ISSUE THREAD

**Issue by akshaygarg834** [chentsulin/electron-react-boilerplate#1043]
I am trying to do is this.
```js
    const execFile = require('child_process').execFile;
    const child = execFile('node', ['./app/scripts/test.js',localStorage['1090']], (error, stdout, stderr) => {
      if (error) {
        throw error;
      }
      console.log('ab aaya  hai');
      //console.log(stdout);
    });
    child.stdout.on('data', (data) => {
      console.log(`${data}`);
    });
    child.stderr.on('data', (data) => {
      console.log(`Error: ${data}`);
    });
    child.on('exit', (code) => {
      console.log(`Child process exit with code ${code}`);
      alert(`Child process exit with code ${code}`);
    });
```

Works Fine !
In production Build without packaging it works fine too. But doesn't work after packaging the app.
I packaged the the whole application with DEBUG_PROD true.
In console it shows this error.

> Uncaught Error: Command failed: node ./app/scripts/test.js C:\Users\aksgarg\Desktop\enterprisebusinesscenter
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\aksgarg\Desktop\JARVIS\release\win-unpacked\app\scripts\test.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

After packaging the reference to this test.js file is no longer exist.

**Comment by amilajack** [comment]
What does your file/folder structure look like?

**Comment by akshaygarg834** [comment]
![image](https://user-images.githubusercontent.com/14201958/26910687-0a5b1fe8-4c26-11e7-96ad-5cb5bf9deadc.png)

see that script folder.

Also Renderer Process's cwd is 'project' not 'project/app' so I had to do './app/script/test.js';

**Comment by amilajack** [comment]
Add https://github.com/chentsulin/electron-react-boilerplate/pull/1023/commits/a65256b6f0ebf1e57070e9930834deafef4076a7 to your branch and let me know if you're still experiencing issues. This will change the `__dirname` to the actual dirname

**Comment by akshaygarg834** [comment]
No, Nothing Changed ! It remains same.

**Comment by akshaygarg834** [comment]
Did you find solution for it?

**Comment by akshaygarg834** [comment]
This error is is with windows only. I tried with linux (Ubuntu) works fine.

**Comment by akshaygarg834** [comment]
https://github.com/akshaygarg834/Temp.git
Clone it and have a look !

It works fine with Linux even after packaging. But gives module not found error on windows after packaging.

**Comment by akshaygarg834** [comment]
```
node: {
    __dirname: false,
    __filename: false
 },
```

After adding these lines to webpack.config.renderer.dev.js  if you check you find that __filename will return path of app.html or if you don't add these lines __filename will be index.js

**Comment by amilajack** [comment]
Fixed in `v0.12.0`. [See this line](https://github.com/chentsulin/electron-react-boilerplate/pull/1023/files#diff-9a8fdaf5a26c1d165745372b73aa5dbcR242).

**Comment by akshaygarg834** [comment]
Still doesn't fix !

**Comment by RussGlover** [comment]
I am having a similar issue. Is it possible to package a worker.js in app.asar?

**Comment by amilajack** [comment]
Make sure that the file that you are trying to execute is also included in the production build. You can probably do this by adding it to the [files config](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L36). Note that this options does not require the file to be processed by webpack or babel. You will have to make sure the `worker.js` file can be executed without being transpiled.

A better solution is to create a webpack entry point for the worker file. See https://github.com/chentsulin/electron-react-boilerplate/issues/1095 for creating a second entry point. Then make sure that the output of the second entry point is added to the files config. Also make sure that the path to the script is correct in both production and development.

**Comment by RussGlover** [comment]
Thank you Amila!! This was just what I needed.

**Comment by amilajack** [comment]
I'm assuming you resolved this issue. Let me know if you're still experiencing issues

**Comment by akshaygarg834** [comment]
I am still having same issue in MAC.
I have add scripts folder in file config in package.json.
I did not add any second entry in in any config file.
What to do ?

**Comment by akshaygarg834** [comment]
@RussGlover 
Did you add any entries in any webpack config?
Did you app creates child process after packaging?

**Comment by RussGlover** [comment]
@akshaygarg834 
I just followed Amila's suggestion and was able to run a child process after packaging.
