### ISSUE TITLE
App root directory

### ISSUE THREAD

**Issue by brospars** [chentsulin/electron-react-boilerplate#1047]
Hi,
I'm using `electron-react-boilerplate` to create a desktop app (targeted os : ubuntu, windows) that uses an external 'backend' that does the hardwork  and is located at the root folder of my repository as so :
```
/
| app/
| backend/
| ...
| package.json
```

This backend is spawned inside my mainProcess and I'm using `process.cwd()` to locate it relatively to the app root directory. It works fine on windows (dev, production and packaged) but on linux when packaged and installed using `dpkg`, `process.cwd()` doesn't return the app root directory but the home folder of the user instead.

Any tip to make it work on all plateform and environment ?

Thanks

**Comment by amilajack** [comment]
This seems to be a configuration webpack issue. For now, try to use something like this:

```js
process.env.NODE_ENV === 'production
   ? yourProductionMath
   : process.cwd()
```

I'll look into this issue in the meantime

**Comment by amilajack** [comment]
Also take a look at this comment: https://github.com/chentsulin/electron-react-boilerplate/issues/374#issuecomment-307441098

**Comment by brospars** [comment]
Yes it is pretty much the same issue. So there is no universal solution for this.
If I find something, I will post the fix there.

Thanks

**Comment by eric-burel** [comment]
Just to give a working solution, this seems to work on all platforms and environment:
```js
const rootFolder = process.env.NODE_ENV === 'development' 
? process.cwd()
: path.resolve(app.getAppPath(), '../../');
```
 `app.getAppPath()` returns the asar archive where we usually store application private assets. When going two folders up, we access the `resources` folder, that contain the `extraFiles` (for example executables that need to be spawned).

**Comment by TimoSolo** [comment]
Thanks @eric-burel! that helped!

to be more specific:

`const {app} = require('electron').remote;
const path =  require('path');
const rootFolder = process.env.NODE_ENV === 'development' 
? process.cwd()
: path.resolve(app.getAppPath(), '../../');
`
I also had to add "extraFiles" to the package.json to get it to include the file I needed to execute. HTH someone.

**Comment by rendomnet** [comment]
@TimoSolo @eric-burel 
I have this error 
**Cannot read property 'app' of undefined**
