### ISSUE TITLE
Johnny Five JS - Which package.json ?

### ISSUE THREAD

**Issue by rooque** [chentsulin/electron-react-boilerplate#1049]
I'm trying to install Johnny Five JS (https://www.npmjs.com/package/johnny-five), but don't know which package.json should I use in this case ...

**Comment by talha131** [comment]
@rooque can you please go through this [wiki article](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure). It has tips and explanation on how to pick package.json file.

Your feedback will help us improve it.

**Comment by rooque** [comment]
I will test and provide feedback ASAP. Keep this open please

**Comment by rooque** [comment]
Johnny Five uses serialport, which is a native module ... So I put Johnny Five at /app/package.json.

But then this error:

> \app\node_modules\serialport\build\Release\serialport.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 53. This version of Node.js requires
> NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or`npm install`).
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
>     at Object.Module._extensions..node (module.js:598:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)

Already tried to to rebuild with npm run postinstall but nothing ...

**Comment by amilajack** [comment]
Try to change the target to ` --target=1.7.0` in the postinstall script

**Comment by rooque** [comment]
@amilajack I tried up to 1.6.10 before your comment and nothing ... with 1.7.0 it worked. Thanks so much.

Also for documentation for anyone that will use Johnny Five JS with electron-react-boilerplate: 

You need to initialize board without repl or things will get messy.

`var five = require("johnny-five");
var board = new five.Board({
  repl: false
});`

**Comment by datnordstrom** [comment]
where is the --target that I need to change for this work?

**Comment by amilajack** [comment]
Its in `./app/package.json`
