### ISSUE TITLE
Slow postinstall, rebasing flow-typed cache hangs

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1051]
If your `postinstall` script doesn't exit, its probably because of this issue: https://github.com/flowtype/flow-typed/issues/909.

Seems to happen if you're on node >= 8 and npm >= 5.

**SOLUTION: This was fixed in node `8.3.0`** 🎉 🎉 🎉

**Comment by uppe-r** [comment]
Don't seem to be getting this issue on Node `v7` https://github.com/flowtype/flow-typed/issues/909#issuecomment-308200444

**Comment by Unforgiven-wanda** [comment]
I can confirm, on Node 8 and npm 5 the installs are just unbearable.
Downgrading helps, a lot.

**Comment by amilajack** [comment]
@Unforgiven-wanda what version of flow-typed did you upgrade to?

**Comment by panuta** [comment]
+1, Node 8 and NPM 5

**Comment by anthonyraymond** [comment]
If you are patient enought, it does finish, but it takes at least 10 minutes.

**Comment by amilajack** [comment]
**This was fixed in node `8.3.0`** 🎉 🎉 🎉
