### ISSUE TITLE
e2e not starting app

### ISSUE THREAD

**Issue by brandonmp** [chentsulin/electron-react-boilerplate#1053]
I'm guesing there's some step I'm missing here, but can't make e2e tests work at all.

Tested on fresh git clone, Ubuntu 17.04, `node v7.9.0`

```
$ git clone https://github.com/chentsulin/electron-react-boilerplate.git
$ cd electron-react-boilerplate/ && yarn
$ npm start // starts & builds fine
$ npm run build 
$ npm run test-e2e
```

The test hangs until the timeout, throwing the following (and failling every subsequent test):

```
 FAIL  test/e2e/e2e.spec.js (15.57s)
  ● main window › should open window

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)

```

**Comment by brandonmp** [comment]
Actually, it works fine on another machine with Ubuntu, as well as in a MacOS Sierra VM, so this must be something unique to my machine. 

Tried with `node 6.9.5` & nothing. 

This is likely specific to my machine, but still welcome any trouble-shooting advice if someone's got more spectron exp. than i do (read: any)

**Comment by brandonmp** [comment]
works now after:

```
reboot
yarn cache clean
rm -rf node_modules
yarn
npm run build
npm run test-e2e
```


like all great bugs, the cause of this one may be lost forever.

**Comment by amilajack** [comment]
The main process needs to be build before running the e2e tests

**Comment by brandonmp** [comment]
This is actually happening again, so i guess it didn't sort itself out


> The main process needs to be build before running the e2e tests

@amilajack  I though this was accomplished with `npm run build` ? i.e.: 

```
...
"build": "concurrently \"npm run build-main\" \"npm run build-renderer\"",
...
```

To be sure, I ran `npm run build-main` and `npm run build-renderer` separately before running `npm run test-e2e`, but same problem. As I mentioned, `npm start` works fine, so the build must be working I'd think.

I've also increased `jasmine.DEFAULT_TIMEOUT_INTERVAL` to 150k just to see if something's taking too long, but the process still just hangs after this jest line:

```
RUNS test/e2e/e2e.spec.js
``` 

Have tried clearing `/tmp`, `npm cache clean`, `yarn cache clean`, as well as switching to `node` versions `6.9` & `8.1`, but still no luck with `npm run test-e2e` in a fresh clone of this repo.

Any ideas how to troubleshoot further?

**Comment by amilajack** [comment]
You only need to build the main process: `npm run build-main`. `npm run build` will build both the renderer and main processes. Clearing the cache should have no affect.

**Comment by brandonmp** [comment]
Okay, thanks. Building just the `main` had no impact.

I'm able to repro this on another machine with Ubuntu, but MacOS seems to work pretty consistently. I started playing with a minimal `spectron` example to trace the problem and it seems to follow the same pattern (hanging on the first test), so I suppose that repo is my next stop. 

The real pain here is that there's no console or anything to check for debugging info, so I'm stabbing around in the dark.

**Comment by amilajack** [comment]
You might actually have to build the renderer process as well. My bad.

**Comment by brandonmp** [comment]
np-I tried every build script so I figured it wasn't that.

Not sure what the cause was but think I figured this out. In some cases, my test was causing the `chromedriver` process to hang. When I `ctrl+c`'d the test, `chromedriver` would persist.

Now I just manually kill `chromedriver` thru the system monitor when things hang & it looks like it's good-to-go.

**Comment by brandonmp** [comment]
Looking more into it and I notice your `e2e.spec.js` calls `this.app.stop()` in `afterAll()`

The spectron example, though, uses `beforeEach()`/`afterEach()`

I think when the test process dies before all tests, `chromedriver` hangs and blocks future instances from running. 

Is there a benefit to using `beforeAll`/`afterAll`?

**Comment by amilajack** [comment]
@brandonmp That is a better option. I'll be adding it in https://github.com/chentsulin/electron-react-boilerplate

**Comment by brandonmp** [comment]
I just realized that the [Jest plugin for VS Code](https://github.com/orta/vscode-jest) was trying to run tests in the background to power its inline pass/fail indicators.

This was starting Chromedriver instances all willy-nilly, which was blocking everything up.

Works much better after uninstalling that extension.
