### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by panuta** [chentsulin/electron-react-boilerplate#1054]
I've just cloned this repo and run `npm install`. Then I got this error

`ERROR in unknown: Don't use path.replaceWith() with a source string, use path.replaceWithSourceString()`

I'm using node 8.1.1 with npm 5.0.3

I have tried to follow the steps in [Installation Debugging Solutions](https://github.com/chentsulin/electron-react-boilerplate/issues/400), but still got the error.

Then I tried to clear everything on my machine by delete all npm cache and uninstall node. Still got the error.

**Comment by Moai-** [comment]
Getting this as well. +1

**Comment by panuta** [comment]
@Moai- Using `yarn` has solved this issue for me. Thank you.

**Comment by amilajack** [comment]
This issue is actually caused by babili. You can temporarily disable it in your webpack production configs

**Comment by fernandomantoan** [comment]
I have the same problem, I tried to use `yarn` and also to disable `babili` without success.

I'm using node 8.1.1 and npm 5.0.3.

**Comment by amilajack** [comment]
@fernandomantoan did you disable it in both `webpack.renderer.prod.js` and `webpack.main.prod.js`?

**Comment by fernandomantoan** [comment]
@amilajack Sorry, I had disabled only on `webpack.main.prod.js`, now everything is working, thanks.
