### ISSUE TITLE
Build broken in node 6.

### ISSUE THREAD

**Issue by glomotion** [chentsulin/electron-react-boilerplate#1060]
Getting this error when trying to run $ yarn run dev in a node@6 env:

/Users/xxxx/GIT-Repos/test-electron/webpack.config.renderer.dev.js:10
import path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/Users/xxxx/GIT-Repos/test-electron/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxxx/GIT-Repos/test-electron/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm ERR! code ELIFECYCLE

$ node --version
v6.11.0

Has/Is anyone else experiencing the same?

**Comment by amilajack** [comment]
You might have changed the `dev` script. Paste your `package.json` here

**Comment by glomotion** [comment]
Don't think i've changed anything in there, but here it is:

{
  "name": "electron-react-boilerplate",
  "productName": "ElectronReact",
  "version": "0.12.0",
  "description": "Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development",
  "scripts": {
    "test": "cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 node --trace-warnings ./test/runTests.js",
    "test-all": "npm run lint && npm run flow && npm run test && npm run build && npm run test-e2e",
    "test-watch": "npm test -- --watch",
    "test-e2e": "cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 node --trace-warnings ./test/runTests.js e2e",
    "lint": "eslint --cache --format=node_modules/eslint-formatter-pretty .",
    "lint-fix": "npm run lint -- --fix",
    "lint-styles": "stylelint app/*.css app/components/*.css --syntax scss",
    "lint-styles-fix": "stylefmt -r app/*.css app/components/*.css",
    "hot-updates-server": "cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js",
    "build": "concurrently \"npm run build-main\" \"npm run build-renderer\"",
    "build-dll": "cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --progress --profile --colors",
    "build-main": "cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors",
    "build-renderer": "cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors",
    "start": "cross-env NODE_ENV=production electron ./app/",
    "_prestart": "npm run build",
    "flow": "flow check",
    "flow-typed": "rimraf flow-typed/npm && flow-typed install --overwrite || true",
    "start-hot-renderer": "cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.dev",
    "postinstall": "concurrently \"npm run flow-typed\" \"npm run build\" \"npm run build-dll\" \"install-app-deps\" \"node node_modules/fbjs-scripts/node/check-dev-engines.js package.json\"",
    "dev": "cross-env START_HOT=1 npm run hot-updates-server",
    "package": "npm run build && build --publish never",
    "package-win": "npm run build && build --win --x64",
    "package-linux": "npm run build && build --linux",
    "package-all": "npm run build && build -mwl"
  },
  "browserslist": "electron 1.6",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/chentsulin/electron-react-boilerplate.git"
  },
  "author": {
    "name": "C. T. Lin",
    "email": "chentsulin@gmail.com",
    "url": "https://github.com/chentsulin"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/chentsulin/electron-react-boilerplate/issues"
  },
  "keywords": [
    "electron",
    "boilerplate",
    "react",
    "redux",
    "flow",
    "sass",
    "webpack",
    "hot",
    "reload"
  ],
  "homepage": "https://github.com/chentsulin/electron-react-boilerplate#readme",
  "jest": {
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/internals/mocks/fileMock.js",
      "\\.(css|less|sass|scss)$": "identity-obj-proxy"
    },
    "moduleFileExtensions": [
      "js"
    ],
    "moduleDirectories": [
      "node_modules",
      "app/node_modules"
    ],
    "transform": {
      "^.+\\.js$": "babel-jest"
    }
  },
  "devDependencies": {
    "asar": "^0.13.0",
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-jest": "^20.0.3",
    "babel-loader": "^7.0.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-dynamic-import-webpack": "^1.0.1",
    "babel-plugin-flow-runtime": "^0.11.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.5.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.24.1",
    "babili-webpack-plugin": "^0.1.1",
    "chalk": "^1.1.3",
    "concurrently": "^3.4.0",
    "cross-env": "^5.0.0",
    "cross-spawn": "^5.1.0",
    "css-loader": "^0.28.3",
    "devtron": "^1.4.0",
    "electron": "^1.6.10",
    "electron-builder": "^18.0.1",
    "electron-devtools-installer": "^2.2.0",
    "enzyme": "^2.8.2",
    "enzyme-to-json": "^1.5.1",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-formatter-pretty": "^1.1.0",
    "eslint-import-resolver-webpack": "^0.8.1",
    "eslint-plugin-compat": "^1.0.3",
    "eslint-plugin-flowtype": "^2.33.0",
    "eslint-plugin-flowtype-errors": "^3.3.0",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-jest": "^20.0.3",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.0.1",
    "express": "^4.15.3",
    "extract-text-webpack-plugin": "^2.1.0",
    "fbjs-scripts": "^0.7.1",
    "file-loader": "^0.11.1",
    "flow-bin": "^0.47.0",
    "flow-runtime": "^0.12.0",
    "flow-typed": "^2.1.2",
    "html-webpack-plugin": "^2.28.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^20.0.4",
    "jsdom": "^11.0.0",
    "minimist": "^1.2.0",
    "node-sass": "^4.5.3",
    "react-addons-test-utils": "^15.5.1",
    "react-test-renderer": "^15.5.4",
    "redux-logger": "^3.0.6",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.5",
    "sinon": "^2.3.1",
    "spectron": "^3.7.0",
    "style-loader": "^0.18.1",
    "stylefmt": "^5.3.2",
    "stylelint": "^7.10.1",
    "stylelint-config-standard": "^16.0.0",
    "url-loader": "^0.5.8",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-dev-server": "^2.4.5",
    "webpack-merge": "^4.1.0"
  },
  "dependencies": {
    "electron-debug": "^1.1.0",
    "font-awesome": "^4.7.0",
    "history": "^4.6.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-hot-loader": "3.0.0-beta.6",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0",
    "source-map-support": "^0.4.15"
  },
  "devEngines": {
    "node": ">=6.x",
    "npm": ">=3.x",
    "yarn": ">=0.21.3"
  }
}

**Comment by amilajack** [comment]
Interesting. It seems like `babel-register` isn't working in this case. Try solution 1 of #400
