### ISSUE TITLE
"npm run package" not working

### ISSUE THREAD

**Issue by jfcartier** [chentsulin/electron-react-boilerplate#1065]
Ok so I followed the doc, step by step. 

$ git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git your-project-name
$ cd your-project-name
$ npm install
$ npm run dev 

So far everythings fine. The errors come when I run the package script.

$ npm run package

Here's my non exhaustive logs below. Do you have the same issue?

Thanks 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.12.0 build: `concurrently "npm run build-main" "npm run build-renderer"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.12.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jfcartier/.npm/_logs/2017-06-15T14_14_08_946Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.12.0 package: `npm run build && build --publish never`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.12.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jfcartier/.npm/_logs/2017-06-15T14_14_08_965Z-debug.log
```
File logs : https://cl.ly/2U0M1a11263D

**Comment by amilajack** [comment]
Try running `npm run build-main` and `npm run build-renderer` separately. Do any of them run successfully?

**Comment by jfcartier** [comment]
Hi @amilajack, so it actually crash when I launch "npm run build-main". 
I think the main error is this 

**ERROR in unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`**

I've seen this error on "npm install" too I think. 
Here's full log below. 

Thanks

```
~/Desktop/allo $ npm run build-main

> electron-react-boilerplate@0.12.0 build-main /Users/jfcartier/Desktop/allo
> cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors

1525ms building modules
60ms sealing
11ms optimizing
0ms basic module optimization
3ms module optimization
0ms advanced module optimization
0ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
1ms module and chunk tree optimization
44ms module reviving
3ms module order optimization
13ms module id optimization
2ms chunk reviving
1ms chunk order optimization
34ms chunk id optimization
35ms hashing
1ms module assets processing
58ms chunk assets processing
1ms additional chunk assets processing
0ms recording
2896ms additional asset processing
166ms chunk asset optimization
1ms asset optimization
24ms emitting
Hash: 46d68976d5bf5e16cfb5
Version: webpack 2.6.1
Time: 4874ms
                 Asset    Size  Chunks                    Chunk Names
    ./app/main.prod.js  615 kB       0  [emitted]  [big]  main
./app/main.prod.js.map  689 kB       0  [emitted]         main
[./app/main.dev.js] ./app/main.dev.js 3.14 kB {0} [built]
       [] -> factory:52ms building:172ms = 224ms
[./app/menu.js] ./app/menu.js 5.84 kB {0} [built]
       [] -> factory:63ms building:994ms dependencies:0ms = 1057ms
[./node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
       [] -> factory:49ms building:27ms = 76ms
[./node_modules/babel-polyfill/node_modules/core-js/fn/regexp/escape.js] ./~/babel-polyfill/~/core-js/fn/regexp/escape.js 107 bytes {0} [built]
       [] -> factory:95ms building:107ms dependencies:201ms = 403ms
[./node_modules/babel-polyfill/node_modules/core-js/modules/_core.js] ./~/babel-polyfill/~/core-js/modules/_core.js 117 bytes {0} [built]
       [] -> factory:229ms building:223ms = 452ms
[./node_modules/babel-polyfill/node_modules/core-js/modules/es6.map.js] ./~/babel-polyfill/~/core-js/modules/es6.map.js 541 bytes {0} [built]
       [] -> factory:186ms building:199ms = 385ms
[./node_modules/babel-polyfill/node_modules/core-js/modules/es6.object.get-own-property-names.js] ./~/babel-polyfill/~/core-js/modules/es6.object.get-own-property-names.js 147 bytes {0} [built]
       [] -> factory:136ms building:126ms dependencies:442ms = 704ms
[./node_modules/babel-polyfill/node_modules/core-js/modules/es6.regexp.flags.js] ./~/babel-polyfill/~/core-js/modules/es6.regexp.flags.js 198 bytes {0} [built]
       [] -> factory:184ms building:187ms dependencies:374ms = 745ms
[./node_modules/babel-polyfill/node_modules/core-js/modules/es6.set.js] ./~/babel-polyfill/~/core-js/modules/es6.set.js 396 bytes {0} [built]
       [] -> factory:187ms building:198ms dependencies:363ms = 748ms
[./node_modules/babel-polyfill/node_modules/core-js/shim.js] ./~/babel-polyfill/~/core-js/shim.js 7.38 kB {0} [built]
       [] -> factory:94ms building:76ms = 170ms
[./node_modules/electron-devtools-installer/dist/downloadChromeExtension.js] ./~/electron-devtools-installer/dist/downloadChromeExtension.js 2.32 kB {0} [built]
       [] -> factory:258ms building:20ms dependencies:1ms = 279ms
[./node_modules/electron-devtools-installer/dist/index.js] ./~/electron-devtools-installer/dist/index.js 4.63 kB {0} [built]
       [] -> factory:487ms building:307ms dependencies:3ms = 797ms
[./node_modules/regenerator-runtime/runtime.js] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
       [] -> factory:92ms building:40ms = 132ms
[./node_modules/source-map-support/source-map-support.js] ./~/source-map-support/source-map-support.js 16.4 kB {0} [built]
       [] -> factory:263ms building:524ms = 787ms
   [9] multi babel-polyfill ./app/main.dev 40 bytes {0} [built]
        factory:0ms building:2ms = 2ms
    + 328 hidden modules

ERROR in unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! electron-react-boilerplate@0.12.0 build-main: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.12.0 build-main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jfcartier/.npm/_logs/2017-06-15T17_27_31_230Z-debug.log
```

**Comment by amilajack** [comment]
See this discussion: https://github.com/chentsulin/electron-react-boilerplate/issues/1054#issuecomment-308458706. What is the hash commit that you'r on in the master branch? And when did you clone the boilerplate?

**Comment by jfcartier** [comment]
Thanks for your reply. To answer your question, I cloned it just before every post. 

**It works now**. npm install seems to be at the origin of the "replaceWith" error. I propose someone change the .md documentation cause it obviously create an error that makes packaging impossible, it just fails... So to recapitulate, in order to make it work : 

$ git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git your-project-name
$ cd your-project-name
~~$ npm install~~ $ yarn
$ npm run dev
$ npm run package 

Thanks for your help.

**Comment by himsoftware** [comment]
Hi @amilajack Please help me
below is the error I am getting

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pack:renderer' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'prepack:renderer', 'pack:renderer', 'postpack:renderer' ]
5 info lifecycle field-inspection-app@1.1.0~prepack:renderer: field-inspection-app@1.1.0
6 info lifecycle field-inspection-app@1.1.0~pack:renderer: field-inspection-app@1.1.0
7 verbose lifecycle field-inspection-app@1.1.0~pack:renderer: unsafe-perm in lifecycle true
8 verbose lifecycle field-inspection-app@1.1.0~pack:renderer: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\GSR\sourcecode\FIELD-ISPECTION-APP\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\GSR\sourcecode\FIELD-ISPECTION-APP\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\GSR\sourcecode\FIELD-ISPECTION-APP\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\Users\P10424005\AppData\Local\Microsoft\WindowsApps;C:\Users\P10424005\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\P10424005\AppData\Local\Programs\Fiddler;C:\Users\P10424005\AppData\Local\Yarn\bin
9 verbose lifecycle field-inspection-app@1.1.0~pack:renderer: CWD: C:\GSR\sourcecode\FIELD-ISPECTION-APP
10 silly lifecycle field-inspection-app@1.1.0~pack:renderer: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js' ]
11 silly lifecycle field-inspection-app@1.1.0~pack:renderer: Returned: code: 2  signal: null
12 info lifecycle field-inspection-app@1.1.0~pack:renderer: Failed to exec pack:renderer script
13 verbose stack Error: field-inspection-app@1.1.0 pack:renderer: `cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid field-inspection-app@1.1.0
15 verbose cwd C:\GSR\sourcecode\FIELD-ISPECTION-APP
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pack:renderer"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error field-inspection-app@1.1.0 pack:renderer: `cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js`
22 error Exit status 2
23 error Failed at the field-inspection-app@1.1.0 pack:renderer script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

Please help me.Its urgent for me
