### ISSUE TITLE
npm run build fails at build-renderer script

### ISSUE THREAD

**Issue by cdiezmoran** [chentsulin/electron-react-boilerplate#1066]
I'm using:
`node v7.10.0`
`npm  v4.2.0`
`electron-builder v^17.1.1`

When I run `npm run dev` everything works fine but when I try running `npm run build` or `npm run package` I get this error message:
```
Failed at the AlphaStage@0.9.0 build-renderer script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors'.
```

Here is my debug log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/carlosdiez/.nvm/versions/node/v7.10.0/bin/node',
1 verbose cli   '/Users/carlosdiez/.nvm/versions/node/v7.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-renderer' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebuild-renderer', 'build-renderer', 'postbuild-renderer' ]
5 info lifecycle AlphaStage@0.9.0~prebuild-renderer: AlphaStage@0.9.0
6 silly lifecycle AlphaStage@0.9.0~prebuild-renderer: no script for prebuild-renderer, continuing
7 info lifecycle AlphaStage@0.9.0~build-renderer: AlphaStage@0.9.0
8 verbose lifecycle AlphaStage@0.9.0~build-renderer: unsafe-perm in lifecycle true
9 verbose lifecycle AlphaStage@0.9.0~build-renderer: PATH: /Users/carlosdiez/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/carlosdiez/Dev/AlphaStage-refactor/node_modules/.bin:/Users/carlosdiez/Dev/AlphaStage-refactor/node_modules/.bin:/Users/carlosdiez/.config/yarn/link/node_modules/.bin:/Users/carlosdiez/Dev/AlphaStage-refactor/node_modules/.bin:/Users/carlosdiez/.config/yarn/link/node_modules/.bin:/Users/carlosdiez/.nvm/versions/node/v7.10.0/bin:/Users/carlosdiez/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/carlosdiez/.nvm/versions/node/v7.10.0/bin/node_modules/npm/bin/node-gyp-bin:/Users/carlosdiez/.nvm/versions/node/v7.10.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle AlphaStage@0.9.0~build-renderer: CWD: /Users/carlosdiez/Dev/AlphaStage-refactor
11 silly lifecycle AlphaStage@0.9.0~build-renderer: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors' ]
12 silly lifecycle AlphaStage@0.9.0~build-renderer: Returned: code: 2  signal: null
13 info lifecycle AlphaStage@0.9.0~build-renderer: Failed to exec build-renderer script
14 verbose stack Error: AlphaStage@0.9.0 build-renderer: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/Users/carlosdiez/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/carlosdiez/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid AlphaStage@0.9.0
16 verbose cwd /Users/carlosdiez/Dev/AlphaStage-refactor
17 error Darwin 16.6.0
18 error argv "/Users/carlosdiez/.nvm/versions/node/v7.10.0/bin/node" "/Users/carlosdiez/.nvm/versions/node/v7.10.0/bin/npm" "run" "build-renderer"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error AlphaStage@0.9.0 build-renderer: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors`
23 error Exit status 2
24 error Failed at the AlphaStage@0.9.0 build-renderer script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the AlphaStage package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs AlphaStage
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls AlphaStage
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

I don't know if this is helpful but here is a link to [my repo](https://github.com/cdiezmoran/AlphaStage-desktop)

If you have any idea why this is happening please let me know, I ran out of ideas.

Thank you in advance!

**Comment by amilajack** [comment]
I would recommend looking at this: https://github.com/chentsulin/electron-react-boilerplate/issues/1065#issuecomment-308815094 and https://github.com/chentsulin/electron-react-boilerplate/issues/1054

**Comment by cdiezmoran** [comment]
Thank you @amilajack I disabled babili from `webpack.config.main.prod.js`, and `webpack.config.renderer.prod.js` and it is working now! Closing this issue

**Comment by himsoftware** [comment]
Hi Team,
I am getting below error while building my application.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pack:renderer' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'prepack:renderer', 'pack:renderer', 'postpack:renderer' ]
5 info lifecycle field-inspection-app@1.1.0~prepack:renderer: field-inspection-app@1.1.0
6 info lifecycle field-inspection-app@1.1.0~pack:renderer: field-inspection-app@1.1.0
7 verbose lifecycle field-inspection-app@1.1.0~pack:renderer: unsafe-perm in lifecycle true
8 verbose lifecycle field-inspection-app@1.1.0~pack:renderer: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\GSR\sourcecode\FIELD-ISPECTION-APP\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\GSR\sourcecode\FIELD-ISPECTION-APP\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\GSR\sourcecode\FIELD-ISPECTION-APP\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\Users\P10424005\AppData\Local\Microsoft\WindowsApps;C:\Users\P10424005\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\P10424005\AppData\Local\Programs\Fiddler;C:\Users\P10424005\AppData\Local\Yarn\bin
9 verbose lifecycle field-inspection-app@1.1.0~pack:renderer: CWD: C:\GSR\sourcecode\FIELD-ISPECTION-APP
10 silly lifecycle field-inspection-app@1.1.0~pack:renderer: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js' ]
11 silly lifecycle field-inspection-app@1.1.0~pack:renderer: Returned: code: 2  signal: null
12 info lifecycle field-inspection-app@1.1.0~pack:renderer: Failed to exec pack:renderer script
13 verbose stack Error: field-inspection-app@1.1.0 pack:renderer: `cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid field-inspection-app@1.1.0
15 verbose cwd C:\GSR\sourcecode\FIELD-ISPECTION-APP
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pack:renderer"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error field-inspection-app@1.1.0 pack:renderer: `cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js`
22 error Exit status 2
23 error Failed at the field-inspection-app@1.1.0 pack:renderer script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
Please help me
