### ISSUE TITLE
Unable to package on mac

### ISSUE THREAD

**Issue by VladCherniavsky** [chentsulin/electron-react-boilerplate#1073]
Try to run 'npm run package' on mac and got error:

`ERROR in unknown: Don't use path.replaceWith() with a source string, use path.replaceWithSourceString()`

`npm`
`[1]  ERR! code ELIFECYCLE`
`[1] npm ERR! errno 2`
`[1] npm ERR! electron-react-boilerplate@0.12.0 build-renderer: cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors`
`[1] npm ERR! Exit status 2`
`[1] npm ERR! `
`[1] npm ERR! Failed at the electron-react-boilerplate@0.12.0 build-renderer script.`
`[1] npm`
`[1] ERR! This is probably not a problem with npm. There is likely additional logging output above.`
`[1] `
`[1] npm ERR! A complete log of this run can be found in:`
`[1] npm ERR!     /Users/sergey/.npm/_logs/2017-06-16T11_19_28_815Z-debug.log`
`[1] npm run build-renderer exited with code 2`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! electron-react-boilerplate@0.12.0 build: concurrently "npm run build-main" "npm run build-renderer"`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the electron-react-boilerplate@0.12.0 build script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /Users/sergey/.npm/_logs/2017-06-16T11_19_28_902Z-debug.log`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! electron-react-boilerplate@0.12.0 package: npm run build && build --publish never`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the electron-react-boilerplate@0.12.0 package script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /Users/sergey/.npm/_logs/2017-06-16T11_19_29_175Z-debug.log`

**Comment by uppe-r** [comment]
Check https://github.com/chentsulin/electron-react-boilerplate/issues/1065

**Comment by VladCherniavsky** [comment]
It didn't help I still have error:  
`ERROR in unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()``

**Comment by uppe-r** [comment]
Did you use npm install or yarn @VladCherniavsky ?

**Comment by VladCherniavsky** [comment]
@uppe-r  yarn

**Comment by uppe-r** [comment]
Maybe try https://github.com/chentsulin/electron-react-boilerplate/issues/1066#issuecomment-308943183 ? If it doesn't work, try running `yarn run build-main` and `yarn run build-renderer` separately and upload the debug log.

**Comment by VladCherniavsky** [comment]
@uppe-r  After disabling babili from `webpack,config.main.prod.js` and 'webpack,config.renderer.prod.js' it works correctly. Thanks a lot
