### ISSUE TITLE
Post install fails with style loader using path.replaceWith()

### ISSUE THREAD

**Issue by sineo** [chentsulin/electron-react-boilerplate#1075]
[2017-06-17T14_55_11_728Z-debug.txt](https://github.com/chentsulin/electron-react-boilerplate/files/1082599/2017-06-17T14_55_11_728Z-debug.txt)

During the postinstall I'm getting the following error:

ERROR in unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`

I've attached my log. I'm running npm v5 and node v7.

Has anyone experienced this lately?

**Comment by amilajack** [comment]
Try installing with yarn instead
