### ISSUE TITLE
Imported (not global) css is not working.

### ISSUE THREAD

**Issue by tcr-nyt** [chentsulin/electron-react-boilerplate#1076]
Hi, I am relatively new to css-modules and webpack, so I hope there is a simple solution to this problem:

When I use the boilerplate webpack config my css file (sourced from `node_modules`) does not work when imported in my React component. It also does not throw an error.

However, the styling is applied when I change this rule in `webpack.config.renderer.dev` from: 
```
      {
        test: /^((?!\.global).)*\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]',
            }
          },
        ]
      },
```
to this:
```
 {
        test: /^((?!\.global).)*\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]',
            }
          },
        ]
      },
```

The import statement I am using is as follows:
`import 'react-tabs/style/react-tabs.css';`, where `react-tabs` is a package I have installed in `node_modules`.

As you can see, removing the `modules: true` allows the css to be imported properly. Is there something wrong with the webpack config or with my code? If this is a simple css-modules issue please let me know.

**Comment by amilajack** [comment]
From your global sass file, try importing it like so:

```sass
@import "~font-awesome/css/font-awesome.css";
```

**Comment by tcr-nyt** [comment]
Thank you! I had a fundamental misunderstanding about the way css-modules/global css worked, this cleared it right up.
