### ISSUE TITLE
Command-Line Interface

### ISSUE THREAD

**Issue by akshaygarg834** [chentsulin/electron-react-boilerplate#1084]
Is it possible to provide a command line interface for application. I mean user should be able to do the same operations which they would do with GUI. My application have some function as 'createNewPlugin' which generates a some folders and files at a location. User will click on a button in GUI to do so. Most of application have command line interface like Sublime Text. You can open a file directly from terminal in Sublime Text using 'subl filename.txt'. I want my application to do some operations from CLI . How to do it ????

**Comment by amilajack** [comment]
Let's merge this into https://github.com/chentsulin/electron-react-boilerplate/issues/1000
