### ISSUE TITLE
Cannot import CSS?

### ISSUE THREAD

**Issue by raitucarp** [chentsulin/electron-react-boilerplate#1087]
Why I can not import CSS to my component? I won't import it as global CSS.

For example, I cannot import this CSS:
https://www.draft-js-plugins.com/plugin/inline-toolbar

I also hack the webpack config but nothings happened. 
Please elaborate more, what is the proper way to import CSS.

**Comment by amilajack** [comment]
Import it like so: https://github.com/falcon-client/falcon/blob/master/app/app.global.css#L1

**Comment by raitucarp** [comment]
@amilajack: OK. Thanks. I will investigate more about that.  

Sometimes I encounter strange behavior when  a component only need import a specific stylesheet rather than include all as global.

**Comment by talha131** [comment]
@amilajack check this out new wiki page, [CSS and SCSS](https://github.com/chentsulin/electron-react-boilerplate/wiki/CSS-and-SCSS)

**Comment by amilajack** [comment]
@talha131 ahh this is so nice. Thanks!

**Comment by LoaneShark** [comment]
Is this information anywhere now? Both of the previously posted links are broken and the new docs website does not have any information about CSS imports.

**Comment by t4t5** [comment]
For those wondering, the new link to the docs is [here](https://electron-react-boilerplate.js.org/docs/styling/#how-to-import-css-file-from-node-modules).

You need to import your CSS in a `.global.css` file like this (note the **~** at the beginning of the `node_modules` package!)

```css
@import '~bootstrap/dist/css/bootstrap.css'; // <-- Like this!

html,
body {
  padding: 0;
  ...
```
