### ISSUE TITLE
Packaging a Windows exe: node.dll missing

### ISSUE THREAD

**Issue by mlukasch** [chentsulin/electron-react-boilerplate#1090]
Im building an exe file by: npm run package-win
But executing on a windows machine, I get an error that node.dll is missing.

**Comment by mlukasch** [comment]
Thanks, I need to start the exe from the win-unpacked-folder:
Question now: how to deliver the folder in a self-installing file?

**Comment by amilajack** [comment]
`npm run package-win` builds a `nsis` file, which is portable

**Comment by amilajack** [comment]
https://github.com/electron-userland/electron-builder/wiki/options
