### ISSUE TITLE
Is there any way to customize installation steps ?

### ISSUE THREAD

**Issue by VladCherniavsky** [chentsulin/electron-react-boilerplate#1094]
I'd like to customize instalation  steps: i.e

- add gif during installation process
- add checkbox "Accept terms and conditions ..."
- select destination folder

Is there any way to do this ?

**Comment by amilajack** [comment]
Try electron-builder's `pkg` option

**Comment by amilajack** [comment]
https://github.com/electron-userland/electron-builder/wiki/options

**Comment by VladCherniavsky** [comment]
@amilajack maybe you have any examples ?

**Comment by develar** [comment]
For windows set https://github.com/electron-userland/electron-builder/wiki/options#NsisOptions-oneClick to false, for macOS "Try electron-builder's pkg option" (i.e. set target to `pkg`).

**Comment by VladCherniavsky** [comment]
@develar thanks for the  answer, but how to add any text or gif animation ? Below an example of what I want.
![screenshot_1](https://user-images.githubusercontent.com/8988069/27588888-53439056-5b52-11e7-9a4b-666bf81fea97.jpg)

**Comment by develar** [comment]
@VladCherniavsky electron-react-boilerplate uses electron-builder 18.x — this branch is obsolete and some release in this branch contains regression — no text in this dialog. It was fixed in the 19.x Please upgrade electron-builder to 19.10.0.

**Comment by develar** [comment]
@VladCherniavsky But if you want to show License information/EULA — you need to set oneClick to false.
