### ISSUE TITLE
Create 2nd render window / is this a 2nd webpack entry?

### ISSUE THREAD

**Issue by mtompkins** [chentsulin/electron-react-boilerplate#1095]
I'm not quite sure if this is my limited nodejs knowledge, or a function of the boilerplate so I'm going to pose a question / ask for help.

In short, I'm trying to create a 2nd renderer thread for launching background processes so jobs don't freeze the main renderer or main threads (like db async or cpu intensive calls). Referencing the fundamental [electron-api-sample](https://github.com/electron/electron-api-demos) app, here's some code that sort of demonstrates my goal ...

Let's say we can import `bkWin` somewhere in the primary renderer thread with the intent to send a job to the background (not yet) invisible window

`background-helper.js`

```
// @flow
import { ipcRenderer, remote } from 'electron';
import path from 'path';

export function bkWin() {
  const windowID = remote.BrowserWindow.getFocusedWindow().id;

  let appPath;

  process.env.NODE_ENV === 'development' ?
    appPath = path.join(remote.app.getAppPath().replace('/node_modules/electron/dist/resources/default_app.asar', '/app')) :
    appPath = remote.app.getAppPath();

  const invisPath = path.join(appPath, 'renderer/background-worker/invisible.html');
  const win = new remote.BrowserWindow({ width: 400, height: 400 });
  win.loadURL(`file://${invisPath}`);

  win.webContents.on('did-finish-load', () => {
    const input = 100;
    win.webContents.send('compute-factorial', input, windowID);
  });
}

ipcRenderer.on('factorial-computed', (event, input, output) => {
  const message = `The factorial of ${input} is ${output}`;
  console.log('-- MESSAGE --', message);
});

```
`invisible.html`
```
<html>
  <div>LOADED</div>
    <script type="text/javascript">
    const ipc = require('electron').ipcRenderer
    const BrowserWindow = require('electron').remote.BrowserWindow

    ipc.on('compute-factorial', function (event, number, fromWindowId) {
      const result = factorial(number)
      const fromWindow = BrowserWindow.fromId(fromWindowId)
      fromWindow.webContents.send('factorial-computed', number, result)
      window.close()
    })

  function factorial(num) {
    if (num === 0) return 1
    return num * factorial(num - 1)
  }
  </script>
</html>
```

What I'm looking for is a little help/instruction on how to incorporate this into the boilerplate. 

Does this addition cause it to become a [webpack multi-entry](https://webpack.github.io/docs/multiple-entry-points.html)?   
... or is there a more direct method I'm simply missing to get it into the final packages and transformed solution?    
I'd like to be able to do `import from './some/path/in/the/app/file.js` and such.

Many thanks for any direction...
Mark

**Comment by amilajack** [comment]
Things you'll need to do: 

1. Create another html file that is very similar to the `app.html` file (maybe called `second-renderer.html` or something). Make sure to change the paths to something like this:
```js
        scripts.push(
          (process.env.HOT)
            ? 'http://localhost:' + port + '/dist/bundle.js'
            : './dist/bundle.js'
        );
```

**Comment by mtompkins** [comment]
Thank you - this was a great nudge. 

It seems there is some conflict with the steps above as I believe the outputs write to the same file?
I'm trying to alter the `dev` side first, I receive:

```
ERROR in chunk background [entry]
bundle.js
Conflict: Multiple assets emit to the same filename bundle.js
Not rewriting GET /dist/bundle.js because the path includes a dot (.) character.
```
which if I understand correctly is:

[Webpack Multi-Entry Points](https://webpack.github.io/docs/multiple-entry-points.html)
> When using multiple entry points you must override the default output.filename option. Otherwise each entry point would write to the same output file. Use [name] to get the name of the entry point.

**Comment by mtompkins** [comment]
I'll come back to confirm my results for future visitors, but as to the above I've made the following changes:   

`webpack.config.renderer.prod.js`
```
// entry: ['babel-polyfill', './app/index'],

  entry: {
    main: ['babel-polyfill', './app/index'],
    background: ['babel-polyfill', './app/backgroundRenderer'],
  },

  output: {
    filename: '[name].entry.js',
    path: path.join(__dirname, 'app/dist'),
    publicPath: '../dist/'
  },
  // output: {
  //   path: path.join(__dirname, 'app/dist'),
  //   publicPath: '../dist/'
  // },
```
`webpack.config.base.js`
```
  output: {
    path: path.join(__dirname, 'app'),
    filename: '[name].entry.js',
    // https://github.com/webpack/webpack/issues/1114
    libraryTarget: 'commonjs2'
  },

  // output: {
  //   path: path.join(__dirname, 'app'),
  //   filename: 'bundle.js',
  //   // https://github.com/webpack/webpack/issues/1114
  //   libraryTarget: 'commonjs2'
  // },
```

`webpack.config.renderer.dev.js`
```
  entry: {
    main: [
      'react-hot-loader/patch',
      `webpack-dev-server/client?http://localhost:${port}/`,
      'webpack/hot/only-dev-server',
      path.join(__dirname, 'app/index.js'),
    ],
    background: [
      'react-hot-loader/patch',
      `webpack-dev-server/client?http://localhost:${port}/`,
      'webpack/hot/only-dev-server',
      path.join(__dirname, 'app/backgroundRenderer.js'),
    ],
  },

  output: {
    filename: '[name].entry.js',
    publicPath: `http://localhost:${port}/dist/`
  },

  // output: {
  //   publicPath: `http://localhost:${port}/dist/`
  // },
```

`app.html`
```
 // Dynamically insert the bundled app script in the renderer process
      const port = process.env.PORT || 1212;
      // scripts.push(
      //   (process.env.HOT)
      //     ? 'http://localhost:' + port + '/dist/bundle.js'
      //     : './dist/bundle.js'
      // );
      scripts.push(
        (process.env.HOT)
          ? 'http://localhost:' + port + '/dist/main.entry.js'
          : './dist/main.entry.js'
      );
```

and a new `html` for the 2nd renderer referencing `background.entry.js`

This should leave changes to things like `.gitignore` still to be done but overall the necessary changes.

**Comment by mtompkins** [comment]
The referenced changes seem to work as hoped for. I haven't tried it from a package yet, however, `yarn run dev` and `yarn run start` seem to be good.

I am a bit uncertain as to my change to `webpack.config.base.js`. I know there is now effectively no `bundle.js` so a change is needed, but as there is no obvious "entry" in that file I'm unsure if the change I've made is correct based on the boilerplate.

**Comment by mtompkins** [comment]
Resolved the package issue with adding the new `html` to `package.json` `files: { ... }`

**Comment by amilajack** [comment]
@talha131 Would be awesome if you could document this in a wiki

**Comment by elcorders** [comment]
can i achieve a the same result with the `HtmlWebpackPlugin()` ?

**Comment by jdpigeon** [comment]
This was a very helpful thread for me in figuring out how to package my app, which includes a second process running as a webview inside the renderer window.

I used essentially the same changes reported by @mtompkins above. The only changes I had to make for working with a webview were to remove react-hot-loader and webpack-dev-server plugins from my dev webpack config and change the 2nd process's html to prevent the app from trying to hot load it.

I also cut corners by avoiding CSS loading for the second process entirely and writing it directly into the 2nd process's html header.

`webpack.config.renderer.dev.js`
```
entry: {
    main: [
      "react-hot-loader/patch",
      `webpack-dev-server/client?http://localhost:${port}/`,
      "webpack/hot/only-dev-server",
      path.join(__dirname, "app/index.js")
    ],
    viewer: [
      path.join(__dirname, "app/viewer.js")
    ]
  },

  output: {
    publicPath: `http://localhost:${port}/dist/`,
    filename: "[name].entry.js"
  },
```

`viewer.html`
```
{
    const scripts = [];

    // Insert the bundled app script in the viewer process
    const port = process.env.PORT || 1212;
    scripts.push('./dist/viewer.entry.js');

    document.write(
        scripts
        .map(script => '<script defer src="' + script + '"><\/script>')
        .join('')
    );
}
```

**Comment by fakob** [comment]
Thanks for this thread. It helped me set up a 2nd render window. In my case I had to also change some lines of code for the `css` to properly work.
In `webpack.config.renderer.prod.js` I changed `style.css` to `[name].css`
```
// new ExtractTextPlugin('style.css'),
new ExtractTextPlugin('[name].css'),
```
and also under plugins I added `webpack.optimize.CommonsChunkPlugin`. This I am not sure if it is absolutely needed.
```
new webpack.optimize.CommonsChunkPlugin({
  children: true,
}),
```
And in the `app.html` and `worker.html` (my second render window) I had to change to use the resolved css names. For example, as the `entry` of my second window was called `worker` I changed in `worker.html` the following
```
// link.href = './dist/style.css';
link.href = './dist/worker.css';
``` 

The reason these changes were necessary was that, apparently when [creating a multipage entry](https://webpack.js.org/concepts/entry-points/#multi-page-application) more chunks get added. In my case webpacks chunk 0 `style.css` was overwritten by chunk 1 `style.css`.
For this to be visible in the logs I added `--display-chunks` to the npm build-renderer script
```
"build-renderer": "cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors --display-chunks --display-modules",
```
webpack build log before 
```
[1] chunk    {0} renderer.prod.js, style.css, renderer.prod.js.map, style.css.map (renderer) 2.04 MB [entry] [rendered]
[1]  [./app/actions/index.js] ./app/actions/index.js 16 kB {0} {1} [built]
... some lines removed ...
[1]      + 918 hidden modules
[1] chunk    {1} worker.prod.js, style.css, worker.prod.js.map, style.css.map (worker) 2.08 MB [entry] [rendered]
[1]  [./app/actions/index.js] ./app/actions/index.js 16 kB {0} {1} [built]
... some lines removed ...
[1]      + 908 hidden modules
```
webpack build log after the fix
```
[1] chunk    {0} renderer.prod.js, renderer.css, renderer.prod.js.map, renderer.css.map (renderer) 2.04 MB [entry] [rendered]
[1]  [./app/actions/index.js] ./app/actions/index.js 16 kB {0} {1} [built]
... some lines removed ...
[1]      + 918 hidden modules
[1] chunk    {1} worker.prod.js, worker.css, worker.prod.js.map, worker.css.map (worker) 2.08 MB [entry] [rendered]
[1]  [./app/actions/index.js] ./app/actions/index.js 16 kB {0} {1} [built]
... some lines removed ...
[1]      + 908 hidden modules
```

**Comment by jp887** [comment]
In case it's useful for anyone else who arrives here, I've made an example repo with a basic two window setup. The commit history shows the steps I used, most of which are described above. https://github.com/jp887/electron-react-boilerplate/

**Comment by talhaanees** [comment]
Hi,

Is this possible with HTML webpack plugin? If yes, can someone share code or an example?

Fairly new to all of this.

**Comment by jp887** [comment]
@talhaanees the repo here https://github.com/jp887/electron-react-boilerplate/ provides a simple example of a two window app. ERB doesn't use html-webpack-plugin though, so neither does that example.

It should be fairly straight forward to add it (just modify the renderer webpack config) but I cant think why you would want to... the main purpose of that plugin is to automatically include the webpack bundles in a generated HTML file if the bundle name changes between builds (for example contains a cache busting hash). 

By default the renderer bundle name in an ERB app doesn't change so html-webpack-pluigin is unnecessary unless you need it for some other reason.

**Comment by talhaanees** [comment]
@jp887 hhhmm.. I am new to webpack, so just followed the trend. Doesn't html-webpack-plugin help reduce your bundle size? But, if what you mentioned is the sole purpose of html-webpack-plugin, I'll move my project away from it in the future. 

Thank-you for the repo and quick response!

**Comment by dbvrac** [comment]
> In case it's useful for anyone else who arrives here, I've made an example repo with a basic two window setup. The commit history shows the steps I used, most of which are described above. https://github.com/jp887/electron-react-boilerplate/

This is working great for me and I really appreciate it. But... 
Firebase is now getting called twice `app.initializeApp(config);` and I haven't figured a way around this. I'm also getting two errors from `react-hot-loader` which I am attributing to the Firebase issue, though I could be wrong:
```misconfiguration detected, using production version in non-production environment.```
and
```Hot Module Replacement is not enabled.```

**Question:** Is there a way I can move Firebase up the tree so it only gets called once?
The Firebase docs don't quite seem to address this issue: [https://firebase.google.com/docs/projects/multiprojects](https://firebase.google.com/docs/projects/multiprojects)

My directory structure:
app/window1/
app/shared/components/Firebase
app/window2

**Comment by dbvrac** [comment]
> > In case it's useful for anyone else who arrives here, I've made an example repo with a basic two window setup. The commit history shows the steps I used, most of which are described above. https://github.com/jp887/electron-react-boilerplate/
> 
> This is working great for me and I really appreciate it. But...
> Firebase is now getting called twice `app.initializeApp(config);` and I haven't figured a way around this. I'm also getting two errors from `react-hot-loader` which I am attributing to the Firebase issue, though I could be wrong:
> `misconfiguration detected, using production version in non-production environment.`
> and
> `Hot Module Replacement is not enabled.`
> 
> **Question:** Is there a way I can move Firebase up the tree so it only gets called once?
> The Firebase docs don't quite seem to address this issue: https://firebase.google.com/docs/projects/multiprojects
> 
> My directory structure:
> app/window1/
> app/shared/components/Firebase
> app/window2

UPDATE
My Firebase implementation is based on this tutorial: [https://www.robinwieruch.de/complete-firebase-authentication-react-tutorial](https://www.robinwieruch.de/complete-firebase-authentication-react-tutorial)

After several days of breaking my application I seem to have found an answer from this article:
[https://medium.com/@ravirupareliya/you-can-also-resolve-this-error-with-following-code-715be01d55d7](https://medium.com/@ravirupareliya/you-can-also-resolve-this-error-with-following-code-715be01d55d7)

`if (!firebase.apps.length) {
  firebase.initializeApp(config);
}`

However, while it no longer appears that Firebase is being called twice, I'm still getting the same React Hot Loader errors even though it does seem to be working.

**Comment by jp887** [comment]
@dbvrac glad you got your app working. It's hard to comment on the react-hot-loader issue without more information or seeing your code.

RE: your duplicate initialization problem.. I dont work with Firebase myself but having had a quick glance at the tutorial you linked one option might be to put your firebase interactions in the main process and push data to/from the two renderers with Electron's IPC APIs. That would be a very different architecture to one shown in the tutorial though. Also, given that ERB already includes Redux it might be worth looking at integrating at the Redux level like in [this article](https://medium.com/quick-code/how-to-integrate-react-redux-and-firebase-in-3-simple-steps-c44804a6af38) but I guess it totally depends on your app.

**Comment by dbvrac** [comment]
@jp887 I went through the tutorial in that link (thanks, btw) and was able to add Firebase Analytics just fine, but it doesn't work in my ERB app using the same methods. It's likely this has nothing to do with a second renderer, so I'll take this problem elsewhere. 
Thanks for your help.

**Comment by pdw207** [comment]
Thanks for all that chimed in. It helped me get unblocked. I did want to call out that you need to create another instance of HtmlWebpackPlugin to handle the new worker HTML.
```
  entry: {
    app: [ 
      `webpack-dev-server/client?http://localhost:${port}/dist`,
      'webpack/hot/only-dev-server',
      path.join(webpackPaths.srcRendererPath, 'app/index.tsx'),
    ],
   // worker and nesting is new
    worker: [ 
      `webpack-dev-server/client?http://localhost:${port}/dist`, 
      'webpack/hot/only-dev-server', 
      path.join(webpackPaths.srcRendererPath, 'worker/index.tsx'), 
    ],
  },

// path filename is dynamic
output: {
    path: webpackPaths.distRendererPath,
    publicPath: `/`,
    filename: '[name].entry.js', // changed
    library: {
      type: 'umd',
    },
  },

// new HtmlWebpackPlugin creates two HTML documents in release/app/dist directory and references entrypoint defined above in chunks
plugins: [
  new HtmlWebpackPlugin({
      filename: path.join('worker.html'), 
      template: path.join(webpackPaths.srcRendererPath, 'worker/index.ejs'), 
      ...
      chunks: ['worker'],
    }),
  new HtmlWebpackPlugin({
      filename: path.join('index.html'), 
      template: path.join(webpackPaths.srcRendererPath, 'app/index.ejs'), 
      ...
      chunks: ['app'],
    }),

]
```

**Comment by TrofinSorin** [comment]
@pdw207 This works good for development, but for production?

```
 entry: {
    main: [
      path.join(webpackPaths.srcRendererPath, 'index.tsx'),
    ],
    shortcutWindow: [
      path.join(webpackPaths.srcRendererPath, 'shortcutWindow/index.tsx'),
    ],
  },

  output: {
    path: webpackPaths.distRendererPath,
    publicPath: './',
    filename: '[name].renderer.js',
    library: {
      type: 'umd',
    },
  },
  
   new MiniCssExtractPlugin({
      filename: '[name].style.css',
    }),
    
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.join(webpackPaths.srcRendererPath, 'index.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      chunks: ['main'],
      isBrowser: false,
      isDevelopment: process.env.NODE_ENV !== 'production',
    }),
    new HtmlWebpackPlugin({
      filename: path.join('shortcutWindow/index.html'),
      template: path.join(webpackPaths.srcRendererPath, 'shortcutWindow/index.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      chunks: ['shortcutWindow'],
      isBrowser: false,
      env: process.env.NODE_ENV,
      isDevelopment: process.env.NODE_ENV !== 'production',
      nodeModules: webpackPaths.appNodeModulesPath,
    }),
```

```
shortcutWindow = new BrowserWindow({
        title: 'App',
        width: 850,
        height: 850,
        icon: addIconToApp(),
        webPreferences: {
          preload: app.isPackaged
              ? path.join(__dirname, 'preload.js')
              : path.join(__dirname, '../../.erb/dll/preload.js'),
          devTools: true
        },
      });

await shortcutWindow.loadURL(resolveHtmlPath('shortcutWindow/index.html'));
```

The issue is that it will create a shortcutWindow folder inside which is shortcutWindow.html but the other files like shortcutWindow.renderer.js and the css is beeing created on root, and when you try to open the quick access window, it will try to get renderer from the shortcutWindow folder, which is not there, but on root.

**Comment by 491239** [comment]
> @pdw207 This works good for development, but for production?
> 
> ```
>  entry: {
>     main: [
>       path.join(webpackPaths.srcRendererPath, 'index.tsx'),
>     ],
>     shortcutWindow: [
>       path.join(webpackPaths.srcRendererPath, 'shortcutWindow/index.tsx'),
>     ],
>   },
> 
>   output: {
>     path: webpackPaths.distRendererPath,
>     publicPath: './',
>     filename: '[name].renderer.js',
>     library: {
>       type: 'umd',
>     },
>   },
>   
>    new MiniCssExtractPlugin({
>       filename: '[name].style.css',
>     }),
>     
>     new HtmlWebpackPlugin({
>       filename: 'index.html',
>       template: path.join(webpackPaths.srcRendererPath, 'index.ejs'),
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true,
>       },
>       chunks: ['main'],
>       isBrowser: false,
>       isDevelopment: process.env.NODE_ENV !== 'production',
>     }),
>     new HtmlWebpackPlugin({
>       filename: path.join('shortcutWindow/index.html'),
>       template: path.join(webpackPaths.srcRendererPath, 'shortcutWindow/index.ejs'),
>       minify: {
>         collapseWhitespace: true,
>         removeAttributeQuotes: true,
>         removeComments: true,
>       },
>       chunks: ['shortcutWindow'],
>       isBrowser: false,
>       env: process.env.NODE_ENV,
>       isDevelopment: process.env.NODE_ENV !== 'production',
>       nodeModules: webpackPaths.appNodeModulesPath,
>     }),
> ```
> 
> ```
> shortcutWindow = new BrowserWindow({
>         title: 'App',
>         width: 850,
>         height: 850,
>         icon: addIconToApp(),
>         webPreferences: {
>           preload: app.isPackaged
>               ? path.join(__dirname, 'preload.js')
>               : path.join(__dirname, '../../.erb/dll/preload.js'),
>           devTools: true
>         },
>       });
> 
> await shortcutWindow.loadURL(resolveHtmlPath('shortcutWindow/index.html'));
> ```
> 
> The issue is that it will create a shortcutWindow folder inside which is shortcutWindow.html but the other files like shortcutWindow.renderer.js and the css is beeing created on root, and when you try to open the quick access window, it will try to get renderer from the shortcutWindow folder, which is not there, but on root.

Have you fixed this?
