### ISSUE TITLE
Installation failing on Mac due to electron-builder

### ISSUE THREAD

**Issue by dland512** [chentsulin/electron-react-boilerplate#1101]
I'm trying to install on macOS 10.12.5 (Sierra) and getting this issue:

```
npm i
npm WARN prefer global colorguard@1.2.0 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> fcopy-pre-bundled@0.1.2 install /Users/dave/Desktop/temp/electron-react-boilerplate/node_modules/fcopy-pre-bundled
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/dave/Desktop/temp/electron-react-boilerplate/node_modules/fcopy-pre-bundled) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dave/Desktop/temp/electron-react-boilerplate/node_modules/fcopy-pre-bundled
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

I had a [similar issue](https://github.com/szwacz/electron-boilerplate/issues/278) in another electron seed that turned out to be related to [electron-builder](https://github.com/electron-userland/electron-builder). In that case the fix was to [bump the version](https://github.com/szwacz/electron-boilerplate/commit/6234bb4c4fb73d39c05bc4de4357d4023cdda740) of electron-builder.

I went ahead and tried that here and it seemed to work.

**Comment by amilajack** [comment]
See #400

**Comment by dland512** [comment]
Can you expound a bit on which aspect of that post applies? Is it the node-gyp stuff? I have that installed but I'm still seeing the issue. I also tried cleaning the cache and re-installing. No luck.

**Comment by amilajack** [comment]
What are your node and npm version? Try using the latest version of yarn and npm. Then follow number 3 of #400

**Comment by dland512** [comment]
Reinstalled the latest versions of node, npm, and yarn and it's working fine now. Not sure what that was about. ¯\_(ツ)_/¯ . Thanks for the help though.

**Comment by amilajack** [comment]
Just to help out others in the future, what versions were you using before? Were you using npm or yarn?

**Comment by dland512** [comment]
So it still happens when I try to use npm (version 3.10.10). When I use yarn it seems to work fine.
