### ISSUE TITLE
unable to get dockerode working.

### ISSUE THREAD

**Issue by sachethegde** [chentsulin/electron-react-boilerplate#1102]
I have installed dockerode (`npm install dockerode`) and the app did not run with the following error. 

ERROR in ./~/docker-modem/~/JSONStream/index.js
Module parse failed: /Users/sachet/Desktop/d-g-IGC/web-stage/dg-IGC/node_modules/docker-modem/node_modules/JSONStream/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #! /usr/bin/env node
| 
| var Parser = require('jsonparse')
 @ ./~/docker-modem/lib/modem.js 11:15-36
 @ ./~/dockerode/lib/docker.js
 @ ./app/components/helpers/dockerOperations.js
 @ ./app/components/Settings/Settings.js
 @ ./app/containers/settingsContainer.js
 @ ./app/routes.js
 @ ./app/containers/Root.js
 @ ./app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1212 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.js

Node  v8.1.2
npm  5.0.3

**Comment by amilajack** [comment]
See this comment https://github.com/chentsulin/electron-react-boilerplate/issues/1036#issuecomment-311232017

**Comment by sachethegde** [comment]
I had gone through #1036 before posting this issue and did not find the right solution addressed. However going through the above error, I have got into `index.js` of the library and removed this first line `#! /usr/bin/env node`
It worked.

**Comment by amilajack** [comment]
So does that mean you resolved the issue?

**Comment by sachethegde** [comment]
Yes. 
Thanks.
