### ISSUE TITLE
could not load dll plugin on `npm run package-win`

### ISSUE THREAD

**Issue by muscaiu** [chentsulin/electron-react-boilerplate#1103]
The app that i'm working on is built on top of the `electron-react-boilerplate`.

I'm debugging for 2 days an issue regarding the loading of a dll plugin (pepflashplayer.dll)
The dll is being loaded in a file very similar to `main.dev.js` using this code:
```
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname+'//lib//', pluginName))
```
**The plugin is being loaded correctly in dev and prod mode**, but when the app is being packaged `    "package-win": "npm run build && build --win --x64"`, **the plugin is not being loaded.**

I've taken the code apart and the problem is not in in the `main.dev.js` file.
I'm asking for your opinions since i'm a beginner in all of the technologies used.
Where do you think the problem is?

**Comment by amilajack** [comment]
Not sure how much I can help here because I never used a ppapi API before. My guess is that The file is located in your local environment but is not packaged with the app. Try checking to see if adding that file to your [files configuration](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L36) for electron-builder. See the docs for it [here](https://github.com/electron-userland/electron-builder/wiki/options#config--platformspecificbuildoptions).

**Comment by muscaiu** [comment]
Here are some tests i've made, trying to debug this issue.

1. The `pepflashplayer.dll` is being copied in `release/win-unpacked/resources/app/lib` folder, but i don't know how to check if the app has access to it.

2. The files field in `package.json` looks just like the boilerplate one:
```
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
```

3. I've been cloning the boilerplate and trying to load the plugin, but failed on all dev, prod, and package stages.

**Comment by muscaiu** [comment]
3. I succesfully loaded the plugin in `electron-react-boilerplate` dev and prod mode, but the problem is the same when `package-win`.

The only things added to the boilerplate is the `pepflashplayer.dll` file and this code:
**Home.js**
```
        <iframe src={url}</iframe>
```
**main.dev.js**
```

app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, 'pepflashplayer.dll'))

  mainWindow = new BrowserWindow({
    webPreferences: {
      plugins: true
    }
  });
```

Any chance webpack could be the issue here?
