### ISSUE TITLE
electron-react-boilerplate taking too much CPU.

### ISSUE THREAD

**Issue by sovanjana** [chentsulin/electron-react-boilerplate#1109]
Why this boilerplate package taking more than 35% CPU usage ?
Can anyone help me to get rid of some dependencies , I don't need all of these for my project ?

**Comment by uppe-r** [comment]
@sovanjana Are you on the latest boilerplate release?

**Comment by sovanjana** [comment]
@uppe-r I'm using version-0.12.0, and I think this is the latest available version of electron-react-boilerplate.

**Comment by uppe-r** [comment]
@sovanjana You're not cloning from master (v0.11.2), you're cloning the v0.12.0 branch. Try cloning master as described in README. Check also if you're doing everything else described in README (user yarn, for example).

Tried reproducing this with Node v7/v8, npm v4/v5 on two different computers and nothing... @amilajack any ideas?

**Comment by amilajack** [comment]
Might have something to do with these issues:
https://github.com/webpack/webpack/issues/701
https://github.com/webpack/webpack/issues/1706
https://github.com/webpack/webpack-dev-server/issues/472

**Comment by nikhilag** [comment]
If you just run `git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git your-project-name`, you still see `"version": "0.12.0"` in package.json. So I don't think the version is the problem here.

**Comment by nikhilag** [comment]
On simply following the instructions of using git clone, running `yarn` and then running `npm run dev`, I still see **27% CPU** being consumed by a blank application!

**Comment by uppe-r** [comment]
Have you tried https://github.com/webpack/webpack/issues/1706#issuecomment-280060069?

**Comment by amilajack** [comment]
Use this instead: `ignored: 'app/dist,app/main.prod.js,dll,flow-typed,node_modules,app/node_modules,release',`

**Comment by nikhilag** [comment]
In `webpack.config.renderer.dev.js`, I added the following `ignored` property in `watchOptions`:-

```
    watchOptions: {
      aggregateTimeout: 300,
      poll: 100,
      ignored: 'app/dist,app/main.prod.js,dll,flow-typed,node_modules,app/node_modules,release'
    },

```
But it didn't make any difference! I still see > 30% CPU being consumed.

**Comment by nikhilag** [comment]
Actually directly using the fix from https://github.com/webpack/webpack/issues/1706#issuecomment-280060069 seems to have worked! I am seeing around 3% cpu usage now :)
ignored property is supposed to be a regex which is why that string didn't work earlier. I simply used the following:-
```
    watchOptions: {
      aggregateTimeout: 300,
      poll: 100,
      ignored: /node_modules/
    },
```

**Comment by nikhilag** [comment]
I think we should consider making this a part of boilerplate code. Thoughts?

**Comment by amilajack** [comment]
@nikgraf Already did this locally.
