### ISSUE TITLE
Very high cpu requirement for development

### ISSUE THREAD

**Issue by nikhilag** [chentsulin/electron-react-boilerplate#1110]
In my case, the dev application is taking up 33% cpu approx which is extraordinarily high! Has anyone else seen this issue? How can I find out what's going on here?

**Comment by amilajack** [comment]
I've noticed this as well. Might be that webpack is doing some unnecessary work. Not sure at the moment.

**Comment by amilajack** [comment]
Duplicate of https://github.com/chentsulin/electron-react-boilerplate/issues/1110. Let's merge this into that discussion.

**Comment by nikhilag** [comment]
This issue is #1110. Kindly update the number of original issue here.

**Comment by amilajack** [comment]
Fixed
