### ISSUE TITLE
Blank page and missing manifest.json error on running prod version of application

### ISSUE THREAD

**Issue by nikhilag** [chentsulin/electron-react-boilerplate#1114]
On running the prod version using 'npm run build' and 'npm start', I get a blank application and the following error message:-

```
> Electron-App@0.12.0 start /Users/nikhilagarwal/electron-app
> cross-env NODE_ENV=production electron ./app/

Reading /Users/nikhilagarwal/electron-app/manifest.json failed.
Error: ENOENT: no such file or directory, open '/Users/nikhilagarwal/electron-app/manifest.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at getManifestFromPath (/Users/nikhilagarwal/electron-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:34:26)
    at Function.BrowserWindow.addDevToolsExtension (/Users/nikhilagarwal/electron-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:373:22)
    at App.Z.enabled.X.on (/Users/nikhilagarwal/electron-app/webpack:/~/electron-debug/index.js:78:1)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```
Why is it looking for a manifest.json? How can I fix this?

**Comment by nikhilag** [comment]
I made the following changes to temporarily fix my issue:-

1) Removed DEBUG_PROD part of if condition from app/main.dev.js for installing extensions

2) Changed configureStore.prod.js history object to createHashHistory() from createBrowserHistory(). I saw hash history being used in configureStore.dev.js and hence I made it same for prod.

**Comment by jonathanagosto** [comment]
I'd like to point out that the error related to the _"manifest.json missing ..."_ file, and the blank page are two different issues, at least for me. I followed @nikhilag [comment](https://github.com/chentsulin/electron-react-boilerplate/issues/1114#issuecomment-3124193060) and found that changing `createBrowserHistory` import to `createHashHistory` solved the blank page.

However, if you run `DEBUG_PROD=true npm start` to debug the app, then the _"manifest.json missing ..."_ manifests 😅

**Comment by nikhilag** [comment]
@jonathanagosto Yes these are two different issues and I updated the issue title to reflect that. Thanks for pointing this out.

**Comment by amilajack** [comment]
Was this issue resolved?

**Comment by jonathanagosto** [comment]
@amilajack I believe this issue requires a PR with changes to `configureStore.prod.js`. At least for the blank page issue.

**Comment by yourfavorite** [comment]
I have created a PR to fix the blank page issue. I am not sure what is the best way to solve the manifest.json error but it is still an issue for me. It does not seem to affect performance of the app.

**Comment by Strnadj** [comment]
@yourfavorite are you sure this is the "issue"? I'am having the same problem in my app, I solve that with https://github.com/ReactTraining/react-router/issues/4671.

**Comment by yourfavorite** [comment]
It fixed it for me.

**Comment by himanshu309** [comment]
@yourfavorite 
Hey can you tell me how you fixed it

**Comment by yourfavorite** [comment]
@himanshu309 See the 2 pull requests above. It was merged and should no longer be an issue in the current version. You may be having a similar result but different issue.
