### ISSUE TITLE
Flow raises "Required module not found" error

### ISSUE THREAD

**Issue by psamim** [chentsulin/electron-react-boilerplate#1115]
Hi,

Flow raises "Required module not found" error for my own files and local modules while the module exists and works fine.

![image](https://user-images.githubusercontent.com/1868679/27759656-20de018e-5e25-11e7-8bcb-17cd871c03fc.png)

Thanks

**Comment by amilajack** [comment]
List your directories here.

**Comment by psamim** [comment]
@amilajack Thanks for the quick reply but it seems that it was my fault. After some time the error is gone. Maybe it was an old daemon not reading the file changes.
