### ISSUE TITLE
Cannot open window!

### ISSUE THREAD

**Issue by AkashiX** [chentsulin/electron-react-boilerplate#1118]
I cannot open the window with 'npm run dev'. As follow:
![image](https://user-images.githubusercontent.com/23026766/27828681-fd6e1ed2-60ef-11e7-9c6d-192c08b51bf5.png)
What's up?

**Comment by amilajack** [comment]
I dont have enough information to debug this issue

**Comment by jonathanagosto** [comment]
I believe I've encountered that situation a few times, usually caused by a `debugger;` clause, or a breakpoint that paralyzes the thread before the windows open. My workaround is to activate the Electron window, go to _Windows > Enter Full Screen_. I hope it works for you!

**Comment by jgarec** [comment]
Hi,

Same problem for me and i have found a workaround.
The app try to install extensions at startup (see main.dev.js). Because of my corporate proxy, it hangs forever (no timeout)...

I still search for a way to set my proxy (with auth) for electron-devtools-installer ...
The workaround is to comment :
```
    'REACT_DEVELOPER_TOOLS',
    'REDUX_DEVTOOLS'
```

**Comment by nessup** [comment]
I just ran into this issue after accidentally leaving a breakpoint in the Inspector -- lost an hour in the process. I'm not exactly sure what an appropriate fix is here. Ideally the render thread would focus the Inspector when a breakpoint is hit. @amilajack Any thoughts? 

In the meantime, I got around it by launching main and render threads separately, which somehow caused the inspector to open.
