### ISSUE TITLE
something error on packing

### ISSUE THREAD

**Issue by Tanjh1996** [chentsulin/electron-react-boilerplate#1119]
When i pack my application today, it meet some errors. I reset to the previous version,it has the same error. how can i deal with it.
![error](https://user-images.githubusercontent.com/20512530/27858795-2bf61dae-61a9-11e7-971e-2a1b58f5a6c5.png)

**Comment by amilajack** [comment]
This is an issue with [`electron-builder`](https://github.com/electron-userland/electron-builder). I would recommend checking if your `build` config in your `./package.json` isnt missing any properties. If your config has all the necessary properties, then file the issue in the electron-builder repo.
