### ISSUE TITLE
cannot require('electron-prebuilt')

### ISSUE THREAD

**Issue by mleonard87** [chentsulin/electron-react-boilerplate#112]
Hi all,

I want to open an external url using `shell.openExternal` however, when I add `const shell = require('electron-prebuilt').shell;` I get an error in the dev tools console saying:

`Uncaught Error: ENOENT: no such file or directory, open '/path.txt'`

I have validated that the path.txt file exists in node_modules/electron-prebuilt. My assumption is that this is something to do with trying to read path.txt whilst in the context of the browser.

Is there some other way of requiring electron-prebuilt?

**Comment by chentsulin** [comment]
```
const shell = require('electron').shell;

shell.openExternal('https://github.com');
```

see https://github.com/atom/electron/blob/master/docs/api/shell.md#shell

**Comment by mleonard87** [comment]
That worked! Thanks!
