### ISSUE TITLE
Possible path issue on package-win

### ISSUE THREAD

**Issue by muscaiu** [chentsulin/electron-react-boilerplate#1120]
What is the difference between `npm run dev` and `npm package-win`.

I'm trying to find the reason why `pepflashplayer.dll` is being loaded ok on `dev` and `prod` mode, but **fails to load** on `package-win`.
I've been doing hundreds of tests inside a clean boilerplate changing the path and even adding the dll file in all the folders, but the issue is always the same.
Don't see any problem in `main.dev.js` or `package.json` and webpack is too confusing at this point.
So i'm thinking it could be a path problem somewhere, but i can't see where.
Any ideas would be highly appreciated.

This issue is related to [ #1103](https://github.com/chentsulin/electron-react-boilerplate/issues/1103)

**Comment by amilajack** [comment]
What does your directory structure look like? How are you including the dll file? What does your `files` config look like?

**Comment by amilajack** [comment]
What is the error you're getting?

**Comment by muscaiu** [comment]
It's always this one.   
![dllissue6](https://user-images.githubusercontent.com/11426309/28009792-674e02e4-6565-11e7-80aa-9a6eac3c2f13.jpg)
Same as if the path to the dll was wrong.

**Comment by amilajack** [comment]
And electron is throwing this error?

**Comment by muscaiu** [comment]
It's inside the iframe. Instead of the flash iframe to get loaded as it does in dev or prod mode, there is this error.

**Comment by amilajack** [comment]
Can you make a simple example project that replicates this error that I can clone? That would make it a lot easier for me to debug this.

**Comment by muscaiu** [comment]
Give me 5 minutes. I'll make a git repo.

**Comment by muscaiu** [comment]
Here is the link: https://github.com/muscaiu/electron-react-boilerplate-dll-issue

**Comment by muscaiu** [comment]
Is the demo ok? If you need anything please let me know.
I'm out of ideas, trying to find clues in the webpack configs, but i'm not too familiar with it.

**Comment by amilajack** [comment]
I haven't cloned it yet. Will investigate this today.

**Comment by muscaiu** [comment]
Could you explain how does electron or webpack should load the same `dll` file that is loaded ok in `dev` and `prod` mode with some code like this:
```
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname + '/lib/', 'pepflashplayer.dll'))
```
Is the file supposed to be archived and accesed somehow from withing that archive automatically?
Or should the file be loaded for example as `"extraResources": ["./app/lib/*.dll"]` and the path should be changed to match the `resources` folder ?

I have messed with the path in dozens of ways, copied the `dll` file in every folder, really don't know how to poke at it anymore.
This issue is turning out to be a real pain for the project. 
Please help! :>

**Comment by muscaiu** [comment]
Issuse fixed [here](https://github.com/electron-userland/electron-builder/issues/1829)
