### ISSUE TITLE
Flexible development structure

### ISSUE THREAD

**Issue by farskid** [chentsulin/electron-react-boilerplate#1129]
Hello there. First of all, thanks for the great job.
I just started to use your project and seems like a really firm structure for a scalable electron application. But there is a thing that somehow bothers me:
The structure you're using is kind of advanced in Javascript development environment, using linters and static type checks, ...
Wouldn't it be great if you created a CLI tool that creates boilerplate out of what developer actually needs? Many developers may not use linters or chances are they use Typescript! :)

**Comment by amilajack** [comment]
see https://github.com/chentsulin/electron-react-boilerplate/issues/1129

**Comment by farskid** [comment]
@amilajack Current issue is #1129!! Guess you are referencing the wrong URL?

**Comment by amilajack** [comment]
Sorry. meant https://github.com/chentsulin/electron-react-boilerplate/issues/1000
