### ISSUE TITLE
Native modules couldn't find their binary.

### ISSUE THREAD

**Issue by async3619** [chentsulin/electron-react-boilerplate#1133]
I want to use my own native modules on my react app that uses this boilerplate, but native module couldn't find their own binary. for example, I'll use `node-fibers` that lists on this boilerplate's document.

Suppose that you just completely installed this boilerplate:

```bash
git clone https://github.com/chentsulin/electron-react-boilerplate example-app
cd example-app
yarn
```

after It `yarn`ed successfully, I'll install `node-fibers` under `./app/` directory as documented on wiki:

```bash
cd ./app/
npm install --save fibers
```

Now, I'll inject a code snippet on `./components/Home.js` to use `node-fibers` native module:

```jsx
// @flow
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import styles from './Home.css';
import fibers from 'fibers'; // <-- this line has injected

export default class Home extends Component {
  render() {
    return (
      <div>
        <div className={styles.container} data-tid="container">
          <h2>Home</h2>
          <Link to="/counter">to Counter</Link>
        </div>
      </div>
    );
  }
}
```

And I tried to run this app but It stops working with an error:

```bash
cd ..
npm run dev
```

```
## There is an issue with `node-fibers` ##
`D:\Project\electron-react-boilerplate\app\node_modules\fibers\bin\win32-x64-54\fibers.node` is missing.

Try running this to fix the issue: D:\Project\electron-react-boilerplate\node_modules\electron\dist\electron.exe D:\Project\electron-react-boilerplate\app\node_modules\fibers/build
```

even if there's a `.\app\node_modules\fibers\bin\win32-x64-54\fibers.node` file. and this error occurs not only `node-fibers` module. this error occurs on my module too. It's my fault or webpack's fault? can I even solve this issue?

**Comment by amilajack** [comment]
See https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure

**Comment by async3619** [comment]
Not working, I've followed all recommendations on link you gave me, but It still not working.

I've tried this way:

```js
const foo = "fib";
const bar = "ers";

const fibers = require(foo + bar);
```

but this occurs `Cannot find module "."`, so I install it on `./package.json` instead of `./app/package.json`. but it not works too.

Do you even followed my question? can you give me exact answer how do I get rid of this error instead giving me a wiki link that I already read many times?

**Comment by amilajack** [comment]
Don't use `require()` use es6 imports

**Comment by async3619** [comment]
@amilajack yes, I've just used `import(foo + bar)` and it still occurs error `Cannot find module "."` too. 
and `import("fibers")` still prints out error:

```
## There is an issue with `node-fibers` ##
`D:\Project\electron-react-boilerplate\app\node_modules\fibers\bin\win32-x64-54\fibers.node` is missing.
```

and there's a binary in correct place.

**Comment by amilajack** [comment]
> can you give me exact answer how do I get rid of this error instead giving me a wiki link that I already read many times?

Sure. Preparing an example for you

**Comment by amilajack** [comment]
Hope this helps: https://github.com/amilajack/erb-node-fibers-example/blob/master/README.md

**Comment by async3619** [comment]
@amilajack sorry, It's not working too.

![img](https://img.dndcrew.us/af2f.png)

I don't know it occurs windows only, but It seems very big problem here. does it works well on your computer?

**Comment by amilajack** [comment]
Try `npm install -g node-gyp`

**Comment by async3619** [comment]
@amilajack oh I think It works well. It occurs because there's no `win32-x64-54` directory on `fibers/bin` path. It seems I'm using wrong version of electron or nodejs. I'll try change version. I really appreciate it!

**Comment by amilajack** [comment]
Try using the latest version of both node (`8.1.4`) and yarn

**Comment by async3619** [comment]
@amilajack I've just updated latest version of node (v8.1.4) and yarn still it requires `win32-x64-54`.

**Comment by amilajack** [comment]
You might want to create a bug report in that project. I don't think this issue is specific to this boilerplate.

**Comment by async3619** [comment]
@amilajack you was right. That was a bug of fibers. i really appreciate your help.
