### ISSUE TITLE
Implement API call (fetch)

### ISSUE THREAD

**Issue by nicolabortignon** [chentsulin/electron-react-boilerplate#1134]
Hi, first and foremost,
thanks for the great work!

I was trying to have some actions that run asynchronous api call. 
In react standard project I would use fetch. 

Unfortunately, I was not able to do something similar with this boilerplate.
Did anyone had any luck in implementing either a fetch node library, or any other solution with this boilerplate? (especially the packaging seems to be really tricky, as well as having those libraries being invoked in actions and not on the main thread).

**Comment by KELiON** [comment]
@nicolabortignon can you share your code/errors? Electron have 2 kinds of process: renderer process and `fetch` works well in such kind of process, but main process is just node process, so doesn't have browsers APIs. So, to call API in main process you'd need to use [node-fetch](https://www.npmjs.com/package/node-fetch) or included [http](https://nodejs.org/api/http.html)

**Comment by nicolabortignon** [comment]
Thank you @KELiON for the prompt answer.

To rephrase my question,
if I want to have an async call to an http resource in a react action in this boilerplate, how can I do it?

**Comment by nicolabortignon** [comment]
Turn out Fetch did work, just need to close the react hot reloader server and restart it.
