### ISSUE TITLE
PureComponent Breaks Hot Reloading

### ISSUE THREAD

**Issue by JakRazzi** [chentsulin/electron-react-boilerplate#1137]
Changing a react class to extend from PureComponent causes the hot module reloader to stop re-rendering. I would normally create this issue in react-transform-hmr, but that project is deprecated. Are there any plans to update to a new hot module reloader, or are we just waiting until something new comes out?

I'm happy to submit a PR if someone has a HMR package suggestion.

**Comment by amilajack** [comment]
We're using [react-hot-loader](https://github.com/gaearon/react-hot-loader)

**Comment by cramatt** [comment]
Should the README be updated then to remove the reference to HMR package on line 24? I was confused by this as well and didn't notice that although mentioned in the README, the HMR is no longer used in this project...
