### ISSUE TITLE
Configuring the default 'create desktop shortcut'

### ISSUE THREAD

**Issue by cathal-killeen** [chentsulin/electron-react-boilerplate#1139]
I am developing an application with this boilerplate code, and it has been invaluable to date (thank you, contributors!)

Apologies if this question has already been asked, but I couldn't find anything after some searching both here and in the official [Electron repo](https://github.com/electron/electron/issues). 

When I package my application (for Windows) there is a **'Setup' dialog** that displays before the main application starts. It includes a progress bar and some brief messages such as **'Create shortcut: C:\Users\some\path\...\Desktop\MyAppName.Ink'**

Is there some way I can configure this Setup dialog? Right now, **I would like to disable this desktop shortcut creation**, but ultimately it would be nice know how to configure all aspects of this Setup flow.

**Comment by talha131** [comment]
You will find relevant information in the `win` and `nsis` section of [electron-builder wiki](https://github.com/electron-userland/electron-builder/wiki/Options).

> `createDesktopShortcut` = `true` Boolean - Whether to create desktop shortcut.

**Comment by cathal-killeen** [comment]
Thank you @talha131
