### ISSUE TITLE
[Question] New Window with relative path

### ISSUE THREAD

**Issue by bennygenel** [chentsulin/electron-react-boilerplate#1142]
Hi;
I'm trying to open up a new window with relative path to main app.
I manage to get it working on development. When I run `npm run dev` it works just fine but when I pack the app with `npm run package-win` and run the exe new window gives an error 
`now allowed to open up local resources`

I have router set and page opens if I open it up directly on main window.

Here is my code sample:

```
previewOrders() {
    const parent = electron.remote.getCurrentWindow();
    const win = new electron.remote.BrowserWindow({
        show: false,
        useContentSize: true,
        title: 'Preview',
        parent,
        modal: true,
        minWidth: 600,
        minHeight: 600,
        webSecurity: false
    });
    setTimeout(() => {
        win.loadURL(`${electron.remote.getCurrentWindow().getURL()}/#/preview`);
    }, 2000);
    win.webContents.on('did-finish-load', () => {
        if (!win) {
            throw new Error('"mainWindow" is not defined');
        }
        win.openDevTools();
        win.show();
        win.focus();
    });
}
```
I run this function on a `onClick` prop from a `<Link />`

Thanks

**Comment by amilajack** [comment]
try
`webSecurity: false` should be in the `webPreferences` object.

```js
const win = new electron.remote.BrowserWindow({
  ...,
  webPreferences: {
    webSecurity: false
  }
});
```

**Comment by Unforgiven-wanda** [comment]
Tried your answer, it doesn't seem to work though.

**Comment by DanMMX** [comment]
@bennygenel @Unforgiven-wanda did you happen to find a solution to this ?

**Comment by Unforgiven-wanda** [comment]
@DanMMX I haven't tried it myself (I managed to "circumvent" the issue in my case) But I believe that what we were looking for was Electron's ```app.getPath('exe')``` that gives the path to the exectuable file. From there we can check whether the app is packaged or not (whether we're running in Dev or not), to either access the `resources` folder, or another folder.
