### ISSUE TITLE
execSync works in dev but not after Packaged the app.

### ISSUE THREAD

**Issue by nicolabortignon** [chentsulin/electron-react-boilerplate#1143]
I have this line of code:

`result = require('child_process').execSync('/usr/bin/which sb').toString();`

The idea is to execute a which to return the location of the command **sb** (which can or cannot be installed). 

Strangely enough, the command work when running in dev, and returns the right location of the command SB but it fails after packaging, with an error ' Command Fail'
Any idea why . ?

**Comment by amilajack** [comment]
What is the stack trace?

**Comment by nicolabortignon** [comment]
Interesting enough, if I change the command to '/usr/bin/which ping'  it does return the right location of ping (please note that sb is a custom command that I've created, not a system one, and it is usually in /usr/local/bin/sb)

@amilajack How can I read the stack trace from a packaged app? (I implemented a text field in the app to catch that, and I'm getting Command failed: /usr/bin/which sb.

The current, very ugly way that I have to do this is:

`   var result;
    try{
      result = require('child_process').execSync('/usr/bin/which sb').toString();
      consoleBuffer = consoleBuffer + result;
      if(result.length > 0 ){
        return true;
      } else {
        return false;
      }
    }catch(error){
      consoleBuffer = consoleBuffer + error.toString();
    }`

**Comment by amilajack** [comment]
> How can I read the stack trace from a packaged app
[This is in the readme](https://github.com/chentsulin/electron-react-boilerplate#devtools-extension)

Also I don't think this is an issue with the boilerplate. Seems like a more use-case specific issue. Going to close this but lets continue the discussion.

**Comment by nicolabortignon** [comment]
I managed to package with the DEBUG_PROD=true flag. This will be definitely a time saver.

I logged the stacktrace of the above code,
The try fails, and it gets caught with:

 

> : Command failed: /usr/bin/which sb
> 
> 
>     at checkExecSyncError (child_process.js:493:13)
>     at Object.execSync (child_process.js:533:13)
>     at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:685:22)
>

**Comment by nicolabortignon** [comment]
I've crossposted here: https://github.com/electron/electron/issues/10094  since it seems more of an electron issue as @amilajack  was pointing out

**Comment by amilajack** [comment]
By electron issue, i meant its more of a issue about how to use electron. I dont think its a bug with electron. I would recommend asking that question in a discussion instead of creating an issue because it makes it easier for maintainers/

**Comment by nicolabortignon** [comment]
Why do you think is not a bug?
I currently have this 4 scenarios:

with standard commands (ie.: ping)
Dev= Works
Prod= Works

with custom commands (ie.: sb)
Dev= Works
Prod= Doesn't Work

**Comment by amilajack** [comment]
I believe that there is something wrong with your use case. Just my assumption. Electron is pretty battle-tested. Finding a bug in it would be like finding a bug in node or chrome. Pretty unlikely

**Comment by nicolabortignon** [comment]
Fair point!

Do you know if child_process is executed differently when in dev vs in prod? Maybe there are some Enviroment variables or $PATH set differently between the two, and when executing in prod, child _process doesn't have visibility into /usr/local/bin but can access /sbin/

**Comment by amilajack** [comment]
Lets move this discussion to [gitter](https://gitter.im/electron-react-boilerplate/Lobby) because its getting pretty lengthy. I don't believe there is a difference between them
