### ISSUE TITLE
[Question] Relative path of urls in css?

### ISSUE THREAD

**Issue by wassgha** [chentsulin/electron-react-boilerplate#1146]
Hello. I have the following structure in my project:

> app
> - styles
> -- myscss.scss
> -- fonts
> --- myfont.ttf

In myscss.scss I have
`
@font-face {
  font-family: 'weathericons';
  src: url('fonts/myfont.ttf');
  font-weight: normal;
  font-style: normal;
}
`

However I get 
`
Module not found: Error: Can't resolve 'myfont.ttf' in '/Users/wassgha/Downloads/electron-react-boilerplate-master/app/styles'
`
I am sure I am doing a very stupid mistake. Can someone please point it out :( .

Thank you!
/cc @amilajack

**Comment by wassgha** [comment]
Update, I figured out that `~` is the `node_modules` folder so I am using `~/../styles/fonts/myfont.ttf` and it works. However, I feel that there's a cleaner solution...

**Comment by uppe-r** [comment]
Have you tried `'./fonts/myfont.ttf'` ?

**Comment by wassgha** [comment]
I see, that worked :) ! Thanks
