### ISSUE TITLE
install-app-deps options when rebuilding dependencies

### ISSUE THREAD

**Issue by kosiokarchev** [chentsulin/electron-react-boilerplate#1149]
I am working on a project that uses `node-sqlite3`, but it also needs ICU support, so I am building it against a local instance of libsqlite by:
`npm install --build-from-source --sqlite=/path/to/my/sqlite`

In order to be able to use node-sqlite3 in an Electron app, though, I have to rebuild it using
`electron-build install-app-deps`
It seems like this step is somehow discarding my previous reference to the local libsqlite. Is there a way to specify these command line options for when electron-builder rebuilds my dependencies?

**Comment by amilajack** [comment]
This is more of a question about electron-builder. Please file that issue there.
