### ISSUE TITLE
Native module tries to find native module binary on wrong path.

### ISSUE THREAD

**Issue by async3619** [chentsulin/electron-react-boilerplate#1150]
I have installed `serialport` (as known as `node-serialport`) module on ./app directory. but It prints error because the module tries to find native module binary on wrong path when I try to import that module.

Helpful screenshot below:

![image](https://img.dndcrew.us/889a.png)

The native module **should** find their binary on their module path. not project path. and this problem isn't fault/bug of `serialport`, because my own native module prints same error too.

**Comment by amilajack** [comment]
Made [this example](https://github.com/amilajack/erb-serialport-example) for you. Let me know if it works for you.

**Comment by async3619** [comment]
@amilajack Thanks, It works! but there was an error when I `yarn` on `./erb-serialport-example` directory but that seems compile error.

Can I use that example as boilerplate of my project?

**Comment by amilajack** [comment]
What is the error?

**Comment by async3619** [comment]
```
fatal error LNK1104: 'D:\Project\erb-serialport-example\app\node_modules\serialport\build\Release\serialport.node'
```

but this seems not important. Isn't it? It worked well.

**Comment by amilajack** [comment]
Seems like an issue with the dependency

**Comment by async3619** [comment]
@amilajack I have a question: Why this boilerplate was finding native module binary in wrong path? I just cloned master branch of this boilerplate and just import it. I think I wasn't doing different with your example. Did you have some update your code before?

**Comment by async3619** [comment]
@amilajack Oh I just found what is the main problem, Trying to import a module that isn't installed with package manager (maybe `yarn` or `npm` whatever thing that)  and I just copied a whole module folder on `./node_modules` path. That was the problem. 

How about note `you should install native module properly to use it on renderer process` on README.md or somewhere?
