### ISSUE TITLE
Unable to import leveldown for windows build   [win32 and 64 installers]

### ISSUE THREAD

**Issue by 9gaurav** [chentsulin/electron-react-boilerplate#1153]
I am using pouchdb with leveldb backend for local storage.

I have added following dependancies to  ./app/package.json
```
"dependencies": {
    "level": "^1.7.0",
    "pouchdb": "^6.2.0"
  }
```

I have rebuild pouchdb using

```
yarn add --dev electron-rebuild
./node_modules/.bin/electron-rebuild --version=1.7.0 --force --types prod,dev,optional
./node_modules/.bin/electron-rebuild --version=1.7.0 --force --types prod,dev,optional --module-dir app
```

It works fine with package created for Mac. 
But win32 and win64 packages fail to connect to leveldb with an error.

Here is my code to test levelDB connection.
```
leveldbDB.info().then(function (info) {
     console.log('We can use PouchDB with LevelDB! ');
   }).catch(function (err) {
     console.log('Error for LevelDB'+err);
   });
```
And here is the error.
```
Error for LevelDB:
Error: %1 is not a valid win32 application.
\\?\C:\Users\Gaurav\AppData\Local\Temp\1C0C.tmp.node: unable to import leveldown
```

**Comment by amilajack** [comment]
I suspect that this is an issue with the dependency rather than the boilerplate

**Comment by 9gaurav** [comment]
@amilajack 

Ok So I tried reducing / changing dependancies. I removed level or leveldown from dependancies.

Tried following two combination by taking reference from 
https://github.com/nolanlawson/hello-electron-with-pouchdb/blob/master/package.json

Again both combinations work fine for dev and prod for Mac. But I get same error on Windows.

**Dependancy 1**
```
"dependencies": {
    "pouchdb": "^6.2.0"
  }
```
For adapter
```
// LevelDB

var NodePouchDB = require('pouchdb');

var leveldbDB = new NodePouchDB('mydb-leveldb');
```

And


**Dependancy 2**
"dependencies": {
    "pouchdb": "^6.1.0",
    "pouchdb-adapter-node-websql": "^6.1.0"
  }
For adapter
```
// node-websql

NodePouchDB.plugin(require('pouchdb-adapter-node-websql'));
var sqliteDB = new NodePouchDB('mydb-sqlite', {adapter: 'websql'});
```

**Comment by 9gaurav** [comment]
I tried many ways and combinations of dependancies. Still same error. I tried using sqlite adapter as well. In that case app does not lauch to foreground. I can see background process in task-manager. I am trying to build heavy client app with lots of data to be saved on local side for offline use.

If this does not work , any other alternatives I can use?

e.g.

```
"dependencies": {
    "pouchdb": "^6.1.0",
    "pouchdb-adapter-node-websql": "^6.1.0"
  }
```

**Comment by amilajack** [comment]
Try adding all the pouched dependencies to `./app/package.json` and uninstalling them from `./package.json`

**Comment by 9gaurav** [comment]
Tried adding all pouchdb dependencies to `./app/package.json` no dependencies in `./package.json`

Still same error.
```
Error: %1 is not a valid win32 application.
\\?\C:\Users\Gaurav\AppData\Local\Temp\88EE.tmp.node: unable to import leveldown
```

Based on https://www.npmjs.com/package/pouchdb my `./app/package.json` looks like this.
```
"dependencies": {
    "argsarray": "^0.0.1",
    "buffer-from": "^0.1.1",
    "clone-buffer": "^1.0.0",
    "debug": "^2.6.8",
    "double-ended-queue": "^2.1.0-0",
    "immediate": "^3.2.3",
    "inherits": "^2.0.3",
    "level-codec": "^7.0.0",
    "level-write-stream": "^1.0.0",
    "leveldown": "^1.7.2",
    "levelup": "^1.3.9",
    "lie": "^3.1.1",
    "ltgt": "^2.2.0",
    "pouchdb": "^6.2.0",
    "readable-stream": "^2.3.3",
    "request": "^2.81.0",
    "spark-md5": "^3.0.0",
    "through2": "^2.0.3",
    "uuid": "^3.1.0",
    "vuvuzela": "^1.0.3"
  }
```

**Comment by 9gaurav** [comment]
Here is what I found over internet about this issue.

Possible culprits
- node on development machine is x64 and one bundled with release is ia32

- My build is ia32 but libraries I am using are x64 [ unlikely ]

- My libraries are ia32 but thier dependancies are x64 [ unlikely]

- Issue with including dependancies while creating package


To avoid delays in development I am now using https://github.com/jviotti/electron-json-storage instead of `pouchdb` as temporary measure.  

Other recomended solution is building windows building using windows maching. Which I cant test right now due to time constraints.

If someone can help please do drop a comment or mail.

**Comment by amilajack** [comment]
Closing because this seems application specific

**Comment by aguynamedben** [comment]
@9gaurav I'm running into this too, did you ever find a solution? PouchDB+leveldown work fine on macOS but not on Windows 7.

**Comment by courageDeveloper** [comment]
Check out https://github.com/nolanlawson/hello-electron-with-pouchdb
