### ISSUE TITLE
webpack production  url-loader  limit   path error 

### ISSUE THREAD

**Issue by IDrinkMoreWater** [chentsulin/electron-react-boilerplate#1156]
webpack.config.renderer.prod.js  modify

```
{
        test: /\.(?:ico|gif|png|jpg|jpeg|webp)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 10000,
          }
        }
      }
```

Home.js  modify
```
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import styles from './Home.css';
import logoIcon from './images/logo.png';

export default class Home extends Component {
  render() {
    return (
     <div>
        <div className={styles.container} data-tid="container">
          <h2>Home</h2>
          <img src={logoIcon} alt="logo" />
          <Link to="/counter">to Counter</Link>
        </div>
      </div>
    );
  }
}
```

console log

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///D:/Documents/Desktop/electron-react-boilerplate/dist/7b83e16ed2ae3841129ae710997b48eb.png
```

but,The correct should be 
` file:///D:/Documents/Desktop/electron-react-boilerplate/app/dist/7b83e16ed2ae3841129ae710997b48eb.png`

**Comment by amilajack** [comment]
Try changing [this line](https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/webpack.config.renderer.prod.js#L25) from `publicPath: '.,/dist/',` to `publicPath: './dist/',`

**Comment by IDrinkMoreWater** [comment]
@amilajack  publicPath: '../dist/', to publicPath: './dist/'，I tried it，but  it  will  bring more problems.
All other‘s image will  throw  exceptions，

**Comment by amilajack** [comment]
Set the public path [like so for extract css](https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/webpack.config.renderer.prod.js#L35)

**Comment by IDrinkMoreWater** [comment]
it's working ,thank you very much
