### ISSUE TITLE
How to use roboto-fontface (npm)

### ISSUE THREAD

**Issue by anthonyraymond** [chentsulin/electron-react-boilerplate#1157]
Hi,

i'm trying to include roboto-fontface to my Electron app, but i fail lamentably and i have no clues why it's not working...

### How to reproduce
1. `yarn add roboto-fontface`

<br />

2. add this line to `app.global.css`:
```
@import "~roboto-fontface/css/roboto/roboto-fontface.css";
```

3. `npm run dev`

### Error
Now i expect Roboto fonts to be packaged and available, but they are not, and i can see and error in console log:

```
GET file:///C:/Users/*******/workspace/my-app/app/b2a6341ae7440130ec4b4b186aff8413.woff2 net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/*******/workspace/my-app/app/ab96cca26751239828b8e9c524cca5bb.woff2 net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/*******/workspace/my-app/app/081b11ebaca8ad30fd092e01451015dc.woff net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/*******/workspace/my-app/app/ad140ff02a7091257e2b31619106194e.woff net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/*******/workspace/my-app/app/99b14f0da0591e0d71678dc163eaff8b.ttf net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/*******/workspace/my-app/app/56a76a220d9c9765946d0802d4d661c4.ttf net::ERR_FILE_NOT_FOUND
```

Am i missing something?

**Comment by amilajack** [comment]
Install the package to your `./app/package.json`

**Comment by anthonyraymond** [comment]
Alright... it works, it is still obscure why some dependencies need to be in the nested package.json...

Thanks for your help 😃

**Comment by amilajack** [comment]
All dependencies that you don't want to be processed with webpack should go in the `dependencies` of `./app/package.json`.

**Comment by anthonyraymond** [comment]
Woaw awesome, haven't seen that you wrote some wiki pages. I'll take a look at that.
Thanks

**Comment by soriyath** [comment]
could you add this to the README.md? it could save people a lot of time.

**Comment by amilajack** [comment]
Its already in the readme

**Comment by bn3t** [comment]
https://github.com/chentsulin/electron-react-boilerplate/issues/1495 Contains the fix for the production build:

In webpack.config.renderer.prod.js:

output: {
    path: path.join(__dirname, 'app/dist'),
    publicPath: '../dist/',
    filename: 'renderer.prod.js'
  },
