### ISSUE TITLE
Getting a click event on a frameless window Menu Bar

### ISSUE THREAD

**Issue by muscaiu** [chentsulin/electron-react-boilerplate#1158]
I need to get the double click event from the top menu bar to change the full screen box from full to normal.
Tried adding click events on `content` or `content-header` divs, but nothing happens.

It is a special zone of the window, since right clicking displays the menu you see in the picture.
How can i get a click event on that?

![header](https://user-images.githubusercontent.com/11426309/28781593-46be310c-7613-11e7-823c-b4a106010430.png)

**Comment by uppe-r** [comment]
@muscaiu I don't really understand what you mean by "change the full screen box from full to normal", but about getting events from the top menu bar when using `-webkit-app-region: drag` [check this](https://github.com/electron/electron/issues/1354#issuecomment-300860582)

**Comment by muscaiu** [comment]
Sorry for not being clear enough, it's really simple to explain if you sit next to me, but more difficult to explain by text :-) I will try again.

![header](https://user-images.githubusercontent.com/11426309/28814949-4b6fed7c-76a8-11e7-9f71-dcf8f05ccf7d.png)


I'm able to switch from full screen to normal by clicking on ▭ (pic selection1),  or double clicking anywhere on the menu bar (pic selection2).
I am able to change from this ![menu2](https://user-images.githubusercontent.com/11426309/28814547-b59bf8f0-76a6-11e7-9c9b-4b5f73871e54.png) to this ![menu1](https://user-images.githubusercontent.com/11426309/28814558-c2312644-76a6-11e7-9472-c348f8114833.png) by clicking on the ▭, because i can just add a click event to it.

**I need to be able to get the double click event from the menu bar** to update the UI in the same way from this ![menu2](https://user-images.githubusercontent.com/11426309/28814817-c19b4470-76a7-11e7-91f4-b29036193c6e.png) to this  ![menu1](https://user-images.githubusercontent.com/11426309/28814826-ce7e5a7e-76a7-11e7-8d94-8b916b64406f.png), and there is no div that will do that.

**Comment by amilajack** [comment]
Maybe try adding an onclick event listener and call an electron api that will do that. This is more of an app-specific issue. Closing because its not directly related to the boilerplate but feel free to continue the discussion.

**Comment by uppe-r** [comment]
@muscaiu Try using Electron's BrowserWindow maximize event as described in https://github.com/electron/electron/blob/master/docs/api/browser-window.md

**Comment by muscaiu** [comment]
Thanks for the idea, but how can add this in React?

Right now i'm using this in the click event of the Header.

```
  handleFullscreen(e) {
    e.preventDefault();

    if (remote.getCurrentWindow().isMaximized()) {
      remote.getCurrentWindow().unmaximize();
    } else {
      remote.getCurrentWindow().maximize();
    }
    this.props.toggleFullScreen()
  }
```
If i add this to `render()`, my screen will probably explode =)

**Comment by uppe-r** [comment]
Hey @muscaiu , that is one way, I guess you're trying to make "your own titlebar" without using app-region, right?
My idea (easier I believe):
```jsx
import { remote } from 'electron';
...
componentDidMount() {
    const appWindow = remote.getCurrentWindow();
    appWindow.on('maximize', () => {
      // do whatever you need to when window is maximized
    });
    appWindow.on('unmaximize', () => {
      // do whatever you need to when window is unmaximized
    });
  }
```
Pretty much, everything will work as it is with `-webkit-app-region: drag`, but you'll be able to execute code every time the window is maximized and unmaximized (change the button) - **this also works with double click on the titlebar**.

**Comment by uppe-r** [comment]
Can you post toggleFullscreen please? @muscaiu

**Comment by muscaiu** [comment]
The `togglefullScreen()` is a simple action that toggles the Redux `fullScreen` state to `true` or `false`.
```
    const initialState = {
        fullScreen: false
    };
    ......
        export default function window(state = initialState, action: actionType) {
            switch (action.type) {
                case 'WINDOW_TOGGLE_FULLSCREEN':
                    return {
                        ...state,
                        fullScreen: ! state.fullScreen
                    }
```
What i'm curios is why is that function logging the output twice.

**Comment by muscaiu** [comment]
I had some 'test code' in the render function. That's why the double output was happening.
All good now. 
Thank you @uppe-r !

**Comment by muscaiu** [comment]
I got hasty didn't fully tested all pages.

The Header is being imported and loaded in every page.
This is the output from testing in 3 pages:
![loadedtwice](https://user-images.githubusercontent.com/11426309/28868239-88a39c5a-7781-11e7-82c9-b8d9517817e4.png)
So in every page chage, the output is being incremented by 1.

Any way i could **re-initialize the appWindow** before the component is being reloaded?

**Comment by uppe-r** [comment]
Hey @muscaiu, place all the code inside `componentDidMount `(and `componentDidMount `itself) on the `App` component insider of the `containers `folder. The thing here is that as you were mounting header again, and again, and again, the `appWindow.on('maximize / unmaximize')` event was called as many times as header had been mounted. By placing the code inside a parent component that is mounted once only, like `App`, the event will only be called once 😄

**Comment by muscaiu** [comment]
@uppe-r , i appreciate your patience. Right now the app's `routes` looks like this:

```
export default (
  <Route path="/" component={App}>
    <IndexRoute component={AccountPage} />
    <Route path="/home" component={HomePage} />
    ...
```
The `App.js` file looks like this:
```
    return (
        <MuiThemeProvider>
          {this.props.children}
        </MuiThemeProvider>
```
So if i understand correctly, your suggestion is to load the Header directly in the main `App`, and remove it from every file?

**Comment by uppe-r** [comment]
@muscaiu Nope, just place 
```jsx
componentDidMount() {
    console.log('header mounted')

    const appWindow = remote.getCurrentWindow();

    appWindow.on('maximize', () => {
      console.log('maximize')
      this.props.toggleFullScreen()
    })
    appWindow.on('unmaximize', () => {
      console.log('unmaximize')
      this.props.toggleFullScreen()
    })
  }
```
inside of App.js. This way, every time you maximize/unmaximize the window, that code ^ is still called, but is defined only ONCE, since the App component doesn't get rendered multiple times.

**Comment by Antix-Development** [comment]
I today discovered this exact issue and for me it seems that any element with `-webkit-app-region: drag;` will NOT receive any clicking events, hence you are unable to change your maxamize/restore imagery as you would like.

I found a messy partial solution on https://gist.github.com/jorgeortega/59ec45e572ef247ace57bbdf3600faec

My final solution was to add 

'
window.addEventListener('resize', (e) => {
    (screen.availWidth - window.innerWidth === 0) ? document.getElementById('window-maximize-btn').src = 'svg/restore.svg' : document.getElementById('window-maximize-btn').src = 'svg/maximize.svg';
});
'

I know its old news maybe but I thought I'd at least share my personal grief and solution just in-case somebody else finds it useful.
