### ISSUE TITLE
Not working normally after npm package.

### ISSUE THREAD

**Issue by uyu423** [chentsulin/electron-react-boilerplate#1161]
`npm run dev` is working.
`npm run build && npm run start` is working.
`npm run package && ./release/linux-unpacked/electron-react-boilerplage` is not working

![image](https://user-images.githubusercontent.com/8033320/28925570-308ab786-78a0-11e7-8406-8ef6b80a1e8a.png)

Is there an expected reason?

**Comment by uyu423** [comment]
When I did `asar list app.asar | grep react`, react did not appear. Is it normal?

**Comment by uyu423** [comment]
I'm trying to do a lot of things, and I added `react` and `react-dom` to the dependencies in `./app/package.json`, so the error message changed. I should try a little more.

**Comment by uyu423** [comment]
I modified `./app/package.json` as follows, and it works fine. Is this normal? I do not think so.

```json
{
  "name": "electron-react-boilerplate",
  "productName": "electron-react-boilerplate",
  "version": "1.0.0",
  "description": "Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development",
  "main": "./main.prod.js",
  "author": {
    "name": "C. T. Lin",
    "email": "chentsulin@gmail.com",
    "url": "https://github.com/chentsulin"
  },
  "scripts": {
    "postinstall": "npm rebuild --runtime=electron --target=1.6.6 --disturl=https://atom.io/download/atom-shell --build-from-source"
  },
  "license": "MIT",
  "dependencies": {
    "escpos": "^2.4.2",
    "moment": "^2.18.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-addons-css-transition-group": "^15.6.0",
    "react-addons-transition-group": "^15.6.0",
    "react-dom": "^15.6.1",
    "react-hot-loader": "3.0.0-beta.6",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",
    "redux": "^3.7.1",
    "redux-thunk": "^2.2.0",
    "reactstrap": "^4.8.0"
  }
}
```

**Comment by uyu423** [comment]
For reference, boilerplage v0.12.0 is being used.

**Comment by amilajack** [comment]
Please read [this wiki](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure). Your dependencies are in the wrong `package.json`. The docs explain this.

**Comment by uyu423** [comment]
@amilajack According to the wiki, `package.json` includes a library related to react, and `./app/package.json` seems to contain only native modules. Is this right? So why should I include react in `./app/package.json` to work?

**Comment by amilajack** [comment]
Include it in `./package.json`

**Comment by uyu423** [comment]
@amilajack  That method did not work properly. It just prints the message 'not found module react' as mentioned in the text.

**Comment by uyu423** [comment]
Unlike the README, the react package should also be included in `./app/package.json` so that it builds normally. Why is this issue closed? I want someone to explain to me.

**Comment by billel-boudchicha** [comment]
@uyu423 have the same problem here but with `moment.js`, i had to install it to the `./app/package.json` , otherwise , `cannot find module moment`
