### ISSUE TITLE
history.push changes location but does not render component.

### ISSUE THREAD

**Issue by yourfavorite** [chentsulin/electron-react-boilerplate#1168]
I am using nedb for a local data store. Inside of app/index.js, I load the data from my database then dispatch an action that loads the data into the store and pushes the url from `/` to `/groups/{first group id`. Using history.push seems to update the URL but the page does not re-render showing the group page.

```
const loadNedb = () => {
  groups.getAllTasks()
  .then(data => {
    const formattedGroups = {};
    data.forEach(g => {
      formattedGroups[g._id] = g;
    });

    store.dispatch(loadGroups(formattedGroups));
    history.push(`/groups/${data[0]._id}`);
    return true;
  })
  .catch(e => {
    console.log('ERROR:', e);
  });
};
```

**Comment by yourfavorite** [comment]
My apologies. In my research I thought this was a bug related to BrowserHistory. Turns out it was misconfiguration on my part. Please ignore.

**Comment by msadraka** [comment]
I have same issue! Can you describe about how to solve this problem and/or refer to the BrowserHistory issue?

**Comment by yourfavorite** [comment]
@msadraka I'm really sorry as I hate when people say "Got it fixed" and then don't explain how for people that run into this in the future. Yet I did it here. :( Sadly I don't even remember running into this issue, let alone what I did to fix it.
