### ISSUE TITLE
Cannot find module in 'app' directory

### ISSUE THREAD

**Issue by DSBalaban** [chentsulin/electron-react-boilerplate#1170]
Title is based on the error I'm facing, but feel free to edit it to something more appropriate.

I have a few services that I need to use in both the React and the Electron parts of the application. I actually switched to this boilerplate to solve this very problem, and yet:

`import constants from 'lib/constants';` works fine in the renderer, whereas the same does not work in the main process at all, saying it couldn't find that module. 

This is likely a misunderstanding on my part, since I was hoping I could have both the renderer and main processes look for modules in `app` and `node_modules`, but I can't get it working. 

What I'd like to know is:

1. Can I actually accomplish what I mentioned above?
2. My electron code is in `app/backend`, should it be elsewhere?
3. If I can't synchronize the module paths between React and Electron (or Node, if you will) as I've been trying to, how should I go about it? 

More of the same:

Inside `containers/App/index.js`:

```
import constants from 'lib/constants';
console.log(constants); // works as expected
```

Inside `main.dev.js`:

```
import constants from 'lib/constants'; // throws error, module not found
```

Note that `lib/constants` is a custom file of mine, it's _not_ in `node_modules`. 

Furthermore, here's the resolve code in webpack config:

```
resolve: {
    extensions: ['.js', '.jsx', '.json'],
    modules: [
      path.resolve(__dirname, 'app'),
      'node_modules',
    ]
  }
```

**Comment by talha131** [comment]
It seems your `package.json` is messed up. Can you please go through [this wiki article](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure) and confirm you have your modules in the right `package.json`?

**Comment by DSBalaban** [comment]
@talha131 Thank you for the reply. I checked all the packages, and the wildest of them use CoffeeScript, but none of them use C/C++. My `app/package.json` is empty.
