### ISSUE TITLE
How to remove CSS modules completely from the boilerplate ?

### ISSUE THREAD

**Issue by sovanjana** [chentsulin/electron-react-boilerplate#1172]
I want to remove **CSS Modules** completely from this boilerplate as I don't want to use **CSS Modules**.
Help me to get rid of this problem. @chentsulin

**Comment by yeraydiazdiaz** [comment]
According to the [`css-loader` options docs](https://github.com/webpack-contrib/css-loader#options) you just need to remove or set to `false` the `modules` property in all `css-loader` options.

For example [this line of the webpack.config.renderer.prod](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.prod.js#L46).
