### ISSUE TITLE
Required module not found. When using react-redux-form

### ISSUE THREAD

**Issue by yourfavorite** [chentsulin/electron-react-boilerplate#1174]
`import { combineForms } from 'react-redux-form';` has been added to my index.js reducer and now I get a `Required module not found.` error.

```
app/reducers/index.js:4
  4: import { combineForms } from 'react-redux-form';
                                  ^^^^^^^^^^^^^^^^^^ react-redux-form. Required module not found
```

**Comment by amilajack** [comment]
This is application specific. You need to install the flow types for that package. `flow-typed install`

**Comment by yourfavorite** [comment]
Ah sorry. I am new to Flow.

What is the solution for handling this error when a package does not have flow types? Or would this error not appear unless the package did have flow types?

**Comment by amilajack** [comment]
You should either install the dependencies. If there are no types then flow will stub the dependencies. For more information, please refer to the flow community.
