### ISSUE TITLE
Error: Cannot find module: 'jest-cli'

### ISSUE THREAD

**Issue by JimmyMow** [chentsulin/electron-react-boilerplate#1175]
After installing and trying to run `npm run test` it cannot find `jest-cli` or `xtend`

Not sure what I'm doing wrong here. Any help would be much appreciated. Thanks

**Comment by JimmyMow** [comment]
I ended up running `yarn add jest-cli -S` and received the following error output:

`
error /Users/jmow/Projects/bolt/bolt-desktop/node_modules/electron: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /Users/jmow/Projects/bolt/bolt-desktop/node_modules/electron
Output:
/Users/jmow/Projects/bolt/bolt-desktop/node_modules/electron/install.js:48
  throw err
  ^

Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/Users/jmow/Projects/bolt/bolt-desktop/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

But then ran the tests and the application and it is working. Also added xtend to my dev-dependencies. Would love some insight on why it's working, I don't really understand

**Comment by amilajack** [comment]
What are your OS, node, and npm versions? What steps did you follow to install the boilerplate? Did you make any changes to the boilerplate after cloning it?

**Comment by JimmyMow** [comment]
MacOS Sierra Version 10.12.5
Node v8.3.0
NPM 5.3.0

Yeah, I added lots of dependencies via npm. I can paste my package.json and yarn.lock if that would help?

**Comment by amilajack** [comment]
Don't switch between `yarn` and `npm`. That should fix your issue. 

```bash
rm -rf node_modules && rm -rf app/node_modules
yarn
```
