### ISSUE TITLE
Browser history not working in electron app

### ISSUE THREAD

**Issue by chie4hao** [chentsulin/electron-react-boilerplate#1178]
My electron app works fine with HashHistory, but when I switch to browserHistory,not working fine.
I noticed that the two have different initial pathname.
```bash
const history = createHashHistory();
console.log(history.location.pathname);     
//  "/"
```
```bash
const history = createBrowserHistory();
console.log(history.location.pathname);     
//  "/C:/Users/asdf/Documents/GitHub/electron-react-boilerplate/app/app.html"
//  This path matches the route "/C:/"
//  and when I use "history.goBack()" and "history.goForward()" also found some errors
```

**Comment by chie4hao** [comment]
then i use the following code, the problem is solved.
```bash
const history = createBrowserHistory({
  basename: window.location.pathname
});
```

**Comment by barretron** [comment]
Just ran into this same issue. Thanks for providing the solution!

**Comment by ericpyle** [comment]
May be superceded by https://github.com/chentsulin/electron-react-boilerplate/pull/1184

https://github.com/chentsulin/electron-react-boilerplate/commit/30aca607f25c774e5766fd8aeca48ead29e17a63
