### ISSUE TITLE
Firing redux actions from the application menu

### ISSUE THREAD

**Issue by slightlytyler** [chentsulin/electron-react-boilerplate#118]
What's the preferred way of hooking the application menu into redux? I've implemented undo / redo but am having trouble firing the actions from the menu click. It would be nice to have an example of this included in the repo

**Comment by jhen0409** [comment]
We can use [ipc](https://github.com/atom/electron/blob/master/docs/api/ipc-main.md) to do it.
Also, if we done #108, it may become easier. :)

**Comment by slightlytyler** [comment]
@jhen0409 I am interested in #108 however I would like to see the starter include an example of how to accomplish it without redux-electron-store. 

In my app I created a function `bindStoreToMenu` that is called when the store is configured. Also created a middleware `undoRedoMenuState` to properly set the enabled boolean for the menu items. 

https://github.com/slightlytyler/mocksy/blob/master/app/store/bindStoreToMenu.js
https://github.com/slightlytyler/mocksy/blob/master/app/store/undoRedoMenuState.js

Any feedback on my logic is welcome, I'll gladly contribute what I can if this is something the project would like to include

**Comment by amilajack** [comment]
@burkhardr is it possible to do this with `electron-redux`?

**Comment by burkhardr** [comment]
@amilajack Yeah, couldn't see why not!

**Comment by amilajack** [comment]
Great! Closing this in favor of https://github.com/chentsulin/electron-react-boilerplate/issues/968.

**Comment by wandonye** [comment]
Can anyone explain a little bit how this is done with `electron-redux`? Do I need to create a container for MenuBuilder just like other components?

**Comment by wandonye** [comment]
ok, looks like #1615 is the answer for me

**Comment by wandonye** [comment]
never mind, this[ stackoverflow solution](https://stackoverflow.com/questions/35529532/how-to-change-the-redux-state-based-on-an-electron-menu-click/35539560) is the simplest. I tried `electron-redux`, but in my case it creates some weird sync problem.
