### ISSUE TITLE
use ConnectedSwitch instead of Switch?

### ISSUE THREAD

**Issue by chie4hao** [chentsulin/electron-react-boilerplate#1180]
[https://github.com/ReactTraining/react-router/issues/5072](https://github.com/ReactTraining/react-router/issues/5072)
I have a same problem when i press a back button in production build.Create a ConnectedSwitch in place of Switch resolves the problem.

**Comment by amilajack** [comment]
Sure. Can you PR this to the `v0.13.0` branch?
