### ISSUE TITLE
IMPOSSIBLE to debug error while building

### ISSUE THREAD

**Issue by bradennapier** [chentsulin/electron-react-boilerplate#1182]
I have spent 6 hours on this now before reporting this... I have absolutely no way of debugging this error that happens with the build-renderer script.

```
ERROR in unknown: Unexpected token (454:28)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

unknown... unexpected token... i have MILLIONS of lines of code i have to read to try to find one little error somewhere!?

Any ideas on what would cause this?

**Comment by amilajack** [comment]
Are you using babili?

**Comment by bradennapier** [comment]
Yes, I did update it just now to babel-minify-webpack-plugin same issue with both. :-\

**Comment by amilajack** [comment]
If you are, install `yarn add --dev uglifyjs-webpack-plugin@1.0.0-beta.2` and add the following lines to your `webpack.config.{main,renderer}.prod.js`: https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/webpack.config.main.prod.js#L28-L31

**Comment by bradennapier** [comment]
Remove babel-minify ?

**Comment by amilajack** [comment]
Yea. Remove all the babili and babel magnification related plugins

**Comment by bradennapier** [comment]
Thanks for the help @amilajack -- now im getting

```
 91% additional asset processing/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:240
          return new Error(`${file} from UglifyJs\n${err.message} [${requestShortener.shorten(original.source)}:${original.line},${original.column}][${file}:${err.line},${err.col}]`);
                TypeError: requestShortener.shorten is not a function
    at Function.buildError (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:240:87)
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:174:56
    at Array.forEach (<anonymous>)
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:157:21
    at step (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:110:11)
    at done (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:120:22)
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:125:15
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/node_modules/worker-farm/lib/farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)                                                                      ^

```

**Comment by amilajack** [comment]
Interesting. Try:
```bash
rm -rf node_modules
yarn
```

**Comment by bradennapier** [comment]
lol ugh now im getting

```
Unexpected token: keyword (import)
```

in  the renderer.prod.js 

havent done the rm -rf so i am trying that now.

**Comment by bradennapier** [comment]
ahh i think i know why that is happening - although i feel like it shouldn't -

**Comment by bradennapier** [comment]
So it appears that it is not properly handling the import statements.  I removed the modules: false value and had to add the dynamic import plugin which is how you guys do it here... but why is that necessary?  I thought webpack now handles all that for us?

**Comment by amilajack** [comment]
The reason why we don't have `modules: false` in the boilerplate is because we use babel to transpile node modules (ex. `webpack.config.main.prod.js`). So everything that isn't processed by webpack requires babel module transpilation

**Comment by amilajack** [comment]
Also was this issue resolved?

**Comment by bradennapier** [comment]
Yes it is now resolved.  Thank you very much.

**Comment by charlesstrong** [comment]
could spend the 20-30 minutes debugging this issue in master to use local. Instead cloned git@github.com:pbarbiero/enhanced-electron-react-boilerplate.git
OR
git@github.com:pbarbiero/basic-electron-react-boilerplate.git
both work

**Comment by SirWindfield** [comment]
Sorry to highjack this issue again, but why was babili removed in favour of uglifyjs?

**Comment by amilajack** [comment]
It was too slow
