### ISSUE TITLE
TIP: GOOGLE_API_KEY Solution

### ISSUE THREAD

**Issue by bradennapier** [chentsulin/electron-react-boilerplate#1183]
So this was a huge pain.  Wanted to share in case anyone else runs into this and goes through the same.  Webpack changes your process.env calls even if you do something like

```js
process.env.GOOGLE_API_KEY = 'mykey'
```
 to
```js
'mykey' = 'mykey'
```

which obviously isnt going to help you out much.

electron-builder does not allow setting environment variables so that isnt really possible.

I almost resorted to just removing webpack for the main process which woudl have sucked big time and taken many hours... then I realize it could be solved easily enough by simply providing a npm package

```bash
yarn add webpack-set-environment
```

```js
import setEnv from 'webpack-set-environment'
setEnv({
  GOOGLE_API_KEY: 'mykey'
})
```

**Comment by amilajack** [comment]
Add a config similar to [this](https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/webpack.config.main.prod.js#L47-L50) to your base webpack config

**Comment by bradennapier** [comment]
@amilajack that does not work when you package for production... only for development.

**Comment by amilajack** [comment]
Oh that's probably because that env variable is accessed at runtime. Webpack can't statically analyze those cases

**Comment by amilajack** [comment]
Thanks for pointing this out

**Comment by bradennapier** [comment]
Yes, others basically have ended up manually editing plist files on every build or worse.  This solution seems to be quick and easy to implement for this issue.  

https://electron.atom.io/docs/api/environment-variables/

**Comment by harut-g** [comment]
Webpack ```DefinePlugin``` only rewrites the ```process.env```  variables and it won't help if varible which is specified in ```DefinePlugin``` not exists, if you will write for example in main.dev.js:
```javascript
process.env.GOOGLE_API_KEY = "MY_KEY";
```
it will become in main.js (producation build):
```javascript
Object({"NODE_ENV":"production"}).GOOGLE_API_KEY = "MY_KEY";
```
Hack to avoid this will be passing process object to another variable by reference and assign to it **GOOGLE_API_KEY**, like this:
```javascript
const _process = process;
_process.env.GOOGLE_API_KEY = "MY_KEY";
```
it helped me.
