### ISSUE TITLE
Sass themes

### ISSUE THREAD

**Issue by jackmallers** [chentsulin/electron-react-boilerplate#1186]
I am curious what you all think the best way to implement sass themes is. I've been doing some research for webpack + sass and am just interested to hear opinions. Thanks

**Comment by amilajack** [comment]
Use [this](https://github.com/amilajack/popcorn-time-desktop/blob/master/app/styles/main.scss) as an example

**Comment by jackmallers** [comment]
Hmmm. I need to import certain themes dynamically and override certain sass variables, that's when I started to question myself a bit

**Comment by amilajack** [comment]
So you want sass to recompile dynamically at runtime? That is way out of the scope of this project.

**Comment by jackmallers** [comment]
No, maybe extract multiple css files for each theme and be able ti dynamically include them via HTML @amilajack. Would that make sense?
