### ISSUE TITLE
Yarn lint failed at NODE_ENV check

### ISSUE THREAD

**Issue by liyixcn** [chentsulin/electron-react-boilerplate#1188]
After I modify the `.eslintrc` file(remove the parser property), the `yarn lint` command failed at NODE_ENV check, even I restore the `.eslintrc`.

```bash
⇒  yarn lint
yarn lint v0.27.5
$ eslint --cache --format=node_modules/eslint-formatter-pretty .
"process.env.NODE_ENV" must be "development" to use this webpack config
error Command failed with exit code 2.
```

According to my investigate this command failed at [webpack.config.renderer.dev.js](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.dev.js#L20).
I think env `NODE_ENV=development` should be added for `lint` script.

**Comment by Toosick** [comment]
`"lint": "cross-env NODE_ENV=development eslint --cache --format=node_modules/eslint-formatter-pretty .",` fixed this problem.
