### ISSUE TITLE
eslint import error

### ISSUE THREAD

**Issue by hemedani** [chentsulin/electron-react-boilerplate#1195]
eslint trow error for import every package listed in app/package.json but it's not listed in root/package.json
```
[eslint] 'react' should be listed in the project's dependencies. Run 'npm i -S react' to add it (import/no-extraneous-dependencies)
```

**Comment by uppe-r** [comment]
I can't reproduce this with the boilerplate. Are you sure you're on the latest boilerplate release?

**Comment by hemedani** [comment]
No I'm in a old release because of my project
How can i solve this error

**Comment by uppe-r** [comment]
Maybe try checking the last commit made by the maintainers when you cloned the boilerplate and see if the commits done after have something to do with your issue?

**Comment by amilajack** [comment]
Not enough information to debug this. Closing until more information is provided
