### ISSUE TITLE
PouchDB broken after packaging

### ISSUE THREAD

**Issue by skdenmark** [chentsulin/electron-react-boilerplate#1198]
I have PouchDB working perfectly in developer mode but as soon as I package my application and starts it I get the following error. I use the vanilla `electron-react-boilerplate` where I only have added PouchDB.

```
IO error: /Users/MyUser/MyApplication/release/mac/DemoApp.app/Contents/Resources/app.asar/../app.db/LOCK: Not a directory
```
I thought it was something to do with the path I specify for PouchDB, but I already tried the followings without luck.

```
const DB = new PouchDB(`${window.__dirname}/../app.db`);  // 1
const DB = new PouchDB(`${window.__dirname}/app.db`); // 2
const DB = new PouchDB('app.db');  // 3
```

Have any of you had any similar errors? and if so, can guide me in the right direction for how to get it working in production aka. when I package my application. If feel like to are missing any information feel free to ask :) 

**app/package.json:**:

```
...
"scripts": {
    "postinstall": "../node_modules/.bin/electron-rebuild --version=1.7.0 --force --types prod,dev,optional --module-dir ."
  },
  "license": "MIT",
  "dependencies": {
    "pouchdb": "^6.3.4"
  }
...
```

**Comment by talha131** [comment]
Do you see any useful information when you create and run production package using

```
DEBUG_PROD=true npm run package
```

**Comment by skdenmark** [comment]
Yes - When I run it with `DEBUG_PROD=true npm run package` I get the following error: 

```
OpenError: IO error: /Users/MyUser/MyApplication/release/mac/DemoApp.app/Contents/Resources/app.asar/../app.db/LOCK: Not a directory
    at /Users/MyUser/MyApplication/release/mac/DemoApp.app/Contents/Resources/app.asar/node_modules/levelup/lib/levelup.js:125:34
    at /Users/MyUser/MyApplication/release/mac/DemoApp.app/Contents/Resources/app.asar/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

So somehow it seems like it is unable to open the specified folder

**Comment by Unforgiven-wanda** [comment]
This is probably from the fact that your path points to the asar archive, which is read-only.
Try ```const DB = new PouchDB(`app.db`);```, or else instantiate the app inside the appUser folder, it should work.

**Comment by skdenmark** [comment]
@Unforgiven-wanda: Thanks for the input. Fixed the issue by placing the database in `appData` via `app.getPath('appData')`.
