### ISSUE TITLE
How to load images via css

### ISSUE THREAD

**Issue by danielstorch** [chentsulin/electron-react-boilerplate#120]
Hey, 

im trying to load and .png icon via css, but i get an error.

This is my css:
`.MenuItem-icon-home{
    content: url(../../img/ic_home_black_24dp_1x.png);
}
`

This is the error i get
`ERROR in ./app/img/ic_home_black_24dp_1x.png
Module parse failed: usr/app/img/ic_home_black_24dp_1x.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./app/components/Navigation/Navigation.module.css 6:1375-1421
`

**Comment by jhen0409** [comment]
Install [url-loader](https://github.com/webpack/url-loader) and [file-loader](https://github.com/webpack/file-loader), then add to webpack config:
```js
  ......
  module: {
    loaders: [
      ......
      {
        test: /\.png$/,
        loader: 'url'
      }
    }
  },
  ......
```
It will work. :)

**Comment by chentsulin** [comment]
Just like what @jhen0409 say, you should use `url-loader` or `file-loader` to handle png ext files.

**Comment by danielstorch** [comment]
Perfekt, works.
Thanks!
