### ISSUE TITLE
npm run test still runs e2e tests

### ISSUE THREAD

**Issue by JM-Mendez** [chentsulin/electron-react-boilerplate#1200]
Like the title says, I can't get the runner to skip the e2e tests. Running just the e2e files works fine tho. I can work around it by only running tests related to the changed files during development. But I noticed that both commands get executed in the travis.yml file and wonder if there's something I'm doing wrong.

**Comment by amilajack** [comment]
That's by design. e2e tests take a while to run so running them on every test run would be time consuming

**Comment by JM-Mendez** [comment]
That's the issue. They run on every single test run, unless I filter the runs by test file.

**Comment by emreeren** [comment]
Strange, I also can't make it ignore e2e tests. @JM-Mendez did you solved it? I'm running it on Windows and as expected `npm run test-e2e` runs only e2e tests for me. 

![image](https://user-images.githubusercontent.com/835381/37150073-5527fa68-22e1-11e8-98b7-03399246e646.png)

**Comment by JM-Mendez** [comment]
The issue I had was that when running `npm run test-watch` and then pressing 'a' to run all tests files, it would also run e2e. I didn't realize that it was clearing the initial filter when I did that. 

I'm not on windows, but your regex filter is different than mine. The version I'm on uses this regex
`test/(?!e2e/)[^/]+/.+\\.spec\\.tsx?$`
which resolves on my mac to
`Ran all test suites matching /test\/(?!e2e\/)[^\/]+\/.+\.spec\.tsx?$/i`.

I see you're using typescript, so I'm wondering if you edited it or used a modified boilerplate.

I have a working typescript fork based on another fork of this boilerplate you can look at if you want
https://github.com/JM-Mendez/electron-react-typescript-boilerplate/blob/master/src/scripts/RunTests.ts

**Comment by emreeren** [comment]
Thank you very much for answering my question. I tested with your regex but unfortunately it still includes e2e tests. Yes I'm using modified version of this boilerplate. https://github.com/iRath96/electron-react-typescript-boilerplate. It looks like your problem was different so it probably relates with the boilerplate I'm using. I'll try to compare differences of my setup with the original one.

**Comment by emreeren** [comment]
I didn't fully tested it but changing regex as `^((?!/e2e/).)*$` worked fine for me.

![image](https://user-images.githubusercontent.com/835381/37162964-abc2119e-2307-11e8-9324-db50876cb127.png)

 I'm not sure how
`test/(?!e2e/)[^/]+/.+\\.spec\\.tsx?$` 
expression can match `test\e2e\e2e.spec.ts` file on my system. Even `test.(?!e2e).*` runs all tests including e2e test :)

**Comment by JM-Mendez** [comment]
> I'm not sure how
test/(?!e2e/)[^/]+/.+\\.spec\\.tsx?$
expression can match test\e2e\e2e.spec.ts file on my system.

You said you're on windows, and if you look at the [jest docs](https://facebook.github.io/jest/docs/en/cli.html#jest-regexfortestfiles), it says you'd need to use '/' as the path separator, or escape '\\', which you did. So this may be a jest bug, not sure. At least you got it working.
