### ISSUE TITLE
Get root path of the app

### ISSUE THREAD

**Issue by amorino** [chentsulin/electron-react-boilerplate#1202]
I'm having some trouble looking for the app root directory of the boilerplate on production (or package) mode.

I'm using the file-loader for some json files. I can't use json-loader because the files are huge. I have no trouble on dev, because webpack gives the file on the dev-sever (with http://localhost). However in production the files are server on the app.asar.

Is there any way I can get the root directory of the app?

**Comment by Kronenberg** [comment]
That how it works:
![screen shot 2017-09-13 at 5 25 41 pm](https://user-images.githubusercontent.com/13053374/30382758-adbd5132-98a8-11e7-8e45-e79be8ca3be2.png)

P.S. after packaging root folder is app/
you can create dummy api folder in app, and for production mode  just type: ./api/yourjsonfile.json
Basically you fave two options you can create static file with extraResources or add it to file list. I am provide my structure with the image.

**Comment by wwwizzarrdry** [comment]
Thank you for this.

"files": [
   "../resources/somefile.ext"
]

Finally cleared up some issues I had targetting the correct path in asar packaged apps.
