### ISSUE TITLE
Path to JSON file

### ISSUE THREAD

**Issue by Kronenberg** [chentsulin/electron-react-boilerplate#1203]
After packaging .dmg i can't find my json file.
Question is: how can i get the local json file after "npm run package"?
P.S. in dev and prod everything is fine and i have no any console errors except this 

![screen shot 2017-09-11 at 2 28 36 pm](https://user-images.githubusercontent.com/13053374/30272518-8b793408-96fd-11e7-89ed-0f6729a886c4.png)

Here is my folders and my action.
![screen shot 2017-09-11 at 12 32 40 pm](https://user-images.githubusercontent.com/13053374/30268288-f4934d3a-96ed-11e7-8f6f-8ab0ba04d1be.png)
![screen shot 2017-09-11 at 12 32 46 pm](https://user-images.githubusercontent.com/13053374/30268289-f4b527d4-96ed-11e7-8e40-7249a124eaa7.png)

**Comment by BenBach** [comment]
We have the same problem. Could you please share the solution? :-)

**Comment by Kronenberg** [comment]
![screen shot 2017-12-27 at 6 16 21 pm](https://user-images.githubusercontent.com/13053374/34386592-1b479146-eb32-11e7-844a-f5472cf9683a.png)

You can add your static files inside the package.json file i provide the image.

If you want to check if the file exists after packaging you can use this module https://github.com/electron/asar to unpack your asar archive to see what happens after packaging. 

P.S. root folder is app.
