### ISSUE TITLE
Import mp4 files into components

### ISSUE THREAD

**Issue by eoghanmccarthy** [chentsulin/electron-react-boilerplate#1206]
I can import image files into a components but I can't import video files (mp4).

Error reads:

_Failed to load resource: the server responded with a status of 404 (Not Found)_

Usually, where are media files (jpg, mp4) put in the folder structure? And how do I import them into individual components?

**Comment by Cherviakov** [comment]
You just require them in your .jsx file where needed, and add following lines to webpack.config.render.dev.js
```javascript
  // Video loading
       {
         test: /\.mp4/,
         use: {
           loader: 'url-loader',
           options: {
             limit: 10000,
             mimtetype: 'video/mp4',
           }
         }
       },
       {
         test: /\.html$/,
         use: 'html-loader?attrs[]=video:src'
       }
```

**Comment by Cybugg** [comment]
How do I Mod

> You just require them in your .jsx file where needed, and add following lines to webpack.config.render.dev.js
> 
> ```js
>   // Video loading
>        {
>          test: /\.mp4/,
>          use: {
>            loader: 'url-loader',
>            options: {
>              limit: 10000,
>              mimtetype: 'video/mp4',
>            }
>          }
>        },
>        {
>          test: /\.html$/,
>          use: 'html-loader?attrs[]=video:src'
>        }
> ```

Please how do i modify the webpack in next.config.js in nextJS
