### ISSUE TITLE
Cannot use brace package

### ISSUE THREAD

**Issue by zfanta** [chentsulin/electron-react-boilerplate#1213]
I'm trying to use [react-ace](https://github.com/securingsincity/react-ace) and I have to use [brace](https://github.com/thlorenz/brace). But when I import something from 'brace' like `import 'brace/mode/javascript';`, I got this error

```
Could not load worker TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at new WorkerClient (index.js:16800)
    at Mode.createWorker (wollok.js:764)
    at EditSession.$startWorker (index.js:9120)
    at EditSession.$onChangeMode (index.js:9076)
    at EditSession.eval (index.js:9057)
    at AppConfig.exports.loadModule (index.js:3684)
    at EditSession.setMode (index.js:9046)
    at ReactAce.componentDidMount (ace.js:94)
    at eval (ReactCompositeComponent.js:264)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
```

At `new WorkerClient (index.js:16798-16800)` it requires `w3c-blob` of node version.
```
var Blob = __webpack_require__("./node_modules/w3c-blob/index.js");
var blob = new Blob([ workerSrc ], { type: 'application/javascript' });
var blobUrl = (window.URL || window.webkitURL).createObjectURL(blob);
```
[w3c-blob](https://github.com/chrisdickinson/w3c-blob) also provides browser version, and `electron-react-boilerplate` should load browser version.

**Comment by amilajack** [comment]
See [this example](https://github.com/falcon-client/falcon/blob/782b443a4d01db4ba0aa7271c90b68707c42624f/app/components/Structure.js#L5-L10)

**Comment by zfanta** [comment]
@amilajack, I got same issue on your falcon. I edited `falcon/app/containers/Query.js` by adding `import 'brace/mode/javascript';` and switching `mode` to `javascript`.

![falcon](https://user-images.githubusercontent.com/6619332/30582032-40380832-9d5d-11e7-9bb3-027fe6ddbce1.png)

**Comment by amilajack** [comment]
```bash
git clone https://github.com/amilajack/falcon-ui-rewrite-2
cd falcon-ui-rewrite-2
```
open `QueryPage.js` and replace all three occurrences of `sql` with `javascript`. Guaranteed to work. Closing because this is not an issue with the boilerplate and more of a project/library specific issue
