### ISSUE TITLE
postinstall fails npm install because of concurrently

### ISSUE THREAD

**Issue by Nauss** [chentsulin/electron-react-boilerplate#1215]
I've been using the boilerplate for a while now for a professional project with a 4-members team.
We have our own native dependency that requires rebuild during the `postinstall` task. The project (and the number of dependencies) getting bigger, we started to have `npm install` failing on the `postinstall`. We had different errors on different computers and even different errors when running the `npm install` multiple times. For a while we managed to workaround the problem just launching `npm install` multiple times but at some point it did not work anymore.
After a lot of searching, retries, waiting, blaming dependencies, I came to the conclusion that `concurrently` was the problem. Removing it totally fixes `npm install`.

So, in order to allow scaling I suggest replacing the package.json line:
`"postinstall": "concurrently \"npm run flow-typed\" \"npm run build-dll\" \"electron-builder install-app-deps\" \"node node_modules/fbjs-scripts/node/check-dev-engines.js package.json\"",`
with
`"postinstall": "npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json",`

**Comment by Rafi993** [comment]
I have the same issue too

**Comment by amilajack** [comment]
Please show the entire stack trace. Closing this until this is provided

**Comment by Kronenberg** [comment]
I have the same issue, i am just remove postinstall )
