### ISSUE TITLE
Electron autofocus when reloaded, disturbs develop.

### ISSUE THREAD

**Issue by linonetwo** [chentsulin/electron-react-boilerplate#1217]
When there is a syntax error, Electron reloads and autofocus, while I'm still typing to fix error! It's so annoying. Is there a setting can turn off this?

**Comment by Miklet** [comment]
Is it not this option bothers you? 
https://github.com/chentsulin/electron-react-boilerplate/blob/16bc3e12048150b967721e8bd8e906f760805959/app/main.dev.js#L77

**Comment by linonetwo** [comment]
OMG that solved it!

**Comment by linonetwo** [comment]
Unsolved, sometimes not autofocus, sometimes does.

If I'm in a syntax error situation, further syntax error won't cause autofocus.
But if I fix syntax error, It autofocus itself.

**Comment by amilajack** [comment]
No way around this

**Comment by DenQ** [comment]
Hey guys, I did PR - https://github.com/chentsulin/electron-react-boilerplate/pull/1279.
Not the best solution, but it works.

**Comment by cjcdoomed** [comment]
Try using

`mainWindow.showInactive()`

**Comment by ashvin777** [comment]
This problem still exist, is there any workaround for this ? The focus shift issue is very annoying

**Comment by Sanan4li** [comment]
I am having the same issue, sad to see the issue is there for 3 years and closed without resolving it.

**Comment by linonetwo** [comment]
It doesn't show on my side anymore, I'm still using this boilerplate.

Maybe I just remove all the 

```
      mainWindow.show();
      mainWindow.focus();
```
