### ISSUE TITLE
EACSESS .config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js

### ISSUE THREAD

**Issue by Cherviakov** [chentsulin/electron-react-boilerplate#1220]
Linux Mint Cinnamon 17.3 Rosa (Ubuntu 14.04)
Node 8.5.0 (nvm)
Got this error on every `npm run dev` in terminal. 
Resolved with changing build directory permissions to 744.

**Comment by jhen0409** [comment]
Thanks! Please waiting the fix for https://github.com/MarshallOfSound/electron-devtools-installer/issues/63.

**Comment by amilajack** [comment]
Fixed in https://github.com/MarshallOfSound/electron-devtools-installer/pull/64

**Comment by Cherviakov** [comment]
Thanks, error disappeared after updated package and removed old folder with extensions.
