### ISSUE TITLE
Opening link with middle mouse button

### ISSUE THREAD

**Issue by DanMMX** [chentsulin/electron-react-boilerplate#1227]
Whenever you click on a link with the middle mouse button a window will popup. The problem with the packaged version of the project (or when running `npm start`) is that the window will always show a blank page.

I've found a workaround for at least showing up some content (the root route content) on the packaged version with this code:

```

  mainWindow.webContents.on('new-window', (event, url) => {
    console.log(url)
    if (url.indexOf('.html') < 0) {
      url = url.replace('file://', `file://${__dirname}/app.html#`)
    }

    event.preventDefault();
    console.log(url)
    const win = new BrowserWindow({ parent: mainWindow, show: false })
    win.once('ready-to-show', () => win.show())
    win.loadURL(url)
    event.newGuest = win
  })
```

but won't load the needed url but the root url.

I've logged the requested urls and not sure if you can help me out but the requested url doesn't have the original file (on the production version)

```
// requested url
file:///orders/59c530ce6dc4bd4941053d64
// needed url
file:///Users/dan/Documents/projects/casa-cuesta-branch/app/app.html#/orders/59c530ce6dc4bd4941053d64
```

the second url works on development version but on production version only loads the root state.

You can test this by trying opening a new window (ctrl + click / cmd + click or middle button click) on the boilerplate for the counter link on the homepage.

**Comment by amilajack** [comment]
This is a question about electron and not the boilerplate. Please ask this issue in the electron community

**Comment by DanMMX** [comment]
Actually this happens with this specific boilerplate. But thanks 😃
