### ISSUE TITLE
 Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by muscaiu** [chentsulin/electron-react-boilerplate#1228]
I'm getting this error when running the tests.
I just cloned the `boilerplate` and i'm trying to figure out why the tests are failing and what do the error messages mean after just adding the following lines tp `Counter.js`.
```
import { remote } from 'electron';
const { shell} = remote
...
shell.openExternal('https://www.facebook.com')
```

![electron tests failing](https://user-images.githubusercontent.com/11426309/30805627-dfc66370-a1fa-11e7-8953-7ef7f5bb1216.png)

**Comment by amilajack** [comment]
Are you still experiencing this?

**Comment by muscaiu** [comment]
I resolved it by separating the electron components to a separate file, so `jest` doesn't bump into it.
