### ISSUE TITLE
Icon App not show

### ISSUE THREAD

**Issue by rahmatkruniawan** [chentsulin/electron-react-boilerplate#1242]
why there is not icon on my app after build to dmg file for mac

![screen shot 2017-09-28 at 10 00 28 am](https://user-images.githubusercontent.com/9253817/30947434-eaf6b764-a433-11e7-8fed-d5ff70b1194e.png)

**Comment by Cherviakov** [comment]
@rahmatkruniawan Try to make hello-world app in pure electron and make icon appear there, first. Then check if same work for this boilerplate. Experience with icons shows it is more likely electron issue rather than anything else.
