### ISSUE TITLE
Need this setup React in web dev :s

### ISSUE THREAD

**Issue by Nyura95** [chentsulin/electron-react-boilerplate#1248]
Hello !

Someone at this setup "reactJS" in web dev ?

I could not find a similar project on github (with flow-typed -redux - hot - ...)

thank you in advance !

**Comment by uppe-r** [comment]
http://andrewhfarmer.com/starter-project/ You've got a bunch of them!

**Comment by Nyura95** [comment]
thx u upper-r ! i should find with this :+1:

ps : yes sry :(
