### ISSUE TITLE
Cannot read property type of undefined

### ISSUE THREAD

**Issue by alexemorris** [chentsulin/electron-react-boilerplate#1256]
<img width="1026" alt="screen shot 2017-10-05 at 11 14 52" src="https://user-images.githubusercontent.com/13317885/31222280-8075456e-a9be-11e7-9af4-3dfc5ef04ee5.png">

Getting the following error EVERYTIME I dispatch an action. The actions work ok and I can see them in redux devtools, but it is still concerning. Any ideas?

Some notes - I've removed all Redux Router features from my app as I don't need them, but even after porting things into a fresh boilerplate I still get the same issue. I've written plenty using this boilerplate before and not had this problem!

Thanks in advance,
Alex

**Comment by uppe-r** [comment]
Can you post part of your code relevant to the issue @alexemorris ?

**Comment by alexemorris** [comment]
Hi,
Sorry I should have followed this up. Essentially there was a bug in my code meaning 99 times out of 100 the first action dispatched didn't have a type. I would expect the above error in this case... However

However this error didn't break app continued to work, just thereafter every single action caused an Uncaught TypeError as above, even though they did have an associated type. I think it may be due to Redux Logger trying to access the type of all actions dispatched to that point which was causing the problem. 

So not necessarily a bug or an issue but worth knowing!

Alex
