### ISSUE TITLE
Uncaught ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by wangyueming** [chentsulin/electron-react-boilerplate#1261]
There is an error "Uncaught ReferenceError: __webpack_require__ is not defined" in render process of production environment. Installed webpack version is 3.6.0 and had same issue with version 2.x.x.

It took me almost one day to solve it and finally fixed it by changing `"babili-webpack-plugin": "^0.1.2",` to  `"babili-webpack-plugin": "0.0.11"`.

**Comment by wangyueming** [comment]
I also have a circular import issue in production environment while it is okay in development production. It seams `BabiliPlugin` a little not reliable. Is it possible to have other solution?

**Comment by uppe-r** [comment]
The boilerplate will be using uglifyjs for the next version (#1166) instead of babili. Maybe try implementing the changes relative to uglifyjs in the respective commit for the meantime?

**Comment by wangyueming** [comment]
@uppe-r thanks. uglifyjs works. I switched uglifyjs.

**Comment by fishear** [comment]
@wangyueming Do you use uglifyjs-webpack-plugin in webpack3?
