### ISSUE TITLE
Build: Error: package.json does not exist

### ISSUE THREAD

**Issue by JimmyMow** [chentsulin/electron-react-boilerplate#1264]
When I `package-all` or `build` and then start the app I get `App threw an error during load
Error: package.json does not exist at` and then gives a destination that the application does not live in.

Has anyone else experienced this issue?

**Comment by JimmyMow** [comment]
Ah, seems it has to do with `grpc`. Any ideas on how to build with `grpc`?

**Comment by amilajack** [comment]
Closing because this is not an issue with the boilerplate

**Comment by JimmyMow** [comment]
Ok. Any ideas on where I can find a solution?

**Comment by amilajack** [comment]
Try theses:
* https://github.com/grpc/grpc/issues/6138
* https://github.com/iheanyi/go-electron-grpc
* https://github.com/electron/electron/issues/7731
* https://github.com/grpc/grpc/issues/8260

**Comment by JimmyMow** [comment]
Thanks!

**Comment by GuillaumeCisco** [comment]
Sorry to put a new comment in this thread, but did you succeed to fix this issue @JimmyMow?
I've read the issues pointed by @amilajack, but couldn't find a fix.
Thanks,

**Comment by GuillaumeCisco** [comment]
For the record and for people in this case, I succeeded to fix it in this issue:
https://github.com/grpc/grpc/issues/13049#issuecomment-337677610
Cheers ;)

**Comment by kaitian186** [comment]
Hey GuillaumeCisco. How are you?
Can you please help me?
I am trying to import sql.js to my electron and react app.
btw, I got the following error.

![Screenshot_1](https://user-images.githubusercontent.com/64065818/113351756-e2c1c480-936d-11eb-9113-df7285b0cc88.png)

**Comment by ec2-learn-instant** [comment]
Same issue here also.

@kaitian186 Any update on this?
