### ISSUE TITLE
google analytics using react-ga 

### ISSUE THREAD

**Issue by muscaiu** [chentsulin/electron-react-boilerplate#1266]
```js
    import ReactGA from 'react-ga'
    ReactGA.initialize('UUU-XXXXX', { debug: true });

    export default class Home extends Component {
      constructor(props) {
        super(props)
        ReactGA.pageview('/React-BP');
      }
```
I tried adding `react-ga` using the same code in `create-react-app` and in `electron-react-boilerplate`.

In `create-react-app`  it works, but **in `electron-react-boilerplate` it doesn't work.**

The data is being sent, but nothing is coming to google analytics.

![react-ga](https://user-images.githubusercontent.com/11426309/31552662-cfcb378a-b040-11e7-8929-c1e5705de502.jpg)

Is this a known issue or i'm supposed to do something extra?

**Comment by muscaiu** [comment]
For now the only solution i found is using [universal-analytics](https://www.npmjs.com/package/universal-analytics) instead.

**Comment by amilajack** [comment]
This isn't a known issue. Might have something to do with https://github.com/chentsulin/electron-react-boilerplate/issues/1183
