### ISSUE TITLE
Does Electron App Reloads, When There Is A Change In main.dev.js For Dev Env?

### ISSUE THREAD

**Issue by shankarshastri** [chentsulin/electron-react-boilerplate#1267]
May be we can use https://github.com/Quramy/electron-connect to do it?

**Comment by amilajack** [comment]
There is an ongoing experiment for this

**Comment by shankarshastri** [comment]
@amilajack, can you share the experiment branch if present, I would also help in contributing?

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate/tree/hot-reload-main-process

**Comment by fatfatson** [comment]
hello, what's the progress?
