### ISSUE TITLE
Dev runs fine but packaged version crashes with a cannot find module error

### ISSUE THREAD

**Issue by roelofvkr** [chentsulin/electron-react-boilerplate#1269]
I've been working on this for a bit now and when i tried to package the app i got this error when launching
![image](https://user-images.githubusercontent.com/1549898/31570759-b50ea11a-b087-11e7-8461-63e643581f01.png)
This error has not happened while running the debug and while working on it and I don't know why it's happening. 
I've tried deleting both node_modules folders and reinstalling and i've made sure electron-download-manager is a dependency in the right package.json (./package.json, in the root).

How would I go about solving this issue?

Thanks in advance,
Roelof VK

**Comment by amilajack** [comment]
What does your `package.json` look like?

**Comment by roelofvkr** [comment]
it had to do with some dependencies that weren't listed in the second package.json, putting them in there fixed it.
