### ISSUE TITLE
Cannot import 'dialog' in reducer

### ISSUE THREAD

**Issue by hamxiaoz** [chentsulin/electron-react-boilerplate#127]
I can do this in main.js:
```
const electron = require('electron');
const dialog = electron.dialog;
dialog.showOpenDialog();
```

But when I try to write it in one of my reducers, it has error:
```
TypeError: Cannot read property 'showOpenDialog' of undefined
```

I tried `import {dialog} from 'electron';` too, it didn't work

**Comment by nozaq** [comment]
`dialog` module is only available in the main process, so you need to use it via `remote` from the renderer process.

```
const remote = require('electron').remote;
const dialog = remote.require('dialog');
```

http://electron.atom.io/docs/v0.36.4/api/remote/

**Comment by hamxiaoz** [comment]
It works, thank you!
