### ISSUE TITLE
No store found on Linux

### ISSUE THREAD

**Issue by eric-burel** [chentsulin/electron-react-boilerplate#1277]
Hi, when using this boilerplate, `redux-devtools` prints the deadly `No store found.` message, though there are no error on installing it. I use the last version of the boilerplate, though this issue also appeared on the version I used some months ago. Weird part is that it seems to only happen on Linux (Ubuntu 16.03).

Note : `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` is undefined when running yarn dev, which might explain the problem. But yet the installation does not seem to fail.

Here is a sample of my modified code, but once again I can reproduce on a just created app:
```javascript
// If Redux DevTools Extension is installed use it, otherwise use Redux compose
/* eslint-disable no-underscore-dangle */
const composeEnhancers = ((typeof window !== 'undefined') && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) ?
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
    // Options: http://extension.remotedev.io/docs/API/Arguments.html
    actionCreators,
  }) :
  compose;

export default function configureStore(
  initialState: Object = {},
  middlewares: Array<*> = [],
  sagas: Array<Generator<*, *, *>> = []
): Store {
  /* eslint-enable no-underscore-dangle */
  const enhancer = composeEnhancers(
    applyMiddleware(...middlewares),
    // If I uncomment this, this will work on Ubuntu, but breaks both Storybook and Windows, saying the store is loaded twice...
    //! (typeof window !== 'undefined') && window.devToolsExtension ? window.devToolsExtension() : f => f
  );
```

**Comment by eric-burel** [comment]
This might be related to [this issue:](https://github.com/zalmoxisus/redux-devtools-extension/issues/219).

**Comment by amilajack** [comment]
All the CI tests run on linux pass. You may have incorrectly configured something

**Comment by amilajack** [comment]
All the CI tests run on linux pass. You may have incorrectly configured something
