### ISSUE TITLE
Alternative to using `shell`

### ISSUE THREAD

**Issue by muscaiu** [chentsulin/electron-react-boilerplate#1278]
Is there an alternative to `shell` of opening a link into the default browser?

I'm asking because `shell` or any electron native objects are not recognized by `jest`, and the tests are NOT passing.

This question is related to [1228](https://github.com/chentsulin/electron-react-boilerplate/issues/1228)

**Comment by uppe-r** [comment]
Hey @muscaiu, try giving a look at [this](https://github.com/electron/electron/issues/1344) and [this](https://github.com/pwnall/node-open)

**Comment by muscaiu** [comment]
Thanks, i've actually decided to separate all electron components from react components, so now the tests are passing.
