### ISSUE TITLE
Using axios error

### ISSUE THREAD

**Issue by aindong** [chentsulin/electron-react-boilerplate#128]
Hi I have a rest api and I want to use a library called Axios to do ajax requests on my api but when I tried adding the package `npm install axios --save` and import it into one of my component `import axios from 'axios'` it gives me this error 

```
ERROR in ./~/axios/package.json
Module parse failed: /Users/alleoindong/Public/projects/restoko/restoko-desktop-app/node_modules/axios/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       "axios@^0.8.1",
 @ ./~/axios/lib/adapters/http.js 11:10-41
```

any work around or hints of the problem? Thank you so much for helping!

**Comment by aindong** [comment]
right now what I did is I added it into the externals to make the webpack build successful

**Comment by jhen0409** [comment]
The `axios` module load `.json` file, so you should add `json-loader` to webpack config. :)

**Comment by aindong** [comment]
after adding `json-loader` I got this

```
ERROR in ./app/index.js
Module build failed: SyntaxError: Unexpected token i
    at Object.parse (native)
    at Object.module.exports (/Users/alleoindong/Public/projects/restoko/restoko-desktop-app/node_modules/json-loader/index.js:7:48)
 @ multi main
```

putting it into the externals is working.

**Comment by chentsulin** [comment]
`axios` package has `http`(for node) and `xhr`(for browser) adapters, and electron renderer can run both or two. Notice that, http adapter can't be packed by webpack.

You can list `axios` in [externals](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.base.js#L27) as a quick work around. Or try to replace `"./lib/adapters/http.js"` to `"./lib/adapters/xhr.js"` via webpack, see also https://github.com/mzabriskie/axios/blob/master/package.json#L61

**Comment by calderaro** [comment]
i have exactly the same problem.
`| {
|   "_args": [
|     [
|       "axios@^0.9.1",
 @ ./~/axios/lib/adapters/http.js 10:10-41
`
and when i try with externals.
`ReferenceError: axios is not defined`

**Comment by HarrisRobin** [comment]
None of the solutions mentioned above solved it for me. Could someone guide me to an example of this boilerplate using axios or any other HTTP library? Would be much appreciated! Thanks

**Comment by jhen0409** [comment]
> The axios module load .json file, so you should add json-loader to webpack config. :)

This is real... see [this branch](https://github.com/jhen0409/electron-react-boilerplate/commit/23b43d9fecee7cff98c02bf0bebae020301e70c0), it work.

@chentsulin is right, but it just problem of json file.

**Comment by HarrisRobin** [comment]
@jhen0409 thank you for this.

One mistake I was also making is saving json-loader to devDependencies. After looking at @jhen0409 's example, when saving json-loader to dependencies it worked.

**Comment by chentsulin** [comment]
@jhen0409 Should we support `json-loader` as default loaders?

**Comment by jhen0409** [comment]
> Should we support json-loader as default loaders?

I think yes, because node require json file is natural, but it was broken by webpack.
