### ISSUE TITLE
Image is not loaded with createBrowserHistory

### ISSUE THREAD

**Issue by wangyueming** [chentsulin/electron-react-boilerplate#1280]
I use `history.push(path)` to switch react route, but the image is not loaded when I use createBrowserHistory.  Using `createHashHistory` works.

I load image in this way.
`              <Image src="./views/img/about.png" size="massive" style={{ width: '100%' }} />
`

I know `<Image src={require('./views/img/about.png')}` works in both way, but I don't like this way.

**Comment by v9Chris** [comment]
I believe I have the same issue.

When i first run my packaged application the iamge displays, but on navigating to that page from somewhere else using react-router-dom my image is missing.

Works fine in development.

**Comment by amilajack** [comment]
Try this solution:
https://github.com/chentsulin/electron-react-boilerplate/issues/250#issuecomment-269661920
