### ISSUE TITLE
Some question in packing

### ISSUE THREAD

**Issue by 673800357** [chentsulin/electron-react-boilerplate#1283]
Hello, i want to regard a xxx.json file which place on my /app  directory as  a config file. But when i have packed the application, I can find not my xxx.json file. I want to modify this file in my install directory so that my application can use the config. How can i deal with it or there are some comfigure?

**Comment by Kronenberg** [comment]
![screen shot 2017-10-23 at 6 27 27 pm](https://user-images.githubusercontent.com/13053374/31897839-313bcdc2-b820-11e7-87a0-d29afc7b821a.png)

1) You can add your static file to this config as on image
2) Root path of this boilerplate start from app folder

**Comment by 673800357** [comment]
@Kronenberg Oh sorry, my problem is diffrent with it. I want that the xx.json file is placed on the install directory and i can modify it so that my application can use the config. I follow the image but the xxx.json can not be found on the install directory

**Comment by Kronenberg** [comment]
Maybe if you will go inside your app after packaging, and unpack your asar archive, you see what the structure you have after packaging. This npm module should help your, https://github.com/electron/asar. I hope so. Or i miss something, anyway good luck!

**Comment by amilajack** [comment]
Closing due to no response

**Comment by BenBach** [comment]
I have the same problem. We are trying to load language files from the filesystem in a javascript module
It works in dev but not in production. I checked the asar file and the folder is in there.


This is our code:
```
i18next
  .use(Backend)
  .init({
    initImmediate: false,
    // debug: true,
    fallbackLng: 'zu',
    backend: {
      loadPath: path.join(__dirname, '/locales/{{lng}}.json'),
      jsonIndent: 2
    }
  });
```
