### ISSUE TITLE
Getting "Uncaught TypeError: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by nguiard** [chentsulin/electron-react-boilerplate#1284]
Hello,
I'm stuck with this error after trying to install the ogg package. Full error : 

```
Uncaught TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7)
    at dirname (path.js:1324)
    at Function.getRoot (bindings.js:146)
    at bindings (bindings.js:55)
    at eval (binding.js:1)
    at Object../node_modules/ogg/lib/binding.js (renderer.dev.dll.js:565)
    at __webpack_require__ (renderer.dev.dll.js:21)
    at eval (packet.js:6)
    at Object../node_modules/ogg/lib/packet.js (renderer.dev.dll.js:600)
    at __webpack_require__ (renderer.dev.dll.js:21)
```

I'm not certain that here is the best place to post because it seems like a webpack (config?) related issue. But I'm still unfamiliar with these tools and I've already spent hours trying to find a solution. I'm on Mac OS. Windows and Linux untested for now.

To reproduce, just install a fresh version of the boilerplate, then do : 
```
npm i --save ogg
```
Then try to import the ogg module in some js file ("import ogg from 'ogg';").

When running "npm run dev" for the first time after that, I got a "Could not locate the bindings file" error. Then after fixing this issue by removing a "ogg.node" file and rebuilding, I get the above error and am stuck here.

I searched and tried quite a bit of things, but couldn't get it to work. Some people got this type of error fixed by upgrading or downgrading to specific versions of node or other modules. I tried updating every module to the latest version, downgrading to some other node versions... Also tried the "installation debugging solutions" proposed here: https://github.com/chentsulin/electron-react-boilerplate/issues/400. Also the ogg module works fine in another project of mine not using electron/react/webpack etc. Couldn't figure this out for now. 

Any help would be greatly appreciated, thanks all!

**Comment by uppe-r** [comment]
Hey @nguiard, have you tried installing this module inside of the `app` folder instead of the root folder, as described [here ](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure#what-is-a-native-module) ?

**Comment by nguiard** [comment]
Oh wow yeah that was it! Such a simple thing... Just install native modules in the app folder.
Too bad it didn't find that page while searching.

Thanks a whole lot!

**Comment by uppe-r** [comment]
By the way, there will be a native dependencies checking for every new dependency you install in the boilerplate's next version (v0.13.0).

**Comment by nguiard** [comment]
Great idea! And by the way, that's an awesome boilerplate :)
