### ISSUE TITLE
Web worker can't setup.

### ISSUE THREAD

**Issue by linonetwo** [chentsulin/electron-react-boilerplate#1287]
I'm using redux-worker-middleware, which works pretty well in web browser 
( I use a separated webpack config to get codes inside this boilerplate run on electron and browser )

And I loads webworker using worker-loader:
```js
{
        test: /\.worker\.js$/,
        use: { loader: 'worker-loader' },
}
```

But when it ran in electron, webworker just don't work.

**Comment by uppe-r** [comment]
Hey @linonetwo give a look at https://github.com/electron/electron/blob/master/docs/tutorial/multithreading.md#multi-threaded-nodejs

**Comment by linonetwo** [comment]
@uppe-r  Thanks, but I surely had tried that:

```js
// main.dev.js
...
  mainWindow = new BrowserWindow({
    show: false,
    width: 1600,
    height: 728,
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      nodeIntegrationInWorker: true,
    },
  });
...
```

**Comment by uppe-r** [comment]
What do you mean with "webworker just don't work" ?

**Comment by linonetwo** [comment]
I set up webworker like this:

<img width="897" alt="wx20171026-183533 2x" src="https://user-images.githubusercontent.com/3746270/32048596-9d61451e-ba7c-11e7-8e3b-f4468ea63e39.png">

This work in browser:

![wx20171026-183617](https://user-images.githubusercontent.com/3746270/32048602-a35f6932-ba7c-11e7-9ae2-a6e71ac6f421.png)

But not electron:

<img width="271" alt="wx20171026-183723 2x" src="https://user-images.githubusercontent.com/3746270/32048633-bdb3fdb6-ba7c-11e7-8e44-c6c646ceec55.png">

**Comment by linonetwo** [comment]
How did you successfully set up webwork in electron renderer process? @uppe-r

**Comment by uppe-r** [comment]
I didn't set up any webworker in electron yet. Maybe try checking the Service Workers on the Application tab in the devtools?

**Comment by linonetwo** [comment]
Sad, option in that article don't work too.

```js
// useless
          {
            test: /\.worker\.js$/,
            include: paths.appSrc,
            use: { loader: 'worker-loader', options: { inline: true } },
          },
```

I'm considering wrapping https://github.com/electron-userland/electron-remote and webworker and choose the one fit electron or browser at runtime.
