### ISSUE TITLE
mp4 files not included in production build

### ISSUE THREAD

**Issue by LoganArnett** [chentsulin/electron-react-boilerplate#1288]
I found #1206 and was successful in including the `.mp4` files in the dev build but including those same loaders in the production webpack config does not actually include the videos properly and the videos are just missing.

I have an `assets/*.mp4` path to 2 videos and I import them like so:

```js
import Splash from '../assets/Splash.mp4'`
```

Trying to figure out the best way to get these in an actual packaged app. On `npm run package` of any OS the app still builds and webpack doesnt throw any errors about the file type, the videos are just not there

**Comment by LoganArnett** [comment]
disregard, I found another issue with my webpack config

**Comment by snavaneeth78** [comment]
@LoganArnett care to explain what your issue was? I'm having the same problem even after following #1206

**Comment by LoganArnett** [comment]
@snavaneeth78 I followed #1206 and I had added something else for another loader incorrectly which was causing my issue, fixing my syntax and confirming that I had added the mp4 code to both the `renderer.dev` and `renderer.prod` configs was what worked for me
