### ISSUE TITLE
Electron Auto Updater [Main Process]

### ISSUE THREAD

**Issue by Kronenberg** [chentsulin/electron-react-boilerplate#1289]
Question is: as i understand correctly i can run Auto Updater only from main process, but in this boilerplate how i can hook the main process, does anyone can provide me an example.
Great Thx!

**Comment by Slapbox** [comment]
**In main.dev.js**

```
import AppUpdater from "./AppUpdater";
// Put the next line within the window creation function
new AppUpdater();
```

**In a new file named `AppUpdater`**

import { autoUpdater } from "electron-updater"
```
export default class AppUpdater {
  constructor() {
    const log = require("electron-log")
    log.transports.file.level = "info"
    autoUpdater.logger = log
    autoUpdater.checkForUpdatesAndNotify()
  }
}
```

**Comment by deadcoder0904** [comment]
@Slapbox I think this should be put in the docs itself as this was a hard find. I mean the `main.dev.js` contents :)

**Comment by Slapbox** [comment]
@deadcoder0904 - Done: https://github.com/chentsulin/electron-react-boilerplate/wiki/Auto-updater-Basic-Configuration

**Comment by deadcoder0904** [comment]
@Slapbox Thanks but I thought this was Electron Builder Repo lol 😂 & I came looking from there. But anyways thank you.

**Comment by Slapbox** [comment]
Haha I'd hope it would be easier to find in their docs!
