### ISSUE TITLE
Images not showing in packaged app

### ISSUE THREAD

**Issue by NikZar** [chentsulin/electron-react-boilerplate#129]
Hi all, I am having problems with images (referenced in app.css) in my packaged electron application.

`  background-image: url(images/splashscreen.gif); `

While developing, the images are loaded correctly. 
I am using the url-loader for png and gif images in my _webpack.config.base.js_:

```
module: {
    loaders: [
    {
      test: /\.jsx?$/,
      loaders: ['babel-loader'],
      exclude: /node_modules/
    },
    {
      test: /\.png$/,
      loader: "url-loader?limit=100000"
    },
    {
      test: /\.gif$/,
      loader: "url-loader?limit=100000"
    },
    {
      test: /\.jpg$/,
      loader: "file-loader"
    }
    ]
  },
```

The images seem also to be correctly generated in the dist folder.
However in the packaged app (after running "npm run package-all") the images are not showing correctly (I don't know how to debug a packaged app).
Here it is my dummy project: [repo](https://github.com/NikZar/Reactiwall)
This is the first time I am using react and webpack, am I missing something? 
Could we add something to correctly cover image handling in the boilerplate?

Thank you in advance!

**Comment by jhen0409** [comment]
It should use `./images/splashscreen.gif` instead of `images/splashscreen.gif`? refer [this document](https://github.com/webpack/css-loader#local-scope).

**Comment by NikZar** [comment]
I tried changing the code as you suggested but nothing changes. 
Like before the image is showing while developing but not after packaging the app.
I am testing on OSX El Capitan 10.11.3

If i do not use the url-loader I get this error while running "npm run hot-server hot":
> ERROR in ./app/images/splashscreen.gif
> Module parse failed: /Users/XXX/Developer/Desktop Apps/Reactiwall/app/images/splashscreen.gif Line 1: Unexpected token ILLEGAL
> You may need an appropriate loader to handle this file type.
> (Source code omitted for this binary file)
>  @ ./~/css-loader!./app/app.css 6:164-200

**Comment by jhen0409** [comment]
@NikZar  I tried your project, it's problem of webpack `publicPath`, and it resolved by #124, please update. :)

**Comment by NikZar** [comment]
Thank you so much! Now it is all working as expected :)

**Comment by sanjay-3129** [comment]
> It should use `./images/splashscreen.gif` instead of `images/splashscreen.gif`? refer [this document](https://github.com/webpack/css-loader#local-scope).

It worked for me, Thanks.

**Comment by lacymorrow** [comment]
I'm still struggling with this issue, I am trying to load images but have only been successful with the `file://` protocol
