### ISSUE TITLE
Different store history for development and production

### ISSUE THREAD

**Issue by musyilmaz** [chentsulin/electron-react-boilerplate#1295]
Nearly 1 month ago, I had a problem regarding to the production build not showing any of the contents.

I have solved this issue at the beginning of october and wrote the solution in gitter. The reason was using createBrowserHistory in the configureStore.prod. In where the entire boilerplate and its connections with electron rely on hashHistory and it is defined as createHashHistory in the configureStore.dev. Currently, I am at production and it is working with the hashHistroy.

My question is that is this an intended issue or an error?

**Comment by offaxis** [comment]
Hi @musyilmaz,

It seems i got the same problem, but i tried to replace in the configureStore.prod.js the createBrowserHistory by the createHashHistory function, but it doesn't fix the bug !

In production, i can't navigate through my Link (from react-router-dom), without any error in the console (Running with DEBUG_PROD=true npm run package). I'm stuck...

Thank you !

**Comment by amilajack** [comment]
@offaxis would be helpful if you could create a minimal fork of the boilerplate that reproduces this issue

**Comment by emilbruckner** [comment]
Not a minimal fork, but for I have the same problem. The problem is that the router somehow receives the complete absolute pathname, like `… electron/release/mac/Find Better Questions.app/Contents/Resources/app.asar/app.html`, which makes no route fit
