### ISSUE TITLE
Failed npm install on win7 x64

### ISSUE THREAD

**Issue by dariuszsikorski** [chentsulin/electron-react-boilerplate#130]
Hello, initial `npm install` downloads all the required packages, but fails to continue with following log:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\joinfiles\erb-myapp\npm-debug.log
```

I made node cache clean with no success, any suggestions?

**Comment by wub** [comment]
Make sure you've got Python 2.7 (and that it's in your path), and some kind of Windows SDK (will need to find out which one). :smile:

**Comment by Lokeh** [comment]
I was able to solve this by installing Visual Studio 2015, and then installing the Visual C++ tools.

**Comment by andrerpena** [comment]
I'm having this problem as well.

 - Python 2.7 is installed and on my path.
 - Visual Studio 2015 is installed (not sure about the Visual C++ tools)

**Comment by Lokeh** [comment]
@andrerpena Visual Studio 2015 does not automatically install the Visual C++ tools. Once I installed them, the problem was resolved for me.

Try it out.

**Comment by andrerpena** [comment]
@Lokeh I'm giving it a try. Thank you!

**Comment by andrerpena** [comment]
@Lokeh Thank you very much. Installing Visual C++ in Visual Studio 2015 fixed it for me. Yes, it seems that the "install" process tries to compile something, maybe Electron itself.

**Comment by andrerpena** [comment]
Maybe this issue should be closed if this solves for everyone.

**Comment by mikerockett** [comment]
So I downgraded Python to 2.7.10 from 3.4, and re-running `npm i` worked. However, `npm start` doesn't, and I'm pretty sure it's got something to do with th Visual C++ tools. I have Visual Studio 2013 installed. How do I install the tools?

Here's the error I'm getting:

```
$ npm start

> electron-react-boilerplate@0.8.0 start x:\var\bps\electron-react-boilerplate-master
> cross-env NODE_ENV=production electron ./

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'x:\var\bps\electron-react-boilerplate-master\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (x:\var\bps\electron-react-boilerplate-master\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by mikerockett** [comment]
Ah, not to worry. Ran `npm i` in `electron-prebuilt`. All working like a charm now. :+1:

**Comment by andrerpena** [comment]
@mikerockett this error you mentioned is exactly because you don't have Visual C++ installed so it cannot compile electron. Good too know that using the pre-built solves it as well. That makes sense.

**Comment by mikerockett** [comment]
@andrerpena I'm new to Electron and React in general, and so wasn't aware that it was meant to compile Electron in the first place. Assumed from my previous usage with the Vue boilerplate that it would simply use pre-built.

So this is working now - everything except for #151.

**Comment by barrystaes** [comment]
I also get the node-gyp error on Windows 10.

@wub said:
> Make sure you've got Python 2.7 (and that it's in your path), and some kind of Windows SDK (will need to find out which one). :smile:

Is this requirement (node-gyp / Python) introduced by Electron, by React, by `electron-react-boilerplate`, or some optional feature ?

As a beginner (its a boilerplate package..) i would expect to find this listed in `Readme.md`.
