### ISSUE TITLE
Files not present after build

### ISSUE THREAD

**Issue by JimmyMow** [chentsulin/electron-react-boilerplate#1301]
I am using icons stored in a `app/icons` directory. After build the application I am getting:

`file:///Users/jmow/Projects/bolt/bolt-desktop/release/mac/ZapDesktop.app/Contents/Resources/app.asar/icons/wallet.svg net::ERR_FILE_NOT_FOUND`

After digging through the folders I don't have a `app.asar` folder. Only a `app.asar.unpacked` that only contains `node_modules`

I assume this is an error on my part but any help here? How can I successfully use icons in prod?

**Comment by amilajack** [comment]
Try adding `'icons'` to the `files` config
