### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by cameronb23** [chentsulin/electron-react-boilerplate#1302]
Receiving `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` when running `yarnpkg build` in the build-renderer step. `yarnpkg dev` runs fine without error.

**Comment by goldquest** [comment]
Did you find a solution or ways to debug it?

**Comment by zhanyouwei** [comment]
@cameronb23 why closed?
