### ISSUE TITLE
Running express INSIDE electron app

### ISSUE THREAD

**Issue by cameronb23** [chentsulin/electron-react-boilerplate#1304]
What would be the best way to run an express server _inside_ my electron app? I have tried forking a process and just plain starting it in `main.dev.js` but nothing seems to be working correctly.

**Comment by Slapbox** [comment]
I'm also interested in an answer to this.

**Comment by amilajack** [comment]
Will create an example for this

**Comment by Slapbox** [comment]
Hooray for @amilajack!

**Comment by amilajack** [comment]
https://github.com/amilajack/erb-express-example

**Comment by Slapbox** [comment]
@amilajack always delivers!

Thanks very much for your expertise and contributions!

**Comment by htran844** [comment]
any update??
