### ISSUE TITLE
App icon in Development VS Production

### ISSUE THREAD

**Issue by MortyHD** [chentsulin/electron-react-boilerplate#1315]
Hi!

I just build an app using this boilerplate and i added a custom icon in main.dev.js where is makes a new BroswerWindow, but whenever i build it it says application icon not found uses standard electron icon. Am i missing a place?

`  mainWindow = new BrowserWindow({
    show: false,
    width: 1170,
    height: 728,
    icon: __dirname + '/icon.png',
    autoHideMenuBar: true
  });`

**Comment by uppe-r** [comment]
Hey @MortyHD ! You don't need to do all of that, just change the files inside the [`resources` ](https://github.com/chentsulin/electron-react-boilerplate/tree/master/resources) folder.

**Comment by pavlobu** [comment]
this script helped me to generate .icns from on source 1024x1024 png image:

https://github.com/jamf/icns-Creator
