### ISSUE TITLE
Handle persistent data

### ISSUE THREAD

**Issue by MaximilianKindshofer** [chentsulin/electron-react-boilerplate#1316]
I want to save some data to disk - I tried nedb but it only works in dev

Here is the code I have in my action creator

```
import Datastore from "nedb-promise"
const db = new Datastore({ filename: './budgetdatabase.json', autoload: true });

import { FETCH_BUDGETS, CREATE_BUDGET } from './action_types';

export function fetchBudgets() {
    return async (dispatch) => {
        const budgets = await db.find({type: "budget"})
        dispatch ({
            type: FETCH_BUDGETS,
            payload: budgets

        })
    }
}

export function createBudget(values) {
    return async (dispatch) => {
        await db.insert({
            name: values.budgetName,
            type: "budget"
        })
        const budget = await db.findOne({ name: values.budgetName })
        dispatch ({
            type: CREATE_BUDGET,
            payload: budget
        })
    }
}

```
I guess nedb can't access the file in production 

I don't necessarily want to use nedb but I want to store data. 

Maybe sqlite would be a better choice for my project but I don't see how to integrate it in the boilerplate.

Can you help me resolve the issues?

It would be great if a wiki entry existed for persistent data handling.

**Comment by Cherviakov** [comment]
Hi, we using nedb in our project and it works well both in dev and prod. Though we using not promisified nedb and wrap its operations into promises ourselves.

**Comment by MaximilianKindshofer** [comment]
Do you use nedb in the main process or at the render process? 

I guess the redux action belong to the render process - this means they don't have file access.

I would have to create some kind of middleware to communicate between main and render process then...

**Comment by talha131** [comment]
@MaximilianKindshofer Whether you use nedb or sqlite, you must have following structure.

1. Access nedb/sqlite on main thread
2. Process redux actions on renderer thread

In order to update your db in response to redux actions, you will have to implement IPC. See these two links from docs

1. [ipcRenderer](https://electronjs.org/docs/api/ipc-renderer)
2. [ipcMain](https://electronjs.org/docs/api/ipc-main)
