### ISSUE TITLE
npm run lint getting resolve error

### ISSUE THREAD

**Issue by sklink** [chentsulin/electron-react-boilerplate#1317]
This is the error I'm getting when running `npm run lint`:
> Resolve error: Cannot find module D:\dev\electron_project\app\webpack.config.eslint.js  import/extensions

While the last part seems to reference the `eslint` rule that's being broken, which can help me solve it--this one was because I'm importing a `.json` file without the webpack rule setup. (at least as far as I can tell)

Either way, there's still an issue with the actual output of the message which would otherwise confirm the root cause of the error.

I should note that many of the errors do not have this issue, just some of the import statements at the top of the files.

**Comment by amilajack** [comment]
Are you still experiencing this issue?
