### ISSUE TITLE
Suggestion: wiki page with steps to get this working regardless of stack.

### ISSUE THREAD

**Issue by AoDev** [chentsulin/electron-react-boilerplate#132]
Hello, 

I am trying to achieve the same development flow. But I don't use Redux.
That said, I think most people already know how to build a react app.
Instead, I ended up here to find how to have the same workflow with Electron.

I'd find really useful to have documentation about how to setup webpack config and which module you use and what they do. I know you use this: webpack-target-electron-renderer . It would be nice to know the "what" and "how" so that anyone can use and setup any webpack based build to get it working with electron. Such guidelines would work even for an angular app for example.

**Comment by chentsulin** [comment]
Thanks for you suggestion!
This should covers some of important webpack mechanism, and I will take care of it next week.

**Comment by AoDev** [comment]
Thank you for all the work :)
If I can help you with it, let me know.

**Comment by chentsulin** [comment]
I added some explanation for webpack-target-electron-renderer:
https://github.com/chentsulin/webpack-target-electron-renderer#how-this-module-works

**Comment by amilajack** [comment]
> t would be nice to know the "what" and "how" so that anyone can use and setup any webpack based build to get it working with electron.

@AoDev This is a really good idea. So in a sense, this boilerplate would be more helpful if it was more like a 'todo-mvc' app but with explanations. @chentsulin Would a PR for short explanations for parts of the boilerplate be welcome? I think we should plan this out.

**Comment by amilajack** [comment]
Adding this to next release
