### ISSUE TITLE
What makes nodejs work in app？

### ISSUE THREAD

**Issue by jkest** [chentsulin/electron-react-boilerplate#1320]
I need to make an desktop app and I'd like to use reactjs, but when I do such thing via creact-react-app, I cannot use nodejs modules in my App.js, which use jsx.
But this amazing project do this, and what confused me is that I cannot figure out how does it do that.
I find out the webpack-config has some property named NODE, and it wraps __dirname, but how about other nodejs modules work in App.js? Such as child_process, etc.
It does work, but I cannot figure it how, and I am urge to know it. Could somebody help me? I will be really really thank you~

**Comment by amilajack** [comment]
Dont use create-react-app with this boilerplate
