### ISSUE TITLE
Redux Link doesn't work on Prod app (package)

### ISSUE THREAD

**Issue by offaxis** [chentsulin/electron-react-boilerplate#1322]
Hi Electron !

I'm stuck with this problem and i can't figure it out ! Thanks for helping

### Problem 
I use the Link component from react-router-dom to navigate in my app, when i'm running on Dev, all is OK, i can navigate, but when i package the app (on Mac),  The app is "working" but the Links do not work at all !
No errors are displayed, on packaging and when Link is clicked ! Just this message is displayed in the console if i click 2 times (or more) on the same link :

> Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack

### Attempts
- I tried to replace createBrowserHistory by createHashHistory in configureStore.prod.js => not resolved
- I tried to use react-router Link component => not resolved
- I tried to purge node modules ([400](https://github.com/chentsulin/electron-react-boilerplate/issues/400)) => not resolved

#### configureStore.prod.js
```
// @flow
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';

// import { createBrowserHistory } from 'history';
import { createHashHistory } from 'history'; // Try with dev config

import { routerMiddleware } from 'react-router-redux';
import rootReducer from '../reducers';

// const history = createBrowserHistory();
const history = createHashHistory();

const router = routerMiddleware(history);
const enhancer = applyMiddleware(thunk, router);

function configureStore(initialState = {}) {
  return createStore(rootReducer, initialState, enhancer);
}

export default { configureStore, history };
```

#### Root.js
```
// @flow
import React from 'react';
import { Provider } from 'react-redux';
import { ConnectedRouter } from 'react-router-redux';
import Routes from '../routes';

import IntlWrapper from '../modules/Intl/IntlWrapper';

type RootType = {
  store: {},
  history: {}
};

export default function Root({ store, history }: RootType) {
    return (
        <Provider store={store}>
            <IntlWrapper>
                <ConnectedRouter history={history}>
                    <Routes />
                </ConnectedRouter>
            </IntlWrapper>
        </Provider>
    );
}
```

#### routes.js
```
/* eslint flowtype-errors/show-errors: 0 */
import React from 'react';
import { Switch, Route } from 'react-router';
import App from './modules/App/App';

import HomePage from './modules/App/pages/HomePage';
import UserLoginPage from './modules/User/pages/UserLoginPage/UserLoginPage';
import UserProfilePage from './modules/User/pages/UserProfilePage/UserProfilePage';
import Test from './modules/App/pages/Test';

export default () => (
    <App>
        <Switch>
            <Route path="/login" component={UserLoginPage} />
            <Route path="/profile" component={UserProfilePage} />
            <Route path="/test" component={Test} />
            <Route exact path="/" component={HomePage} />
        </Switch>
    </App>
);
```

In addition i put the code of the Component intlWrapper witch is dedicated to add intl data to children, maybe it is troubling the router redux process 

#### intlWrapper.js
```
import React from 'react';
import PropTypes from 'prop-types';
import { IntlProvider } from 'react-intl';
import { connect } from 'react-redux';

export function IntlWrapper(props) {
  return (
    <IntlProvider {...props.intl} >
      {props.children}
    </IntlProvider>
  );
}

IntlWrapper.propTypes = {
  children: PropTypes.element.isRequired,
  intl: PropTypes.object.isRequired,
};

// Retrieve data from store as props
function mapStateToProps(store) {
  return {
    intl: store.intl,
  };
}

export default connect(mapStateToProps)(IntlWrapper);
```

**Comment by offaxis** [comment]
After several others bugs, i changed my App component witch was connected to Redux, i removed the connect() call on the App component, and it solves the problem !

If it cans help other people...

**Comment by rivertam** [comment]
Thank you for leaving a solution! Unfortunately, I can't really do this, as I'm actually using the `connect` productively. This seems like a genuine bug in one of the libraries (electron? react-router? redux (doubtful)?). Does anyone have a solution that doesn't involve changing logic?
