### ISSUE TITLE
custom .node file do not in asar file.

### ISSUE THREAD

**Issue by wjljack** [chentsulin/electron-react-boilerplate#1323]
I have build a custom native module xx.node file and place in app/libs/myLib.node,and use it with 
`const fuzzyKey = remote.require('../app/libs/myLib')`
and in dev and prod module
`npm run dev` `npm start` is ok.
but when i build windows package,i found myLib.node is not in asar file .
i also use node-loader in webpack ,but it seems can't resolve remote.require,only native require supported.
anyone plz help me ,thank you.

**Comment by amilajack** [comment]
Have you tried [node-loader](https://github.com/webpack-contrib/node-loader)?

**Comment by wjljack** [comment]
i have tried node-loader,my custom node file works but electron-store can't find

**Comment by amilajack** [comment]
I dont have enough information to debug this. This seems like an issue with `electron-store`. As long as you have `node-loader`, webpack should be able to import it. I'm going to close this because it doesn't seem like an issue with the boilerplate but feel free to continue the discussion. Share your stack trace here.

**Comment by wjljack** [comment]
Uncaught Error: Cannot find module 'electron-store'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (D:\Work\electron\shark-mac-client\release\win-unpacked\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.electron-store (file:///D:/Work/electron/shark-mac-client/release/win-unpacked/resources/app.asar/dist/index.prod.js:44:427163)
    at t (file:///D:/Work/electron/shark-mac-client/release/win-unpacked/resources/app.asar/dist/index.prod.js:1:115)
    at Object../app/utils/requestClient.js (file:///D:/Work/electron/shark-mac-client/release/win-unpacked/resources/app.asar/dist/index.prod.js:44:282376)
    at t (file:///D:/Work/electron/shark-mac-client/release/win-unpacked/resources/app.asar/dist/index.prod.js:1:115)
    at Object../app/actions/LiveActions.js (file:///D:/Work/electron/shark-mac-client/release/win-unpacked/resources/app.asar/dist/index.prod.js:1:2640)

**Comment by wjljack** [comment]
before i use node-loader , electron-store works , by add

**Comment by amilajack** [comment]
Try this:
Uninstall `electron-store` from `./package.json` and install it in `./app/package.json`

**Comment by wjljack** [comment]
Thank you very much, it works.

**Comment by arnaubennassar** [comment]
I'm trying to build a native module for my project without luck.
I've been able to compile it into a .node file, but when I try to import it:
`const credentialsManager      = require('credentialsManager')`

I got this error:
```
ERROR in ./app/native_modules/credentialsManager.node
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./app/windowBrowser/core/emailSender/index.js 18:27-56
 @ ./app/windowBrowser/scenes/Boards/scenes/Board/components/BoardContactUsButton/components/ContactUsFormWindow/index.js
 @ ./app/windowBrowser/scenes/Boards/scenes/Board/components/BoardContactUsButton/index.js
 @ ./app/windowBrowser/scenes/Boards/scenes/Board/index.js
 @ ./app/windowBrowser/scenes/Boards/routes.js
 @ ./app/windowBrowser/scenes/Boards/index.js
 @ ./app/windowBrowser/components/AddapsBase/routes.js
 @ ./app/windowBrowser/components/AddapsBase/index.js
 @ ./app/windowBrowser/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1212 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/windowBrowser/index.js
```

In order to build the .node I've tried two strategies:

- npm install
- manually with this commands: 

```
HOME=~/.electron-gyp node-gyp rebuild --target=0.36.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
node-gyp configure
```

In both cases I've used this binding.gyp file:

```
{
  "targets": [
    {
      "target_name": "credentialsManager",
      "sources": [
        "main.cc"
      ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")"
      ],
    }
  ]
}
```
Can anyone guide me through the steps to build and import the module? @wjljack
