### ISSUE TITLE
DOCS: Clarify run instructions

### ISSUE THREAD

**Issue by hedgerh** [chentsulin/electron-react-boilerplate#1324]
Just getting started with the boilerplate, and I'm a little confused by the run instructions:

> Start the app in the dev environment. This starts the renderer process in hot-module-replacement mode and starts a server that sends hot updates to the renderer process:
>
> $ npm run dev
> Run these two commands simultaneously in different console tabs:
>
> $ npm run start-renderer-dev
> $ npm run start-main-dev

I'm a little confused about the second option.  I originally thought I needed to run all 3 together, but obv got a used port error from start-renderer-dev.  I looked and `npm run dev` seems to just call `start-renderer-dev`.  Do I still need to run the `start-main-dev` command?

Are these just two separate options for running the app?  I think the point of the second set of scripts could use some clarification.

If someone can clarify the wording I can drop a PR in real quick.

**Comment by talha131** [comment]
> **Alternatively**, run these two commands simultaneously in different console tabs:

Will this do?

**Comment by hedgerh** [comment]
I opened a PR to add the word "Alternatively."  Is there some reason the user would want to run those two scripts instead of just running `npm run dev`?  May be nice to have an explanation for why they may want to.

https://github.com/chentsulin/electron-react-boilerplate/pull/1325

**Comment by talha131** [comment]
> May be nice to have an explanation for why they may want to.

See [this comment](https://github.com/chentsulin/electron-react-boilerplate/pull/162#issuecomment-190619469)

Kindly add it to you PR after rewording it appropriate.

**Comment by amilajack** [comment]
Merged this
