### ISSUE TITLE
PR: Migrate to webpack@4

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1343]

**Comment by JacoBotha** [comment]
Has there been any progress on this issue?

**Comment by hatton** [comment]
I have a project based on this boilerplate that I upgraded to WP4, if that's of any help @JacoBotha. Main commit is [here](https://github.com/MEaCoM/saymore-mac/commit/bbb4073da4c3d8c6e9f4d489b82cd3b87640bf40).  Probably only helpful if you set out to do the conversion yourself and get stuck on a particular thing, you could see what I did to get past it.

**Comment by JacoBotha** [comment]
Thanks for the speedy reply, it's gotten me a bit further and it seems that the main process is running and Electron is opening, but still not getting any windows to show up...
