### ISSUE TITLE
Using Electron-Builder remote build service?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1347]
I'm trying to use the remote build service, but I'm having some issues figuring out the configuration.

There's some details on the issue here: https://github.com/electron-userland/electron-builder/issues/2359

I think the crux of the issue is where the `dist/` folder is being output. @amilajack do you have any thoughts on how to remedy this? Thanks so much!

**Comment by amilajack** [comment]
This is a relatively new addition to the electron infrastructure ecosystem. I havent gotten the time yet to check it out.

**Comment by Slapbox** [comment]
It seems like the issue may be that the build service expects the `dist\` folder to exist in the `release\` folder rather than in the `app\` folder.

**Comment by Slapbox** [comment]
This has been resolved by the Electron Builder team as of version 19.56
