### ISSUE TITLE
Undefined variables in production

### ISSUE THREAD

**Issue by pavsidhu** [chentsulin/electron-react-boilerplate#1352]
I'm assuming this is an issue with the webpack setup or the way I've been using it, I'm not entirely sure.

Whenever running my app in development, using `yarn dev`, the app build fine no issues. After running `yarn start` the app does not work. I receive errors such as the following: 

```Uncaught ReferenceError: O is not defined```

or

```Uncaught ReferenceError: _ref is not defined```

It's hard to find the traceback for the errors since the errors only appear in production. I've enabled the devtools in production to see the logs but the error messages above are all that I can see.

Are there any ideas with working around this? I have not modified the webpack config. Thanks :)

**Comment by pavsidhu** [comment]
This was not an issue with the package but an issue on my end. I had variables declared after they were used in certain files. While this can work in development, in production doesn't.

**Comment by einsteinx2** [comment]
@pavsidhu Thanks you saved me so much time! I was stuck on this all day getting nowhere until I read your comment.
