### ISSUE TITLE
Images not re rendering on navigation after packaging.

### ISSUE THREAD

**Issue by pikvik** [chentsulin/electron-react-boilerplate#1354]
Alls well off in dev build. The images are successfully loaded on the landing page. But after navigating through the app, the images are not re-rendered. Also the images for static components are perfectly rendered. 
I read through the forum and could not find a solution to this specific problem. I tried using the require statement while loading the image path. But that seemed to pop some error.
Is it some issue with webpack? 

![2017-12-22 12_32_33-asystguard](https://user-images.githubusercontent.com/18361946/34288745-0bbe8872-e715-11e7-95da-a881fb1fdf10.png)
![2017-12-22 12_32_59-asystguard](https://user-images.githubusercontent.com/18361946/34288746-0befcae0-e715-11e7-9788-29d0950d7730.png)
![2017-12-22 12_33_20-asystguard](https://user-images.githubusercontent.com/18361946/34288747-0c1fb138-e715-11e7-905c-8b0b843f62b0.png)

**Comment by Kronenberg** [comment]
What is the folder are you use to keep your assets?

**Comment by pikvik** [comment]
I have kept all the icons images inside only yet the problem appears in rendering .

**Comment by amilajack** [comment]
What are the errors in the console?

**Comment by pikvik** [comment]
Thank you all !! Sorted !!
