### ISSUE TITLE
How to get the right path of third party exe file?

### ISSUE THREAD

**Issue by adcentury** [chentsulin/electron-react-boilerplate#1355]
I have a third party exe file, located in `app/libs/thirdparty.exe`.

In dev mode, I can get this file using `path.join(__dirname, 'libs', 'thirdparty.exe')`. However, when I packaged this app, this doesn't work.

I have added it to the `package.json`, but it seems not work.
```
"build": {
  ...,
  "files": [
    ...,
    "libs/"
  ]
}
```

Can anyone tell me how to find the files in a packaged app? Thanks!

**Comment by Kronenberg** [comment]
Maybe this post help you -> https://github.com/chentsulin/electron-react-boilerplate/issues/1202
