### ISSUE TITLE
Cant install styled-components

### ISSUE THREAD

**Issue by marksalpeter** [chentsulin/electron-react-boilerplate#1363]
this is what I get after trying to install styled-components. any insights 
```bash
$: npm install styled-componenets
$: npm run dev
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-react-boilerplate@0.12.0 dev: `cross-env START_HOT=1 npm run start-renderer-dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.12.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Mark/.npm/_logs/2018-01-05T01_08_12_079Z-debug.log
```

**Comment by uppe-r** [comment]
Hey, can you post the log mentioned in the message?

**Comment by amilajack** [comment]
Let's reopen this once we get the response

**Comment by marksalpeter** [comment]
@amilajack , @uppe-r, You guys are great, thank you. Seeing your responsiveness makes me much more confident in shipping something seeded from this project.

I fixed my issue shortly after posting and forgot to close it myself. I have a hard time remembering exactly what I did to fix it and the logs aren't located in the `/_logs` directory any more, but I went back and looked at the diff for you. All I did was upgrade some packages. 

Specifically: 
```json
...
"electron-devtools-installer": "^2.2.0",
...
"extract-text-webpack-plugin": "^2.1.0",
...
```

Was upgraded to
```json
...
"electron-devtools-installer": "^2.2.3",
...
"extract-text-webpack-plugin": "^3.0.1",
...
```

I hope that helps. Thanks again. Let me know if you need anything else.

**Comment by peterpanBest** [comment]
npm install styled-componenets => npm install styled-components

styled-componenets is wrong word.

**Comment by marksalpeter** [comment]
Kind of irrelevant and this point but, yea that was it @peterpanBest
