### ISSUE TITLE
Can't run 'npm run electron-rebuild', no such file or directory

### ISSUE THREAD

**Issue by jinfromkorea** [chentsulin/electron-react-boilerplate#1369]
i tried followed command 
1. npm run build
    -> it works. 
2. npm run dev
    -> it works. 
3. npm run start
    -> it works.
4. npm run package
    -> i failed.  
what's wrong ? help me, please. 
my os is ubuntu(linux). 

i failed, then i ran 'npm run electron-rebuild', it's my logs.

<pre>
jinia@jin:~/Documents/GitHub/electron-react-boilerplate$ npm run electron-rebuild

> electron-react-boilerplate@0.13.0 electron-rebuild /home/jinia/Documents/GitHub/electron-react-boilerplate
> electron-rebuild --parallel --force --types prod,dev,optional --module-dir app

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
ENOENT: no such file or directory, lstat '/home/jinia/Documents/GitHub/electron-react-boilerplate/app/node_modules'

Error: ENOENT: no such file or directory, lstat '/home/jinia/Documents/GitHub/electron-react-boilerplate/app/node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! electron-react-boilerplate@0.13.0 electron-rebuild: `electron-rebuild --parallel --force --types prod,dev,optional --module-dir app`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.13.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
jinia@jin:~/Documents/GitHub/electron-react-boilerplate$ 

</pre>

**Comment by jinfromkorea** [comment]
check this page ( https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure ) 

there are two package.json files. 
ie. ./package.json and ./app/package.json

i copied dependencies and devDependencies from ./package.json to ./app/package.json

then it works ( npm run electron-rebuild )

**Comment by amilajack** [comment]
Actually this is a bug with the boilerplate. Made https://github.com/chentsulin/electron-react-boilerplate/pull/1370 to fix this. Let me know if it works for you

**Comment by jinfromkorea** [comment]
@amilajack thanks. it works
