### ISSUE TITLE
Export includes node_modules

### ISSUE THREAD

**Issue by John0x** [chentsulin/electron-react-boilerplate#137]
Hey, why does the export include the node_modules folder?
It's not needed since everything needed should be inside the bundle (well except fontawesome).

Wouldn't it be smarter to remove the node_modules folder, since it contains a lot of unnecessary files which just bloat up the binaries?

**Comment by chentsulin** [comment]
Some of modules will not be bundled by `webpack`, for example, such as mysql, mongoose...so we can't ignore all node_modules by default. But you can list modules which you want to ignore to `devDependencies` https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.js#L27

**Comment by davej** [comment]
@chentsulin This doesn't really work with flat deps in npm3 because it only excludes the 0-depth dependencies.

What do you think of adding all of the `node_modules` as webpack externals rather than bundling with webpack? Bundling all node_modules becomes an issue when you have a multi-window application because each of the windows need a separate bundle and there is usually a lot of repeated code in each bundle.

**Comment by chentsulin** [comment]
I bulit [flat-dependencies](https://github.com/chentsulin/flat-dependencies) and [installed-local-modules](https://github.com/chentsulin/installed-local-modules) for this issue yesterday. IMO we can ignore all installed modules which are not dependencies in flat folder structure. But, still need some tests...I am not sure that every cases is considered.

**Comment by davej** [comment]
Is the idea that when doing `npm run package` then only the packages returned by `flat-dependencies` and `installed-local-modules` would be copied to the package's node_modules folder? I *think* that should work. There is a theoretical possibility that if you have different versions of a sub-dependency then it may get copied even though it is extraneous. This is a very minor issue though and it won't cause problems (it just adds to the package weight).

**Comment by lostfictions** [comment]
I'm just using [webpack-node-externals](https://github.com/liady/webpack-node-externals) to exclude everything in node_modules from bundling, and it works great -- I have to whitelist `webpack-hot-middleware` for development, but otherwise it's already making dev server startup and hot reloading a lot quicker.

**Comment by davej** [comment]
@lostfictions That works for npm 2.x but not for npm 3.x.

**Comment by lostfictions** [comment]
Um, yes it does?

Maybe it wasn't clear from my comment, but `webpack-node-externals` doesn't have anything to do with what gets chosen to pass as ignores to `electron-packager` in `package.js`. It just prevents anything in `node_modules` from being bundled when webpack is invoked, which is a separate step in the build process (and one that also gets invoked during development, eg. running the hot-server.) Whether or not the contents of `node_modules` are flattened doesn't affect this at all.

Again, these are related but distinct issues; `webpack-node-externals` improved the situation for me insofar as I'm concerned with the speed of bundling and the size of the emitted bundle during development, but I agree that it's also useful to not copy over unneeded modules into the packaged Electron apps. That's for sure a thornier issue.

**Comment by davej** [comment]
@chentsulin Would it be possible to get a usage example of `flat-dependencies` and `installed-local-modules` working together with webpack externals to efficiently package an app?

**Comment by niieani** [comment]
@davej See [my Aurelia fork](https://github.com/niieani/skeleton-navigation-typescript/blob/new-webpack/skeleton-typescript-webpack/config/electron.package.js) for an example usage of flat-dependency and module filtering.

**Comment by davej** [comment]
@niieani: That's awesome. Would you consider PRing your changes to this lib?

**Comment by niieani** [comment]
@davej I'm afraid I don't work with React at this moment so wouldn't have the time to invest it into a PR here. But it should be fairly simple. Feel free to copy my changes and make your own pull request. I've had to fork both `flat-dependencies` and `installed-local-modules` into `flat-npm-dependencies` and `installed-local-npm-modules` - you'd need to use those too.

**Comment by davej** [comment]
@niieani Got around to trying this out. It sorta works but it only seems to keep deps that are two-levels deep so I ended up with quite a number of deps that were ignored even though they were sub-dependencies of modules which I had added to webpack `externals`. Any thoughts?

**Comment by MarshallOfSound** [comment]
@davej It looks like you are using `electron-packager`, if you are, simply using the `prune` flag should resolve most of your issues.  It automatically runs `npm prune --production` on a copy of your node_modules folder to remove all dev dependencies.  Then you simply have to ensure that any module you want copied is in the normal `dependencies` object

**Comment by davej** [comment]
@MarshallOfSound Yeah, I have `prune` set to true already. Perhaps the easiest thing to do is move all of my `deps` to `devDeps` and selectively move everything in webpack externals back to `deps`. Feels a bit hacky though.

**Comment by MarshallOfSound** [comment]
Is it though?  The definition of those two sections in your package.json

Dependencies
> Things that are required for your program or tool to run, without these modules when someone `npm install`'s your program it would fail to run correctly.

Dev Dependencies
> Things that are required to build your program, normally build tooling, linting and test frameworks.  An enduser should not need these dependencies for your program to run correctly.

So in this case, anything that is compiled or included by webpack is **technically** a dev dependency as you do not need to install it when downloading / running the compiled version.

At least IMO 😆

**Comment by davej** [comment]
Those descriptions are for modules that are designed to be consumed (`npm install`ed) as opposed to top-level apps though. Putting React in the depDeps feels semantically wrong to me.

Your point is well-made though, you can definitely justify it either way. Interesting that this boilerplate doesn't adopt that approach. Any thoughts from @chentsulin or @jhen0409?

**Comment by vinnymac** [comment]
I've been doing things the way @MarshallOfSound proposed and it has been working great for a while now. For most of my projects webpack serves a very different purpose, where your devDependencies are mostly tools, and your dependencies are browser libraries. It makes a lot of sense to keep things organized that way.

In the case of a production binary built using electron I think that the only dependencies that should be delivered to consumers are the ones that aren't needed during transpile/minify time. It keeps size down, and makes it clear what code was delivered. The dependencies list becomes a whitelist.

**Comment by amilajack** [comment]
Closing this, as we have come to a conclusion
