### ISSUE TITLE
Chrome notifications API

### ISSUE THREAD

**Issue by Kronenberg** [chentsulin/electron-react-boilerplate#1379]
Here is my code

```
 notifieTEST = () => {
    if (!Notification) {
      alert('Desktop notifications not available in your browser. Try Chromium.'); 
      return;
    }
  
    if (Notification.permission !== "granted")
      Notification.requestPermission();


      this.notifyMe();
   
  }

   notifyMe = () => {
    if (Notification.permission !== "granted")
      Notification.requestPermission();
    else {
      var notification = new Notification('Notification title', {
        icon: 'http://cdn.sstatic.net/stackexchange/img/logos/so/so-icon.png',
        body: "Hey there! You've been notified!",
      });
  
      notification.onclick = function () {
        // window.open("http://stackoverflow.com/a/13328397/1269037"); 
        console.log('please WORK!');     
      };
    }
  }
```

i am just run notifieTEST function from button, i see the notifications but onclick event not working at all, better to say sometimes it works 😭 
what i miss?

p.s. i using MacOS

**Comment by cr05s19xx** [comment]
The most basic explanation I can theorize is that in Chromium based applications (usually Google Chrome as an example), the notification object is automatically configured to be handled by IPC to be passed down to the renderer process. But in an Electron apps, you may have to set it up yourself.

You can read on the Electron Notifications and how to handle them [here](https://electronjs.org/docs/tutorial/notifications). I personally haven't employed notifications and so I can't be of much help. But you can try the modules recommended in the article
