### ISSUE TITLE
Building options

### ISSUE THREAD

**Issue by Matheus-Ribeiro95** [chentsulin/electron-react-boilerplate#1380]
Hi guys, this is a amazing repo to develop Electron apps, but the build step is still a issue.
Besides the problem with package and app/package.json theres some source code things that isn't working as it should (dev mode is perfect).
Is there a way to only package the app without any code modifications?
Because the WebPack and Babel build step is broking my app.
Thanks adv.

**Comment by Matheus-Ribeiro95** [comment]
Nice help!

**Comment by amilajack** [comment]
No, there isn't a way to do that easily with this boilerplate. Paste the logs that are outputted when your app crashes

**Comment by Matheus-Ribeiro95** [comment]
Fuckkkkkkk!!!!!! I update to last version, added some packages, and the build runned PERFECTLY!
Man, this repo is simply the best to DEV a Electron application, thanks so much to the team!!!!!!!!!!!!
I love you guys, the community is amazing!
Thanks!

**Comment by Matheus-Ribeiro95** [comment]
EDIT: I dont know how to mark as resolved, sorry. Closing issue here.
