### ISSUE TITLE
No flow@v0.63.1

### ISSUE THREAD

**Issue by MonkeyInWind** [chentsulin/electron-react-boilerplate#1382]
I clone 'electron-react-boilerplate'.
When I run 'npm install'
![cc92b6e8-d766-4f99-8155-a217256f1cec](https://user-images.githubusercontent.com/34543887/35020610-ee232d10-fb67-11e7-88b4-1c68648daba3.png)

**Comment by talha131** [comment]
It just means that flow-type definitions for dependencies like electron cannot be found.

This boilerplate has chosen flow-type over typescript to provide type checking. Like typescript, flow expects definitions for all the dependencies used. If it does not found one, say for electron, it complains. 

But at the same time, it creates stubs for you automatically that are pretty much useless but hides the error.

If you are wondering when flow-type definitions for electron will be available then checkout [this thread](https://github.com/flowtype/flow-typed/issues/756).

It seems typescript has become the standard type checking provider for JS projects.
