### ISSUE TITLE
yarn or npm install cause error

### ISSUE THREAD

**Issue by FanShiDe** [chentsulin/electron-react-boilerplate#1388]
Node `v8.0` npm `v5.0`,cause a error:
```js
error /home/ksuser/Documents/projects/cypher-poker-client/node_modules/electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments:
Directory: /home/ksuser/Documents/projects/cypher-poker-client/node_modules/electron-chromedriver
Output:
/home/ksuser/Documents/projects/cypher-poker-client/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: connect ETIMEDOUT 52.216.80.72:443
```
and I try again，but also can't resolve this problem。

Then，I see that node `v8.0` have a probelm from #1051 。So  I try to change the version of Node： node `v8.5`。Finally，it is work。

**Comment by amilajack** [comment]
It might be a bug in node 8. It is recommended that you use the latest version of node. Node 8 had a lot of performance bugs initially so I would not be surprised if this is one of them

**Comment by tc-imba** [comment]
I think it's because you are in Mainland China, where amazon aws (52.216.80.72) is blocked sometimes. Please use a VPN and try again.

**Comment by envobgm** [comment]
> `nrm use taobao && npm install`
> I solved this problem

thanks...it works for me
