### ISSUE TITLE
Failed to fetch extension, trying 4 more times

### ISSUE THREAD

**Issue by lyyh** [chentsulin/electron-react-boilerplate#1391]

**Comment by amilajack** [comment]
Add logs please

**Comment by gzhanghui** [comment]
I have this problem, t
![Uploading 111.png…]()
oo

**Comment by hututuhu** [comment]
I have the same problem,too

**Comment by hututuhu** [comment]
> I have the same problem,too

I update the sass and sass-loader version to the latest, then it works.
