### ISSUE TITLE
Is there clean-up script?

### ISSUE THREAD

**Issue by vinogradov-m** [chentsulin/electron-react-boilerplate#1393]
Hello there. 
Earlier there was a way to get rid of boilerplate sample code. I just needed to run `npm run cleanup`. Currently I'm not able to find some script with similar functionality.

Could you please clarify, which steps should I take for starting custom dev? Should I manually remove components, reducers and other code related to "counter"? Or should I keep these files in my project (maybe it helps to avoid merge conflicts when I "sync" my project with the boilerplate)?

**Comment by amilajack** [comment]
There isn't one yet unfortunately
