### ISSUE TITLE
Unable to resolve './' paths

### ISSUE THREAD

**Issue by cr05s19xx** [chentsulin/electron-react-boilerplate#1395]
In my code... as an example, I have the following directory structure
```
|-app
...
    |- Home.jsx
    |- index.js
    |- Test.jsx
```

inside the `index.js`, I have the following as barrel exports
```javascript
// index.js

export * from './Home';
export * from './Test';
```

inside the `Home.jsx` I have the following test code
```javascript
// Home.jsx
import React from 'react';
import { Test } from './';

export class Home extends React.Component {
    render() {
        return (
            <div className="home-class">
                <Test />
            </div>
        );
    }
}
```

inside my `Test.jsx` I have the following code
```javascript
import React from 'react';

export class Test extends React.Component {
    render() {
        return <p>This is a test element</p>;
    }
}
```

In development, when I run, there was no problem. But in production, the component is not rendered. Upon changing the import from `'./'` to point to the file, i.e. `'./Test'`, it started working. Is there any reason why this is so?

**Comment by isotopeee** [comment]
Any updates on this?
