### ISSUE TITLE
Avast detects infection

### ISSUE THREAD

**Issue by talhasch** [chentsulin/electron-react-boilerplate#1396]
<img width="314" alt="ekran resmi 2018-01-29 16 30 21" src="https://user-images.githubusercontent.com/1177676/35512741-dd190234-0511-11e8-8578-be75bba5710f.png">

macOs 10.13.2, Avast 13.04 (18012402)

**Comment by amilajack** [comment]
[Not the first time this happened](https://github.com/chentsulin/electron-react-boilerplate/issues/306). You should ignore this
