### ISSUE TITLE
how can i add support for decorators in development mode?

### ISSUE THREAD

**Issue by asmallfurrywombat** [chentsulin/electron-react-boilerplate#1401]
hi..
I think the stage-3 preset and transform-decorators-legacy plugin would work, but I'm not sure how to enable them for 'npm run dev'. Any help would be appreciated.

Production seems to work, but I'm not clear on the division of responsibilities between the .babelrc and the various webpack.config.* files so there is probably some unnecessary duplication. An explanation would also be nice.

thanks!

**Comment by amilajack** [comment]
I think the `transform-decorators-legacy` plugin doesn't work with react-hot-loader. This is mostly a babel issue.

**Comment by asmallfurrywombat** [comment]
This issue seems relevant, too: https://github.com/gaearon/react-hot-loader/issues/279 . Not a blocker - switched back to a non-decorator equivalent.
