### ISSUE TITLE
Unable to go though ipcRenderer.send Process

### ISSUE THREAD

**Issue by princesoni1989** [chentsulin/electron-react-boilerplate#1403]
Hi All,

I am facing strange issue. I am working on Linux environment with **electron-react-boilerplate**.
I have completed app in development mode and is running fine. When i packaged app I noticed that place where i am using **ipcRenderer.send or ipcRenderer.sendSync** nothing seems to working after that not sure  what is happening. I am little new to electron js and not sure how can i debug app after packaging it.
It not going after ipcRender.send line. I am attaching sample code let me know if their is any  issue in code (Same code works in development environment)

```javascript
import { ipcRenderer } from 'electron';
import { ACCEPT_LICENSE_EVENT, GET_LICENSE_EVENT } from 'Common/IPCevents';

export const ACCEPT_LICENSE = 'ACCEPT_LICENSE';

export function accepted(state) {
  return {
    type: ACCEPT_LICENSE,
    state
  };
}

export function acceptLicense() {
  return (dispatch) => {
    const reply = ipcRenderer.sendSync(ACCEPT_LICENSE_EVENT);
    dispatch(accepted(reply));
  };
}


export function getLicense() {
  return (dispatch) => {
    const reply = ipcRenderer.sendSync(GET_LICENSE_EVENT);
    dispatch(accepted(reply));
  };
}

```
This work when is run app using `npm run dev` but after packing app it does not works.

Below is code i am using in my main process

```javascript
import { ipcMain } from 'electron';
import { add, get, storageKey } from '../utils/storage';
import { ACCEPT_LICENSE_EVENT, GET_LICENSE_EVENT } from '../../../common/IPCevents';
import config from '../../../config';

ipcMain.on(ACCEPT_LICENSE_EVENT, async (event) => {
  event.returnValue = await add(storageKey.version, config.version);
});

ipcMain.on(GET_LICENSE_EVENT, async (event) => {
  const result = await get(storageKey.version);
  event.returnValue = config.version === result;
});

```

**Comment by princesoni1989** [comment]
This is seems to be issue with my build process, Please ignore.

**Comment by amilajack** [comment]
Just curious. What was the issue?

**Comment by princesoni1989** [comment]
I used module which recursively iterate over folder and requires files in main process. When webpack was packaging app it was not calling that function so those files were not included in my main.prod.js.
