### ISSUE TITLE
How can I use dynamic videos/images and package in production?

### ISSUE THREAD

**Issue by kimthangatm** [chentsulin/electron-react-boilerplate#1405]
I added videos, images to `resource` but it only show in `dev`, not in `production` when run package.
Example: I have a list images, videos and I want to show its to user. The user can choice an item to set background application after they restart app.

**Comment by BuckyMaler** [comment]
`resources` is meant to contain only build resources. That's set in the `package.json` and used by `electron-builder` when packaging the app. Try placing your images and videos in an assets directory, such as `app/assets`.

**Comment by kimthangatm** [comment]
@BuckyMaler I placeing my images, videos in `app/assets` but it not work for production.

I use Ubuntu and I use `Toggle Developer Tools` for production and script in html like `<script defer="" src="./dist/renderer.prod.js"></script>`, and the location of js file is file:///opt/ElectronReact/resources/app.asar/dist/renderer.prod.js .

The folder structure for app in `/opt/ElectronReact/`
```
├── blink_image_resources_200_percent.pak
├── content_resources_200_percent.pak
├── content_shell.pak
├── electron-react-boilerplate
├── icudtl.dat
├── libffmpeg.so
├── libnode.so
├── LICENSE.electron.txt
├── LICENSES.chromium.html
├── locales
│   ├── am.pak
│   ├── ....
├── natives_blob.bin
├── pdf_viewer_resources.pak
├── resources
│   ├── app.asar
│   └── electron.asar
├── snapshot_blob.bin
├── ui_resources_200_percent.pak
└── views_resources_200_percent.pak
```

For the images and videos, I only want it put on a folder, not combine, compress in `app.asar`. Because if I use import videos or images, webpack will package it like `demo.mp4` to `674f50d287a8c48dc19ba404d20fe713.mp4`

So, how can put my resources (images, videos....) to install folder. Can you give me an example?

**Comment by amilajack** [comment]
I'll create an example repo for this

**Comment by amilajack** [comment]
Hi @kimthangatm. I just created a [fork of the boilerplate](https://github.com/amilajack/erb-video-example) that demonstrates importing a video using webpack. This works in dev and prod environments. Hope you find it useful

**Comment by kimthangatm** [comment]
Hi @amilajack, My question is `How can I use dynamic videos/images and package in production`.

And in previous comment
```
For the images and videos, I only want it put on a folder, not combine, compress in app.asar. Because if I use import videos or images, webpack will package it like demo.mp4 to 674f50d287a8c48dc19ba404d20fe713.mp4
```
Im my case: I have a database of images, videos and all of them in a folders. And I cannot use `import` to import static videos or images.

**Comment by SyedAman** [comment]
any solutions to this?

@kimthangatm has encountered a similar problem as me. How do you use images dynamically if you can't `require` or `import` dynamically?

None of these work. I've tried other ways too, but I haven't figured out how to dynamically import images.

`
render() {
     return fileNames.map(fileName => <img src={require(`${app.getAppPath()}/assets/fileName`)} />)
}
`

`
render() {
     return fileNames.map(fileName => <img src={`${app.getAppPath()}/fileName`} />)
}
`

`
render() {
     return fileNames.map(fileName => <img src={`${app.getAppPath()}/assets/fileName`} />)
}
`
