### ISSUE TITLE
How to reference files in production

### ISSUE THREAD

**Issue by jimmybaker** [chentsulin/electron-react-boilerplate#1409]
I've added some files to my project by including them in the app folder and referencing them in the build configuration of package.json like so:
<img width="319" alt="image 2018-02-01 at 11 40 18 pm" src="https://user-images.githubusercontent.com/50668/35718283-48741872-07a9-11e8-9ef4-a78397966f48.png">

I can use them in development mode just fine, but I get "not found" errors in the production package:

<img width="668" alt="image 2018-02-01 at 11 41 24 pm" src="https://user-images.githubusercontent.com/50668/35718297-6d1513c0-07a9-11e8-8c87-62be43dd6a02.png">

Anyone know what I'm doing wrong?

**Comment by amilajack** [comment]
Make [these changes](https://github.com/amilajack/erb-video-example#notes) to your app. Make sure to use the `.pem` extension instead of the `mp4` extension which is shown in the example. Import the `*.pem` files and they will be exposed as strings to you. ex:

```js
import pem from './foo.pem'
key = pem // typeof pem === 'string'
```

**Comment by jimmybaker** [comment]
This worked perfectly. Should I do the same thing if I want to include fonts and images? I noticed my fonts and images are not appearing in the production package as well.

**Comment by amilajack** [comment]
yup. what kinds of images and fonts do you have?

**Comment by jimmybaker** [comment]
Right now I've just been using svg for images. I think my fonts are ttf, otf and woff.

Also, thank you for the great work you've done here and for the support!
