### ISSUE TITLE
Uncaught Error: Cannot find module 'C:\Users\thierry\Desktop\electron\infoSystem\app\node_modules\sqlite3\lib\binding\electron-v1.7-win32-x64\node_sqlite3.node'

### ISSUE THREAD

**Issue by thierryxc** [chentsulin/electron-react-boilerplate#1410]
Hey,
I installed sqlite with no problem

> PS C:\Users\thierry\Desktop\electron\infoSystem\app> npm install sqlite3 --save

> sqlite3@3.1.13 install C:\Users\thierry\Desktop\electron\infoSystem\app\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

> [sqlite3]Success: 

> "C:\Users\thierry\Desktop\electron\infoSystem\app\node_modules\sqlite3\lib\binding\node-v51-win32-x64\node_sqlite3.node" is installed via remote 

but when I `var sqlite3 = require('sqlite3').verbose();`, it has error

> Uncaught Error: Cannot find module 'C:\Users\thierry\Desktop\electron\infoSystem\app\node_modules\sqlite3\lib\binding\electron-v1.7-win32-x64\node_sqlite3.node'

**Comment by amilajack** [comment]
See https://github.com/amilajack/erb-sqlite-example

**Comment by thierryxc** [comment]
ok I'll try it, thanks l lot
