### ISSUE TITLE
Got a blank page when reloaded.

### ISSUE THREAD

**Issue by AkashiX** [chentsulin/electron-react-boilerplate#1414]
I use browserHistory instead of hashHistory:
```javascript
// configureStore.dev.js
const history = createBrowserHistory({ basename: window.location.pathname });
```
instead of 
``` javascript
// configureStore.dev.js
const history = createHashHistory();
```
I do this and get a blank page, why?

**Comment by hidden4003** [comment]
works fine for me https://github.com/hidden4003/shoko-electron/blob/master/app/store/configureStore.dev.js

**Comment by cr05s19xx** [comment]
It worked for me when I used `window.location.href` instead, i.e.
```javascript
// configureStore.dev.js
const history = createBrowserHistory({ basename: window.location.href });
```

**Comment by niksauer** [comment]
> ```const history = createBrowserHistory({ basename: window.location.href });```

Sadly didn't help. Reload only works on root page. Works fine on any page with `createHashHistory`. 

Would you mind taking a look? https://github.com/niksauer/serverless-software-license-example/tree/ef0e319e8472802105f99a97a1b4a589f86fc212
