### ISSUE TITLE
Build failing due to npm module with less files

### ISSUE THREAD

**Issue by oadeojo** [chentsulin/electron-react-boilerplate#1415]
I added `"ant-design-pro": "^1.1.0"` and my build started failing.
```
ERROR in ./node_modules/ant-design-pro/es/Login/index.js
Module parse failed: Unexpected character '@' (10:0)
You may need an appropriate loader to handle this file type.
| import styles from './index.less';
|
| @Form.create()
| class Login extends Component {
|   static defaultProps = {
 @ ./node_modules/ant-design-pro/es/index.js 19:0-28
 @ dll renderer

```

I added the following to `webpack.config.renderer.dev.js`,  `webpack.config.renderer.dev.dll.js` and  `webpack.config.renderer.prod.js`

```
{
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          use: [
            {
              loader: 'css-loader',
              options: {
                minimize: true
              }
            },
            {
              loader: 'less-loader'
            }
          ],
          fallback: 'style-loader'
        })
      },

```

I still get the same error.
Sample repo: https://github.com/oadeojo/electron-react-boilerplate

**Comment by amilajack** [comment]
See https://github.com/amilajack/erb-ant-design-example

**Comment by oadeojo** [comment]
@amilajack antd works fine. Ant-Pro is the issue.

**Comment by amilajack** [comment]
I didnt know there were differences in the libraries. It is because decorators are not supported by webpack's parser yet. This doesn't have to do with the boilerplate.

**Comment by gorilla-devs** [comment]
I can't make antd with less files work. Can you share your repo if it works?
