### ISSUE TITLE
Unable to load preload script in packaged app

### ISSUE THREAD

**Issue by cobarx** [chentsulin/electron-react-boilerplate#1425]
I have a webview that uses preload to load a script in the webview. My directory structure looks like:
```
app/components/store/Store.js
app/preload/StorePreload.js
```

When developing the app, everything works fine:
`<webview preload="./preload/StorePreload.js" src="about:blank" />`

However, when I package the app, the webview isn't finding the preload script. I had to require StorePreload from Store to get it to be included in dist/bundle.js in app.asar. However no matter what path I specify, I can't seem to point to the right path. I've tried:
```
./store/StorePreload.js
remote.app.getAppPath() + '/store/StorePreload.js'
etc.
```

but end up with errors like:
```
/path/to/myproject/release/mac/MyApp.app/Contents/Resources/electron.asar…:179
Unable to load preload script: 
/path/to/myproject/release/mac/MyApp.app/Contents/Resources/app.asar/preload/StorePreload.js

/path/to/myproject/release/mac/MyApp.app/Contents/Resources/electron.asar…:180 
Error: Cannot find module '/path/to/myproject/release/mac/MyApp.app/Contents/Resources/app.asar/preload/StorePreload.js'
    at Module._resolveFilename (module.js:485)
    at Function.Module._resolveFilename (/path/to/myproject/release/mac/MyApp.app/Contents/Resources/electron.asar…:35)
    at Function.Module._load (module.js:437)
    at Module.require (module.js:513)
    at require (internal/module.js:11)
    at Object.<anonymous> (/path/to/myproject/release/mac/MyApp.app/Contents/Resources/electron.asar…:177)
    at Object.<anonymous> (/path/to/myproject/release/mac/MyApp.app/Contents/Resources/electron.asar…:184)
    at Module._compile (module.js:569)
    at Object.Module._extensions..js (module.js:580)
    at Module.load (module.js:503)
```

I'm not sure I need to use webpack and package the preload script separately or what. Any help would be appreciated.

**Comment by cobarx** [comment]
I was able to work around this by creating a separate bundle for my preload files in `dist/preload.js`. If you know of a cleaner way to do this, let me know.

**Comment by amilajack** [comment]
That is because by default electron builder doesn't add the file in the dist directory by default. See https://github.com/chentsulin/electron-react-boilerplate/issues/1043#issuecomment-312514802. You will need to do something similar to that.

**Comment by cobarx** [comment]
I ended up creating a webpack entry like you suggested. Glad to know that's the right approach. Thanks.
