### ISSUE TITLE
Thoughts on Parcel Implementation?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1430]
I'm at the end of my rope with Webpack's total lack of interest in resolving the gross source map inaccuracies. I'm wasting days of development at this point and desperate to find a resolution besides setting `devtool: 'eval'`

**Comment by amilajack** [comment]
I will consider a fork that swaps webpack for parcel.

**Comment by Slapbox** [comment]
I am working on a very basic setup right now, which I will of course post here. Should have something shortly. Unfortunately Parcel can do a lot, but not all those things are documented.

**Comment by amilajack** [comment]
Great. Point me to your fork when you're done

**Comment by Slapbox** [comment]
@amilajack here's what I've got.

https://github.com/Slapbox/electron-react-boilerplate-parcel

There's a lot left to do. For "zero-config" I sure did have a hard time getting it working, but Electron isn't exactly the simplest case I suppose.  It turned out the biggest issue was with `menu.js`. 

**Here's some things I know don't work and other notes:**

- CSS Modules don't work the same (see below)
- FontAwesome import doesn't work
- App.html has hardcoded scripts
- Main.dev.js is being loaded the same way as before
- Menu.js had to be commented out
- The `dist` folder for Parcel is at the top level, not in the `App` folder
- Probably a thing or two more I missed

**CSS Modules note:**

I had to import as `import './Home.css';` instead of `import Style from './Home.css';`

Let me know what you think. Some things like FontAwesome seem to be known issues. Other things are probably easy fixes for someone who knows better.

SourceMaps have (so far) lined up! Hooray!

**Comment by amilajack** [comment]
Nice! I'll take a look

**Comment by Slapbox** [comment]
Whoops one more note, it relies on Parcel being installed globally.

**Comment by Slapbox** [comment]
Gonna keep remembering major points I should have mentioned earlier, like that I only worked on a `dev` config, no packaging. I figured getting `dev` working is step #1.

**Comment by Slapbox** [comment]
To follow-up on this idea, I abandoned Parcel following Webpack 4. Parcel has a lot of promise, but wasn't yet ready for real-world use as of February, 2018.
