### ISSUE TITLE
Current default configuration does not work (clean boilerplate install)

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1432]
I am finding that installing `electron-react-boilerplate` as is leads to a failure to resolve the `app.html` when I run `yarn run dev`

The solution is to add a `/` to the end of the script URL in `app.html` for whatever reason.

Line 34 (fails):
`            ? 'http://localhost:' + port + '/dist/renderer.dev.js'`

Line 34 (works):
`            ? 'http://localhost:' + port + '/dist/renderer.dev.js/'`

I'm on Windows 7 x64. Can anyone else confirm this issue?

**Comment by amilajack** [comment]
I've tested on windows 10 recently and it seemed to work fine. Also our tests on windows pass.

**Comment by Slapbox** [comment]
I wonder what I could possibly have done to broken this locally.
