### ISSUE TITLE
PSA: Electron 1.8.2 - Source Map Stepping Works Differently (Not inaccurate as previously noted)

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1433]
This is not a bug, but a PSA. After spending days trying to debug broken sourcemaps, I've found it to be Electron 1.8.2 which is causing this. The boilerplate currently uses 1.7.x and I  advise everyone stick with it.

http://recordit.co/rHKX3quofA

**Comment by amilajack** [comment]
Thanks for this!

**Comment by Slapbox** [comment]
To update on this, I did make a ticket, but I haven't have time to make a repo to demonstrate this, so I expect no recognition of it until I do. After fighting for days for working source maps, I'm not in a rush to dive back in to make that repo. 

The issue is probably only in conjunction with Webpack.

https://github.com/electron/electron/issues/11984
