### ISSUE TITLE
Cant Resolves certain modules in dll.

### ISSUE THREAD

**Issue by stefan1968** [chentsulin/electron-react-boilerplate#1434]
![screen shot 2018-02-22 at 14 33 42](https://user-images.githubusercontent.com/5500038/36544114-8974d7be-17dd-11e8-9e61-04dde41ab884.png)

And yes, both modules are in the dependency (Not devDependencies) section of my package.json

It just seems to be these two particular packages.

**Comment by amilajack** [comment]
Try moving those dependencies to `devDependencies`. I think that might fix it

**Comment by stefan1968** [comment]
But they're not dev dependencies?

It's not going to help much for production build?

**Comment by amilajack** [comment]
Yea it's a little confusing. The `devDependencies` aren't bundled by the dll.

**Comment by stefan1968** [comment]
But when I make a production build the devdependencies wont be bundled in
the actual production bundle code? Therefore I'll get errors about those
modules being missing in production builds?

On 23 Feb 2018 07:07, "Amila Welihinda" <notifications@github.com> wrote:

Yea it's a little confusing. The devDependencies aren't bundled by the dll.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chentsulin/electron-react-boilerplate/issues/1434#issuecomment-367928218>,
or mute the thread

**Comment by amilajack** [comment]
None of the `dependencies` and `devDependencies` are packaged in production
