### ISSUE TITLE
Problem with run dev

### ISSUE THREAD

**Issue by cvalenzuela** [chentsulin/electron-react-boilerplate#1438]
I did a fresh install following all instructions in the `README.md` and after running `npm run dev` I get this error:

```
dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: /Users/use/testApp/app/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace

dyld: Symbol not found: _SSL_library_init
  Referenced from:  /Users/user/testApp/app/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace
```

Any ideas how to solve it?

**Comment by amilajack** [comment]
What OS are you on? Make sure that you have the build requirements. They should be in the readme

**Comment by cvalenzuela** [comment]
macOS 10.13.3. And I have all build requirements.

I managed to get around it by installing dependencies with this flags:

```
CPPFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib npm install
```

Not sure why is there a mismatch on the SSL link, could be something from my OS. I guess you can close this for now.

thanks!

**Comment by amilajack** [comment]
Did you make any modifications to the boilerplate?

**Comment by cvalenzuela** [comment]
nop

**Comment by amilajack** [comment]
> Not sure why is there a mismatch on the SSL link, could be something from my OS. I guess you can close this for now.

Yea this seems specific to your machine.
