### ISSUE TITLE
Blank page and unknown component at root

### ISSUE THREAD

**Issue by clem91** [chentsulin/electron-react-boilerplate#1449]
Hi,
I started an application with this boilerplate. It work well in dev with the HMR but when I package it. The page appear to be blank with an unknown component.

package command:
`DEBUG_PROD=true yarn run package`

here the react structure extracted from react devtool:
![react devtools screenshot](https://user-images.githubusercontent.com/10882592/36791318-c68f08d6-1c97-11e8-9873-07515f2cb743.png)

The same structure in dev environment:
![image](https://user-images.githubusercontent.com/10882592/36791600-8f3e9fb2-1c98-11e8-8fc0-5b94161c2089.png)

Does anyone have already had the same issue?

**Comment by Slapbox** [comment]
I could be totally off the mark, but may be related to this issue I had:

https://github.com/chentsulin/electron-react-boilerplate/issues/850

If it is, I included a (really ugly) workaround in that ticket.

**Comment by clem91** [comment]
I doesn't seems to be related to your issue the store and history are defined. The issue come from the routes I think but I don't know where to begin.

**Comment by clem91** [comment]
After reading the #1423 , I changed `createBrowserHistory()` to `createHashHistory()` in configureStore.prod.js to make it work but I don't know the real impact of this change. @amilajack can you tell me what are the consequences?

**Comment by amilajack** [comment]
You can safely change to `createHashHistory`. There should be no consequences in production.
