### ISSUE TITLE
React flow types are undefined

### ISSUE THREAD

**Issue by eunikitin** [chentsulin/electron-react-boilerplate#1451]
It all started when I noticed the message in the console: "flow-runtime: Could not reference the given type, try t.typeOf(value) instead. (got undefined)".

![1](https://user-images.githubusercontent.com/2767639/36906702-aa3b7208-1e47-11e8-9516-997b62970b26.PNG)

After some search i found out the reason - type definitions in App.js container. React.Node is undefined, same for other types described in [flow docs](https://flow.org/en/docs/react/types/). 

![2](https://user-images.githubusercontent.com/2767639/36906706-adc842e8-1e47-11e8-9bf9-e39c7374d208.PNG)

Does anyone know how to solve this? I mean, the main problem here is not the message itself, but undefined react type definitions.

**Comment by eunikitin** [comment]
@amilajack I have found the problem. React types are defined by flow and flow-runtime can't access them. To solve this flow-runtime has a [cli tool](https://www.npmjs.com/package/flow-runtime-cli), which resolves types from flow-typed directory and exports them to a file which should be imported to your project. I tried this myself, but i get a generic error and don't really understand how to solve this.

![image](https://user-images.githubusercontent.com/2767639/36914745-6929fd12-1e5f-11e8-95f5-acd3b6ae9503.png)

Another thing is that flow-typed directory doesn't contain any react definitions. I have found something like this [here](https://github.com/facebook/flow/blob/master/lib/react.js), but haven't tried them at the moment.

**Comment by amilajack** [comment]
Okay. Please PR if you find a solution for this

**Comment by armenr** [comment]
@eunikitin - Any hope on this? I pulled down the repo and tried getting started today...and got jammed up, dead in my tracks, over this exact issue.

Any clues?

**Comment by eunikitin** [comment]
@armenr, @amilajack actually I gave up to solve this. The problem comes from flow-runtime. The idea of the library is very cool, but it has limited flow support and huge problems with external type definitions, especially with react. I'm not so experienced with flow, actually I'm a newbie, but as I understand, it stores its type definitions in flow-typed directory and resolves them from there when running (Now, I talk about flow which is analyzes types statically, not flow-runtime, it's important). Flow-runtime has no default access to them, so you must import external types in your code by yourself. It uses babel plugin to transpile flow-like syntax to ordinary functions which execute in runtime and generate exceptions for you when something goes wrong. You can check it [here](https://codemix.github.io/flow-runtime/#/try).

So the first thought I had - was to import react type definitions myself, and thats where the first real pain began - [flow-runtime don't understand "declare" syntax of flow.](https://flow.org/en/docs/libdefs/creation/) "Ok", said I, found react type definitions, which was another challenging quest and started to rewrite them without declare statements, at some point I thought I succeeded but after some tests I found some strange behavior I cannot understand and describe clearly, I can only assume what is happening.

The code had a lot of [generic types magic](https://media1.giphy.com/media/12NUbkX6p4xOO4/giphy.gif). And everything breaks when flow-runtime checks this:

![image](https://user-images.githubusercontent.com/2767639/38951584-d187b766-4351-11e8-9791-d291a1d0d1c3.png)

I have a thought that ElementType is not a valid type, but flow-runtime internal function, like one of this which define types in runtime.

![image](https://user-images.githubusercontent.com/2767639/38951756-4ae80bce-4352-11e8-8bcb-3dc4298653b3.png)

Also I had another idea - as I wrote earlier I tried to use cli tool but it's buggy and doesn't work:C So I've spent about a week trying to fix this, but failed and took a break when I'll have more free time.

**Comment by eunikitin** [comment]
Also, I have opened a ticket in flow-runtime repo, but it has no replies:( https://github.com/codemix/flow-runtime/issues/198

**Comment by kwdata** [comment]
// @flow
import * as React from 'react';
import type {Node} from 'react';

type Props &lt;Node&gt; = {
children: Node
};

**Comment by eunikitin** [comment]
@kwdata Node in Props definition is not an imported one. [It's a generic](https://flow.org/en/docs/types/generics/), so when you use your Props somewhere, you will need to write something like this:

`
class Example extends Component<Props<SomeNodeDefinition>> {}
`

It's just a variable type, you should specify later. Try to console.log your own type and types you've imported from react and you'll notice that your types are functions but imported are undefined.
