### ISSUE TITLE
postinstall script fails after adding CSS library (like Bootstrap)

### ISSUE THREAD

**Issue by zaki-yama** [chentsulin/electron-react-boilerplate#1454]
I'd like to ask you the correct way installing 3rd party CSS library, like [bootstrap](https://getbootstrap.com/).

When I run

```zsh
$ git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git your-project-name
$ cd your-project-name
$ yarn
$ yarn add bootstrap
```

It raises the following error.

<details>
  <summary>Error log when installing bootstrap</summary>

```
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors

Hash: 972cdc4ff7d2b48360d3
Version: webpack 3.10.0
Time: 1365ms
              Asset     Size  Chunks                    Chunk Names
renderer.dev.dll.js  1.28 MB       0  [emitted]  [big]  renderer
[./node_modules/electron-debug recursive] ./node_modules/electron-debug 160 bytes {0} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 596 bytes {0} [built]
   [0] dll renderer 12 bytes {0} [built]
    + 149 hidden modules

WARNING in ./node_modules/electron-debug/index.js
81:45-58 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
84:85-106 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'jquery' in '/Users/yamazaki/workspace/electron/electron-react-boilerplate/node_modules/bootstrap/dist/js'
 @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:81-98
 @ dll renderer

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in '/Users/yamazaki/workspace/electron/electron-react-boilerplate/node_modules/bootstrap/dist/js'
 @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:100-120
 @ dll renderer
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! electron-react-boilerplate@0.13.2 build-dll: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.13.2 build-dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yamazaki/.npm/_logs/2018-03-04T21_13_00_517Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
</details>

Also, when I try to install [Lightning Design System](https://lightningdesignsystem.com/), I got the following error.

<details>
  <summary>Error log when installing lightning design system</summary>

```
$ yarn add @salesforce-ux/design-system
...
ERROR in dll renderer
Module not found: Error: Can't resolve '@salesforce-ux/design-system' in '/Users/yamazaki/workspace/electron/electron-react-boilerplate'
 @ dll renderer

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'jquery' in '/Users/yamazaki/workspace/electron/electron-react-boilerplate/node_modules/bootstrap/dist/js'
 @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:81-98
 @ dll renderer

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in '/Users/yamazaki/workspace/electron/electron-react-boilerplate/node_modules/bootstrap/dist/js'
 @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:100-120
 @ dll renderer
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! electron-react-boilerplate@0.13.2 build-dll: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.13.2 build-dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yamazaki/.npm/_logs/2018-03-04T21_19_46_858Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
</details>

I found that in [webpack.config.renderer.dev.dll.js#L175-L181](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.dev.dll.js#L175-L181), some dependencies are excluded from dll, so I changed like this:

```javascript
entry: {
  renderer: (
    Object
      .keys(dependencies || {})
      .filter(dependency => {
        // also ignore installed CSS library
        return dependency !== 'font-awesome' && dependency !== '@salesforce-ux/design-system';
      })
  )
},
```

installation successfully finished.

But I don't know what is the correct way. Does it mention in the docs?

**Comment by amilajack** [comment]
`popper.js` and `jquery` is a peerDeps of bootstrap

**Comment by zaki-yama** [comment]
@amilajack 
Thanks for your reply.
What about other CSS frameworks?

Actually what I want to know is the correct way adding any CSS library, not how to install bootstrap.

**Comment by amilajack** [comment]
What kind of UI library? There's many kinds. There are react-based ones. If you're going that route, I would recommend [styled-components](https://www.styled-components.com). If you're not the I'd recommend bootstrap or antd. Here's a working example for [antd](https://github.com/amilajack/erb-ant-design-example). It really depends on the library. For styled-components, you should be able to just import it and use it like you would in any other react app.

**Comment by zaki-yama** [comment]
I'd like to use [Lightning Design System(LDS)](https://lightningdesignsystem.com/), pure CSS library created by Salesforce.

Thank you very much for introducing me your [antd example](https://github.com/amilajack/erb-ant-design-example)!
I've never heard of that library, but certainly I could install it without errors (`yarn add antd`).

It seems the difference between antd and LDS (& font-awesome) is that, antd has JS files and LDS & font-awesome doesn't.
If I want to install the UI library which contains no JS files, I should ignore from `entry` by hand?

**Comment by amilajack** [comment]
Yes, see [this example](https://github.com/amilajack/popcorn-time-desktop/blob/master/app/styles/main.scss#L13-L16). You can import `css/scss` styles without importing js.

**Comment by zaki-yama** [comment]
Thank you. That's really helpful.

I found that, one of the libraries you highlighted above, `ionicons-temp` is pure CSS library.
But you defined it as `devDependencies`, not `dependencies` in `package.json`.

So when running `build-dll`, `ionicons-temp` is not contained [here](https://github.com/amilajack/popcorn-time-desktop/blob/master/webpack.config.renderer.dev.dll.js#L9).
So build finishes successfully.

I refer to your approach, thanks!

**Comment by amilajack** [comment]
Yea. Adding dependencies to `devDependencies` ensures that they dont get bundled in the webpack dll

**Comment by alvirtuoso** [comment]
@amilajack So how can I add jquery and popper.js for bootstrap to work? The example link will work with bootstrap alerts?

**Comment by amilajack** [comment]
@alvirtuoso. I believe so. Try it
