### ISSUE TITLE
aws-amplify Browserify is not defined

### ISSUE THREAD

**Issue by Crowstrum** [chentsulin/electron-react-boilerplate#1460]
I am by no means a webpack wizard, so some help to point me in the right direction would be great. 
If I do a fresh clone of the repo and install the aws-amplify package on running the project I get an error saying “Browserify is not defined” it appears to be stemming from crypto-Browserify which this package leverages when doing auth. 
I am 99% sure I’m just missing something in the webpack configs, and of course I have searched for the solution but to no avail.

**Comment by amilajack** [comment]
it uses c so its probably a native dependency. Try installing it to `./app/package.json` instead of `./package.json`. See [my explanation](https://github.com/chentsulin/electron-react-boilerplate/issues/1042#issuecomment-307336977)

**Comment by philippefutureboy** [comment]
As a note for whoever passes by here, the package to install in `./app/package.json` is `aws-amplify`, not `crypto-browserify`
