### ISSUE TITLE
Further modularizing .dev.dll 

### ISSUE THREAD

**Issue by nessup** [chentsulin/electron-react-boilerplate#1468]
Since the `module` property of `webpack.config.renderer.dev.dll` contains the same thing as the `module` property in `webpack.config.renderer.dev`, I'm wondering if there was there a reason for the repetition. If not, maybe we could rewrite `webpack.config.renderer.dev.js` and `webpack.config.renderer.dev.dll.js` sorta like this:

```js
// In webpack.config.renderer.dev.dll...
export default merge.smart(baseConfig, {
  // ...
  module: require('./webpack.config.renderer.dev').module
  // ...

// In webpack.config.renderer.dev...
if (module.parent.filename !== 'webpack.config.renderer.dev.dll.js' && !(fs.existsSync(dll) && fs.existsSync(manifest))) {
```

That's the basic idea. Might look weird or have other unintended side effects, but curious if something like this makes sense or can be done better? Happy to PR with a working version

**Comment by amilajack** [comment]
Good suggestion. The configs actually used to be more modular. But here's the issue:
If the dll isn't built, `webpack.config.renderer.dev.js` will run `yarn build-dll`, which build's the dll. But the `webpack.config.renderer.dev.dll.js` imports the `webpack.config.renderer.dev.js`. So here's the cycle:

`build-dll` => `import dev dll` => `imports dev` => `build-dll` => `import dev dll` => `imports dev` 
...and so on

But there should be a workaround for this. Simplifying configs when possible is definitely the direction the boilerplate should be heading in

**Comment by nessup** [comment]
I'll send in a PR with one possible solution soon
