### ISSUE TITLE
Including Dependencies from both Package.json Files in DLL

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1471]
It seems like only dependencies references in my top level package.json are built into the DLL. Is this some behavior I've accidentally introduced? Behavior by design? Something with room for improvement? Thanks!

**Comment by amilajack** [comment]
This was intentional. I'll investigate this further to see if this is possible. I suspected that webpack couldn't do much because `./app/package.json` deps are externals anyways so webpack can't process them

**Comment by Slapbox** [comment]
Thanks for the Webpack lesson and speedy response as always @amilajack!

I have most of my dependencies in the top level, but the build time on my project just keeps growing and I'm running out of ways to keep it in check.

**Comment by amilajack** [comment]
Can you share the results of the bundle analyzer and tell me how many dependencies you have? Maybe I can help you optimize your workflow
