### ISSUE TITLE
How to run locally in prod mode

### ISSUE THREAD

**Issue by neerajdotname** [chentsulin/electron-react-boilerplate#1476]
`npm run dev` runs app in dev mode.

Before packaging I want to test the app in prod mode. What command I need to execute to do that.

**Comment by amilajack** [comment]
Add a script called `"start-prod": "cross-env NODE_ENV=production electron ./app/main.prod.js",` and then run `npm run start-prod`. note that this skips building the main and renderer processes in production. It assumes that you've done that already =

**Comment by amilajack** [comment]
Forgot to mention that that script should be an npm script. I updated my comment

**Comment by neerajdotname** [comment]
If I understand correctly then I need to execute following commands.

```
npm run build-main #builds in prod mode by default
npm run build-renderer #builds in prod mode by default
npm run start-prod
```

Should we add it to README? Others might have the same question.

**Comment by amilajack** [comment]
Yea I can PR for that
