### ISSUE TITLE
ERR_FILE_NOT_FOUND multiple times when running in production.

### ISSUE THREAD

**Issue by NatKarmios** [chentsulin/electron-react-boilerplate#1477]
When my app has been packaged and is running in production, I'm getting some `ERR_FILE_NOT_FOUND` messages in the console, and I can't for the life of me figure out what's causing it.

It *looks* like there are font files missing, though it seems any fonts needed by my app are there (the text at the top-left of the screenshots is in the correct font in both cases).

In case it's relevant, I'm using beta v38 of Material-UI.

Here are some screenshots...

In dev mode (working):
![In dev mode (working)](https://puu.sh/zK4H7/5f388fa645.png)

In production (not working):
![In production (not working)](https://puu.sh/zK4yV/d8f909bf67.png)

*Note:*
*In case of confusion, it may look like one screenshot is from Windows and the other from Linux, but the Windows screenshot is just being run on the same Linux device, via X-Forwarding.*

**Comment by amilajack** [comment]
Try making the following change to your app

**Comment by NatKarmios** [comment]
@amilajack, sorry, what change?

**Comment by amilajack** [comment]
Oh whoops. Forgot to add the link. Here it is: https://github.com/chentsulin/electron-react-boilerplate/pull/1473/files

**Comment by NatKarmios** [comment]
Ok, that seems to work for the styling just fine. However, the content of my app isn't showing at all, whilst the navbar is (it still looks largely similar to the above screenshots, but with correct styling in the navbar).
@amilajack, know any fixes for this?
Thanks a bunch for your help so far.

**Comment by amilajack** [comment]
What are the errors?

**Comment by NatKarmios** [comment]
There aren't any.

**Comment by NatKarmios** [comment]
I suppose I should make a new issue for this, since it's likely a different problem entirely.
