### ISSUE TITLE
Router renders nothing whilst in production.

### ISSUE THREAD

**Issue by NatKarmios** [chentsulin/electron-react-boilerplate#1479]
When building my app for production and running it, the router/switch does not appear to render.
There are no errors being printed to the console. I have tried changing the default route to a simple component to see if it was update blocking, but it still does not render (though it may still be blocking and I just don't understand the issue). It gets as far as rendering the `App` and `Switch` components , but nothing renders inside the `Switch`.

**Comment by NatKarmios** [comment]
Ok, I think I've fixed it; I changed `createStore.prod.js` to use `createHashHistory` rather than `createBrowserHistory`.
This seems to resolve it; maybe this is how it should be in the boilerplate?

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.3/app/store/configureStore.prod.js

**Comment by kimgysen** [comment]
Why is ERB married to flow? Why is the issue on how to deactivate Flow referenced here without further follow-up? Not sure I'm getting this.

**Comment by amilajack** [comment]
There are plans on making a migration to typescript soon
