### ISSUE TITLE
How to disable Flow and ESLint without tears?

### ISSUE THREAD

**Issue by pooya-golchian** [chentsulin/electron-react-boilerplate#1480]
When i build my application, i see White Screen of Death?
Please help, How to disable Flow and ESLint?
Thanks. :+1:

**Comment by amilajack** [comment]
See https://github.com/chentsulin/electron-react-boilerplate/issues/1479

**Comment by arnaudambro** [comment]
@amilajack I don't see in your link the way to disable flow.
Is there a way ?
