### ISSUE TITLE
Error when using with nightmare.js

### ISSUE THREAD

**Issue by JonathanKolnik** [chentsulin/electron-react-boilerplate#1487]
* **Version**: 19.55.3

* **Target**: OSX 10.12.6

Hi I am trying to require Nightmare and call it from an action in my [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) app. 

I have made an example project [here](https://github.com/JonathanKolnik/nightmare-electron-react-boilerplate/commit/56e7eee321eac5e37e624ea1e7c3c9b9ad18e6c5)

As you can see the only changes I have made are adding `nightmare` to package.json

package.json https://github.com/JonathanKolnik/nightmare-electron-react-boilerplate/commit/56e7eee321eac5e37e624ea1e7c3c9b9ad18e6c5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R194
```
"nightmare": "^3.0.0",
```

and requiring nightmare in my actions file.

app/actions/counter.js https://github.com/JonathanKolnik/nightmare-electron-react-boilerplate/commit/56e7eee321eac5e37e624ea1e7c3c9b9ad18e6c5#diff-8d8cfdccbaf9609609d43684b5474d22R4
``` 
var Nightmare = require('nightmare');
```

Upon running my app locally, with `yarn run dev`, the error in the console is:

```
nightmare.js:332 Uncaught Error: Cannot find module "."
    at webpackMissingModule (nightmare.js:332)
    at Object.eval (nightmare.js:332)
    at eval (nightmare.js:643)
    at Object../node_modules/nightmare/lib/nightmare.js (renderer.dev.dll.js:598)
    at __webpack_require__ (renderer.dev.dll.js:21)
    at Object../node_modules/nightmare/lib/nightmare.js (nightmare.js from dll-reference renderer:1)
    at __webpack_require__ (bootstrap d137ae8…:678)
    at fn (bootstrap d137ae8…:88)
    at Object.<anonymous> (counter.js:4)
    at Object../app/actions/counter.js (renderer.dev.js:840)
```
![image](https://user-images.githubusercontent.com/1164060/37923911-5c454c62-30fe-11e8-8ac9-f9b459ce2020.png)

I am new to electron development so I might be doing something fundamentally wrong by trying to execute nightmare from the actions file like this. I think this might be somewhat related to https://github.com/electron-userland/electron-builder/issues/1776 but I am not sure.

I know that if I make a script tag in my index.html, I can run nightmare successfully from that file.

Actually I tried to use puppeteer and I got the same error so I'm not sure if it is particularly specific to that library or something I am missing with how to import/require.

Any help would be greatly appreciate!

**Comment by amilajack** [comment]
install nightmare.js to `devDependencies`. If you're trying to use it in production, install to `dependencies` of `./app/package.json`
