### ISSUE TITLE
Integrate g-suite (google) for signup and get user roles

### ISSUE THREAD

**Issue by cubet-rahul** [chentsulin/electron-react-boilerplate#1490]
How can we integrate google signup with this?
Since its a desktop application we cannot use the redirect_url to get the token values after authentication with google. 
Please help.

**Comment by talha131** [comment]
> How can we integrate google signup with this?

There are number of guides available for this scenario 

1. [Google Auth in Electron](https://blog.ecliptic.io/google-auth-in-electron-a47b773940ae)
1. [Electron. oAuth authentication with GitHub](https://www.manos.im/blog/electron-oauth-with-github/)
1. [electron-oauth2](https://www.npmjs.com/package/electron-oauth2)
