### ISSUE TITLE
how to get the bundle id?

### ISSUE THREAD

**Issue by harikrishnanssomdev** [chentsulin/electron-react-boilerplate#1491]
Hi , 
            i have developed a desktop application using electron-react-boilerplate which uses a third party sign-in(google) , so i have to give a return url(instead a bundle id) to get back to the application after signing in using google. where would i get this bundle id or appID of this application?

Help would be awesome

**Comment by Slapbox** [comment]
Can you post some more context on what exactly you're trying to do?

**Comment by amilajack** [comment]
Closing due to no response
