### ISSUE TITLE
include scripts in html

### ISSUE THREAD

**Issue by NugzarGaguliya** [chentsulin/electron-react-boilerplate#1502]
I have some libraries that must be included in html.
In dev i put them in app/libs/ and include like <script src="./libs/snap.svg-min.js"></script>
But in prod app tries to get them from /release/win-unpacked/resources/app.asar/libs/snap.svg-min.js
How i can put external libraries in html, so the build process will copy them to the destination folder and insert correct path?

**Comment by dayfine** [comment]
I think (might be wrong, as I only did it once) you can include what files to package in the `outside package.json` under `build/files`. You can specify any file or directory there, then they will be packaged into somewhere under `release`, you can just tell you app to find it there in `production` mode.

**Comment by amilajack** [comment]
Including html scripts in the boilerplate's html is an antipattern. You should try to import scripts from your app itself. For example, you should try importing the script from `./app/index.js`. This allows you to reap the benefits of optimization from webpack, uglify, etc.

**Comment by NugzarGaguliya** [comment]
@dayfine outside package.json you mean outside boilerplate folder or inside it? I tried my-app/build/files/snap.svg-min.js but release folder after package contains only boilerplate files.

@amilajack I know, but if two libraries use global scope window, I can only edit those libraries to work them in import mode. It's not good idea too.

**Comment by dayfine** [comment]
@NugzarGaguliya Put the path to your file in [here](https://github.com/chentsulin/electron-react-boilerplate/blob/586b84f0ed5d1ded13ab296ba1219d26c70bb9dc/package.json#L37). My use case was I have a python module outside of this that I need to include, and I made it happen by including the path here. This should at least get the file into the right location. Not sure if there's a better way though.

**Comment by NugzarGaguliya** [comment]
it works, thank you
