### ISSUE TITLE
Method for debugging in packaged application no longer works

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1503]
I think this used to work in the packaged app (`yarn run package`) and not only when using `yarn run start` but this no longer works with the current dependency versions. (Or this never worked in the packaged application and I'm remembering incorrectly.)

**Comment by amilajack** [comment]
Are you using the `DEBUG_PROD` env variable?

**Comment by Slapbox** [comment]
Yep yep. Doesn't work in the packaged application anymore. A search turned up lots of results saying it's not possible to set environmental variables in packaged electron apps. I don't know if this is true.

This did used to work in the packaged application ~ 1 year ago though, didn't it? I'm not crazy?

**Comment by Slapbox** [comment]
This is very likely the solution. Trying it now. [Looking back through the history of that file, it used to contain this code](https://github.com/chentsulin/electron-react-boilerplate/blob/5369809a6cff10195e666949f123fd033e3803ff/webpack.config.main.prod.js):

```
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
      'process.env.DEBUG_PROD': JSON.stringify(process.env.DEBUG_PROD || 'false')
    })
```
Whereas it now contains:

```
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      DEBUG_PROD: 'false'
    })
```

**Comment by amilajack** [comment]
Interesting. I checked the `v0.13.3` branch and this seems to work. Can anyone reproduce this error on that branch?

**Comment by Slapbox** [comment]
I haven't tried `0.13.3`, but given that Webpack is being told to set it to false unconditionally in the main process (which runs the `menu.js` file which checks for the `DEBUG_PROD` variable) I don't see how it could work. 

In my case I am using Webpack 4, but even on Webpack 3 I could not get this working. I'm on Windows 7. @amilajack, what OS do you use? The only thing I can imagine is that the variable set by `cross-env` takes precedent over the `webpack.EnvrionmentPlugin`, but at least on Windows 7 this is not the case.

**Comment by BuckyMaler** [comment]
@amilajack I couldn't reproduce this on branches `v0.13.3` or `v0.14.0` on macOS.

@Slapbox the `EnvironmentPlugin` is configured with [default values](https://webpack.js.org/plugins/environment-plugin/#usage-with-default-values). Keys defined on `process.env`, such as in the terminal, will take precedence over the `EnvironmentPlugin` config.

Unfortunately, I don't have a windows machine to test on. I would give the following a shot:

`set DEBUG_PROD=true yarn run start`

or

`set DEBUG_PROD=true && yarn run start`

**Comment by Slapbox** [comment]
Whoops. This issue should be closed. This was solved in another thread that I can't find right now.

I'm not sure if the solution has been merged though.
