### ISSUE TITLE
Packaging project on NPM throws errors

### ISSUE THREAD

**Issue by goldylucks** [chentsulin/electron-react-boilerplate#1507]
Not sure if this is an "issue" per se, since I assume this project is not designed to be exported as an npm package.

I'm building an electron app with this boilerplate, and we need to package it as an npm package, and we run into many errors on install.

the post install script: `Arguments: -c node -r babel-register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`

throws `Error: Cannot find module 'babel-register'`

Which makes sense, since 'babel-register'` is a dev dependency

I can probably get around that, but I'm wondering what is the way to go in order to package the project ad an npm package?

I don't see reference for that on the documentation.

**Comment by goldylucks** [comment]
I'd be more than happy to send a PR with docs + examples, given some guidance (this is my first project on electron)

**Comment by amilajack** [comment]
Hmm that's weird. I'm not sure why you're getting that error.

**Comment by goldylucks** [comment]
I'm closing this since it doesn't bother us, and doesn't seem to be relevant for anyone else ATM
