### ISSUE TITLE
inspect element on production build

### ISSUE THREAD

**Issue by goldylucks** [chentsulin/electron-react-boilerplate#1508]
I'm passing `DEBUG_MODE=true npm run start` but can't right click and inspect element.

I see in the docs I should build the app with the production flag, but I want to be able to pass a debug flag to a production build, and be able to open the dev tools.

from `menu.js`, it looks like it should be possible, since the check for debug flag is in runtime, right?

so why doesn't it work?

**Comment by amilajack** [comment]
You're supposed to run `DEBUG_PROD=true` not `DEBUG_MODE=true `
