### ISSUE TITLE
linting broken when adding resolve.alias to webpack

### ISSUE THREAD

**Issue by goldylucks** [chentsulin/electron-react-boilerplate#1509]
I added resolve.alias:

```
// webpack.config.base.js
resolve: {
  extensions: ['.js', '.jsx', '.json'],
  modules: [
    path.join(__dirname, 'app'),
    'node_modules',
  ],
  alias: {
    '@fortawesome': path.join(__dirname, 'app', 'vendor', '@fortawesome'),
  },
},
```

The alias is working, and app is working fine, but the eslint is broken:

```
$ npm run lint

> @zen/zen-wallet@0.2.15 lint /Users/goldy/apps/zenwallet
> cross-env NODE_ENV=development eslint --cache --format=node_modules/eslint-formatter-pretty .

Cannot find module '/Users/goldy/apps/zenwallet/app/webpack.config.eslint.js'
Error: Cannot find module '/Users/goldy/apps/zenwallet/app/webpack.config.eslint.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.exports.resolve (/Users/goldy/apps/zenwallet/node_modules/eslint-import-resolver-webpack/index.js:68:25)
    at v2 (/Users/goldy/apps/zenwallet/node_modules/eslint-module-utils/resolve.js:94:23)
    at withResolver (/Users/goldy/apps/zenwallet/node_modules/eslint-module-utils/resolve.js:99:16)
    at fullResolve (/Users/goldy/apps/zenwallet/node_modules/eslint-module-utils/resolve.js:116:22)
    at Function.relative (/Users/goldy/apps/zenwallet/node_modules/eslint-module-utils/resolve.js:61:10)
    at remotePath (/Users/goldy/apps/zenwallet/node_modules/eslint-plugin-import/lib/ExportMap.js:379:30)
```

on Atom, linting on files that import '@fortawesome' are broken as well.

Any ideas why is that happening, and how can I fix that?
Do you have an example of a project that uses this boilerplate and has resolve.alias in `webpack.config.base.js`?

**Comment by Slapbox** [comment]
I spent quite a while on this and found no way to get resolving of aliases to work. If you do find a solution though, I would be very glad to hear it.

**Comment by goldylucks** [comment]
@Slapbox I prefer to explicitly import it wherever I'm using it, and not have `<FontAwesomeIcon />` out of nowhere in my app.

**Comment by goldylucks** [comment]
@amilajack have you tried [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver)?

I also tried [resolving webpack path in .selintrc](https://github.com/benmosher/eslint-plugin-import/issues/352#issuecomment-236821515) and didn't work for me (need to convert to `.eslintrc.js` file to try this)

I did NOT try [re writing webpack file in ES5](https://github.com/benmosher/eslint-plugin-import/issues/352#issuecomment-284216693)

Don't know if it's related: in our `webpack.config.eslint.js` we export `module.exports = require('./webpack.config.renderer.dev');` and NOT the `webpack.config.base.js` file. Why is that?

**Comment by amilajack** [comment]
The base config doesn't have the configuration for styles

**Comment by Mati365** [comment]
If you use .eslintrc or .eslintrc.yml please rename it to .eslintrc.js and change webpack resolve function to something like it:
`webpack: {
        config: resolve('./webpack.config.eslint.js'),
      },`
In my case it fixed the problem

**Comment by goldylucks** [comment]
@Mati365 

this works, but breaks atom-linter, see [issue](https://github.com/AtomLinter/linter-eslint/issues/926), tho it has a workaround I tested and it works.

so might be worth while to combine the two approaches?

You can see how I implemented it for atom [here](https://gitlab.com/zenprotocol/zenwallet/commit/77a6d1f83bb4cc4f887a4604ea120a3ffa6e303d?view=parallel)

**Comment by outkine** [comment]
A word of warning: if you're using VSCode the `.eslintrc.js` method seems to break the eslint extension because the eslint server does not have `NODE_ENV` set, and the `CheckNodeEnv('development')` in the `webpack.config.renderer.dev.js` file referenced by `eslint-import-resolver-webpack` requires it. My temporary fix is just to delete that line, but a better solution might just be to stop using the `eslint-import-resolver-webpack` plugin entirely, and replace it by defining the same resolution options as in webpack in the `import/resolver` settings of the `.eslintrc`. I know that this method seems repetitive, but we already have to do that for the `.flowconfig` so I don't think it's that bad. Plus, it gets rid of a dependency :)
