### ISSUE TITLE
Package options not being honoured

### ISSUE THREAD

**Issue by mikerockett** [chentsulin/electron-react-boilerplate#151]
Running `npm run package --asar --name TestReactApp` yields the same result as `npm run package`, with the app's name defaulting to `ElectronReact` and the asar archive not being created (I would assume this should sit alongside `atom.asar`).

Running on Windows, if that makes a difference.

**Comment by chentsulin** [comment]
try `npm run package -- --asar --name TestReactApp`

**Comment by mikerockett** [comment]
Ah, that works, and it explains `"package-all": "npm run package -- --all",` as well (should have tried adding `--` first). What exactly does that do?

**Comment by chentsulin** [comment]
>  The special option `--` is used by getopt to delimit the end of the options. npm will pass all the arguments after the `--` directly to your script:
see: https://docs.npmjs.com/cli/run-script

**Comment by mikerockett** [comment]
:+1: Thanks

**Comment by talha131** [comment]
@chentsulin I tried 

```bash
npm run package-all --asar --name "My App Name"
```
But it didn't honor `--asar` option neither `--name`.

On the other hand

```bash
npm run package -- --all --asar --name "My App Name"
```
works fine.

Any idea why 

```json
"package-all": "npm run package -- --all",
```

in `package.json` is not working.

**Comment by chentsulin** [comment]
@talha131 see my comment above and doc of npm [run-script](https://docs.npmjs.com/cli/run-script)

**Comment by talha131** [comment]
Thank you. 

```bash
npm run package-all -- --asar --name "My App Name"
```

worked.

--- 

A bit tidbit to other people who land here regarding `--icon` option. 

I have to build for Windows platform on a Mac platform. `--icon icon.ico` was not working.

From [`electron-packager` docs](https://github.com/electron-userland/electron-packager)

> If the file extension is omitted, it is auto-completed to the correct extension based on the platform, including when `--platform=all` is in effect.

Therefore, I renamed icon files to

1. icon.icns 
1. icon.ico 
1. icon.png

And change my command to 

```bash
npm run package-all -- --asar --name "My App Name" --icon icon
```

which solved the issue.
