### ISSUE TITLE
Antd styles not working

### ISSUE THREAD

**Issue by gorilla-devs** [chentsulin/electron-react-boilerplate#1511]
I am trying to install antd into this boilerplate. The components are working fine but the styles are not applied. I tried following their guide installing
`yarn add babel-plugin-import`
and then 
`yarn`
then i edited my `.babelrc`:
```
"plugins": [
  "add-module-exports",
  [
    "import",
    {
      "libraryName": "antd",
      "libraryDirectory": "es",
      "style": "css"
    }
  ]
],
```
but still, the styles do not apply. If I inspect the html i can see the classes applied to the button but no styles related to those classes. I tried importing the styles in every way and the only way i could make it work was adding this in the head of app.html, just below the title:
`<script type="style/css" src="../node_modules/antd/dist/antd.css">`
but it was only working in dev, when i package my application it obviously does not work. I couldn't find any information on how to make styles work, any idea?
To reproduce the situation just clone this repo, and try make antd work. If you succeed doing that please share your work

**Comment by amilajack** [comment]
See [this working example](https://github.com/amilajack/erb-ant-design-example)

**Comment by helpceo** [comment]
How to solve？

**Comment by gorilla-devs** [comment]
I solved by importing the entire compiled css antd file.
So in my global css file i have:
`@import "./antd.css";
`
where antd.css is the compiled css from antd. Since i needed it modified i included a less autocompile task in my package.json that compiles antd less files and generate that css compiled file.
If you want you can take a look at the project i used it in [here](https://github.com/gorilla-devs/GDLauncher/tree/cafef648425051edfdebdb8a59835e5046acdee2)

**Comment by wujian-nerc** [comment]
I solved by modifying webpack.config.render.dev/prod.js

`{
  test: /^((?!\.global).)*\.css$/,
  exclude: /node_modules/,
  use: [
    {
      loader: 'style-loader'
    },
    {
      loader: 'css-loader',
      options: {
        modules: true,
        sourceMap: true,
        importLoaders: 1,
        localIdentName: '[name]__[local]__[hash:base64:5]'
      }
    }
  ]
},
{
  test: /\.css$/,
  include: /node_modules/,
  use: [
    {
      loader: 'style-loader'
    },
    {
      loader: 'css-loader'
    }
  ]
}`

**Comment by gcfabri** [comment]
How to solve this?

**Comment by gcfabri** [comment]
> [Example here](https://github.com/amilajack/erb-ant-design-example)

What I supposed to do? I installed `antd` package and import on app.global.css: `@import '~antd/dist/antd.css';`

I made some changes on Home component to use a simple Button from antd and then run script `package-win`.

The `css` seems to work but the fonts are broken. See this [image](https://imgur.com/a/7b4huOq)

**Comment by EugeneSnikhovskiy** [comment]
If someone has this problem. You can fix this without webpack config changes.
Just create local styles file with name your-name.**global**.scss, import it to your App component, and inside styles file add antd. For example
```scss
// file styles.global.scss
@import '~antd/dist/antd.dark.min.css';
```

```ts
import React from 'react';

import './styles.global.scss';
import { Router } from './router';

export function App() {
  return <Router />;
}
```
