### ISSUE TITLE
How to change the Redux state when the user clicks on an Electron menu?

### ISSUE THREAD

**Issue by andrerpena** [chentsulin/electron-react-boilerplate#152]
I'm trying to load the Redux state from a file.

In the main.js file I can implement the behavior for the Electron menu items:

```
 submenu: [{
    label: '&Open',
    accelerator: 'Ctrl+O',
    click: function() {
        // I want to change the Redux state here
    }
  }
```

... However I don't know how to change the Redux state from the click function.

Any idea?

When I find a solution I'm willing to make a PR for documenting this since I think the majority of use cases for this project will involve changing the Redux state based on opening a file.

Thank you.

**Comment by andrerpena** [comment]
I ended up [posting this question on Stackoverflow as well](http://stackoverflow.com/questions/35529532/how-to-change-the-redux-state-based-on-an-electron-menu-click).

**Comment by andrerpena** [comment]
Vadim Macagon has answered my question on Stackoverflow. I'm going to document that on the readme file and submit a pull-request. I hope you accept that.

**Comment by chentsulin** [comment]
duplicated of #118. PR Welcome.
