### ISSUE TITLE
Referencing a file for child_process in dev and production.

### ISSUE THREAD

**Issue by yourfavorite** [chentsulin/electron-react-boilerplate#1521]
I have a file that is located at `/app/lib/manager.js` that calls another file at `/app/lib/process.js` to create a child process and I'm struggling to find a good way to load this properly in both dev and production.

In manager.js I call process.js like this:
```process = cp.fork(`${__dirname}/process.js`, []);```

I can make this work for dev and prod by adding process.js to my package.json build files and changing my webpack.config.main.prod.js to have the following:
```
  entry: {
    'main.prod': path.join(__dirname, 'app/main.dev'),
    'process': path.join(__dirname, 'app/lib/process.js')
  },

  output: {
    filename: '[name].js',
    path: path.join(__dirname, '/app')
  },
```

The problem with this flow is that it creates a process.js file in the /app directory when I run build or package which feels messy. I'd rather not have a duplicate file there. How should I handle this? Thanks!

**Comment by gorilla-devs** [comment]
Can you explain in details how you made it work? I am trying to spawn a child process in my app and it works fine, the problem is that that file is not parsed by webpack so imports/exports will not work. I tried to add that file to package.json but nothing changed

**Comment by amilajack** [comment]
Take a look at https://github.com/chentsulin/electron-react-boilerplate/issues/1043#issuecomment-312514802

**Comment by yourfavorite** [comment]
I never got around this. I just learned to deal with having the duplicate file. You could possibly move it to a different folder so its not in the root bothering you. Maybe have it compile into the /dist/ folder? Then you'd just need to do some handling so that in dev it pulls the original file and in prod it pulls the compiled file in the /dist/ folder.

**Comment by gorilla-devs** [comment]
@yourfavorite can you please write in details the steps you took in order to make it work? I got a file app/workers/downloadPack.js which is using an import statement. It says the import is not valid so i am obliged to use commonjs require. I tried adding the file
```
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "splash.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json",
      "workers/downloadPackage.js"
    ],
```
but it still says the same.
If i try to add two entry points it raises some new errors

**Comment by yourfavorite** [comment]
My entry still looks like I had it in my original post. I wasn't having issues getting my files to load properly, I was only looking for a way around having duplicate files due to webpack build.
