### ISSUE TITLE
Replace "npm ls" in CheckNativeDep.js

### ISSUE THREAD

**Issue by ManuKle** [chentsulin/electron-react-boilerplate#1524]
In CheckNativeDep.js npm ls is used to find dependencies of native packages.
Unfortunately, npm ls fails as soon as there are unmet peer dependencies (see [here](https://github.com/npm/npm/issues/17624)).

I'd suggest replacing the command and checking the dependencies programmatically. If you agree I can give it a try and send a PR.

**Comment by amilajack** [comment]
I agree! A PR would be awesome
