### ISSUE TITLE
main.js file is swallowing every console.log(...) call. Why?

### ISSUE THREAD

**Issue by andrerpena** [chentsulin/electron-react-boilerplate#153]
the `main.js` file should output every call to `console.log()` to the OS console you called `Electron` from.

However, regardless of where I call `console.log()` on the `main.js` file, it's swallowing it.

Any idea?

**Comment by chentsulin** [comment]
I can't reproduce this issue. Could you provide a minimal reproducible example?

We never catch any `console.log` call, so everything should be output normally. Please make sure you checkout your logs in terminal, not in electron renderer console.

**Comment by andrerpena** [comment]
God damn it. I just checked it and found out it's some sort of bug with `WebStorm`. I always work with the built-in `WebStorm` console and have never experienced it swallowing console messages. I guess it does not play nicely with `Electron` then. Anyways... It works on the Windows console.

@chentsulin , I appreciate your time testing this. I'm sorry for not having tested it on Windows before opening this issue.

I hope this will at least be useful to someone in the future that uses `WebStorm` like me.

Thanks.
