### ISSUE TITLE
Build of branch v0.13.3 is broken since 210484f

### ISSUE THREAD

**Issue by doortts** [chentsulin/electron-react-boilerplate#1543]
While I'm waiting for new release, I tested newer branch v0.13.3. And I found that Build of branch v0.13.3 is broken since 210484f 

It's just a F.Y.I. 
Maybe you have already known it but I hope it will be a little help. 

Thanks!

**Comment by doortts** [comment]
I've found the reason. It is because of redux v4.0.0
You can see the breaking changes from here https://github.com/reactjs/redux/issues/1342

Also, if I can find fixes, I'll write it in here.

**Comment by amilajack** [comment]
Is it still broken for you?

**Comment by doortts** [comment]
@amilajack Thank you! I'm testing it and faced some prior problem.
https://github.com/chentsulin/electron-react-boilerplate/issues/1570
