### ISSUE TITLE
adding modules to project

### ISSUE THREAD

**Issue by giorgim** [chentsulin/electron-react-boilerplate#1545]
In section "How to add modules to project", doc says

"If the module **should be included with the published package** (i.e. bcrypt, openbci), it should be listed under dependencies in ./app/package.json."

The question is how/when do we know that a module has to be included with the published package?

**Comment by amilajack** [comment]
Please read these docs https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure

**Comment by giorgim** [comment]
@amilajack I remember having read those docs, but don't remember them talking about the modules "**which should be published with the package**".  (i.e. my question).

Can you put a link where, where those docs talk about exactly what my question was about?

**Comment by amilajack** [comment]
All `dependencies` are packaged with the app. The dependencies in `./package.json` are bundled with webpack and dependencies that cannot be bundled with webpack should be in `./app/package.json`. So all dependencies, in a way, are 'published with the app'. Its just a matter of how the application loads them.

**Comment by giorgim** [comment]
@amilajack Sorry it doesn't. Let me try it once again. Here's the quote: "If the module is native to a platform (like node-postgres) or otherwise should be included with the published package (i.e. bcrypt, openbci), it should be listed under dependencies in ./app/package.json.".


So this quote suggests that since `bcrypt` should be included with the published package, it should to in ./app/package.json.

Now the question is what makes `bcrypt` so special that it has to be included with the published package?
How can I tell that a npm module has to be included with the published package?

Does the question make sense?

**Comment by giorgim** [comment]
@amilajack you say bcrypt is native to platform?
Then lets take the quote again:
"**If the module is native to a platform (like node-postgres)** or otherwise should be included with the published package (i.e. **bcrypt**, openbci), it should be listed under dependencies in ./app/package.json.".

if `bcrypt` was native to platform why in the quote above it was not listed next to `node-postgres`?

Besides the github page, https://github.com/dcodeIO/bcrypt.js, says it is written in JS and not C++ to consider it as native module.

**Comment by amilajack** [comment]
Ahh I see. I think you're confusing the packages. The readme is referring to the npm package `bcrypt`. You are referring to `bcryptjs`. The documentation is referring to [kelektiv/node.bcrypt.js](https://github.com/kelektiv/node.bcrypt.js). You are correct. `bcryptjs` is written in plain js. But `bcrypt` is written in c++
<img width="1021" alt="screen shot 2018-05-11 at 12 03 38 am" src="https://user-images.githubusercontent.com/6374832/39911049-ca49d178-54ae-11e8-8621-6cf7b96084d3.png">

Does that clear things up?

**Comment by giorgim** [comment]
@amilajack If it is native as you say it still doesn't answer my point as below:

"**If the module is native to a platform (like node-postgres)** or otherwise should be included with the published package (i.e. **bcrypt**, openbci), it should be listed under dependencies in ./app/package.json.".

if `bcrypt` was native to platform why in the quote above it was not listed next to ` node-postgres`?

**Comment by amilajack** [comment]
Ah i see what you're saying now. It should be:
> If the module is native to a platform (like node-postgres) or if it is included with the published package (i.e. bcrypt, openbci), it should be listed under `dependencies` in `./app/package.json`.
Correct?

**Comment by giorgim** [comment]
@amilajack We don't seem to well understand each other :).

That quote is from a section which explains which module should go to which package json right?

So there must be easy rules by which I will know which npm module should be put in which package json right?

From above quote I understand node-postgres should go into ./app/package.json, because it is native as quote says.

But what about bcrypt? Why does the quote say it is included with the published package?

**Comment by giorgim** [comment]
@amilajack I think we should reopen it if we didn't come to a conclusion

**Comment by amilajack** [comment]
Ignore what that says. I will update it. It should say "> If the module is native to a platform (like node-postgres), it should be listed under `dependencies` in `./app/package.json`."

**Comment by giorgim** [comment]
@amilajack just a notifier it seems that sentence is still written in the old way.

**Comment by amilajack** [comment]
You are welcome to submit a pr

**Comment by giorgim** [comment]
@amilajack Why should I do that? You said in previous comment you would update that, isn't it?
Okay, I feel I will l file a new issue here with same question, as it seems we didn't get to anything here.

**Comment by amilajack** [comment]
Yea. I didn't do it yet because i have a lot of things on my plate now. But you are always welcome to submit a PR. The project is open source after all

**Comment by amilajack** [comment]
Updated it

**Comment by amilajack** [comment]
Hey @aguynamedben. Thank for taking the time to share that. This is one of many projects that I maintain and it is very difficult to balance my open source work with my career related work and other things. I'm glad that this project and my contributions to it have been of use to you 😄

**Comment by giorgim** [comment]
@amilajack Thanks for the update. Out of interest, can you just post few words why that sentence was there in the first place, if it was not needed?
