### ISSUE TITLE
External link handling

### ISSUE THREAD

**Issue by goldylucks** [chentsulin/electron-react-boilerplate#1549]
Seems like external links in electron should be handled in some way, like [this](https://github.com/electron/electron/blob/e0d0e7651fbeda2b84bad868ed159ffdaea32ab6/docs/api/shell.md#shellopenexternalurl) for example.

Would be nice to be able to write external links "normally" `<a href="http://google.com" />` and have an interceptor some where handling it.

Possible solution:
- https://stackoverflow.com/a/34503175/1226072
- https://github.com/electron/electron/issues/1344#issuecomment-171516261
- https://github.com/electron/electron/issues/1344#issuecomment-171516261
- https://github.com/electron/electron/issues/1344#issuecomment-208839713
- https://github.com/electron/electron/issues/1344#issuecomment-208839713

I can prepare a PR with some guidance / pointers

**Comment by amilajack** [comment]
I think docs for this kind of thing would be more helpful. Adding this to the boilerplate itself would make it too high level IMO. Thoughts on this?

**Comment by goldylucks** [comment]
How about ... we put that logic in a util file, and we import that file from the client index, so users could easily comment that out + adding a reference for that in the docs?

**Comment by amilajack** [comment]
The concerns that erb is too high level comes from multiple users of it. We've gotten complaints that there's too much boilerplate and that it should be kept minimal. But the solution you mentioned above is a sound one.

**Comment by dbvrac** [comment]
Would it be worthwhile to create a "training wheels" branch? I sure could have used it. I love this project, and my skills have improved enormously because of it, but it's mostly been trial-and-error. Mostly error.

**Comment by goldylucks** [comment]
@amilajack I haven't implemented before a solution for external link handling, tho I can give it a go if you wish :)

**Comment by amilajack** [comment]
I think this should belong in a guide
