### ISSUE TITLE
add example to handling binaries and __dirname in external modules

### ISSUE THREAD

**Issue by goldylucks** [chentsulin/electron-react-boilerplate#1550]
given the many issues [like this](https://github.com/electron/electron/issues/8206), this seems like a common problem.

in our project we have a node module that uses `__dirname`, and it points to `app.asar.packed` instead of `app.asar.unpacked`.

The workaround we use is pass the `__dirname` from the electron app to the node module, using `process.resourcesPath`, after adding that node module to `package.json.build.extraResources`

It took me a few hours to debug this, and many people posted working on it for over a day.

I think this will make this boilerplate a more comprehensive solution.

I can prepare a PR with some guidance. It might not be worth it to add it to the code itself, but in the documentation somewhere at least.

Thoughts?

**Comment by amilajack** [comment]
This would be awesome. Maybe you can add this to your WIP error reporting example

**Comment by goldylucks** [comment]
I think this is unrelated to error reporting, so can make a separate PR.

Here's what worked in our project:

- add the node module as [`extraResources`](https://github.com/zenprotocol/zenwallet/blob/2f02c55e374b7dcd58cb73f2ba9cd12523df1c47/package.json#L45)
- pass the [path](https://github.com/zenprotocol/zenwallet/blob/2f02c55e374b7dcd58cb73f2ba9cd12523df1c47/app/ZenNode.js#L191) to the node module

Do you think it's better to add documentation for this, or an actual example?

btw, I'm going on a week vacation, will respond after that
