### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by LustySwimmer** [chentsulin/electron-react-boilerplate#1551]
After run npm install, I can't run demo successful with 'npm run dev',here is the console:

> electron-react-boilerplate@0.13.2 dev /Users/lusty/Desktop/Test/Electron/electron-react-boilerplate
> cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev

> electron-react-boilerplate@0.13.2 start-renderer-dev /Users/lusty/Desktop/Test/Electron/electron-react-boilerplate
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js

Starting Main Process...
Project is running at http://localhost:1212/
webpack output is served from http://localhost:1212/dist
Content not from webpack is served from /Users/lusty/Desktop/Test/Electron/electron-react-boilerplate/dist
404s will fallback to /index.html

> electron-react-boilerplate@0.13.2 start-main-dev /Users/lusty/Desktop/Test/Electron/electron-react-boilerplate
> cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev

Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 4 more times

**Comment by sanusart** [comment]
Looks like related to: https://github.com/MarshallOfSound/electron-devtools-installer/issues/73

if import
`import installExtension, { REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } from 'electron-devtools-installer';`

and change _installExtensions_ function to:
```
const installExtensions = async () => {
  installExtension(REACT_DEVELOPER_TOOLS.id);
  installExtension(REDUX_DEVTOOLS.id);
};
```

in `app/main.dev.js` to:

It seems to work and install both extensions
