### ISSUE TITLE
add modules to project

### ISSUE THREAD

**Issue by giorgim** [chentsulin/electron-react-boilerplate#1552]
On how to add modules the doc says: "If the module is native to a platform (like node-postgres) or otherwise **should be included with the published package (i.e. bcrypt, openbci)**, it should be listed under dependencies in ./app/package.json.".

I had question about the part which is in bold (can see here: https://github.com/chentsulin/electron-react-boilerplate/issues/1545), namely I didn't know **how does one know that a module should be included with the published package like bcrypt**.

In the correspondence I linked, the question was closed but as one can see from the thread it is still entirely unclear why and what the sentence "should be included with the published package (i.e. bcrypt, openbci)" entails.

The person who communicated in the thread just said he would change it, but it occurs he/she is busy.
I don't plan to submit a PR, because I don't know why that sentence should be removed (I can't explain it if someone asks).

Hence I am posting this for someone either to explain what that sentence means, or to modify it in docs, so that the docs are up to date and correct.

**Comment by amilajack** [comment]
Merging this into https://github.com/chentsulin/electron-react-boilerplate/issues/1545. Please don't create duplicates. Thanks
