### ISSUE TITLE
Can not require('ipc') in tests

### ISSUE THREAD

**Issue by borNfreee** [chentsulin/electron-react-boilerplate#156]
Hi,

I'm using the following code in one of my files:
```js
const ipcRenderer = require('ipc');
//...
ipcRenderer.send(...)
```

It works well, but when I run `npm run test` it fails with error:

```js
Error: Cannot find module 'ipc'
```

Could you please help?

**Comment by chentsulin** [comment]
Electron built-in modules are not available in a Node process (which is what we currently use in unit test from the cli). If your want to test files which require built-in Electron modules you have to run them in e2e test or prepare mock objects for them.

**Comment by borNfreee** [comment]
Is it correct to mock it in a such way:

```js
// test/setup.js
//...
// Mocks for Electron
global.window.require = function () {
  return {
    ipcRenderer: {
      send: function () {
        // Fake sending message to ipcMain
      }
    }
  }
};
```

and then use the following code in `app/actions/notifications.js`:
```js
var ipcRenderer = window.require('electron').ipcRenderer;

// other code
```

--------------

It works (and the same approach is used in e.g. (Gitify)[https://github.com/ekonstantinidis/gitify/blob/master/src/js/__tests__/stores/notifications.js], but I want to find the best solution.

**Comment by chentsulin** [comment]
Another solution is that you can use [electron-mocha](https://github.com/jprichardson/electron-mocha) as an alternative of mocha.

**Comment by borNfreee** [comment]
Thank you
