### ISSUE TITLE
Utilizing source maps in remote error reporting (i.e. Sentry, Airbrake)

### ISSUE THREAD

**Issue by aguynamedben** [chentsulin/electron-react-boilerplate#1560]
Has anybody seen any good examples of source maps being used with a remote error reporting platform such as Sentry? (This project produces source maps in app/dist/*.map).

Sentry has libraries for SDKs for Node.js, JavaScript, and a new beta version of an Electron SDK, but it doesn't yet have the ability use source maps from the renderer when errors are reported. My project is using the Sentry Node.js client for the main process and the Sentry JavaScript client for the renderer process. It's all working, but getting the source maps working with Sentry so I can see where production errors actually happened is proving difficult.

Maybe a cool idea would be to add remote JavaScript error reporting to this project. And maybe also somehow integrating electron-log with a remote logging service like Logentries. Deploying a production Electron app is difficult because it's easy to have an oversight that creates a JavaScript error in the renderer. When those errors are reported via something like Sentry it's difficult to configure them to be reported with source maps.

If anybody has done this successfully, please chime in!

**Comment by aguynamedben** [comment]
## Uploading source maps
This is how I ended up doing it and it works great: https://docs.sentry.io/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry

There is a webpack plugin that should work with this project, but we do this...

**upload_sourcemaps.sh**

```sh
#!/bin/bash

echo "Uploading source maps to Sentry"

source env.internal
echo "SENTRY_ORG: $SENTRY_ORG"
export SENTRY_ORG=$SENTRY_ORG
echo "SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN"
export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN

source env.production
echo "SENTRY_PROJECT: $SENTRY_PROJECT"
export SENTRY_PROJECT=$SENTRY_PROJECT

# https://gist.github.com/DarrenN/8c6a5b969481725a4413#gistcomment-1678696
PACKAGE_VERSION=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')
echo "Package version: $PACKAGE_VERSION"

echo "Uploading..."
./node_modules/.bin/sentry-cli releases files $SENTRY_PROJECT-$PACKAGE_VERSION upload-sourcemaps app/dist --url-prefix '~/dist/'
echo "Done uploading sourcemaps"
```

This results in releases in Sentry being something like `myapp-production-1.2.0`.

## Upload Symbols
Also you should upload your symbols to make native crashes more intelligible (godspeed): https://docs.sentry.io/platforms/javascript/electron/#uploading-debug-information

You need to re-upload symbols each time you upgrade the Electron version. We use [this script](https://github.com/getsentry/sentry-wizard/blob/master/scripts/Electron/symbols.js) which is provided by the sentry-cli module if you install that.

## Clean up electron-log/redux-logger messages in Sentry breadcrumbs

You can also clean up electron-log/redux-loggers entries to Sentry breadcrumbs using something like this. If you don't do this, you'll notice nasty color-switching messages from electron-log, and overly verbose logging from redux-logger.

```js
Sentry.init({
  // ...
  beforeBreadcrumb: (breadcrumb) => {
    // Examples:
    // category: electron, type: ui
    // category: console, type: undefined (remove access_token from data)
    // category: xhr, type: http (remove access_token from URL)
    // log.debug(`Breadcrumb - ${breadcrumb.category} - ${breadcrumb.type}`);

    // console breadcrumbs from redux-logger may contain Redux state and
    // therefore access tokens or refresh tokens. Redact tokens from Sentry
    // breadcrumbs.
    if (breadcrumb.category === 'console') {
      breadcrumb.data = scrubObject(breadcrumb.data);
      // log.debug(`New console breadcrumb data`, breadcrumb.data);

      // Keep breadcrumbs from redux-logger console logs, but clean it's
      // messages up before sending to Sentry.
      if (breadcrumb.data && breadcrumb.data.extra && breadcrumb.data.extra.arguments && breadcrumb.data.extra.arguments[1] && breadcrumb.data.extra.arguments[1].type) {
        const reduxAction = breadcrumb.data.extra.arguments[1].type;
        breadcrumb.message = reduxAction;
        breadcrumb.data = {};
      } else if (breadcrumb.message.includes('state color')) {
        // This is a trash message for solely for changing the color of the
        // console, drop it.
        return null;
      }
    }

    // xhr breadcrumbs may contain URLs which may contain access tokens or
    // refresh tokens. Redact tokens from URLs.
    if (breadcrumb.category === 'xhr') {
      breadcrumb.data.url = scrubUrlParams(breadcrumb.data.url);
      // log.debug(`New url breadcrumb data`, breadcrumb.data);
    }

    return breadcrumb;
  },
});
```

Overall, Sentry has great emerging support for Electron apps:
- https://docs.sentry.io/platforms/javascript/electron/
- https://github.com/getsentry/sentry-electron

**Comment by Tej-Sharma** [comment]
Thanks @aguynamedben, that script saved so much time. But one problem was that using the local sentry/cli still caused webpack errors, so I installed it globally via `-g` and modified the uploading part to be:
sentry-cli releases files $SENTRY_PROJECT-$PACKAGE_VERSION upload-sourcemaps release/app/dist --url-prefix '~/dist/'
