### ISSUE TITLE
Anyone to help me in automated release binaries with Trevis-CI

### ISSUE THREAD

**Issue by jonatasfreitasv** [chentsulin/electron-react-boilerplate#1561]
Hey guys!!

Anyone to help me in automated release binaries with Trevis-CI on my open-source project?

https://github.com/HouseOps/HouseOps

**Comment by amilajack** [comment]
For now you'll have to reference the electron-builder docs for that. I have never done that myself so i can't help you out with that. sorry. I'll leave this open in case someone else can help

**Comment by uppe-r** [comment]
Hey @jonatasfreitasv check my small, outdated and abandoned project (ahaha) with this boilerplate [https://github.com/uppe-r/rokett](url), you can check mainly the `travis.yml` and `package.json` files.

It really just consists in running the package scripts you need (`package-linux`, for example) and changing the package script in `package.json` to (or add) "--publish onTagOrDraft" as an argument for the command. If you have any further questions about this, please let me know.

By the way, @amilajack , do you think that it would be useful adding the `--publish onTagOrDraft` argument or similar to some/all of the the package scripts?

**Comment by amilajack** [comment]
@uppe-r I think that would be useful but I think we should ask the user before doing that. It might be so that some users may not want that functionality

**Comment by uppe-r** [comment]
@amilajack Agreed, got any idea for such?
I don't think there is a good way of doing so, unless the whole boilerplate is turned into an npm module.

**Comment by amilajack** [comment]
Maybe we could have a prompt in the CLI? A postinstall script?

**Comment by uppe-r** [comment]
Seems to be really the only option, doesn't it? I guess everyone will add a module before even thinking about building their app, right? 😃 
Want me to take a look at it and see what I can do?

**Comment by amilajack** [comment]
Sure!

**Comment by goldylucks** [comment]
@uppe-r @amilajack you can check our travis and appveyor configs in our project:
https://github.com/zenprotocol/zenwallet
