### ISSUE TITLE
Glyphicons not working in production

### ISSUE THREAD

**Issue by ivanthemeh** [chentsulin/electron-react-boilerplate#1563]
The fonts in my electron react boilerplate app arent working when running npm run start. I am getting a 
```ERR_FILE_NOT_FOUND``` in the console on the .ttf, .woff, .woff2 files.. I am new to webpack and havent been able to figure it out.. maybe someone with some time could help me figure this out. Thanks.

**Comment by dbvrac** [comment]
I'm also still new, but will attempt to improve my skills by addressing your question.
How are you incorporating your fonts into your project?
I added Roboto to my project by appending the following lines to app.global.css:
`@import "~font-awesome/css/font-awesome.css";
@import url(http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300ita‌​lic,400italic,500,500italic,700,700italic,900italic,900);

html, html * {
  font-family: Roboto;
}`

**Comment by ivanthemeh** [comment]
I was just importing the bootstrap into my app.global.scss and it works in development, just a square in production though.. so I tried to import the fonts directly into the app.global.scss which results in an error on the import and the app wont start.

**Comment by ivanthemeh** [comment]
I was able to fix it by changing 
```
output: {
    path: path.join(__dirname, 'app/dist'),
    publicPath: './dist/',
    filename: 'renderer.prod.js'
  },
```
to 
```
output: {
    path: path.join(__dirname, 'app/dist'),
    publicPath: './',
    filename: 'renderer.prod.js'
  },
```
I noticed it was looking for the files in ```app/dist/dist...```

**Comment by ivanthemeh** [comment]
Its not right though because now there are a bunch of font files in my app folder...

**Comment by amilajack** [comment]
This is an issue that still needs to be addressed. It has to do with how web pack rewrites the paths to assets that link to other assets.

**Comment by W1M0R** [comment]
I had the same problem in production when using a global scss file. See my comment here for the resolution: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1426#issuecomment-458824975
