### ISSUE TITLE
START_HOT command line variable does not affect HMR

### ISSUE THREAD

**Issue by brmscheiner** [chentsulin/electron-react-boilerplate#1564]
I want to disable HMR, so I tried changing the `START_HOT` parameter in package.json

`    "dev": "cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev",
`

But changing the value to 0 or 2 does not seem to affect HMR, so I am guessing this is either broken or just a little confusing.

**Comment by goldylucks** [comment]
did you try remove that variable completely?

`"dev": "node -r babel-register ./internals/scripts/CheckPortInUse.js && npm run start-renderer-dev"`
