### ISSUE TITLE
Atom TypeScript linter shows error even tho it's disabled?

### ISSUE THREAD

**Issue by kunokdev** [chentsulin/electron-react-boilerplate#1567]
Just curious if someone else had similar issue in Atom. I even disabled all TypeScript related packages. I still get this linter error:

![image](https://user-images.githubusercontent.com/13220754/40460329-6878c258-5f06-11e8-8e19-f9fb57f58071.png)

**Comment by kunokdev** [comment]
Ok guys I disabled all packages and restarted Atom and it's gone now. I wonder where it's coming from so I don't really need to disable packages when working on this project.

**Comment by amilajack** [comment]
You're not supposed to be running typescript on flow projects. they are different technologies with different syntaxes and semantics
