### ISSUE TITLE
Error in packing for Windows.

### ISSUE THREAD

**Issue by jonatasfreitasv** [chentsulin/electron-react-boilerplate#1575]
Hi guys.

In this project/issue (https://github.com/HouseOps/HouseOps/issues/6).

The packing for windows not run =/.

When start application, have exception.

I'm trying to packing in Windows and Linux SO, booth with bug.

In windows SO, `npm run dev` work nice! 

Help!!!!

**Comment by amilajack** [comment]
What is the error that you are getting?
