### ISSUE TITLE
No flow@v0.72.0-compatible libdefs found in flow-typed for the above untyped dependencies

### ISSUE THREAD

**Issue by proclaim** [chentsulin/electron-react-boilerplate#1576]
I'm running on npm 6.1.0 + node 10.3.0 on mac HS 10.13.4, followed the instruction with git clone, install dep with yarn, and had the following error

<img width="517" alt="error1" src="https://user-images.githubusercontent.com/2252778/40785336-d536f206-651a-11e8-8df3-c0f97122f247.png">
<img width="541" alt="error 2" src="https://user-images.githubusercontent.com/2252778/40785335-d4e409a6-651a-11e8-8849-ab729b3932b7.png">
<img width="1169" alt="error 3" src="https://user-images.githubusercontent.com/2252778/40785334-d4b572bc-651a-11e8-9e19-62c40b4829d8.png">

I hope I am not missing anything, anyone encountered this problem?

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate/issues/1555#issuecomment-391834048

**Comment by whatsdis** [comment]
similar error 

!! No flow@v0.77.0-compatible libdefs found in flow-typed for the above untyped
dependencies !!

**Comment by bepehr** [comment]
I got this error too

**Comment by vikr01** [comment]
@whatdis @bepehr The answer is already posted above right there.

Locking this thread since nobody has anything useful to add.
