### ISSUE TITLE
Migrate to mini-css-extract-plugin

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1578]
See https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/763

**Comment by BuckyMaler** [comment]
@amilajack I've spent the past couple weeks at work updating our webpack configs to v4. Would it be alright if I take this one? If so, let me know what branch I should submit the PR to.

**Comment by BuckyMaler** [comment]
@amilajack this can be closed. I forgot the link in #1580.
