### ISSUE TITLE
How to set environment variable with npm run package

### ISSUE THREAD

**Issue by sfyfe31** [chentsulin/electron-react-boilerplate#1586]
I'm trying to set an environment variable during packaging, to then load different CSS:
```
cross-env OTHER_STYLE=true npm run package -- --mac dir
```

Then in `app.html`:
```
<script>
if (process.env.OTHER_STYLE) {
  const new_link = document.createElement('link')
  new_link.rel = 'stylesheet'
  new_link.href = 'app.other_style.css'
  document.getElementsByTagName('head')[0].appendChild(new_link)
}
</script>
```

But `process.env.OTHER_STYLE` is undefined.

What am I doing wrong?

**Comment by amilajack** [comment]
Add that env variable here:
https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.base.js#L68

**Comment by sfyfe31** [comment]
I need it to be optional though
