### ISSUE TITLE
Changing pages give white screen HMR

### ISSUE THREAD

**Issue by ivanthemeh** [chentsulin/electron-react-boilerplate#1591]
I am getting a white screen when I navigate to another page and HMR runs, I am getting this error ```GET file:///calendar net::ERR_FILE_NOT_FOUND``` it even happens when I go to the calendar page and then back to root... if I stay on root page HMR doesnt give white screen. Please and thanks for any help.

**Comment by amilajack** [comment]
Can you create  a fork that demonstrates this issue? That would make it easier for me to investigate and reproduce this issue
