### ISSUE TITLE
npm run dev:show blue window, but not show Home to Counter

### ISSUE THREAD

**Issue by c2rlost2r** [chentsulin/electron-react-boilerplate#1594]
version of the boilerplate: "0.13.3"
Windows 7
npm run start, work ok
When I package to windows (npm run package-win), work ok
But npm run dev show blue window, but not show Home to Counter
View->Reload, still not show
Thanks in advance
![005-000048](https://user-images.githubusercontent.com/7349486/41629530-50be85a8-7400-11e8-81fd-d303140986eb.jpg)

**Comment by amilajack** [comment]
What are the errors in the console?

**Comment by BuckyMaler** [comment]
@c2rlost2r perhaps you need to run `set UPGRADE_EXTENSIONS=1 && npm run dev`. That will upgrade your devtools extensions.

see: https://github.com/chentsulin/electron-react-boilerplate/issues/1570

**Comment by amilajack** [comment]
Ahhh yes I am pretty sure that is the solution. Thanks @BuckyMaler

**Comment by c2rlost2r** [comment]
Yes, it works, Thank you.
Great Boilerplate!!!!!!!!!!!!!!!
