### ISSUE TITLE
Play audio files in production

### ISSUE THREAD

**Issue by jsrhome** [chentsulin/electron-react-boilerplate#1595]
I've been trying to follow the advice in #250 to configure playing audio files.  That issue was mostly about image files.  I added the following to webpack.config.base, inside module: rules: [

```
{
            test: /\.wav$|\.mp3$/,
            exclude: /node_modules/,
            loader: 'file-loader'
        }
```
I placed the audio files into an app/audio folder.  I was able to import audio using either:
    import mySound from  'audio/mySound.wav'
    import mySound from  '../audio/mySound.wav'
Both work in a developer build.  Neither works in the production build, raising a file not found error.  I even see the corresponding .wav file in the /dist folder, but don't know how to reference the correct path in the code.  It looks like the HTTP get is trying to find the file in a /dist directory within the current router path.

In a developer build, I can also use:  new Audio(path.resolve('./app/audio/mySound.wav'))
This also doesn't work in a production build.

I've tried lots of different combinations of path names, but none seem to work.  This seems like a common use case.  But I can't find any documentation, or StackOverflow guidance, on how to correctly import (or read) an audio file that will consistently work in both developer and production builds.

Is import the preferred way?  If not, where should I place the audio files and how do I get them into the build process?  Do I need to specify different paths for developer vs. production?

Thanks very much for your help, and your extremely useful boilerplate.

**Comment by amilajack** [comment]
Made [this example](https://github.com/amilajack/erb-audio-example) for you. Hope it helps. It took some time to put together this example. [A donation](https://www.paypal.me/amilajack) would be nice :)

**Comment by jsrhome** [comment]
@amilajack First of all, thanks for the amazingly fast response and thorough example.  Your example runs as expected in both dev and production.

However, I applied the exact same techniques to my app, and find myself in the same place as before.  One critical difference is seen when logging the .src property of your Audio(bar) vs. the same .src property in my code.  In your example code, the src attribute shows a fully qualified path name into the .asar file, copied here (with the intermediate paths truncated):
file:///Users/.../ElectronReact.app/Contents/Resources/app.asar/dist/3a8c77cea4f651fe3f791065a72959a5.mp3

In my code, the same .src attribute is just:  file:///dist/3a8c77cea4f651fe3f791065a72959a5.mp3

As I mentioned in my original report, I tried this in a few places in my code, and the HTTP get seems to be resolving relative to the routing path of the application, rather than pointing into the .asar/dist contents.

I'm using React Router, and do a Redirect to the path (like /login or /foo/bar) for my component, rather than a Route (as in your example).  After the redirect, the location object changes from a fully qualified path name to just '/login' or '/foo/bar'.  Do you think that the redirect could be confusing the resolution of the path name to the audio resource?

In my code, if I give the same Audio() constructor a fully qualified path name that points to the same resource (e.g.  ///User/.../app.asar/dist/3a8c77cea4f651fe3f791065a72959a5.mp3) then it works just fine.  So I'm left with wondering if the redirect is somehow the problem.  

If so, is there a suggested way to get the file name of the mp3 file created by Webpack, so that I can concatenate the file name in the code instead of directly using the import?  I can do this by creating a dummy Audio(bar), and extracting the .src property, and constructing the fully qualified path for a new Audio() object, but maybe there is a better way.

Thanks again.

**Comment by amilajack** [comment]
Hmm. This is difficult to debug without any code. I think it could be that your webpack config or a react router issue. These kinds of issues are caused when webpack doesn't rewrite path's correctly because of configuration issues. I think the redirect could also be causing the issue as well. I'd need to take a look at the app to give any meaningful insight

**Comment by jsrhome** [comment]
I found that I could import the audio file, construct a path name relative to the app.asar/dist folder, and then use that path name for the Audio() constructor.   I needed to add a webpack file-loader for audio files (in my case, it is a .wav file).  Then I use the code similar to:

`import audioSrc from '..\audio\myAudio.wav'
...
const resourcesPath = process.resourcesPath;
let audioFileName, audioPath;
audioFileName = path.basename(audioSrc);
            if(isElectron()) {
                audioPath = path.resolve(resourcesPath, './app.asar/dist/' + audioFileName);
                sound = new Audio(audioPath);
}
`
There has to be a better way, but this way worked for me.

**Comment by cloudrex** [comment]
What if you don't exactly know which audio file you're going to load before-hand?

**Comment by amilajack** [comment]
In this case you would do `new Audio(audioPath)` where `audioPath` is the path to the file which is only known at runtime

**Comment by cloudrex** [comment]
The problem is that, if you were to pass an expression, webpack would complain. It works fine for hard-coded paths, but not for methods that return such path...

**Comment by Jimmy-JS** [comment]
hi thanks for the solution @jsrhome I also facing the same issue as you. and I'm trying to follow your code. but how can you call `process.resourcesPath` from the renderer? because when I do that, it throws me an error `ReferenceError: process is not defined`

Or any idea how to make webpack return the full url?

Thanks!

**Comment by Jimmy-JS** [comment]
nvm turns out I need to get it from the main process
