### ISSUE TITLE
Any idea why installer has HW32.Packed false positive?

### ISSUE THREAD

**Issue by genesy** [chentsulin/electron-react-boilerplate#1597]
I just cloned and packaged the app the windows installer has this HW32.Packed virus included which i know is false positive but alarms a lot of people

**Comment by amilajack** [comment]
Not sure actually. Would recommend checking out [these issues](https://github.com/electron/electron/search?q=virus&type=Issues). This is out of the scope of the boilerplate

**Comment by thisismydesign** [comment]
I have the same issue. The report is coming from bkav. A normal electron app doesn't produce the same results, so this is related to the boilerplate.

I don't think it's advisable to use a template that produces this alert. I agree that this is a false positive but also that it's alarming and shouldn't be ignored.

@amilajack What's the consideration for closing this issue? Why is this our of scope?

**Comment by amilajack** [comment]
Please look at the issues I liked to. It is well known that electron shows up as false positives in virus scans.

**Comment by thisismydesign** [comment]
@amilajack This is a specific match by a specific AV vendor and there're not hits for this in the electron repo: https://github.com/electron/electron/search?q=HW32&type=Issues

From everything I looked at this seems to be an issue with something in the boilerplate.

**Comment by amilajack** [comment]
It’s not an issue with this boilerplate. See https://github.com/sindresorhus/caprine/issues/555

**Comment by JohnTHaller** [comment]
It's an issue with bkav itself that affects all kinds of installers. It's a dumb warning from a poor antivirus product.
