### ISSUE TITLE
Electron-rebuild vs npm rebuild?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1601]
I'm running into some issues trying to install gRPC@1.11.3. `grpc-node` team recommends against `electron-rebuild`: https://github.com/grpc/grpc-node/issues/250

Here's the specific issue I'm facing: https://github.com/grpc/grpc-node/issues/412#issuecomment-399519651

I'm wondering what the right way to resolve these is. Do I want to `electron-rebuild` everything except `gRPC` and use `npm rebuild --target=electron --target_runtime=2.0.2 --dist-url=https://atom.io/download/electron` for only gRPC, or do I want to abandon `electron-rebuild` altogether?

Is there some additional benefit `electron-rebuild` brings to the table?

@amilajack, since I know you're the one who's going to respond to this, let me end this by thanking you in advance.

**Comment by nicolasnoble** [comment]
Several things to note here:

 - The main advantage of `electron-rebuild` is to avoid having to specify the runtime version number, so you only have one location to update the electron runtime version instead of two.
 - The main downside of native extensions is that there are few of them that understand how to ship things for electron - but grpc does. So using `electron-rebuild` with grpc brings more pain than it's worth, mainly because we took great care of ensuring our code works with electron, and that we ship electron pre-built binaries.

If grpc is the only extension you have that's native, please do not use `electron-rebuild` at all.

We will alter our documentation to be more specific about all this.

**Comment by Slapbox** [comment]
Possible unintended consequences down the line when packaging or something of the sort, but for now, it looks like @nicolasnoble's suggestion to remove `--build-from-source` from the `postinstall` command in `./app/package.json` is the silver bullet I've been looking for.

I will leave this ticket open because we should discuss the best approach to managing a variety of native modules with either command, if we do in-fact need `electron-rebuild`. I'm not sure that we do.

@amilajack, when you're around let me know your thoughts on this. My use case is obviously not all people's, but I suspect this configuration may cause some very tough to debug issues for users of the boilerplate.

**Comment by amilajack** [comment]
@nicolasnoble's answer is perfect. Try this:
```js
// @flow
import path from 'path';
import { execSync } from 'child_process';
import fs from 'fs';
import dependencies from '../../app/package.json';

const nodeModulesPath = path.join(__dirname, '..', '..', 'app', 'node_modules');
const modules = dependencies.filter(e => e === 'grpc-node').join(',');

if (
  Object.keys(dependencies || {}).length > 0 &&
  fs.existsSync(nodeModulesPath)
) {
  const electronRebuildCmd =
    `../node_modules/.bin/electron-rebuild --parallel --which-module ${modules} --force --types prod,dev,optional --module-dir .`;

  const cmd =
    process.platform === 'win32'
      ? electronRebuildCmd.replace(/\//g, '\\')
      : electronRebuildCmd;

  execSync(cmd, {
    cwd: path.join(__dirname, '..', '..', 'app')
  });
}
```

**Comment by Slapbox** [comment]
Hey @amilajack thanks for your reply. It actually works fine as long as I remove `--build-from-source` from the inner `package.json`, with no changes to `ElectronRebuild.js`. 

I have yet to try installing all my `node_modules` freshly with this method though. It's quite possible one of them did need to be built from source. I will update here if I find that to be the case.

Is there a way we can set it up to only try to build from source in cases of failure? If I'm not mistaken, I think `npm rebuild` does that anyway if it fails to get precompiled binaries. I could be wrong though.

**Comment by murgatroid99** [comment]
One issue with just letting it fall back to building from source, at least historically, is that Electron version numbers can match io.js version numbers, and if the binary download is not parameterized on the runtime, it can end up incorrectly downloading io.js binaries instead and thinking that the installation is successful. I think this is the reason that the Electron documentation says to always build from source.

**Comment by Slapbox** [comment]
Great info! I'll have to do some more.
