### ISSUE TITLE
Jest expects native dependencies built for Node, but I build for Electron? Ideas?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#1604]
I'm having an issue which I've outlined here: https://stackoverflow.com/questions/51029433/jest-expects-a-native-dependency-built-for-node-but-mine-are-built-for-electron

I'm wondering if anyone here knows how to work around this. I'm not using `Jest` as it's setup in the boilerplate as I'm using Babel7, Webpack4 and a fair amount of other customizations.

**Comment by Slapbox** [comment]
Alternatively to an actual solution, if anyone can explain exactly how the `RunTests` file works, that might help as well: https://github.com/chentsulin/electron-react-boilerplate/blob/master/internals/scripts/RunTests.js

**Comment by Slapbox** [comment]
Apparently running `npm rebuild` in the `app` folder after running the build in scripts can resolve this.

**Comment by amilajack** [comment]
That makes sense. You'll have to rebuild for node too. Maybe we can add rebuilding for node in the `ElectornRebuild.js` script. That way we rebuild for both electron and node.

**Comment by Slapbox** [comment]
I was thinking about trying just pin on `&& npm rebuild` on the end of the post install, but I'm trying to navigate between using plain `npm rebuild` and `npm rebuild --build-from-source`

It seems I need some combination of these, but I haven't taken the time to work out exactly what yet.
