### ISSUE TITLE
renderer.dev.js takes 45ish seconds to load for me

### ISSUE THREAD

**Issue by genesy** [chentsulin/electron-react-boilerplate#1607]
This is probably something with my machine, but yesterday this was fine now it takes 45 seconds ish, based on console.time to load. I console.time on app ready, then on window ready to load. it takes 45 seconds before it loads up. I clone this repo and did the same test and it's also 45 ish seconds, anyone have any idea why this suddenly happened? I remember it was opening main window pretty fast before.

**Comment by Slapbox** [comment]
Do you have a DLL folder in the root of your project and does it have files in it? What's the size of those files?

Rendering can take an eternity if you're not building DLLs properly.

**Comment by genesy** [comment]
yes, these are the files in it.
render.dev.dll.js is 5.4mb
renderer.json 162kb

**Comment by Slapbox** [comment]
Not really sure what to say except possible system-wide changes like hard-drive fragmentation, CPU downclocking, etc.

Maybe someone else will have a better idea.

**Comment by genesy** [comment]
now that i think about it, the drive where the project is stored on got full a few hours ago, could that have caused it?

**Comment by amilajack** [comment]
Most likely. That probably means that you dont have a large swapfile. Clear up some disk space and let us know if the issue persists

**Comment by genesy** [comment]
i cloned the project on a seperate ssd, it still takes a while for the renderer.dev.js to finish loading

**Comment by amilajack** [comment]
Interesting. What are your node and yarn versions?

**Comment by genesy** [comment]
Ok weird. I disconnected my internet and tried npm run dev, takes 2 seconds to open the window now. Reconnected thinking it would take long for it to load again but no, it fixed itself. Disconnecting fixed it for some reason. Any theory why?

**Comment by genesy** [comment]
closing it now. super weird, i don't see how disabling my network adapter could've fixed it.

**Comment by mattuiarena** [comment]
Hello, I'm also facing the same Issue. The renderer.dev.js is taking too long to load. But, Once I disconnect my network, it is loading fast. Can someone help me with this issue please.

**Comment by Slapbox** [comment]
@mattuiarena do you have any additional packages installed? What OS? There's no explanation I can think of for why this would be the case, but that doesn't mean it's not the case.
