### ISSUE TITLE
Question: How would I pass command line arguments for dev

### ISSUE THREAD

**Issue by fakob** [chentsulin/electron-react-boilerplate#1608]
Hi

I was wondering how I would pass command line arguments for the `npm run dev` script, so I can use the arguments in the renderer?

With a standard electron setup I read, I could do this
```
./node_modules/.bin/electron main.js argv1 argv2
```
and then require it in the renderer.
```
require('electron').remote.process.argv
```
But with the dev script I am not sure how to do that. Any ideas?
```
"dev": "cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev",
```

**Comment by uppe-r** [comment]
Hey fakob, try adding your argument to the `start-renderer-dev` script, such as:
`cross-env NODE_ENV=development` **YOUR_ARGUMENT_HERE=1** `node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js`

and then in your code access it using `require('electron').remote.process.env.YOUR_ARGUMENT_HERE`

**Comment by fakob** [comment]
Thanks @uppe-r, that was a great tip! 
Easy to implement and works like a charm :-)
