### ISSUE TITLE
There is a bug in ElectronRebuild

### ISSUE THREAD

**Issue by ishandutta2007** [chentsulin/electron-react-boilerplate#1614]
here https://github.com/chentsulin/electron-react-boilerplate/blob/cdff3d414e22e16bca0211faf24d26bc5a055a3c/internals/scripts/ElectronRebuild.js#L5
`dependencies` must be changed to `{ dependencies }` or else it has json of full file.

**Comment by amilajack** [comment]
Good catch. I'll fix this
