### ISSUE TITLE
constants instead hard coded routes

### ISSUE THREAD

**Issue by goldylucks** [chentsulin/electron-react-boilerplate#1618]
how about adding `app/constants/routes.js` with:

```
export const COUNTER = '/counter'
export const HOME = '/home'
```

then on `app/routes.js` (and anywhere else we use routes):
```
import * as routes from '../constants/routes`
...
      <Route path={routes.COUNTER} component={CounterPage} />
      <Route path={routes.HOME} component={HomePage} />
```

Also, maybe rename current `app/routes.js` to `app/Routes.js`, since it exports a `React.Component`?

I can prepare a PR

**Comment by amilajack** [comment]
I think renaming `./app/routes.js` would be welcome. I think adding constants for the routes will abstract things a little too much for newcommers to the boilerplate. Thoughts on this?

**Comment by goldylucks** [comment]
@amilajack It's pretty much common best practice by now, and for newbies it will have the extra benefit of teaching them that.

**Comment by amilajack** [comment]
Good reasoning. A PR for this would be 🎉
