### ISSUE TITLE
Why are there 2 .eslintrc files? (.eslintrc and app/.eslintrc)

### ISSUE THREAD

**Issue by aguynamedben** [chentsulin/electron-react-boilerplate#1620]
Hi, thanks for this great boilerplate. There was some confusion on my team as to why there are 2 different .eslintrc files in this project, and how some people's IDEs load .eslintrc by looking up directories from the current file.

I didn't see anything mentioned about the .eslintrc setup in the README, so was just wondering if you could shed some light on why the boilerplate uses 2 ESLint configs. Thanks!

**Comment by amilajack** [comment]
I think its because flow was having errors with some of the non app related files. But I actually think `./app/.eslintrc` should be removed. `./test/.eslintrc` is necessary because that's where we add test specific eslint rules.

**Comment by aguynamedben** [comment]
Cool, thanks for the info. 👍
