### ISSUE TITLE
The way Antd is introduced

### ISSUE THREAD

**Issue by helpceo** [chentsulin/electron-react-boilerplate#1621]
As an official on-demand introduction, the style does not apply. You can enter the style globally.
em:
In the app.global.css file
```
  @ import "antd/dist/antd.css";
```

If so, other ways are welcome

**Comment by amilajack** [comment]
You can take a look at this. https://github.com/amilajack/erb-ant-design-example. Let me know if this works for you. If it doesn't i can reopen

**Comment by wujian-nerc** [comment]
@helpceo I solved by modifying webpack.config.render.dev/prod.js

```
{
  test: /^((?!\.global).)*\.css$/,
  exclude: /node_modules/,
  use: [
    {
      loader: 'style-loader'
    },
    {
      loader: 'css-loader',
      options: {
        modules: true,
        sourceMap: true,
        importLoaders: 1,
        localIdentName: '[name]__[local]__[hash:base64:5]'
      }
    }
  ]
},
{
  test: /\.css$/,
  include: /node_modules/,
  use: [
    {
      loader: 'style-loader'
    },
    {
      loader: 'css-loader'
    }
  ]
}
```

**Comment by DaZiYuan** [comment]
```<link rel="stylesheet" href="../node_modules/antd/dist/antd.css">```   app.html
