### ISSUE TITLE
Using a dedicated testing NODE_ENV environment

### ISSUE THREAD

**Issue by davidwinter** [chentsulin/electron-react-boilerplate#1625]
Currently, e2e tests are dependent on `npm run build` being run first, generating a production-ready main.prod.js file. The e2e tests are run against this production build.

This, however, means that any code you conditionally use that was meant _just_ for production, will also be executed when e2e tests are run.

Is there currently a way to work around this? Otherwise, I propose a `NODE_ENV` `test` environment, where a `test` build is generated and tested against, so that when you check `process.env.NODE_ENV === 'production'` you can be 100% sure that it'll only ever be run when you mean it to be.

I'd be happy to submit a PR but wanted to start a discussion first to see what other peoples opinions are before writing any code.

**Comment by davidwinter** [comment]
From what I can tell, at a quick attempt to achieve this, the following would be required:

 * Duplicate and create a `webpack.config.main.test.js` and `webpack.config.renderer.test.js` files based off of the production files, replacing references to `production` with `test` _except_ for the webpack `mode` value which should remain as `production`. This will then generate `app/main.test.js` and `dist/renderer.test.js` files
 * Add a `build-main-test` and `build-renderer-test` script in `package.json` that will be the same as the production versions but use the new `test` webpack configs, and also prefix the commands with `NODE_ENV test`
 * In `app/app.html` ensure that the correct `renderer` file is used if `NODE_ENV === 'test'`
 * In your e2e spec, ensure that the Spectron app args reference the `main.test.js` file specifically

I've got a running version of all of the above which then lets you use the `NODE_ENV` conditionals as expected, without accidentally running any production code.

**Comment by amilajack** [comment]
This is something worth implementing. I'm actually thinking of redoing the e2e testing infra. This will probably be one of the changes i introduce
