### ISSUE TITLE
Uncaught Error: Cannot find module JQUERY

### ISSUE THREAD

**Issue by aindong** [chentsulin/electron-react-boilerplate#163]
Hi, I've been using bootstrap theme framework to create an app, and I know that there's problem with jquery on electron so I use this solution

`<script>window.$ = window.jQuery = require('./plugins/jQuery/jQuery-2.1.4.min.js');</script>`

I can always solve this problem using the above fix, but I can't on this boilerplate. Please help
here's the error `Uncaught Error: Cannot find module './plugins/jQuery/jQuery-2.1.4.min.js'`

**Comment by chentsulin** [comment]
What's the problem with jquery on electron? I haven't heard it before.
The information you provided here is not enough for tracing the bug. It may causes by folder structure, path, order of loading script...etc. 

You also can use typical html script including:
`<script src="plugins/jQuery/jQuery-2.1.4.min.js"></script>`
but highly recommended importing with commonjs via webpack.

**Comment by thedamon** [comment]
Bootstrap will require that the jQuery $ variable is available on to the window, but this doesn't have anything to do with the boilerplate. It's an issue of webpack, jquery and maaaybe electron

**Comment by chentsulin** [comment]
As what thedamon says, should consult webpack docs or stackoverflow for this kind of issue. keywords: jquery, commonjs, webpack, import, expose

**Comment by aindong** [comment]
As per my description above, I've made it to work on the starter kit of electron using the solution of requiring it from the node_module

**Comment by DutchKev** [comment]
@aindong Did you ever found another solution for this? Im also encountering it and found the same solution on the internet, but I can't seem to get it find the node_modules folder from the electron app.
