### ISSUE TITLE
how can i packaged to other path(not c://)

### ISSUE THREAD

**Issue by symnetry** [chentsulin/electron-react-boilerplate#1630]
because of i create 2 electron project , so i want to run package one of then to other path 
but if i first package one , then package another one 
the second project will cover the first 
(poor English, wish you can read)

**Comment by uppe-r** [comment]
I'm not sure I understand very well what the issue is, but can't you package one, then move the files and then package the other one?

**Comment by symnetry** [comment]
yes i packaged one ,then i got > ElectronReact Setup .exe 
in this step,i moved that in onther path
then i packaged the other 
ok ,problem is , i install first ‘exe’ file ,will install to path C://
and install the next , the next one will cover the first
maybe i can install the first one and move it to other way
install step is for users ,so i wish i can choose path to install

**Comment by uppe-r** [comment]
Oh, gotcha! Check this: [https://www.electron.build/configuration/win](https://www.electron.build/configuration/win)

Add this to your `package.json` to allow the user to select an install location:

```json
"nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    },
```

Beware that build.win.target has to be equal to "nsis", like so:

```json
"win": {
      "target": [
        "nsis"
      ]
    },
```

**Comment by symnetry** [comment]
wow!  thx
