### ISSUE TITLE
PR: Add data-e2e attr to all elements that are tested in e2e

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1637]

**Comment by goldylucks** [comment]
to replace both of these?
`data-tid`
`data-tclass`

I've seen `data-tid` and `data-test-id` tho `data-e2e` is new on my eyes :)

why go for that?

**Comment by amilajack** [comment]
Good idea. Let's go for the `data-tid` and `data-test-id`. If those are convention then we should go with them. Personally I've been using `data-e2e` because that's what I've been using for my own projects. No real reason.

**Comment by amilajack** [comment]
yup, lets do that

**Comment by amilajack** [comment]
Not necessary anymore with testcafe. https://github.com/DevExpress/testcafe-react-selectors
