### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by Ancinek** [chentsulin/electron-react-boilerplate#1649]
No idea why this is happening.
Code is straight from the repo.

I do not have `electron` installed globally or anything like this.

**Comment by uppe-r** [comment]
Hey, I assume you ran `yarn` or `npm install`, right?
Try removing your node_modules folder and running one of the above again. If it still doesn't work, please post the full error.

**Comment by Ancinek** [comment]
Hello @uppe-r.

I've already did my research and made sure that I did install the dependencies. I've also tried to remove `node_modules`. I'm not using atom terminal, just my mac regular terminal :(

**Comment by uppe-r** [comment]
Hm try posting the full error. It's bigger than `Cannot read property 'on' of undefined`, right?

**Comment by Ancinek** [comment]
I will paste it in a moment, rebuilding this thing once again.
I've noticed that when trying to `console.log(app)` inside `app/main.dev.js` I get the app object in my terminal, but it is `undefined` in the dev tools of the chrome window

**Comment by Ancinek** [comment]
The error itself:

```
index.js:74 Uncaught TypeError: Cannot read property 'on' of undefined
    at module.exports.opts (index.js:74)
    at Object.<anonymous> (main.dev.js:40)
    at Object../app/main.dev.js (renderer.dev.js:1673)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.<anonymous> (spaces.js:2)
    at Object../app/reducers/spaces.js (renderer.dev.js:2087)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.<anonymous> (index.js:3)
```

**Comment by Ancinek** [comment]
I feel ashamed now.
I did not notice that I'm importing from my reducer file some vars that I exported in `main.dev.js`. Removing this import worked!
