### ISSUE TITLE
Problem on installation

### ISSUE THREAD

**Issue by DronVol** [chentsulin/electron-react-boilerplate#1666]
Hello everyone! I have an issue during installation after

>npm install

> electron-react-boilerplate@0.13.3 postinstall C:\Users\DronVol\Documents\electron_react_boilerplate_test\electron-react-boilerplate
> node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js pa
ckage.json

module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:547:15)

    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at Function.Module._preloadModules (module.js:753:12)
    at preloadModules (bootstrap_node.js:475:38)
    at startup (bootstrap_node.js:188:9)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.13.3 postinstall: `node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node
 node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.13.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DronVol\AppData\Roaming\npm-cache\_logs
[2018-07-31T14_42_36_452Z-debug.log](https://github.com/chentsulin/electron-react-boilerplate/files/2245810/2018-07-31T14_42_36_452Z-debug.log)
\2018-07-31T14_42_36_452Z-debug.log

What kind of trouble do I have? babel-register is in its place, in a node_modules folder in the root catalog.

Thanks in advance.

**Comment by amilajack** [comment]
Please make sure to install with `yarn`

**Comment by DronVol** [comment]
It's sad, but yarn gives the same issue. 

PS C:\Users\DronVol\Documents\electron_react_boilerplate_test\electron-react-boilerplate> yarn
yarn install v1.9.2
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsy
nchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "stylelint > postcss-html@0.23.7" has incorrect peer dependency "postcss-syntax@^0.10.0".
warning "stylelint > postcss-markdown@0.23.7" has incorrect peer dependency "postcss-syntax@^0.10.0".
[4/4] Building fresh packages...
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js pa
ckage.json

module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at Function.Module._preloadModules (module.js:753:12)
    at preloadModules (bootstrap_node.js:475:38)
    at startup (bootstrap_node.js:188:9)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\Users\DronVol\Documents\electron_react_boilerplate_test\electron-react-boilerplate> yarn
yarn install v1.9.2
[1/4] Resolving packages...
success Already up-to-date.
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js pa
ckage.json
module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at Function.Module._preloadModules (module.js:753:12)
    at preloadModules (bootstrap_node.js:475:38)
    at startup (bootstrap_node.js:188:9)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

(second yarn command was run after deleting package-lock.json)

**Comment by amilajack** [comment]
Interesting. Try this:
```bash
rm yarn.lock
rm -rf node_modules
yarn cache clean
yarn
```

**Comment by DronVol** [comment]
Still have the same problem. Terminal log:

PS C:\Users\DronVol\Documents\electron_react_boilerplate_test\electron-react-boilerplate> yarn
yarn install v1.9.2

info No lockfile found.
[1/4] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
warning jest > jest-cli > istanbul-api > istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
warning stylefmt > stylelint > doiuse > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning stylefmt > stylelint > stylehacks > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
warning webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js pa
ckage.json
module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at Function.Module._preloadModules (module.js:753:12)
    at preloadModules (bootstrap_node.js:475:38)
    at startup (bootstrap_node.js:188:9)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by amilajack** [comment]
I think you should manually add `babel-register` then: `yarn add --dev babel-register`

**Comment by vikr01** [comment]
`info No lockfile found.`
There is a lockfile in the repository.

Where are you running yarn install from?

**Comment by le-garden-fox** [comment]
this issue persists

**Comment by le-garden-fox** [comment]
OK found the solution.

If you copy the files using Mac Finder you probably missed hidden files.

Use the terminal to copy the repo repo and be sure you have all the files, i.e. files and folders that start with a dot .erb
