### ISSUE TITLE
How can i run production without minification.

### ISSUE THREAD

**Issue by yanivkalfa** [chentsulin/electron-react-boilerplate#1671]
I've tried removing uglyfy from webpack config, and each time i npm run package, its still get minified.

**Comment by amilajack** [comment]
Try looking at the [config options](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#options) of the `UglifyJSPlugin`

**Comment by yanivkalfa** [comment]
I have removed that option completely from the file it still minifie - it shouldnt minifi by default.

**Comment by amilajack** [comment]
Try including the plugin and adding that option

**Comment by yanivkalfa** [comment]
@amilajack Tried include, and exclude . renderer still getting minified

**Comment by amilajack** [comment]
interesting. Try a fresh clone of the boilerplate and checkout the `v0.14.0` branch and add make that config change.

**Comment by yanivkalfa** [comment]
Thanks, will try

**Comment by yanivkalfa** [comment]
@amilajack - cloned, yarned, change to:

```
new UglifyJSPlugin({
      include: []
    }),
```

dist folder is still minified.

**Comment by amilajack** [comment]
Have a working example here: https://github.com/amilajack/erb-disable-minification-example/

**Comment by yanivkalfa** [comment]
Sorry for being rude, do you mind giving me a clue of what you changed, i will have to search the entire thing to find it otherwise.

**Comment by amilajack** [comment]
Look at the last commit

**Comment by yanivkalfa** [comment]
```
optimization: {
    minimizer: [
      new UglifyJSPlugin({
        parallel: true,
        sourceMap: true,
        include: []
      })
    ]
  },
```

hmm.. i dont have any of this optimization/minimizer sections. is that new to? only in 0.14 ?

**Comment by amilajack** [comment]
Were you able to get it working

**Comment by yanivkalfa** [comment]
i got the minification working, but now i know that the bug i encounter also revolves around minification. 


i was trying to debug an error, (not many clues were in console) so i thought i will run in none uglified, and get some more details, however when i do that, the error disappears - so now i know that the error has something to do with minification /uglification.

Its something to do with arrow functions i think.. will have to continue investigation and once i found the answer create an issue here, so you guys can warn your users.

**Comment by amilajack** [comment]
interesting. logging in prod works for me on `v0.14.0` even with minification on. Are you using the `DEBUG_PROD=true` env var?

**Comment by yanivkalfa** [comment]
yea, debug_prod is true,  and i see the error, but its all minified, and i think a weirder error happened in react minification. - not sure. still reading through.

**Comment by yanivkalfa** [comment]
Ok found the issue, I've fixed it before, however someone in the team re introduced it.

https://github.com/Cryptonomic/Tezori/blob/042c1aa0e4514df6ada46460e0a20363785a69ca/app/components/TransactionsLabel/index.js

Line - 10, and line 40-41 create the above issue.

I think its something with context/arrow functions.

Never seen it before though, so i am not sure how to categorize or name it.

Hope that would help others.
