### ISSUE TITLE
No way to access the store from the main process?

### ISSUE THREAD

**Issue by iwuvjhdva** [chentsulin/electron-react-boilerplate#1673]
Hi,

It seems to be impossible to access the store from main.dev.js

I want to make some cleanup tasks in app.on('before-quit') like killing child processes, that requires the access to the app state which seems to be impossible.

Is there a solution to that problem?

Isn't using electron-redux instead of just plain redux is more logical for the boilerplate?

Thanks!

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate/pull/1615
