### ISSUE TITLE
Discussion: Can't extend errors because this project uses Babel, Babel/Webpack schools of thought

### ISSUE THREAD

**Issue by aguynamedben** [chentsulin/electron-react-boilerplate#1684]
### Immediate Problem
I recently tried to `extend` the build-in `Error` class with something like this:

```js
class ReadError extends Error {}

new ReadError('Boom') instanceof ReadError // => false
```

This is a known Babel gotcha: https://github.com/babel/babel/issues/4485
> Extending builtin types like Array and Error and such has never been supported in Babel. It is perfectly valid in a real ES6 environment, but there are requirements to make it work that are very difficult to transpile in a way that is compatible with older browsers.

### What are the best schools of thought in the Electron community on this?

I'm not sure what all the pros/cons are, but given that Electron really combines 2 modern platforms (Node, Google Chrome), long-term I could see this project getting rid of Babel (and maybe Webpack?) magic and relying directly on native ES6 implementations (Node 10, Google Chrome). This is a little above my expertise level, but it seems that there are 2 schools of though for building an Electron app:

#### 1. Rely directly on APIs supported in Node.js and Google Chrome
* You only get access to the APIs supported by whatever version of Node.js and Google Chrome you're on. This problem seems fairly mitigated, as Node.js is making reasonable progress on implementing ES6 features.
* I believe this is what Slack does. If you un-asar Slack, you can see a lot of their code is un-minified and uses Node.js APIs. The dependencies ([here](https://github.com/electron-userland/electron-remote)) members of the Slack team uses seems to rely on Node.js APIs that like (require()) that aren't available in a Webpack environment.
 * This also seems to be the approach of Atom, as documented in their improvements to require()-ing on startup documented [here](http://blog.atom.io/2017/04/18/improving-startup-time.html).
* This approach also seems to be inline with how electron-forge works ([here](https://github.com/electron-userland/electron-forge))

#### 2. Rely on Babel (via Webpack) to transpile code for the main and/or renderer process
* This is the approach of this boilerplate.
* This approach gives you access to Babel configuration (and in turn more bleeding edge APIs).
* This approach may interfere with the use of Node.js dependencies that rely on require.resolve() due to how Webpack overloads this ([here](https://github.com/webpack/webpack/issues/1554)). I.e. you can't use dependencies like umzug, electron-userland/electron-remote because they assume your app is using Node APIs directly.
* This seems to be the option that supports more bleeding edge features, but is less complex to configure.

### What is the best place to discuss these community issues?
I'm still piecing this together. Is this the right way to think about the options out there? Who are the leader in the Electron community who might be able to explain this better than I can?

### Resources
* https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c
* https://node.green/
* https://nodejs.org/api/esm.html#esm_ecmascript_modules
* https://github.com/webpack/webpack/issues/1554

**Comment by amilajack** [comment]
<img width="1018" alt="screen shot 2018-08-08 at 1 52 22 pm" src="https://user-images.githubusercontent.com/6374832/43863683-52278500-9b12-11e8-865b-c2f27c90306c.png">
<img width="342" alt="screen shot 2018-08-08 at 1 52 26 pm" src="https://user-images.githubusercontent.com/6374832/43863684-524d6f90-9b12-11e8-99a7-d7bc5e04806a.png">
<img width="373" alt="screen shot 2018-08-08 at 1 52 31 pm" src="https://user-images.githubusercontent.com/6374832/43863685-5267d6c8-9b12-11e8-9dee-c0f7fb7127ae.png">

**Comment by aguynamedben** [comment]
And here's the implementation for the workaround that allows you to try/catch custom errors with Babel: https://github.com/aguynamedben/electron-react-boilerplate/compare/ef426887c5a2900ce8c38d49f96b05addc77e37f...40699635dbab9ce79c0278275f4b1cd19db6ed98 (see the `error-handling-confusion-workaround` branch on aguynamedben/electron-react-boilerplate).

I'm not really sure I have any other actionable things you can do on this ticket, so feel free to close it... I just wanted to convey the information and see if there is anything to learn. After a year I'm still learning the intricacies of the environmental issues with JavaScript/Babel/Node/Webpack/V8. Tracking down the cause of this issue took about 3/4 of a day.

On second look, I think Slack and electron-forge *do* use Babel, but they don't use Webpack.

Maybe this set of assertions is more accurate:
* Webpack caveats may cause issues dependencies that assume a pure Node.js environment. Webpack patches the environment a lot.
    * [Webpack overrides `require.resolve()`](https://github.com/webpack/webpack/issues/1554#issuecomment-158679844) (affects electron-userland/electron-remote, umzug).
* Babel caveats may cause issues with JavaScript language features. There are caveats that must be respected when Babel is used.
    * [Babel requires special workarounds for extending built-in objects](https://github.com/babel/babel/issues/4485#issuecomment-245779249), affects custom error handling) (affects `extends Error`, `extends Array`, etc.)

🤷‍♂️

**Comment by aguynamedben** [comment]
Closing, this is a similar discussion to https://github.com/chentsulin/electron-react-boilerplate/issues/1827, if anybody has things to add please add in #1827.
