### ISSUE TITLE
How to embed files so that I can use `fs` to read them?

### ISSUE THREAD

**Issue by jakinov** [chentsulin/electron-react-boilerplate#1687]
I'm trying to embed files (essentially text files) that I can read at run time with `fs`. I'm not sure how to embed the files or how to reference them. If I use `fs` it would use the file system of the user running the app but I want to access the file I plan embedded in the app.

I've tried adding the file to the `build` section of `package.json` but no luck.

Is this possible? Can you bundle files within an Electron app which you can read any time you want?

**Comment by amilajack** [comment]
I’d recommend you do this with webpack. Just import the files

**Comment by jakinov** [comment]
@amilajack I got it working thanks. I use `raw-loader`, i found that `file-loader` kept returning a url. `Raw-Loader` loads the file as text which works for my case. But lets say the file was a binary or another type of file where I don't want it loaded as a string. Do you know if it is possible to embed files in the Electron app and access/run them only when needed?

**Comment by amilajack** [comment]
Try [this](https://github.com/chentsulin/electron-react-boilerplate/issues/1530) and then [set this](https://github.com/amilajack/popcorn-time-desktop/blob/5ae276699ab84032810927854593651566524b8f/webpack.config.main.prod.js#L56-L59) for your prod webpack configs

**Comment by amilajack** [comment]
Interesting. So they are text files and are you are trying to import them but webpack is resolving them as JS files? You should probably be getting syntax errors in those cases. Try changing the file extensions of those files. Let me try to create an example

**Comment by amilajack** [comment]
Here you go:
https://github.com/amilajack/erb-local-fs-read-example

**Comment by jakinov** [comment]
@amilajack Thanks again for helping but it does not solve my issue. I had no problems before with importing within a component. I'm trying to import in `~main.js`. For my use case; I intend to build my application with configuration files that are embedded and need to be loaded. It made sense to me to load this at the start of the program and make it global. 

But I ended up finding this which gave me an alternative solution.
https://github.com/chentsulin/electron-react-boilerplate/issues/906

On MacOS it seems that all `.app` "files" are just folders and the `app.asar` gets placed in that folder somewhere. If this was a Windows machine, do you know if I would I be able to rely `__dirname` and be able to access the `.asar` the same way?  Will the Electron built **exe** place the files somewhere?

**Comment by amilajack** [comment]
If you want to do this from the main process you could write a webpack config for the main process. If you think this will work for your situation let me know and i can help you with the config

**Comment by amilajack** [comment]
> But lets say the file was a binary or another type of file where I don't want it loaded as a string. Do you know if it is possible to embed files in the Electron app and access/run them only when needed?

webpack actually doesnt load the file as a string. It loads the files as a buffer instead of a string. Also if you want to load it in a different format you would use a different webpack loader. Using webpack to do this will give some small performance improvements because the production build of the `main.dev.js` will come bundled with the resources you imported. This way you'll only need to make one fs call.
