### ISSUE TITLE
first menu label will not change on npm run dev.

### ISSUE THREAD

**Issue by yanivkalfa** [chentsulin/electron-react-boilerplate#1688]
No matter what change i make to:

https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/menu.js#L48

when i do `npm run dev` it will allways show 'Electron'

On `npm run package` its fine.

**Comment by amilajack** [comment]
That is the expected behavior

**Comment by yanivkalfa** [comment]
No way around it ?

**Comment by amilajack** [comment]
I havent really looked into this much. Its just dev env so it didnt really matter to me
