### ISSUE TITLE
Require ways to support Service Worker

### ISSUE THREAD

**Issue by clujin** [chentsulin/electron-react-boilerplate#1692]

**Comment by amilajack** [comment]
Can you add your webpack config here

**Comment by clujin** [comment]
So taking the current master branch, I made the following small changes:

Inside `app/app.html`, I added:

```
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js')
      .then(() => console.log('Registered!'))
      .catch(console.error);
  })
}
```

Added `app/sw.js`, which just reads:
```
self.addEventListener('install', () => console.log('Service Worker Installed!'));
```

This would work fine during development, but when I build the binary with `yarn package`, the prod version would complain with:
```
TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script.
```

So the first inclination is to augment the `webpack.config.renderer.prod.js` file by adding a new entry:

```
  entry: {
    'renderer.prod': './app/index',
    'sw': './app/sw',
  },

  output: {
    path: path.join(__dirname, 'app/dist'),
    publicPath: './dist/',
    filename: '[name].js'
  },
```

I thought that should go into the `renderer.prod` file, but the production binary still doesn't have the `sw.js` file. Maybe I'm not understanding the build process well enough.
