### ISSUE TITLE
Getting app version while in dev env?

### ISSUE THREAD

**Issue by yourfavorite** [chentsulin/electron-react-boilerplate#1694]
app.getVersion() returns the electron version when running in dev mode. Is there a way to get the actual app version while in dev mode? Ideally via this function but another method would be fine as well.

**Comment by amilajack** [comment]
I havent really looked into this yet. Why is `electron-builder` using a different version?

**Comment by yourfavorite** [comment]
This is the only thread I've been able to find on the issue: https://github.com/electron/electron/issues/7085

**Comment by amilajack** [comment]
Hmm that's really weird. Shouldn't they be the same?

**Comment by yourfavorite** [comment]
On the surface, yes, I think so. But I don't really know the inner-workings of all of this personally.

**Comment by amilajack** [comment]
Yea. This seems like more of an electron issue. Going to close. Let me know if this gets fixed

**Comment by yourfavorite** [comment]
So it looks like the way to possibly get around this has to do with how you start the app. If you reference a file directly then you get electron version. But if your reference the root directory you get the correct app version. I poked around in the boilerplate and I can't figure out how to make that work haha. 

https://github.com/SimulatedGREG/electron-vue/pull/530
