### ISSUE TITLE
How to edit app.html file? if i want to add more script  and css in it ??

### ISSUE THREAD

**Issue by karanshrm44** [chentsulin/electron-react-boilerplate#1695]

**Comment by amilajack** [comment]
It is editable. You just add css to it. But I would recommend you import using sass and import JS from `./app/index.js`

**Comment by karanshrm44** [comment]
1. I have script which are added into html file of public folder( A react project which i try to convert into Electron) So script i added into ./app/index.js according to you?
2.From my project I remove module:true from all css loader so i can use css as normal css( i can import it normally as react project) , this is a good way or not please tell me.

**Comment by amilajack** [comment]
Use [this project as an example](https://github.com/amilajack/popcorn-time-desktop). I'd recommend reverting the css module changes. Import css through [sass like so](https://github.com/amilajack/popcorn-time-desktop/blob/master/app/styles/main.scss#L13). And yea, just import that script in `./app/index.js`. This is an [example that imports dynamically](https://github.com/amilajack/popcorn-time-desktop/blob/master/app/index.jsx#L30)

**Comment by karanshrm44** [comment]
Can i Change predefine Redux and Route structure? just clean ./app/index.js file and then I connect my project in it . Which contain Redux and Route Separate after cleaning default code

**Comment by amilajack** [comment]
I would recommend you not do that. That configuration is difficult to configure. You will probably run into a bunch of issues if you change certain things. Adding new routes is fine. But changing how redux handles routes will probably break your application

**Comment by karanshrm44** [comment]
So According to you I don't have to Change store  folder and I change change things around that

**Comment by amilajack** [comment]
you can if you want. for example you can add new plugins and what not. just dont change the redux interaction
