### ISSUE TITLE
How can you run a script on uninstall to remove added data?

### ISSUE THREAD

**Issue by yanivkalfa** [chentsulin/electron-react-boilerplate#1697]
Say when app runs i create some folders/files in user home directory ( because linux for some reason have issues with creating new files in user data folder). how can i delete those folders/files on uninstall ?

I want to install in home directory due to permissions issue i am having with appData on linux builds.
Its seems that linux will not let you create new file during run time.

**Comment by vikr01** [comment]
You can use `rimraf`, `fs.remove`, or `fs.removeSync`.

**Comment by yanivkalfa** [comment]
@vikr01 Ok, but when/where ? where can i find the un-install life cycle ?

**Comment by vikr01** [comment]
See the `rimraf` api [here](https://github.com/isaacs/rimraf#api).

You'll need to know what directories/files you're erasing, and pass it to the function.

**Comment by talha131** [comment]
> how can i delete those folders/files on uninstall ?

@yanivkalfa if I understand you correctly, you want to remove files when user uninstalls app using the uninstall option in the OS.

To the best of my knowledge @vikr01 suggested solution will not be relevant here. Install and uninstall is handled using [electron-builder](https://github.com/electron-userland/electron-builder).

So you will have to ask this question there.

It seems you will have to add an uninstall script that will be run by package manager. This script will remove the data folders. Rest of the uninstallation will be handled by electron-builder.

By the way, there are utility programs that remove application along with its data files. Windows has Revo Uninstaller. Mac has App Cleaner. Perhaps Linux too has a similar tool.

You should also think about what will happen if user installs the application again. Wouldn't the user want to reuse the old settings? Imagine `.vimrc` is also removed when Vim is unisntalled. How inconvenient that would be?
