### ISSUE TITLE
Additions to README

### ISSUE THREAD

**Issue by uppe-r** [chentsulin/electron-react-boilerplate#1703]
While looking at other boilerplate-ish projects, I found that a ton of them have "cool" badges from [https://forthebadge.com/](https://forthebadge.com/) with things like
![image](https://user-images.githubusercontent.com/12294525/44176171-b683a780-a0e0-11e8-9d44-8a391dc3b00d.png)

which in my opinion look pretty nice and friendly. How about we add some of those into README?

Apart from that, I feel like the project also needed a logo for its README:
![erb](https://user-images.githubusercontent.com/12294525/44176908-a28d7500-a0e3-11e8-8a8c-a453d6b14973.png)
![erb2](https://user-images.githubusercontent.com/12294525/44203609-77d50800-a147-11e8-98f0-f2403527abdc.png)

and these are some of my suggestions (btw, I suck at design. This is just two logos glued together with some text pretty much)

Let me know your opinion on these!

**Comment by uppe-r** [comment]
Give a look also at this quick test I made on my fork's README [https://github.com/uppe-r/electron-react-boilerplate/blob/master/README.md](https://github.com/uppe-r/electron-react-boilerplate/blob/master/README.md).

Think it looks pretty neat.

**Comment by amilajack** [comment]
I like it! But I was a bit confused by the logo. We can merge this for now but I think we should come up with a new logo

**Comment by uppe-r** [comment]
I'll make the PR. I suck at designing anything, I just glued Electron and React's logos together (LOL).
