### ISSUE TITLE
How to change the name of the application on production?

### ISSUE THREAD

**Issue by johhansantana** [chentsulin/electron-react-boilerplate#1704]
I'm trying to figure out how to change this.

I changed the name in `package.json` where it says `productName` but I get an error after doing `yarn package`:
```
WARNING: No more files
NameIChosen.app
```

**Comment by mssodhi** [comment]
You need to add productName under build object:
Here's my example:
`"build": {
    "productName": "AppName",
    "appId": "com.me.AppName",
    "copyright": "Copyright © 2018 AppName",
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": [
        "nsis"
      ]
    },
    "directories": {
      "buildResources": "resources",
      "output": "release"
    }
  },
`

**Comment by runn-vermel** [comment]
Note that if you want to change the version number for production, you'll have to change the version number in the app/package.json file, and not the package.json file in the root.
