### ISSUE TITLE
Nothing shown

### ISSUE THREAD

**Issue by phhoef** [chentsulin/electron-react-boilerplate#1706]
After fresh clone of this repository I ran `yarn` and afterwards `yarn dev`.
The application comes up, but it's completely empty. Only a white screen.
When looking in the dev tools, the body element is totally empty, no child elements.

I am quite new to the Electron, React stuff, so I don't know how to dig into the problem.

I am developing on macOS High Sierra 10.13.6.
yarn 1.9.4
npm 6.3.0
node 10.8.0

Anything, that I could have done wrong?
I didn't changed any file in this project.

**Comment by uppe-r** [comment]
Hey @phhoef are there any errors in the devtools console or in the terminal where you ran the command?

**Comment by phhoef** [comment]
@uppe-r thanks for your very quick reply.

yes, indeed. Sorry I didn't notice the error in the first place.
`Not allowed to load local resource: file:///Users/ph/Documents/Projects/MyApp/app/app.html`

Obviously the `app.html` can not be found.
And actually the `app.html` is not in the root of the project, but below the `app` folder.

Is this a bug in the template?
How can I change the path?

**Comment by phhoef** [comment]
I've tried it several times in different project folders.
The result is always the same. I don't see what's wrong.

**Comment by uppe-r** [comment]
As a last idea, you could try running `yarn cache clean`...
I'm quite out of ideas as well, if that doesn't solve it, no worries, someone else with a better idea might come.

I tested it on Windows and everything's working here with the same versions as yours, so I guess the problem could be with macOS?

**Comment by phhoef** [comment]
Unfortunately clearing the cache did not help.
Still the same error ...

**Comment by PLDaily** [comment]
I have the same problem. when I run yarn dev, I can see the menu 
<img width="345" alt="2018-08-20 2 39 17" src="https://user-images.githubusercontent.com/11615211/44325409-4df34c80-a48b-11e8-8e79-ed7ebd7bd1ce.png">
but I can not see the screen.
My system is
macOs 10.13.3
node 8.11.1
npm 5.6.0
yarn 1.6.0

I am tried in window 10 x64, it works well.

**Comment by amilajack** [comment]
What does the output of `yarn dev` show?

**Comment by phhoef** [comment]
```
yarn dev
yarn run v1.9.4
$ cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js
Starting Main Process...

> electron-react-boilerplate@0.14.0 start-main-dev /Users/ph/Documents/Projects/MyApp
> cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js

2018-08-20 18:37:34.625 Electron[12604:407559] *** WARNING: Textured window <EventDispatchingWindow: 0x7fe3dc520d40> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
2018-08-20 18:37:35.170 Electron Helper[12610:407639] Couldn't set selectedTextBackgroundColor from default ()
```

And this error is logged in the console:
`Not allowed to load local resource: file:///Users/ph/Documents/Projects/MyApp/app/app.html`

The screen shows 
<img width="1036" alt="screenshot" src="https://user-images.githubusercontent.com/32458104/44353825-80f80900-a4a8-11e8-9371-4b6524200b07.png">

**Comment by amilajack** [comment]
Can you screenshot the devtools

**Comment by phhoef** [comment]
I was creating cloning the repository one last time and actually for some reason, it is working now.
Sorry, for the trouble. I already cloned the repository a few times in different directories, but the result was always the same ... until today.

Sorry for bothering you.

**Comment by amilajack** [comment]
Its fine. Thanks for reporting the issue.
