### ISSUE TITLE
Regarding Icon in Erb

### ISSUE THREAD

**Issue by karanshrm44** [chentsulin/electron-react-boilerplate#1710]
I changed the icon of the resource but it still shows default Electron icon When I run yarn dev?

**Comment by amilajack** [comment]
that is expected

**Comment by karanshrm44** [comment]
than how the icon is changed??

**Comment by amilajack** [comment]
No. Its just a related issue. Certain things, such as what was showed in that issue, persist only in development. That is the expected behavior

**Comment by clytras** [comment]
For `2.x`, change:

```js
const RESOURCES_PATH = app.isPackaged
  ? path.join(process.resourcesPath, 'resources')
  : path.join(__dirname, '../resources');
```

to:

```js
const RESOURCES_PATH = app.isPackaged
  ? path.join(process.resourcesPath, 'resources')
  : path.join(__dirname, '../assets');
```

I'm not sure for the production `resources` directory, but it works like this for both development and production packed.

It's nice to create a function so to pick the right icon for the corresponding operating system, for example:

```javascript
export function selectAppIcon(): string {
  switch (os.platform()) {
    case 'win32':
      return getAssetPath('icon.ico');
    case 'darwin':
      return getAssetPath('icon.icns');
    default:
      return getAssetPath('icon.png');
  }
}
```

and then inside `main.dev.ts` use this function to set `BrowserWindow` icon:

```javascript
mainWindow = new BrowserWindow({
  ...
  icon: selectAppIcon(),
  ...
});
```
