### ISSUE TITLE
Menu always showing on dev even when removed

### ISSUE THREAD

**Issue by ButchMonkey** [chentsulin/electron-react-boilerplate#1717]
I have removed `Menu.setApplicationMenu(menu);` from the menu.js and when packaging the app it is not displaying which is as expected. However when I run in dev mode (`yarn dev`) the menu is still visible as a default.

Is there a way to hide the menu in dev and packaged?

**Comment by spcBackToLife** [comment]
you can set a default menu to hide this,such as this(in render progress)
```
const remote = require('electron').remote;
const Menu = remote.Menu;
let menu = new Menu();
    menu.append(new MenuItem({ label: 'xxxx', click: () => {} }))
    menu.popup(remote.getCurrentWindow());
```

**Comment by ButchMonkey** [comment]
Thanks. 
I've actually changed to a borderless design now so don't see the menu anymore anyway.
