### ISSUE TITLE
--asar option returns multiple files rather than single packed executable

### ISSUE THREAD

**Issue by lmatteis** [chentsulin/electron-react-boilerplate#172]
When I do `npm run package -- --all --asar --name FooBar` everything works fine:

```
Packaging app for platform linux ia32 using electron v0.36.9
Packaging app for platform win32 ia32 using electron v0.36.9
Packaging app for platform win32 x64 using electron v0.36.9
Packaging app for platform linux x64 using electron v0.36.9
Packaging app for platform darwin x64 using electron v0.36.9
linux-x64 finished!
linux-ia32 finished!
darwin-x64 finished!
win32-x64 finished!
win32-ia32 finished!
```

However, when I look in my `releases` folder, especially for linux and windows, I get a bunch of different files rather than a single file:

![screen shot 2016-03-04 at 6 17 27 pm](https://cloud.githubusercontent.com/assets/535442/13534435/60158c36-e235-11e5-88a1-e80bdef07d23.png)

How do I distribute this folder to my users? I thought the whole point of `--asar` was to create such a single executable but it doesn't seem to work properly.

**Comment by jhen0409** [comment]
The `asar` file is load by electron runtime, it's not an executable file. It exists in resources/app.asar, and it included your Electron project.
