### ISSUE TITLE
bundle.js 404

### ISSUE THREAD

**Issue by amejias101** [chentsulin/electron-react-boilerplate#175]
I cloned the repo and followed the instructions, everything installed properly. When I run `npm run hot-server` + `npm run start-hot` or `npm run dev`, the window opens up, but the inspector tools complain about the missing bundle.js file

**Comment by chentsulin** [comment]
I can't reproduce this issue with a new fresh cloned repo.

```sh
git clone git@github.com:chentsulin/electron-react-boilerplate.git
cd electron-react-boilerplate
npm i
npm run dev
```

Are there any errors shown on your terminal or renderer console? I am going to close this issue. But if you can provide more detail information, feel free to reopen this. Then, we can trace further.

**Comment by amejias101** [comment]
yeah, tried again and it worked. Not sure what changed

**Comment by arnostpleskot** [comment]
Hi,
I had same issue when instance of [Browsersync](https://www.browsersync.io/) was running on port 3000. 
Terminating Browsersync and reload (`cmd + r` in electron window) did the job for me.

**Comment by xBau** [comment]
I had the same error.
As amejias101 I tried deleting the cloned repo and cloning again and it worked for me.

**Comment by mauriciomelo** [comment]
I had the same error. Seems like Electron opens before the express server that serves the bundle.js. When I reload the page (command + R) it works.

**Comment by henryboldi** [comment]
@amejias101 figure out a way to get it to start without reloading?
