### ISSUE TITLE
package go binaries not implement

### ISSUE THREAD

**Issue by BeAce** [chentsulin/electron-react-boilerplate#1750]
I want to run the go binary file for the simple server in the child process. The dev mode is working, but the server not start and can not connect `127.0.0.1:3000` after package.

Here is my code.

#### child.js
```javascript
import path from 'path';
import childProcess from 'child_process';

const child = () => {
  const node = childProcess.execFile(path.join(__dirname, './gobinaries'), [], {
    cwd: process.cwd()
  });

  node.stdout.on('data', data => {
    console.log(`stdout: ${data}`);
  });

  node.stderr.on('data', data => {
    console.log(`stderr: ${data}`);
  });

  node.on('close', code => {
    console.log(`child process exited with code ${code}`);
  });
};

module.exports = child;
```

#### main.dev.js

```javascript
import childProcess from './child';

app.on('ready', async () => {
  ...
  mainWindow = new BrowserWindow({
    show: false,
    width: 1000,
    minWidth: os.platform() === 'win32' ? 800 : 1000,
    minHeight: os.platform() === 'win32' ? 600 : 750,
    frame: false,
    height: 750,
    title: 'myapp',
    backgroundColor: '#fff',
  });
  ...
  childProcess();
});
```

#### package.json

```json
"build": {
  "files": [
    "dist/",
    "node_modules/",
    "app.html",
    "main.prod.js",
    "main.prod.js.map",
    "package.json",
    "gobinaries"
  ]
 }
```

**Comment by vikr01** [comment]
Do you have a stack trace you could show?

**Comment by BeAce** [comment]
I don't know how to enable a stack trace after `yarn package`, but I enable devtool in production, and got this error.

![image](https://user-images.githubusercontent.com/13284978/45077910-1b9b4d80-b121-11e8-8825-d38a6c1de6e9.png)

**Comment by BeAce** [comment]
I know the file path is not correct, so I add extraResources like that
```json
"extraResources": [
  "binaries/**"
]
```

When I run app used command line
```
./Applications/MyApp.app/Contents/MacOS/myapp
```

It worked!!!

But, direct opening app is always not working.Electron didn't respond. It didn't seem to have been executed, or the sub process blocked the main process.

**Comment by BeAce** [comment]
I have found the reason, the go binaries connected sqllite.db, when server started the db path was not correct. So I solved the problem by pass an env variable of db path to go binaries.
