### ISSUE TITLE
Will Webpack bundle all my node_modules in dist/bundle.js?

### ISSUE THREAD

**Issue by lmatteis** [chentsulin/electron-react-boilerplate#176]
I'm wondering whether I need to include my node_modules directory in my packaged app. Will webpack include everything in bundle.js?

My node_modules is 15mb large and includes lots of code duplication because certain libraries installed with NPM include both the source and minified version.

What's the best way to only include the minified version in the final packaged app?

**Comment by chentsulin** [comment]
duplicated of #137

**Comment by swateek** [comment]
I am still unsure of if I should or should not bundle my node_modules. There isn't a clear example. (I just came here with my issue, not specific to boileplate though)
