### ISSUE TITLE
Add github issue template

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#1762]

**Comment by mattbudde** [comment]
I would like to complete this if nobody else has picked it up yet.

**Comment by amilajack** [comment]
@mattbudde that would be awesome! This still needs to be done 😄

**Comment by mattbudde** [comment]
Awesome, can you assign me to the issue?

**Comment by vikr01** [comment]
I've marked it as `taken` for you @mattbudde. Issues are only able to be assigned to collaborators.

**Comment by vikr01** [comment]
Closed in #1824. Thanks @mattbudde.
