### ISSUE TITLE
use mysql database

### ISSUE THREAD

**Issue by maelfosso** [chentsulin/electron-react-boilerplate#1769]
Hi,

I'm a newbie on React.js
I am building a desktop app, offline app. I want to use a local Mysql database.
I know that it's possible to use Mysql directly with Electron. By using React.js I would like to know how to make a **Redux** via ``reducers`` communicate with Electron.

How to do it please ? (Without  building an API)
Thanks.

**Comment by talha131** [comment]
You can run queries on MySQL from main thread only. 

To enable communication between renderer and main thread you will have to use IPC.

See 

1. https://electronjs.org/docs/api/ipc-main
1. https://electronjs.org/docs/api/ipc-renderer

This how I would do it,

### Inside your front code

1. In your front end code, call a method on button click `fetchRecordsClicked`.
1. This in turn will send message to main thread using `ipcRenderer.send`
1. Your front end code has  a listener too like `ipcRenderer.once`. It will receive response from the main thread.
1. On receiving response from the main thread, listener dispatches appropriate action and pass MySQL result set it.
1. Action and the result set will be received by the reducer and it will do its magic.

### Inside your main thread code

1. Have a listener using `ipcMain.once`. It will receive the message from `ipcRenderer.send`.
1. When it receives fetch records request from the front end, it will call your database layer.
1. Database layer will run the SQL query and return result
1. Send this result to the front end using `ipcMain.send`. The `ipcRenderer.once` will receive it and it will know which action to dispatch.

### Tips

1. All this communication is async, so perhaps its better to use Promise to keep code simplified.
1. Make sure your sender and listener are using the same channel.

**Comment by BrendonChirume** [comment]
Hi I'm trying to achieve the same thing do you mind creating a repo with code and sample data

**Comment by frankgo81** [comment]
why not use this store? https://electron-react-boilerplate.js.org/docs/electron-store
