### ISSUE TITLE
Electron Redux Dev Tools Window

### ISSUE THREAD

**Issue by neurosnap** [chentsulin/electron-react-boilerplate#177]
https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/index.js#L25

Do we have a sample of how to use the redux tools menu as a separate electron window?

**Comment by jhen0409** [comment]
Maybe related to #108, it's possible to implement, but a little complicated. :\
Now there is a simple way is use [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools) and select a [remote monitor](https://github.com/zalmoxisus/remote-redux-devtools#remote-monitoring).

Also, we can wait https://github.com/github/mentorships/issues/98, maybe we can use [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) in the future!

**Comment by chentsulin** [comment]
I think remove `createDevToolsWindow` stuff and point users to `remote-redux-devtools` in the README is a good enough solution ATM.
