### ISSUE TITLE
Tray Icon doesn't show up when I package in MacOS

### ISSUE THREAD

**Issue by runn-vermel** [chentsulin/electron-react-boilerplate#1774]
Hi there!

Sorry, possible newbie question - i've never built an electron app before, let alone package one...

**background:**
my app consists of a tray icon, which, when pressed, shows my main window - which then has a SPA running inside it.

I've kept the general structure of the boilerplate, and the only thing i added (which might or might not be possible under electron ) is electron-json-storage - an npm package which allows writing and reading json from the user's local FS.

**Problem**
Running yarn package does succeed, with the following warnings:

```
WARNING in ./node_modules/electron-debug/index.js 101:45-58
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.js
[0] 
[0] WARNING in ./node_modules/electron-debug/index.js 102:61-74
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.js
```

and I do get a .dmg file, but, when i click it, the program opens, and I only get a menu item with quit in it, and the tray icon doesn't show up at all - which is a problem, since clicking on that launches my app...

any guesses? sadly, i cannot share the entire code base, but i'm happy to share pertinent snippets...

**Comment by runn-vermel** [comment]
SOLVED
When i right clicked the .app file, and chose on show package contents, i could see a Contents/Mac folder, and inside that was a unix executable file, which when i ran in the command line, showed me a rejected promised that had to do with my tray icon - i was doing a path.join(__dirname,'icon.png'). when i changed that to an absolute path ('users/myname/app/icon.png') and rebuilt, it worked!

**Comment by Noitidart** [comment]
Thanks for sharing your struggle, I'm trying this out now.
