### ISSUE TITLE
Discussion: is it possible to remove flow entirely from project?

### ISSUE THREAD

**Issue by alearcy** [chentsulin/electron-react-boilerplate#1775]
Hi! I don't want to use Flow, and I would lighten my fork removing it. 
Is it possible? How can I do that?
Thanks 😉

**Comment by amilajack** [comment]
Remove all the type definitions and uninstall the dependencies and remove flow from npm scripts

**Comment by barbalex** [comment]
> Remove all the type definitions

Sorry, I am a complete flow noob. How do I do this?

**Comment by barbalex** [comment]
Ouch. I tried removing all that contained flow. Unfortunately inside a lot of files there are now flow annotations (is that the right word for this?) that cause javascript errors. 

Example: `const port: string = process.env.PORT || '1212';` inside CheckPortInUse.js.

So this looks like a rather big undertaking :-(

**Comment by benatkin** [comment]
I did a search for flow and specific annotations and removed them, and also removed other stuff by trial and error. It took a while, but after I removed enough stuff I was able to get it to run:

https://github.com/resourcesco/desktop-app/commit/2b9025299522398af5940a0ccfe1f56585bfbaee
