### ISSUE TITLE
add "how to bootstrap a new project using electron-react-boilerplate" in readme

### ISSUE THREAD

**Issue by barbalex** [chentsulin/electron-react-boilerplate#178]
I am probably a bit too nooby but I have read the readme several times trying to find out how to bootstrap a new project using this boilerplate.

I believe it is not explained.

The readme contains two first steps: "Install" and "Run".

Seems to me that there must be a step before "Install" which is running `npm install` which makes no sense without a prior step.

Maybe I have to clone the repository first?

**Comment by chentsulin** [comment]
You are right. I will add instruction of clone repo to README. thanks

**Comment by barbalex** [comment]
thanks for this GREAT tool!


2016-03-14 3:08 GMT+01:00 C. T. Lin <notifications@github.com>:
