### ISSUE TITLE
NPM commands to hot-server throws errors

### ISSUE THREAD

**Issue by kennetpostigo** [chentsulin/electron-react-boilerplate#180]
Hello,

Im currently trying to install this project and get started.I followed the instruction in the README.md:
1. Cloned Rep
2. `CD` into repo and `npm install`

Then when I was attempting to start the project using the two commands you have listed:
`$ npm run hot-server` throws the error below:
![screen shot 2016-03-18 at 2 58 00 pm](https://cloud.githubusercontent.com/assets/8888991/13888816/db6dfb68-ed19-11e5-8d66-54a3628da769.png)

`$ npm run start-hot` runs as it should the electron window opens with the following error:
<img width="1026" alt="screen shot 2016-03-18 at 3 01 59 pm" src="https://cloud.githubusercontent.com/assets/8888991/13888957/6e080392-ed1a-11e5-8917-438bc7ee3466.png">

I open up the code to `main.js` on line 74 and its just the closing array. Same thing happens if I try to run 
`$ npm run dev`

Is there something I may be doing wrong here?

**Comment by jhen0409** [comment]
> $ npm run hot-server throws the error below

It looks port 3000 is occupied.

> $ npm run start-hot runs as it should the electron window opens with the following error

I cannot reproduce this, and `main.js` error should not appear in the Electron DevTools?

**Comment by kennetpostigo** [comment]
@jhen0409 that solved it, I had an old project running on port 3000 and I hadn't realized it. Thank you!
