### ISSUE TITLE
Participate in Hacktoberfest

### ISSUE THREAD

**Issue by uppe-r** [chentsulin/electron-react-boilerplate#1817]
Hey, I believe the project could benefit a lot from participating in Hacktoberfest through the "hacktoberfest" label and various difficulties (it helps people find repos to contribute in).

For more info read [https://hacktoberfest.digitalocean.com/faq](https://hacktoberfest.digitalocean.com/faq)

Maybe we could get the label on some issues?

**Comment by amilajack** [comment]
Great idea! Just did this for some issues. Any other issues you think we should add them to?

**Comment by uppe-r** [comment]
How about [#893](https://github.com/chentsulin/electron-react-boilerplate/issues/893), [#1642](https://github.com/chentsulin/electron-react-boilerplate/issues/1642), [#557](https://github.com/chentsulin/electron-react-boilerplate/issues/557), [#1762](https://github.com/chentsulin/electron-react-boilerplate/issues/1762) and [#](https://github.com/chentsulin/electron-react-boilerplate/issues/447)

**Comment by amilajack** [comment]
Done!
