### ISSUE TITLE
How to integrate redux saga?

### ISSUE THREAD

**Issue by hemel-cse** [chentsulin/electron-react-boilerplate#1818]
If anyone does integrated redux-saga with this boilerplate please share thoughts about it.

Thanks

**Comment by nacmonad** [comment]
inside configureStore (theres a dev and prod version) do something like this:

`const sagaMiddleware = createSagaMiddleware();
  middleware.push(sagaMiddleware)

// Apply Middleware & Compose Enhancers
  enhancers.push(applyMiddleware(...middleware));
  const enhancer = composeEnhancers(...enhancers);

  // Create Store
  const store = createStore(rootReducer, initialState, enhancer);`
