### ISSUE TITLE
Support for SCSS

### ISSUE THREAD

**Issue by kennetpostigo** [chentsulin/electron-react-boilerplate#182]
Hey, 

I've been attempting to tweak the webpack to accept SCSS files, but I haven't quite been able to get them working through webpack.

In my regular projects I usually use:
+ css-loader
+ node-sass
+ sass-loader
+ style-loader

and then put this in my webpack.config file loaders:
   ```js
   {
      test: /\.scss$/,
      loader: 'style!css!sass'
   }
```

This allows me to import scss files into my component `.js` files like so:
```js
import './LandingStyles.scss'
import React from 'react'
...
```

Any reason why this wouldn't be compatible with the webpack setup that you have for this project? As I'm having trouble getting it to work.

**Comment by kennetpostigo** [comment]
I was able to solve this, you can disregard.

**Comment by marlonpp** [comment]
Could you share how!?

Thanks.

**Comment by kennetpostigo** [comment]
@marlonpp add the scss config to only the webpack.config
