### ISSUE TITLE
react router optional params does not work?

### ISSUE THREAD

**Issue by mouhsnimohamed** [chentsulin/electron-react-boilerplate#1822]
How can I add an optional param to react router? here is my routes.json

```
{
  "HOME": "/",
  "INTERMEDIATE": "/intermediate/:cat",
  "CATEGORY": "/category/:cat/:subCat/:subSubCat?"
}
```

I want to set the third param in CATEGORY field as an optional, I added **?** but it did not match the route.

react-router version: **^4.3.1**

**Comment by amilajack** [comment]
This is equivalent to doing something like `<Link to="/category/:cat/:subCat/:subSubCat?" />`. Please try that. If that doesn't work then it is an application related issue on your end.

**Comment by mouhsnimohamed** [comment]
Sorry it's my bad, my code was working

thanks for replay, you can close this issue
