### ISSUE TITLE
How to load external urls?

### ISSUE THREAD

**Issue by SevenSinS02** [chentsulin/electron-react-boilerplate#1825]
For example, I have an image tag with its src set to point to an external link say 'https://via.placeholder.com/350x150'. Setting nodeIntegration to false should work but the rest of the app doesn't work as it uses relative URLs.

**Comment by amilajack** [comment]
Docs for that are [here](https://github.com/electron/electron/blob/master/docs/api/shell.md#shell). You can add an `onClick` prop to the image element.

**Comment by SevenSinS02** [comment]
I see. However, I was hoping for another way(no offense).
I'm using the react-player module to which I'm passing an external URL. If it made a fetch request, all would be fine but it is requesting it through the file protocol. Would I be using the same solution to this as well?

**Comment by amilajack** [comment]
Provide an example. I think that would help me better understand your setup

**Comment by SevenSinS02** [comment]
Ok. This was a silly mistake on my part. I specified the wrong port.
Apologies for raising a false alarm.
Thanks for the great repo!

**Comment by SevenSinS02** [comment]
Hi @amilajack ! 
I am getting  `Loading PDF as base64 strings/URLs might not work on protocols other than HTTP/HTTPS` when trying to load an external URL of a PDF file. I am using the `react-pdf` library which won't load the file over any other protocol other than the HTTP/HTTPS due to security reasons. 
How can I force the file to load over HTTP. Also, I do not see any network request for the file and I've double checked the location of the resource just to be sure.

**Comment by amilajack** [comment]
Share the stacktrace here

**Comment by SevenSinS02** [comment]
Here is the stacktrace.

```
Loading PDF as base64 strings/URLs might not work on protocols other than HTTP/HTTPS. On Google Chrome, you can use --allow-file-access-from-files flag for debugging purposes.
consoleOnDev @ utils.js:168
warnOnDev @ utils.js:177
displayCORSWarning @ utils.js:191
(anonymous) @ Document.js:161
F @ _export.js:36
Document._this.findDocumentSource @ Document.js:149
loadDocument @ Document.js:312
loadDocument @ react-hot-loader.development.js:580
componentDidMount @ Document.js:231
componentDidMount @ react-hot-loader.development.js:570
commitLifeCycles @ react-dom.development.js:14361
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
interactiveUpdates$1 @ react-dom.development.js:16719
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
```

**Comment by SevenSinS02** [comment]
@amilajack so I get an error :  '`ReferenceError: window is not defined`'.
It also points to the two lines below
`var parentHotUpdateCallback = window["webpackHotUpdate"]; `  at bootstrap:1

`return hotCreateRequire("./node_modules/pdfjs-dist/build/pdf.worker.js")(__webpack_require__.s = "./node_modules/pdfjs-dist/build/pdf.worker.js");` at bootstrap:788

Any ideas on how to fix it?

**Comment by amilajack** [comment]
How are you getting `react-pdf` to load an external url

**Comment by amilajack** [comment]
Try this example https://github.com/amilajack/erb-pdf-example

**Comment by SevenSinS02** [comment]
@amilajack thanks for the example. It does work when importing directly from `react-pdf`. However, this would cause performance issue and hence the library author suggests importing like so to have the rendering done off the main thread:
`import { Document } from 'react-pdf/dist/entry.webpack';`

> Enable PDF.js worker
> It is crucial for performance to use PDF.js worker whenever possible. This ensures that PDF files will be rendered in a separate thread without affecting page performance. To make things a little easier, we've prepared several entry points you can use.
> 
> Webpack
> Instead of directly importing/requiring 'react-pdf', import it like so:
> 
> import { Document } from 'react-pdf/dist/entry.webpack';

This is where the `window is not defined `error pops up and the pdf isn't rendered.

**Comment by amilajack** [comment]
This is an issue with the library and webpack. Not related to the boilerplate. See https://github.com/webpack/webpack/issues/6642

**Comment by SevenSinS02** [comment]
Thanks for your time!
