### ISSUE TITLE
yarn package fails on codesign command

### ISSUE THREAD

**Issue by juliend2** [chentsulin/electron-react-boilerplate#1829]
## Prerequisites
- [x] Using yarn
- [x] Using an up-to-date master branch
- [x] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

It should generate a macOS package of the default boilerplate app.

## Current Behavior

* it fails with the following log : https://gist.github.com/juliend2/dcae6838c93be6355698c1b8bea4bdad

## Steps to Reproduce (for bugs)
1. Using the freshly cloned repo.
1. I do `yarn package`, expecting to have a (macOS) package of the app.

Here is the exact `history` of what I did:

```
git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git statusmachine-desktop
cd statusmachine-desktop/
yarn
yarn dev
yarn package
```

## Context
I'm trying to get started with electron.
I did nothing to the boilerplate after cloning it. No modification.

## Your Environment

* Version or Branch used : master, v0.16.0
* Operating System and version : macOS 10.14
* Link to your project : N/A

**Comment by amilajack** [comment]
Followed the exact same commands and I cannot reproduce this. Try this:
```bash
yarn cache clean
rm -rf node_modules
npm i -g yarn@latest
yarn
yarn test-all
```

**Comment by juliend2** [comment]
@amilajack It works now! And all the tests are passing.

I don't know why. Thanks!
