### ISSUE TITLE
How to import file from absolute path

### ISSUE THREAD

**Issue by tiennguyen9988** [chentsulin/electron-react-boilerplate#1836]
How to import file from absolute path the same:
`import mfile from '/appname/app/mfile.js'` or `import mfile from '/app/mfile.js'`
Thank you!

**Comment by amilajack** [comment]
Don't import from absolute path. Import from relative. This is more of a question with node rather than a question with the boilerplate so i'm going to close this. Feel free to ask more questions if you have any
