### ISSUE TITLE
Error when run: yarn package

### ISSUE THREAD

**Issue by tiennguyen9988** [chentsulin/electron-react-boilerplate#1837]
I have an error at file Routes.js when build product version (yarn package)! What is wrong? 
![1](https://user-images.githubusercontent.com/3782474/46591619-1c3f4f00-cae6-11e8-8e3f-81df8f3c2647.png)
![2](https://user-images.githubusercontent.com/3782474/46591620-1cd7e580-cae6-11e8-97bd-7f11a383ec5a.png)
Thanks you!

**Comment by vikr01** [comment]
Please resubmit your issue using [the issue template](https://github.com/chentsulin/electron-react-boilerplate/blob/master/.github/ISSUE_TEMPLATE.md) so we can better understand your issue, thanks.
