### ISSUE TITLE
question about folder structure of large applications

### ISSUE THREAD

**Issue by thisconnect** [chentsulin/electron-react-boilerplate#187]
Hi, there is some discussion going on about how to organize big react/redux projects. As projects grow reducer, actions, components, containers, tests are spread over different directories. IMO This is fine for reusable components.

I would love to hear your personal views and experiences on larger projects and your thoughts on additionally structure files by modules. For example if electron-react-boilerplate would add a Todo page and 5 or 10 other examples pages.

What is your personal opinion on keeping reducer, actions, components, containers, tests together in a directory per page file structure?
(see screenshot)

![screen shot 2016-03-25 at 10 16 14 am](https://cloud.githubusercontent.com/assets/546900/14041595/d064551a-f272-11e5-81bc-85bf931a984b.png)

**Comment by chentsulin** [comment]
IMO, Every approach has it's pros and cons. In some case, actions and reducers will be used by multiple containers, so I don't want to put them together. 

Here's my preference on larger projects:

```
src/
  actions/
    __tests__/
    todo.js
  components/
    Todo/
      __tests__/
      index.js
      TodoItem.js
      TodoItem.css
  containers/
    __tests__/
    TodoPage.js
  reducers/
    __tests__/
    index.js
    todo.js
```

Reusing components is enough for me. If you want to keep container reusable, I think Relay is a more suitable choice in future.

**Comment by chentsulin** [comment]
@thisconnect You can see redux FAQ to find others' discussion on code-structure: https://github.com/reactjs/redux/blob/master/docs/FAQ.md#code-structure
