### ISSUE TITLE
request electron be in PATH instead of making mac-specific paths

### ISSUE THREAD

**Issue by seiyria** [chentsulin/electron-react-boilerplate#19]
Not everyone devs in a mac all the time; a fix is as simple as changing the package.json like so:

```
"start": "electron .",
"start-dev": "NODE_ENV=development electron .",
"start-hot": "HOT=1 NODE_ENV=development electron .",
```

**Comment by chentsulin** [comment]
I will fix this soon, and add a notice about env variable to the README. thanks!

**Comment by rahatarmanahmed** [comment]
Can you not put electron in your dev dependencies?

**Comment by rahatarmanahmed** [comment]
Scratch that, realized electron-prebuilt already registers a binary with npm under "electron", so you don't even need it in your PATH. It should work fine regardless.
