### ISSUE TITLE
[question] How to keep the boilerplate updated, but change the app files?

### ISSUE THREAD

**Issue by yayolius** [chentsulin/electron-react-boilerplate#199]
I really liked your project, but the problem is that if i forked it, or create a new project with the current version of the repository i will lose any updates of the rest of the files.
There is a way to keep this updated even if i change all the files inside app?
Thanks
Claudio

**Comment by chentsulin** [comment]
If your application is a fork from this repo, you can add this repo to another git remote:

```sh
git remote add upstream https://github.com/chentsulin/electron-react-boilerplate.git
```

Then, use git to merge some latest commits:

```sh
git pull upstream master
```

**Comment by yayolius** [comment]
Thanks men

**Comment by barbalex** [comment]
wow. you should add this in the readme
