### ISSUE TITLE
Big blob files in git history

### ISSUE THREAD

**Issue by seiyria** [chentsulin/electron-react-boilerplate#20]
When cloning this boilerplate and pushing it to Github, I first got a warning about big files. I investigated a bit further and found some files in your git history which should probably be pruned:

![](http://i.imgur.com/CPqvZVd.png)

It's as simple as using [this tool](https://rtyley.github.io/bfg-repo-cleaner/#usage) to clean the nasty big files out of your history, which would be friendlier for people to use (and a bit faster to clone/push, too).

**Comment by chentsulin** [comment]
Done. Now it's just little more than 200KB .Thanks for sharing a useful tool ! :+1:
