### ISSUE TITLE
How do i dispatch a router action from a component

### ISSUE THREAD

**Issue by yayolius** [chentsulin/electron-react-boilerplate#202]
Hello, i have been strugling to call a route programaticly without Link, but i don't know how to get the global store, in order to dispatch an event for the router like it says in this link:
https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions

Sorry to have so many questions, i am loving this boilerplate but because there is no documentation i am triying to figurate a lot of things

Best Regards
Claudio

**Comment by jhen0409** [comment]
You can use `dispatch` of connected component, add `push` action to `mapDispatchToProps `:
```js
import { push } from 'react-router-redux';  // import
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import Counter from '../components/Counter';
import * as CounterActions from '../actions/counter';

function mapStateToProps(state) {
  return {
    counter: state.counter
  };
}

function mapDispatchToProps(dispatch) {
  // Add following code
  return {
    counter: bindActionCreators(CounterActions, dispatch),
    push: bindActionCreators(push, dispatch)
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(Counter);
```

Then use `this.props.push` in connected component.

**Comment by chentsulin** [comment]
Thanks for @jhen0409 's tip! 
Nothing different between a web application and a electron application to dispatch a router action here, so please consult documentation at react-redux and react-redux-router repo.

**Comment by tsuz** [comment]
Thanks! @jhen0409
