### ISSUE TITLE
require electron in test (proposed solution)

### ISSUE THREAD

**Issue by piti118** [chentsulin/electron-react-boilerplate#204]
similar to #156 

I workaround this by adding module alias to babel.
```
npm install --save babel-plugin-module-alias
```

May be this should be the default in repo?

```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["add-module-exports"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    },
    "test": {
      "plugins": [
        ["webpack-loaders", { "config": "webpack.config.node.js", "verbose": true }],
        ["babel-plugin-module-alias", [
          { "src": "node_modules/electron-prebuilt" , "expose": "electron" }
        ]]
      ]
    }
  }
}
```

**Comment by GabeIsman** [comment]
@piti118 Thanks for posting this! Was really helpful to me in solving the same problem. However, just linking to `electron-prebuilt` wasn't good enough to get my code to run (it seems as though `import electron-prebuilt` actually just evaluates to the path of the electron binary). I made a simple fake electron object and aliased it in the same way. Would be nice if there were a proper mock-electron object so you could actually make assertions about the calls being made. A project for another day...

**Comment by GabeIsman** [comment]
For reference, this is my complete-enough-for-my-purposes electron fake:
```
import { spy } from 'sinon';

// This is intended as a very dumb/simple mock. Not suitable for much real
// testing of interactions with electron, it is reasonably suitable for
// preventing module not found errors though. This gets rewired to electron in
// .babelrc.
export default {
  remote: {
    require: () => {},
    dialog: {
      showOpenDialog: spy(),
      showSaveDialog: spy()
    }
  }
};
```

**Comment by amilajack** [comment]
This was fixed
