### ISSUE TITLE
remote.require for local modules no longer works in release

### ISSUE THREAD

**Issue by domasx2** [chentsulin/electron-react-boilerplate#205]
Hi,

Let's say I have `main.development.js` and `logging.js`, both in ES6. `logging` exposes a logger instance that I want to use from main proc AND from multiple renderers. 

However  `remote.require('./logging')` from renderer does not work due to `main.development.js` being webpacked into a single file including `logging.js`, while `remote.require` tries to load the original file.

I can work around this by exposing needed modules as globals in main proc and then using `remote.getGlobal('somemodule')` in the renderer.

However, because of this, I feel that perhaps babelifying main process sources without webpacking them into a single file would make more sense for electron

**Comment by chentsulin** [comment]
What if we use `webpack-node-externals` to make all of node modules as external? @jhen0409 What do you think?

**Comment by domasx2** [comment]
that's probably a good idea, but won't solve the issue I had

**Comment by jhen0409** [comment]
Looks `remote.require('./logging.js')` is still looking for an external file, but it doesn't apply to babel syntax in production.

**Comment by bgrayburn** [comment]
any update on this? facing the same thing. is there a way to filter out the `remote.require`s? electron should take care of it on it's own right? sorry I'm a webpack noob

**Comment by edsu** [comment]
I'm seeing the same thing, and am similarly confused. If anyone has any advice I would be most grateful!

**Comment by amilajack** [comment]
> electron should take care of it on it's own right?

@bgrayburn it doesnt. https://github.com/electron/electron/blob/master/docs/api/remote.md#remote-objects

**Comment by amilajack** [comment]
Closing, as I think this was resolved.

**Comment by DominikGuzei** [comment]
Facing the same issue, @amilajack where was this resolved? i don't see any solution posted here.

**Comment by evoye** [comment]
The resolution is specified in the documentation:
"Modules specified by their relative path will resolve relative to the entrypoint of the main process."

In the case in question try to specify a relative path based on main.development.js or the destination file produced by webpack

**Comment by jsyzqt** [comment]
@evoye But this resolution need to use `webpack-node-externals` to make all of `node modules` as external, just as @chentsulin said. But I hope that the `modules` can also be webpacked into a single file. Are there any solutions?
