### ISSUE TITLE
Trying to deploy to a Raspberry Pi3 through Resin.io

### ISSUE THREAD

**Issue by erichardson30** [chentsulin/electron-react-boilerplate#210]
I created an electron application based on this starter project. It is running fine locally. I am trying to deploy it through Resin.io so my raspberry pi3 can pick it up and run it. The error I am currently getting is : 
`
/app/node_modules/fbjs-scripts/node/check-dev-engines.js:31
if (devEngines.node !== undefined) {
              ^

TypeError: Cannot read property 'node' of undefined
    at Object.<anonymous> (/app/node_modules/fbjs-scripts/node/check-dev-engines.js:31:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Linux 4.2.2-coreos-r2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--prefix" "/app"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.10.0 postinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
Removing intermediate container 424b9d205d9c
       Error while processing push: Error: The command '/bin/sh -c npm i --prefix /app' returned a non-zero code: 1
`

And my dockerfile.template looks like : 
`FROM resin/%%RESIN_MACHINE_NAME%%-node:latest

ENV INITSYSTEM on

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -yq --no-install-recommends \
    xserver-xorg-core \
    xorg \
    libgtk2.0-0 \
    libnotify4 \
    libgconf2-4 \
    libnss3 \
    libasound2 \
    matchbox && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN npm config set unsafe-perm true

COPY ./package.json ./app/

#WORKDIR /usr/src/app

RUN npm i --prefix /app

COPY . ./app

RUN npm run build
RUN npm start`

**Comment by jhen0409** [comment]
Are you removed `devEngines` from `package.json`?

**Comment by erichardson30** [comment]
@jhen0409 the package.json is exactly the same. For scripts it still has : 

"scripts": {
    "test": "cross-env NODE_ENV=test mocha --compilers js:babel-register --recursive --require ./test/setup.js test/**/*.spec.js",
    "test-watch": "npm test -- --watch",
    "test-e2e": "cross-env NODE_ENV=test mocha --compilers js:babel-register --require ./test/setup.js --require co-mocha ./test/e2e.js",
    "lint": "eslint app test *.js",
    "hot-server": "node -r babel-register server.js",
    "build-main": "cross-env NODE_ENV=production node -r babel-register ./node_modules/.bin/webpack --config webpack.config.electron.js --progress --profile --colors",
    "build-renderer": "cross-env NODE_ENV=production node -r babel-register ./node_modules/.bin/webpack --config webpack.config.production.js --progress --profile --colors",
    "build": "npm run build-main && npm run build-renderer",
    "start": "cross-env NODE_ENV=production electron ./",
    "start-hot": "cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development",
    "package": "cross-env NODE_ENV=production node -r babel-register package.js",
    "package-all": "npm run package -- --all",
    "postinstall": "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json",
    "dev": "concurrently --kill-others \"npm run hot-server\" \"npm run start-hot\""
  },

**Comment by chentsulin** [comment]
It just use for checking your node version >= 4 (If any user use node version <= 3, they will get a SyntaxError when running app). We define `devEngines` in the `package.json`, so devEngines be `undefined` is unexpected behavior...
https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L110

**Comment by erichardson30** [comment]
@chentsulin Thanks, I ended up just removing it and it was fine

**Comment by erichardson30** [comment]
@chentsulin do you know how to go about running this on a raspberry pi?
