### ISSUE TITLE
"npm run build" and "npm run package" fail on Win 10

### ISSUE THREAD

**Issue by will-hart** [chentsulin/electron-react-boilerplate#211]
Hi, 
I'm using node 5.11.0 and npm 3.5.0 on Windows 10. I'm also using [cmder](http://cmder.net/) with bundled git-for-windows. 

I can `npm run dev` with no issues, however when I run `npm run package` I get a blank application built. Running `npm run build` throws an error:

```bash
λ npm run build

> test-application@0.1.0 build D:\Code\test-application
> npm run build-main && npm run build-renderer


> test-application@0.1.0 build-main D:\Code\test-application
> cross-env NODE_ENV=production node -r babel-register ./node_modules/.bin/webpack --config webpack.config.electron.js --progress --profile --colors

D:\Code\test-application\node_modules\.bin\webpack:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Code\test-application\node_modules\babel-register\lib\node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

Looking at other sources, this is probably a windows specific error, i.e. https://github.com/iam4x/isomorphic-flux-boilerplate/issues/157. I've tried a few of the things suggested in that issue however it looks like this boilerplate is already following this pattern.

I've previously had builds working ok with this boilerplate in a similar build environment, but an older version of the boilerplate. Looking at the `package.json` the working version doesn't use `babel-register`, i.e. 

    "build": "cross-env NODE_ENV=production webpack --config ..."

worked, but now

    "build-main": "cross-env NODE_ENV=production node-r babel-register ./node_modules/.bin/webpack --config ..."

Fails

Any thoughts?

**Comment by benalexb** [comment]
+1
Same problem here :/

**Comment by will-hart** [comment]
Ah great, that fixed it. I tried something similar but forgot to remove the `.` in front of `bin`! Cheers
