### ISSUE TITLE
How built the guest page project use electron ipc?

### ISSUE THREAD

**Issue by artkynet** [chentsulin/electron-react-boilerplate#213]
I have a react + redux project on outside server, I want to use the <webview> tag show it, How can I use ipc.send('name', args) in this guest page to connect electron app project?

**Comment by hardchor** [comment]
@artkynet I'd previously had the same issue. I've solved it by writing an "App Bridge" that exposed certain functions I'd wanted my embedded web app to have access to. The app bridge got [`preload`ed](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) and attached itself to the global namespace (`window`) for easy consumption.

**Comment by amilajack** [comment]
Closing due to no response
