### ISSUE TITLE
redirect to front page

### ISSUE THREAD

**Issue by onelson** [chentsulin/electron-react-boilerplate#218]
I have an idiot question since I'm not that familiar with electron and express, but here goes.

My express app has some routes for handling oauth flow. Once the oauth provider redirects back to my express app, I want to redirect back to the react app, but I'm having trouble figuring out what the route is for this.

Any clues?

**Comment by jhen0409** [comment]
You can go to find how to register URI Scheme for the application, such as Custom URL Scheme in `Info.plist` for OSX. (e.g. [Atom usage](https://github.com/atom/atom/commit/753b11cf15b7302efd5cd8884f107478f53f48d6))

**Comment by onelson** [comment]
OK thanks.

**Comment by onelson** [comment]
So, I found the spot where the electron browser window loads the html file. Turns out the disconnect was the fact that the initial content is being loaded via `file://` and I was expecting `http://`. I added a route for `/` which responds with the `app.html` to the express app, and that _mostly_ works.
