### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by sam-jay** [chentsulin/electron-react-boilerplate#222]
Cloned the repo, npm installed and executed npm run dev.

A window shows up but the app does not run.

Console in the window says: "bundle.js:1 Uncaught SyntaxError: Unexpected token <"

Electron version: 1.1.0
Node version: 5.9.0

**Comment by hepiyellow** [comment]
I got the same issue with Electron 1.2.7
How did you resolve this?

**Comment by amilajack** [comment]
@hepiyellow node and npm version?

**Comment by gammons** [comment]
I had this issue as well.  After trying all sorts of things, I rebooted my laptop and that fixed the issue.

**Comment by LarryMckuydee** [comment]
Check in your **webpack.config.js** to see if your **output.publicPath** or **devServer.publicPath** URL address is being use by other application.

Example: 
`
output: {
    path: '/public/built',
    filename: 'bundle.js',
    publicPath: 'http://localhost:8080/built'
}
`

and there is Application X running in http://localhost:8080

**Comment by hepiyellow** [comment]
@amilajack 
```
$ node --version
v6.3.0
$ npm --version
3.10.9
```

**Comment by amilajack** [comment]
Try testing this against the latest version of the boilerplate. There were a number of fixes recently
