### ISSUE TITLE
enable debug output in browser

### ISSUE THREAD

**Issue by 0x80** [chentsulin/electron-react-boilerplate#23]
Hi,

Have you managed to get debug output in the browser? I somehow can't get it to work.

I've tried ```window.myDebug = require('debug')```. Afaik this should allow me to enable the debug output from the browser console. 

I've also tried to set it directly from code ```window.myDebug.enable('*')``` and via ```localStorage.debug="*"```

**Comment by chentsulin** [comment]
I guess this is a issue between node and browser. Electron will use `main` field in package.json (or index.js) as entry.

https://github.com/atom/electron/issues/1574

But I have not figured out the root cause.

**Comment by 0x80** [comment]
Aha thanks. I guess as a workaround I could fork the debug repo and make a version which always assumes it's a browser environment, and then include that module from the browser code.

**Comment by 0x80** [comment]
I'm closing this since it's an Electron compatibility issue
