### ISSUE TITLE
how to release exe for windows platform

### ISSUE THREAD

**Issue by artkynet** [chentsulin/electron-react-boilerplate#230]
I use this project to build my windows native app, now I wanna release the exe program for windows 32 platform, please help me.

**Comment by amilajack** [comment]
You need to run:
```
npm run package-all
```
If you are on linux or mac, you will need to install [wine](https://www.winehq.org/)

**Comment by chentsulin** [comment]
Please consult package section in Readme:
https://github.com/chentsulin/electron-react-boilerplate#package

**Comment by artkynet** [comment]
thanks guys
