### ISSUE TITLE
`npm run package` takes forever and exhaust memory

### ISSUE THREAD

**Issue by KenetJervet** [chentsulin/electron-react-boilerplate#231]
I'm running Gentoo. I did `npm install` and `npm run package`. It's stuck at "Packaging app for platform linux x64 using electron v1.2.0" message and never proceeds.

I waited for like half an hour, until it ate up all my remaining ~8GB free memory.

I'm new to node and electron. I think it's relavent to babel-register.

**Comment by chentsulin** [comment]
It's hard to dive into this if we don't have more detail information. Could you build app on your os normally using this boilerplate?
https://github.com/sindresorhus/electron-boilerplate

**Comment by chentsulin** [comment]
Close this for now, unless we have a approach to reproduce.

**Comment by KenetJervet** [comment]
@chentsulin Hi. Eventually this is an issue with cnpm (https://github.com/cnpm/cnpm). I have network issues in China so I installed the packages using this tool. It appears that this tool is buggy and sometimes it doesn't install packages properly.

Thanks for your time.
