### ISSUE TITLE
Is there any way in using electron.app from react?

### ISSUE THREAD

**Issue by szebrowski** [chentsulin/electron-react-boilerplate#237]
I would like to use app.getPath('userData') from react. Is there any way to do it? Simply importing it, doesnt work.

**Comment by jhen0409** [comment]
Because `app` is only work in main process, in renderer process use `require('electron').remote.app.getPath('userData')` instead.

**Comment by chentsulin** [comment]
Thanks for the tips from @jhen0409. @szebrowski Official docs will help you further -https://github.com/electron/electron/blob/master/docs/api/remote.md

**Comment by szebrowski** [comment]
thanks for the help :)
