### ISSUE TITLE
[Proposal] react-intl

### ISSUE THREAD

**Issue by madc** [chentsulin/electron-react-boilerplate#239]
I'm working on a project, which is in part based on this very boilerplate and we successfully integrated [react-intl](https://github.com/yahoo/react-intl). That allows us to easily translate the content of the app.

If it is appreciated, I'd offer to create a PR.

**Comment by chentsulin** [comment]
To avoid excessive complexity, I'd like to see this feature be implemented in another repo, and I will link it from the readme.

**Comment by docoder** [comment]
where is it ?

**Comment by madc** [comment]
I never started a new repo, as I do not have the resources to maintain it properly. But you should be able to easily implement [react-intl-redux](https://github.com/ratson/react-intl-redux).
