### ISSUE TITLE
Error when running package under Windows

### ISSUE THREAD

**Issue by chris-me** [chentsulin/electron-react-boilerplate#240]
when trying to run the packaged .exe on windows, it always throws the error:

![screenshot](https://cloud.githubusercontent.com/assets/3713630/15920217/5db5a73a-2e18-11e6-85ac-4f942f443c85.JPG)

I am using Windows 10, node 5.11.1 and performed the following steps:

* clone the Repo
* npm install
* npm run dev (works well)
* npm run package (runs with no erros as well)
* But executing the resulting ElectronReact.exe always produces the error statet above

Am I missing something here?

**Comment by amilajack** [comment]
Possibly a webpack issue

**Comment by jhen0409** [comment]
I've tested on Windows 10, there is no such problem. Could you list `release/win32-x64/ElectronReact-win32-x64/resources/app/node_modules`?

**Comment by chris-me** [comment]
Of course, the build command:
```
C:\daten\code\electron-react-boilerplate>npm run package

> electron-react-boilerplate@0.10.0 package C:\daten\code\electron-react-boilerplate
> cross-env NODE_ENV=production node -r babel-register package.js

start pack...
Packaging app for platform win32 x64 using electron v1.2.2
win32-x64 finished!
```

The node_modules directory afterwards:
```
C:\daten\code\electron-react-boilerplate>dir release\win32-x64\ElectronReact-win32-x64\resources\app\node_modules
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: BEDC-4FDF

 Verzeichnis von C:\daten\code\electron-react-boilerplate\release\win32-x64\ElectronReact-win32-x64\resources\app\node_modules

12.06.2016  10:38    <DIR>          .
12.06.2016  10:38    <DIR>          ..
12.06.2016  10:38    <DIR>          font-awesome
12.06.2016  10:38    <DIR>          source-map
12.06.2016  10:38    <DIR>          source-map-support
```

**Comment by amilajack** [comment]
This should work without errors. Reference the [appveyor build](https://ci.appveyor.com/project/chentsulin/electron-react-boilerplate/branch/master).

**Comment by amilajack** [comment]
@chris-me are you still experiencing issues or did you solve it?

**Comment by chris-me** [comment]
Yes it works now, thank you!
