### ISSUE TITLE
Dev Webpack Issue

### ISSUE THREAD

**Issue by travisgalloway** [chentsulin/electron-react-boilerplate#241]
Webpack is having an issue bundling to /dist when running in development. The bundle indicates valid, but doesn't generate a bundle.js in the /dist directory. Running package will still generate the bundle. I'm thinking it might be an issue with the development dependencies.

Thoughts?

**Comment by chentsulin** [comment]
`webpack-dev-middleware` doesn't actual create a file to `/dist`, but it put bundled result into memory and serve at `http://localhost:3000/dist/bundle.js`.

**Comment by travisgalloway** [comment]
Got it. I misread the configs. Thanks.
