### ISSUE TITLE
`.node` native modules not working in packaged app

### ISSUE THREAD

**Issue by henryboldi** [chentsulin/electron-react-boilerplate#242]
I'm getting this error in the built app
`keytar.js:4Uncaught Error: Cannot find module "../build/Release/keytar.node"`

However, the built `keytar.node` file looks like it's in the correct location. It seems to me that it's not loading because of the file extension.

Works perfectly fine in the dev environment though. Any ideas on why this is happening?

**Comment by amilajack** [comment]
What version of node are you using?

**Comment by henryboldi** [comment]
v5.4.0

**Comment by amilajack** [comment]
I would try:
```javascript
npm cache clean && npm prune && npm rebuild
```

This is what I always do when bindings aren't working correctly

**Comment by henryboldi** [comment]
I think that fixed it. ❤️

**Comment by amilajack** [comment]
(also plz close the issue)

**Comment by amilajack** [comment]
Should we close this issue now?
