### ISSUE TITLE
"npm run package" includes the source directory

### ISSUE THREAD

**Issue by itsjimbo** [chentsulin/electron-react-boilerplate#243]
Within the package.js file the default ops specify dir to be "./", should this not be changed to "dist" or something similar?
I end up with a package that contains the directory structure
```
release/darwin-x64/react-boilerplate-darwin-x64/react-boilerplate.app/Contents/Resources/app/app
```
The first app directory contains the entire source, and the subdirectory app contains the bundled files.  I am new with webpack, so maybe this is how you bundle apps.

Thanks

```
const DEFAULT_OPTS = {
  dir: './',
  name: appName,
  asar: shouldUseAsar,
  ignore: [
    '^/test($|/)',
    '^/tools($|/)',
    '^/release($|/)',
    '^/main.development.js'
  ].concat(devDeps.map(name => `/node_modules/${name}($|/)`))
  .concat(
    deps.filter(name => !electronCfg.externals.includes(name))
      .map(name => `/node_modules/${name}($|/)`)
  )
};

```

**Comment by itsjimbo** [comment]
I think i understand what is going on, the first app is for the main process, and the second is for the renderer, and you can exclude files with the ignore property in the package.js

**Comment by amilajack** [comment]
@chentsulin I think this should be closed.
