### ISSUE TITLE
webpack.DefinePlugin rewrites process.env object

### ISSUE THREAD

**Issue by sergeybekrin** [chentsulin/electron-react-boilerplate#244]
If [using DefinePlugin](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.production.js#L47-L49) for setting `NODE_ENV` property for `process.env`, OS X will result loosing all original `process.env.*` properties in built executable, so most API from `child_process` won't work without `PATH`.

This is extremely hard to debug.

My suggestions are:
- Use `__DEV__` variable instead of `process.env.NODE_ENV`;
- Explicitly set `process.env.NODE_ENV = __DEV__ ? 'development' : 'production';` on top of render process (but probably loose all pre-built optimizations).

Any ideas?

*Update*: Found the easiest solution. See this PR: #245

**Comment by chentsulin** [comment]
Closed via #245
