### ISSUE TITLE
How to include other files into Contents/Resources/ ?

### ISSUE THREAD

**Issue by crucialfelix** [chentsulin/electron-react-boilerplate#252]
Not everything can or should be included with require() and webpack loaders.

My application has directories of .csv and .json datasets and precompiled executables (supercollider sound application) and synthdef files for that.

Previously with electron-react-boilerplate everything was copied into Resources so the assets were there. 

Of course the whole of app and node_modules were there so the apps were too large to ship.

Now the app is bundled in an asar (which is great ! nice and small !), but now I can't figure out how one should copy specific files to Resources.

```
Error: Error: ENOENT, app/synthdefs not found in /Users/crucial/code/idmx/playsplom/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar
    at SoundApp.js:73:17
```

Or if I should be copying these files into the asar. (Executables as well ?)

I've tried this:

```
  externals: [
    './app/synthdefs',
    './app/vendor'
    // put your node 3rd party libraries which can't be built with webpack here
    // (mysql, mongodb, and so on..)
  ]
```

I've tried CopyWebpackPlugin too but it doesn't copy anything. I thought the context would be set and they would end up in the asar.

**Comment by amilajack** [comment]
What you should do is include that kind of content inside of the `app` directory (if you dont want to use webpack for this).

**Comment by Haraldson** [comment]
I think I have a similar problem. I don’t really understand Webpack really well, and [I’ve tried to explain my problem over at StackOverflow](http://stackoverflow.com/questions/39868187/unable-to-bundle-pack-node-binary-code). Basically I have webchimera stuff (precompiled VLC player for Electron) that needs to be included in the packaged app, but not through any archive as that would mangle it somehow.

Copying the modules to `.app/Contents/Resources/app/node_modules` is the only way to get them to resolve, but then their dependencies are missing somehow, as explained over at SO. Do you have any more insight to share, @amilajack? :)

**Comment by amilajack** [comment]
@Haraldson This is [my solution](https://github.com/amilajack/popcorn-time-desktop/blob/master/postinstall.js).

**Comment by Haraldson** [comment]
Thanks for taking the time to reply and point me in the right direction – I’ll have a look and see if I can use the same stack as you – as long as there’s RTMP support it looks promising.
