### ISSUE TITLE
failed to package with sequelize in production

### ISSUE THREAD

**Issue by eaTong** [chentsulin/electron-react-boilerplate#257]
I try to use electron in my project , everything works well when I run `npm run dev` ,but when I try to package it ,something get wrong.
I put sequelize connection info into file` dbUtil.js`, see the code:
`export const Sequelize = require('sequelize');`
`export const sequelize = new Sequelize(database, username, password).....`
and when I run the packaged file , it calls `Uncaught Error: Cannot find module "../dbUtil"` exception.
I guess that`s because I had put 'mysql' and 'sequelize' in externals,and when I package the app , It will ignore these files , but I can`t find any way to solve this problem .

Another question:
Is there any plan to add persistence part(such as mysql or mongodb and so on) in this boilerplate?

**Comment by eaTong** [comment]
In fact I have thinking about if this way is safety , put database config in product ,and maybe any can see the source .
Maybe a better way to solve my question is build a background service and my application just need to call service API , just like a website.But here is the question:if I use electron like a browser , why don`t I just use a browser?

**Comment by jhen0409** [comment]
> and when I run the packaged file , it calls Uncaught Error: Cannot find module "../dbUtil" exception.

This error is thrown on runtime? Not any error logs at webpack build?

**Comment by eaTong** [comment]
yes it's thrown on runtime , there is no any error when package

**Comment by eaTong** [comment]
Maybe my issue should be close because finally I found I'm considering wrong way.I have read the docs and knows that there is another way to save to mysql..
The doc says electron has two progress and I never should run sequelize in my browser progress , I should run it in main progress instead ,so I solve this problem like this:
I created a new folder called "server" and I will run all my background code here.

**Comment by dbvrac** [comment]
Is there a set of guidelines somewhere on how to do this properly with the current erb?

**Comment by amilajack** [comment]
[Here is an example ](https://github.com/amilajack/erb-sqlite-example) of packaging sqlite

**Comment by dbvrac** [comment]
I should clarify. My project uses express and a postgres client based on this project: https://github.com/waiyaki/postgres-express-node-tutorial
...to communicate with a postgres server on AWS. I've also looked at your erb-express-example and attempted a few hybrid solutions, some of which work with `npm run dev` but do not work when I package it as a desktop application. Perhaps I've simply not landed on the right combination of installed items in package.json deps, devdeps, and app/package.json deps. Out of respect for your time and expertise, I'm willing to make a donation.

**Comment by amilajack** [comment]
Can you point me to the solutions that you attempted. I can PR to them and fix them

**Comment by dbvrac** [comment]
I'd like that, but I'm not sure I can. It's a private repo because: A) My code is a mess. B) Unpublished research. C) Security issues. D) My code is really a mess. I've been working with a clone of ERB from April (not a fork) and I don't know how to bring it up to date. Maybe before I take you up on your generous offer I should nuke it and start fresh with a new version of ERB.
