### ISSUE TITLE
Include external global css

### ISSUE THREAD

**Issue by juliuszc** [chentsulin/electron-react-boilerplate#260]
Hello,

I was just wondering how I should go about including an external css file that I want to be used everywhere like bootstrap. Should I just not use the bootstrap node-module and download it directly, adding the .global to the end? I'm sure there is a much better way to do this, but I don't know enough about webpack to mess with the config.

Thanks,
Juliusz

**Comment by codeofsumit** [comment]
@LitleCarl because that is a hacky solution as well tbh. If you use bootstrap, normalize.css, fontawesome or any other CSS library/framework you'd want it used just as your other dependencies and easily updateable via npm (webpack, or bower, whatever)

**Comment by TomCaserta** [comment]
Just put it in the app.html file like a normal <link tag. I dont see why you'd need to pass it through anything.

**Comment by amilajack** [comment]
Seems like @juliuszc is unresponsive. There solutions to this issue above should work. This issue should be closed.
