### ISSUE TITLE
For consideration: easy-webpack

### ISSUE THREAD

**Issue by niieani** [chentsulin/electron-react-boilerplate#267]
I'm the author of [Easy Webpack](https://github.com/easy-webpack/core), which is now used as the default configurator by the official Webpack starter kit for the Aurelia Framework. 
If you like the concept, it could be used to clean-up the Webpack config files used by the Electron React Boilerplate and possibly delegate parts of the config to a separate package that could be npm updated by the users. Feel free to consult [the docs](https://github.com/easy-webpack/core) and decide on your own if this is something you would be interested in using.
Additionally, using babel-register for the reason of the object expansion wouldn't be necessary because of the way `generateConfig` works, which could shave off a second or two of the initial start time caused by Babel kicking in.

Awesome starter kit, btw! 👍

**Comment by chentsulin** [comment]
Personally, I want person can quick start without learning some more modules, so we will not introduce this, but thanks for your suggestion!
