### ISSUE TITLE
[question] Is warning `Failed to fetch extension` normal?

### ISSUE THREAD

**Issue by creeperyang** [chentsulin/electron-react-boilerplate#268]
When I run `npm run start-hot`:

```bash
> electron-react-boilerplate@0.10.0 start-hot /Users/creeper/work/projects/yhost
> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development

Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 0 more times
Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 0 more times
```

And after a while, the window finally shows. So is the behavior normal?

**Comment by jhen0409** [comment]
These fails is from [electron-devtools-installer](https://github.com/GPMDP/electron-devtools-installer/blob/master/src/downloadChromeExtension.js#L17), it mean you cannot connect to Chrome Store?

**Comment by creeperyang** [comment]
Get it. Thanks for your reply.

**Comment by webkonglong** [comment]
i install electron-devtools-installer still like this, the startup project is slow.

`quotationChart git:(master) ✗ npm install electron-devtools-installer --save-dev -g
/usr/local/lib
└─┬ electron-devtools-installer@2.2.1 
  ├── 7zip@0.0.6 
  ├── cross-unzip@0.0.2 
  ├─┬ rimraf@2.6.2 
  │ └─┬ glob@7.1.2 
  │   ├── fs.realpath@1.0.0 
  │   ├─┬ inflight@1.0.6 
  │   │ └── wrappy@1.0.2 
  │   ├── inherits@2.0.3 
  │   ├─┬ minimatch@3.0.4 
  │   │ └─┬ brace-expansion@1.1.8 
  │   │   ├── balanced-match@1.0.0 
  │   │   └── concat-map@0.0.1 
  │   ├── once@1.4.0 
  │   └── path-is-absolute@1.0.1 
  └── semver@5.4.1 

➜  quotationChart git:(master) ✗ cnpm run dev

> FxAir@1.0.0 dev /Users/apple/Desktop/quotationChart
> cross-env START_HOT=1 npm run hot-updates-server


> FxAir@1.0.0 hot-updates-server /Users/apple/Desktop/quotationChart
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack/webpack.config.renderer.dev.js

The `setup` option is deprecated and will be removed in v3. Please update your config to use `before`
Project is running at http://localhost:1212/
webpack output is served from /
Content not from webpack is served from /Users/apple/Desktop/quotationChart/dll, /Users/apple/Desktop/quotationChart/static
404s will fallback to /index.html

> FxAir@1.0.0 start-hot-renderer /Users/apple/Desktop/quotationChart
> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.renderer`

are there any solutions ?
