### ISSUE TITLE
Persist state on window close

### ISSUE THREAD

**Issue by AlexFrazer** [chentsulin/electron-react-boilerplate#271]
Can put in a PR for this if need be.

Just would be nice to see some persistence of the state on closing and re-entering the application. Perhaps a redux-storage middleware on the localStorage.

**Comment by amilajack** [comment]
This is something that you should implement in your own application. I dont think this should become part of this project.

**Comment by madc** [comment]
Have a look at [redux-persist](https://github.com/rt2zz/redux-persist).

**Comment by amilajack** [comment]
Closing, as this is pretty much a dupe of https://github.com/chentsulin/electron-react-boilerplate/issues/108
