### ISSUE TITLE
e2e test failing

### ISSUE THREAD

**Issue by 0bman** [chentsulin/electron-react-boilerplate#274]
When running `npm run build` and `npm run test-e2e` I get this output:

```
> cross-env NODE_ENV=test mocha --compilers js:babel-register --require ./test/setup.js --require co-mocha ./test/e2e.js

../todo/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

SyntaxError: ../todo/app/components/Home.css: Unexpected token (1:0)
> 1 | .container {
    | ^
  2 |   position: absolute;
  3 |   top: 30%;
  4 |   left: 10px;
```
node v5.8.0
npm  v3.7.3

I don't understand, why it happens?

**Comment by jhen0409** [comment]
Currently it should be work fine on OS X / [Linux](https://travis-ci.org/chentsulin/electron-react-boilerplate/jobs/143726486#L417) / [Windows](https://ci.appveyor.com/project/jhen0409/electron-react-boilerplate/build/1.0.59#L1846), do you changed something? Or just try reinstall dependencies.

**Comment by 0bman** [comment]
Just `git clone https://github.com/chentsulin/electron-react-boilerplate.git todo` then `cd todo && npm install && npm run build` and when I try to run `npm run test-e2e` or `npm run test` I have this error.

**Comment by chentsulin** [comment]
It seems that webpack loaders doesn't apply correctly...but I can't repro it with same steps

```sh
git clone https://github.com/chentsulin/electron-react-boilerplate.git todo
cd todo && npm install && npm run build
npm run test-e2e
npm test
```

**Comment by amilajack** [comment]
@0bman try these steps:

```
npm cache clean
git clone https://github.com/chentsulin/electron-react-boilerplate.git todo
cd todo && npm install && npm rb && npm run build
npm run test-e2e
npm test
```

**Comment by 0bman** [comment]
@amilajack wow it works. Thanks 👍

**Comment by amilajack** [comment]
@chentsulin close?

**Comment by 0bman** [comment]
@amilajack yes
