### ISSUE TITLE
[Proposal] Remove ES2015 preset when Node 6 active LTS

### ISSUE THREAD

**Issue by jhen0409** [chentsulin/electron-react-boilerplate#275]
Node 6 will active LTS in Oct 2016 (see [this](https://github.com/nodejs/LTS#lts-schedule)), and currently Electron is used Node 6 as runtime, we can only keep `transform-es2015-modules-commonjs` plugin. (It's not required in the Webpack 2)

Also, the problems:

- [ ] Currently uglify is not supported ES2015 syntax (we can watching [the discussion](https://github.com/mishoo/UglifyJS2/issues/1181))
- [ ] Currently [object-rest-spread](https://babeljs.io/docs/plugins/transform-object-rest-spread) is need destructuring transform, see https://github.com/jhen0409/babel-preset-es2015-node6/issues/2 and [Babel#T7086](https://phabricator.babeljs.io/T7086). In fact, I once said to fix it, but no chance yet. :\

**Comment by amilajack** [comment]
We should use https://github.com/babel/babel-preset-env

**Comment by jhen0409** [comment]
Yeah I think we should pointing to `babel-preset-env` and [babili](https://github.com/babel/babili), and require node ^6 here, waiting for https://github.com/babel/babel/pull/4755 merged, I'll do this.

**Comment by amilajack** [comment]
Apparently its in beta. For the most part, I think it should be stable enough. Wbu

**Comment by hzoo** [comment]
You can always check the actual transforms with debug and then check that against the compat-table

**Comment by amilajack** [comment]
@hzoo which compat table? Also do you think babli is stable enough to be used in production?

**Comment by hzoo** [comment]
https://github.com/kangax/compat-table is where the env data comes from - babili is still in beta but the more people testing it out the better so we can fix the bugs to make it more stable
