### ISSUE TITLE
How to enable crossdomain

### ISSUE THREAD

**Issue by Kornflexx** [chentsulin/electron-react-boilerplate#276]
Hi,

It's seems like crossdomain is enable by default. But I have and error when I tried to set an header to an xhr request.

> Refused to set unsafe header "Cookie"

So I need to put some headers in webpack ( [reference](http://stackoverflow.com/questions/28255284/refused-to-set-unsafe-header-cookie-error-in-browser-yet-request-is-successful) ) 

I tried to add this in webpack.config.development
```
devServer: {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Credentials": "true",
      "Access-Control-Expose-Headers": "*",
      "Access-Control-Allow-Headers": "*"
    }
  }
```

And this in server.js
```
app.get("/*", function(req, res, next) {
    res.setHeader("Access-Control-Allow-Origin","*");
    res.setHeader("Access-Control-Allow-Credentials","true");
    res.setHeader("Access-Control-Allow-Headers","*");
    next();
});
```

Both aren't working :/
Can you help me ?

**Comment by chentsulin** [comment]
It's unrelated to this boilerplate, and dev server only be used for development not for api usage.
You can search for keyword "electron", "cors" and your http client's name.
