### ISSUE TITLE
Deploy as a menu bar macOS

### ISSUE THREAD

**Issue by bpeters** [chentsulin/electron-react-boilerplate#277]
How would you configure the boilerplate to deploy as a menu bar app instead of a tool bar app?

**Comment by bpeters** [comment]
implemented https://github.com/maxogden/menubar and it was good to go.

**Comment by twolfe2** [comment]
@bpeters I'm able to get the development version working but I can't figure out how to package my menubar app correctly. 

I've added the menubar to my main.development.js file and it looks like this: 
```javascript
import menubar from 'menubar';

const mb = menubar({ index: `file://${__dirname}/app/app.html`, width: 600, height: 600, 'preload-window': true, resizable: false});

mb.on('ready', function ready() {}); 
```

Do any other files need to me modified?

**Comment by amilajack** [comment]
See https://github.com/chentsulin/electron-react-boilerplate/issues/286#issuecomment-233358865

**Comment by gvergnaud** [comment]
@twolfe2 I'm running in the same issue. did you find any solution?

**Comment by twolfe2** [comment]
@gvergnaud I didn't. I used [this](http://red-badger.com/blog/2016/04/18/building-desktop-apps-with-electron-webpack-and-redux/) blog post and [github](https://github.com/romanschejbal/electron-blog) repo instead.

**Comment by BrianCortes** [comment]
@twolfe2 I have the same issue!
