### ISSUE TITLE
Cant create Win package, only Mac OSX and Linux

### ISSUE THREAD

**Issue by danielmapar** [chentsulin/electron-react-boilerplate#279]
My project runs well on (npm run dev) also (npm run build & npm run start).

However, when I run (npm run package-all) it only generates binaries for Mac OSX and Linux.

I tried using many node versions (4.4.7, 5.11.1, 6.2.0 and 6.3.0) with nvm and all presented the same issue.

Right now I am using node 6.2.0. The code is available at: https://github.com/SmartPowerSocket/DesktopApp

No warnings are presented. Any tips?

**Comment by jhen0409** [comment]
Do you have checkout [`Building windows apps from non-windows platforms`](https://github.com/chentsulin/electron-react-boilerplate#building-windows-apps-from-non-windows-platforms) of readme? I can't reproduce the problem on any platforms.

**Comment by danielmapar** [comment]
I will try it out at0g.

jhen0409, I will also check this readme... but I am basically running npm run package-all and it is not generating the windows build.

I have a dependency on my project that uses node-gyp.. maybe that is what is causing the problem, since it is compiled I think. (platform dependent)

**Comment by danielmapar** [comment]
at0g , your solution did it! Installing xquartz and wine made the packing process output the win version again. During the packaging wine popup as well.

Thanks a lot!

**Comment by amilajack** [comment]
Close issue?
