### ISSUE TITLE
can't npm dev in win but i got some findings that make it work

### ISSUE THREAD

**Issue by andy547320** [chentsulin/electron-react-boilerplate#283]
first

i got a error code says that  electron-prebuilt module in node_module have a less of path.txt and dist folder,but i dont know why this file weak occur since i always use npm install

second

it still wont work and i found that package.json the start-hot script has problem so i compare the script to others and change to

"start-hot": "cross-env HOT=1 NODE_ENV=development electron ./ -r babel-register -r babel-polyfill ./main.development.js"

it get work ,but i dont know this method is a popular solution ?

**Comment by jhen0409** [comment]
Could you check `npm install` successful? If you haven't reference [node-gyp installation](https://github.com/nodejs/node-gyp#installation) for Windows, it will broken and lead some postinstall script (like `electron-prebuilt`) not started, otherwise it should be work.

**Comment by amilajack** [comment]
@andy547320 try theses steps:

```
rm -rf node_modules
npm cache clean
npm i
npm rb
npm run dev
```

**Comment by etiennejcharles** [comment]
Had the same mistake, and had to do the following to fix.

```
rm -rf node_modules
npm install --msvs_version=2015
```

If you have visual Studio 2013 chances are you'll have to use the build tools for that version. 

`npm install --msvs_version=2013`
