### ISSUE TITLE
[question] development is ok but package generate blank app 

### ISSUE THREAD

**Issue by creeperyang** [chentsulin/electron-react-boilerplate#286]
I means app works well with `npm run dev`. But when I run `npm run package`, the terminal only logs:

```bash
Packaging app for platform darwin x64 using electron v1.2.6
```

No error and the app looks a blank page.

I add `console.log(xxx)` to the top of `package.js` (under `use strict;`), But the terminal gives no other log info too. So am I something wrong?

**Comment by amilajack** [comment]
try debugging this by commenting lines [54](https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.development.js#L54) and [66](https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.development.js#L66) in main.development.js. This will help you debug in production.

**Comment by creeperyang** [comment]
Ok, I will try it.

**Comment by creeperyang** [comment]
@amilajack The error message is that: 

```bash
Not allowed to load local resource: file:///app/app.html
```

**Comment by creeperyang** [comment]
I get the way to fix `Not allowed to load local resource` error. And I then found a `cannot find module` error. 

Um this is because webpack build fails for some files. I can resolve it myself. The only question is why `console.log` in `package.js` not work? I cannot get error info from terminal.

**Comment by chentsulin** [comment]
Because it's production env, so `console.log`s are removed by babel. We should fix this
https://github.com/chentsulin/electron-react-boilerplate/blob/master/.babelrc#L8

**Comment by creeperyang** [comment]
Get it, thanks.
