### ISSUE TITLE
Extra actions after build. 

### ISSUE THREAD

**Issue by gazzer82** [chentsulin/electron-react-boilerplate#288]
I would like to run some extra fictions to zip files, create DMG e.t.c after the package.js script has built the various binaries. But I can't for the life of me work out how to add an additional .then to the promise chain after the build step. Anyone got any suggestions/guidance/examples they could share?

Thanks!

**Comment by amilajack** [comment]
Electron builder makes this easier:

```js
const builder = require("electron-builder")
const Platform = builder.Platform

// Promise is returned
builder.build({
  targets: Platform.MAC.createTarget(),
  devMetadata: {
    "//": "build and other properties, see https://goo.gl/5jVxoO"
  }
})
  .then(() => {
    // handle result
  })
  .catch((error) => {
    // handle error
  })
```

**Comment by gazzer82** [comment]
Interesting, though I am currently using electron-packager, have you modified the package.js file to use electron-builder instead? Could you share your modifications?

Thanks

Gareth

**Comment by amilajack** [comment]
@gazzer82 you could try changing the `package` script:

```
 "package": "cross-env NODE_ENV=production node -r babel-register package.js && some_other_script.js",
```

**Comment by amilajack** [comment]
Closing, due to no response
