### ISSUE TITLE
[question] how to push path for react-router from electron process

### ISSUE THREAD

**Issue by k2truong** [chentsulin/electron-react-boilerplate#293]
So currently I have an action Cmd + N that will navigate from the window to display another page. I want to be able to have react-router change the url instead of calling loadURL(url)

I thought about having the React component listen for Cmd + N and preventDefault/stopPropagation. But this wouldn't work for the scenario where if I have a separate asset window open along with the landing page and would like to restore the landing page window and have it route to the other page with with react router. 

Is there an easy way to have a listener in routes.js or index.js to listen for events from electron.ipcRenderer? Thanks!

**Comment by k2truong** [comment]
I realized that I needed to add a listener into componentWillMount() for my root component and then send an event from my electron process.

i.e:
in React Root Component
`electron.ipcRenderer.on('transitionTo', (evt, route) => { // push route });`

in electron 
`existingWindow.webContents.send('transitionTo', url);`

**Comment by adeperio** [comment]
Hi @kennethtruong what did you mean by the push route comment? What should go in there?

**Comment by sschwartz0** [comment]
@kennethtruong Thanks!

@adeperio and anyone else that will see this. Use react routers history push feature there. 

`history.push(route)`
