### ISSUE TITLE
PR: Webpack DLL Plugin

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#298]
Willing to make a PR to use the Webpack dll plugin:

https://medium.com/@soederpop/webpack-plugins-been-we-been-keepin-on-the-dll-cdfdd6cb8cd7#.mz4xwsoki

Would this be welcome?

**Comment by chentsulin** [comment]
I haven't used it before, so hard to make decision at this moment. However, if you give it a try in a PR, then we can see how it make build process better and maybe merge it or not.

**Comment by amilajack** [comment]
Some few great links I've found regarding this. I'll look into adding DLL support this weekend.

https://github.com/amireh/happypack#benchmarks
https://robertknight.github.io/posts/webpack-dll-plugins/
http://engineering.invisionapp.com/post/optimizing-webpack/

**Comment by amilajack** [comment]
Let's merge this into webpack-blocks discussion
