### ISSUE TITLE
A virus in this repo?

### ISSUE THREAD

**Issue by EzraLopez** [chentsulin/electron-react-boilerplate#306]
This is what my antivirus said:

Trojan.Generic.17449111 deleted
electron-react-boilerplate/node_modules/spectron/bin/launcher.exe

**Comment by amilajack** [comment]
Just because your antivirus says its a virus, doesnt mean it is

**Comment by amilajack** [comment]
Its in spectron's source: https://github.com/electron/spectron/tree/master/bin

**Comment by EzraLopez** [comment]
I guess it is a false positive then.

**Comment by amilajack** [comment]
The repo is authored by the electron team, which is run by github. I dont think github would want you to get viruses when writing OSS.

**Comment by jhen0409** [comment]
duplicated of https://github.com/electron/spectron/issues/93
