### ISSUE TITLE
PR: Simplifying port customization

### ISSUE THREAD

**Issue by akozhemiakin** [chentsulin/electron-react-boilerplate#308]
Currently to customize port used to run development server we need to change corresponding value in several different files (for example, I tried to customize it and have broken HMR feature, repaired it only after greping '3000' through all of the project files). How about to make it a little bit easier?

For example we can allow users to override port using environment variable.

What do you guys think about it? I can prepare a pull request.

**Comment by chentsulin** [comment]
Great idea. I'd like to see this happen and definitely will accept the PR.

**Comment by Aerlinger** [comment]
Agreed. I implemented this a while back in one of my own applications  also using an environment variable.

If it's useful to either of you, here's a git patchfile containing my changes for that commit:
[port_env_config_git_patch.txt](https://github.com/chentsulin/electron-react-boilerplate/files/416867/port_env_config.txt)

**Comment by amilajack** [comment]
Fixed in https://github.com/chentsulin/electron-react-boilerplate/pull/345
