### ISSUE TITLE
`window.open` will behave unexpectedly with current configuration.

### ISSUE THREAD

**Issue by AlexFrazer** [chentsulin/electron-react-boilerplate#311]
When you use `window.open`, currently, it will not behave in a very logical way. It will not show the frame on OS X.

It appears to be the line in the `main.development.js` that says `show: false`

The current workaround in the webapp is to use `electron.BrowserWindow` to create a new window and show it, if anyone needs a quick workaround

**Comment by chentsulin** [comment]
> The newly created BrowserWindow will inherit the parent window's options by default. To override inherited options you can set them in the features string.

https://github.com/electron/electron/blob/master/docs/api/window-open.md

So another solution is to provide a features string to `window.open`

**Comment by amilajack** [comment]
Closing due to no response

**Comment by xmsz** [comment]
any update?
