### ISSUE TITLE
Use electron-prebuilt version for packaging

### ISSUE THREAD

**Issue by tsemerad** [chentsulin/electron-react-boilerplate#33]
Is there a reason why this project is always grabbing the latest electron version for packaging? Wouldn't it make more sense to package with the same version as electron-prebuilt?

For example, [version 0.31.0](https://github.com/atom/electron/releases/tag/v0.31.0) just came out, with some breaking changes, so when I packaged my app it broke. 

I started modifying `package.js` to use the currently-installed version of electron-prebuilt for packaging. I can make a pull request if you're interested.

**Comment by chentsulin** [comment]
Sure, using same version as electron-prebuilt is better, PR welcome.
