### ISSUE TITLE
server side babel-polyfill issue

### ISSUE THREAD

**Issue by jackypan1989** [chentsulin/electron-react-boilerplate#331]
When trying to use async/await es7 feature on server-side by requiring 'babel-polyfill'.
it works. But the webpack-dev-middleware will not wait for the build.
It makes every time the first launch fail to load localhost bundle until you Cmd+R.

without server polyfill
```
[0] Listening at http://localhost:3000
[0] webpack: wait until bundle finished: /dist/bundle.js
[0] webpack built a88f7043336ec8ee2022 in 2911ms
```

with server polyfill
```
[0] Listening at http://localhost:3000
[0] webpack built a88f7043336ec8ee2022 in 2655ms

```

**Comment by amilajack** [comment]
This happens often, even without requiring the polyfill. Try replacing the `"dev"` script with this:

"dev": "npm run hot-server && npm run start-hot"

**Comment by amilajack** [comment]
Closing due to no response.
