### ISSUE TITLE
Unable to load nodobjc code

### ISSUE THREAD

**Issue by cobarx** [chentsulin/electron-react-boilerplate#332]
Kudos on the awesome project. It is great to be able to use all the advanced technologies like React, Redux, WebPack, etc. without having to spend hours wiring everything up.

Unfortunately, I've been having difficulty getting the nodobjc library for bridging Objective C code in an Electron app to work. The same code works fine in the electron-quick-start app, which makes me think perhaps something about webpack is screwing things up.

Here's the code I've been testing with
```
const $ = require('nodobjc');
const pool = $.NSAutoreleasePool('alloc')('init');
const string = $.NSString('stringWithUTF8String', 'GoChip');
console.log("String is " + string);
pool('drain');
```

When I start the app I get a `Uncaught TypeError: Path must be a string. Received undefined` in path.js in the Chrome debugger as it attempts to require the library.

Any idea what I can do to fix this?

**Comment by amilajack** [comment]
What is the stack trace for this?

**Comment by cobarx** [comment]
Here you go:
[nodobjc-chrome-trace.txt](https://github.com/chentsulin/electron-react-boilerplate/files/410346/nodobjc-chrome-trace.txt)

**Comment by amilajack** [comment]
A screenshot would be better

**Comment by cobarx** [comment]
Of the trace in the Chrome debugger?

**Comment by amilajack** [comment]
Yea

**Comment by amilajack** [comment]
I've experienced this issue before:

https://github.com/jaruba/wcjs-player/issues/65

**Comment by cobarx** [comment]
Thanks for the suggestion.

I went ahead and added the nodobjc module to the webpack externals and am no longer getting the error. However, my module versions don't match so I was attempting to do a node-rebuild. When I npm install I now get the following error:
```
> fsevents@1.0.14 install /Users/maxwell/gochip/electron-react-boilerplate/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

Warning: node-pre-gyp could not find exact match for 1.2.8
Warning: but node-pre-gyp successfully choose 1.0.4 as ABI compatible target
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v42-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@1.2.8 (node-v42 ABI) (falling back to source compile with node-gyp) 
Warning: node-pre-gyp could not find exact match for 1.2.8
Warning: but node-pre-gyp successfully choose 1.0.4 as ABI compatible target
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://iojs.org/download/release/v1.2.8/iojs-v1.2.8.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/maxwell/gochip/electron-react-boilerplate/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/maxwell/gochip/electron-react-boilerplate/node_modules/npm/node_modules/request/request.js:977:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:361:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/6.3.1/bin/node" "/Users/maxwell/gochip/electron-react-boilerplate/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/maxwell/gochip/electron-react-boilerplate/node_modules/fsevents/lib/binding/Release/node-v42-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/maxwell/gochip/electron-react-boilerplate/node_modules/fsevents/lib/binding/Release/node-v42-darwin-x64"
```

I don't think I was seeing this previously.

**Comment by amilajack** [comment]
Try this:

```
rm -rf node_modules
npm cache clean
npm i
npm rb
```

**Comment by cobarx** [comment]
It turns out I had an environmental variable set for node-gyp that I had set while troubleshooting. Everything is working now :) Thanks for the help.

**Comment by amilajack** [comment]
No problem? Can this issue be closed?

**Comment by cobarx** [comment]
Yes go ahead and close it. It might be worth adding some examples of modules that have to be excluded from webpack to the README. I had no idea that this was one of them.
