### ISSUE TITLE
[question] How to package when there are two many bundles in dist

### ISSUE THREAD

**Issue by zhouxinyong** [chentsulin/electron-react-boilerplate#338]
I used react react-router, used the code split with webpack,so  when I compile the code to the dist, there are the list: 
``` 
  1.search.js
  2.counter.js
  3.filter.js
  4.mark.js
  5.tags.js
  logo.png
  index.html
  vendor.js
  app.css
  node_modules/
```
but when after packaging the app, I open the app, click the link, the router did not work.the reason is  the file was not found.
![image](https://cloud.githubusercontent.com/assets/15569753/17614787/d2610de4-609b-11e6-9a97-a15d6e1eabad.png)

How do I resolve this problem?

**Comment by amilajack** [comment]
Did you resolve this issue? If not, where are the files being outputted to?

**Comment by amilajack** [comment]
Closing due to no response
