### ISSUE TITLE
Hot module reload server doesn't terminate when app quit?

### ISSUE THREAD

**Issue by Aerlinger** [chentsulin/electron-react-boilerplate#340]
Terminating the client application doesn't seem to successfully terminate the HMR server process when using concurrently via `npm run dev`. It seems `concurrently` sends out a SIGTERM signal to kill to no effect. 

Since the HMR port is still open, it must be closed manually by the user before the app can be run again.

**Expected Behavior:**
Closing the client app should terminate the hot-module-reload server process

**Actual Behavior:**
SIGTERM signal is sent, but is either not received or handled within server.js, forcing the user to close it manually.

Note that `concurrently` logs the SIGTERM being dispatched (font is difficult to see at bottom):
![image](https://cloud.githubusercontent.com/assets/604138/17647149/c96c9960-61b3-11e6-9326-ad58bb33db4d.png)

Yet the `SIGTERM` listener in server.js doesn't get triggered:

```
process.on('SIGTERM', () => {
  console.log('Stopping dev server')

  wdm.close()
  server.close(() => {
    process.exit(0)
  })
})
```

**To reproduce:**
Run `npm run dev` then quit out of electron app. The HMR server will remain open.

**Comment by amilajack** [comment]
This is something I experience about every 30 min or so. Still haven't found a solution for this

**Comment by amilajack** [comment]
@Aerlinger are you still experiencing this with the latest build?

**Comment by amilajack** [comment]
Closing due to no response
