### ISSUE TITLE
PR: Add support for webpack-dashboard

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#341]
Willing to make a PR for migrating to [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard). 

The primary benefit of using it is its significantly cleaner output.

Would this PR be welcome?

**Comment by fearintino** [comment]
I think it will be very cool!

**Comment by amilajack** [comment]
Thanks! Btw it doesnt look like travis ci is enabled:

https://travis-ci.org/JamesTheHacker/Neuron

**Comment by amilajack** [comment]
@chentsulin @jhen0409 Thoughts?

**Comment by chentsulin** [comment]
+1 for this, webpack bundle size analyzer should be helpful.

**Comment by jhen0409** [comment]
👍  I'm all for this.

**Comment by vinnymac** [comment]
I just found this after adding it to my fork. It works well.

https://github.com/vinnymac/electron-react-boilerplate/commit/501e2641bdbf2cc6931b9c420d521e53b392867a

**Comment by amilajack** [comment]
@vinnymac can you show me the output of your fork? I've cloned it and started running it with no success.

**Comment by vinnymac** [comment]
@amilajack all I had to do was `npm install` and `npm run hot-server`

This is what I see after hot-server starts.
![Hot Server](http://i.imgur.com/GgnQhzT.png)

node v6.2.2
npm v3.10.3

**Comment by amilajack** [comment]
There are issues with webpack-dashboard on windows. `react-boilerplate` has [decided to wait until those issues are resolved](https://github.com/mxstbr/react-boilerplate/pull/886) and I think we should do the same
