### ISSUE TITLE
Built app huge - over 2.3GB

### ISSUE THREAD

**Issue by gile-babbler** [chentsulin/electron-react-boilerplate#346]
Sorry if you had this already.

I've clone rep, installed dependencies and once "npm run dev" just to make sure it's fine.
After that I've "npm run package" and got 2.31 GB app.
I haven't change any of files. Haven't even open anything in IDE.

Again, sorry if this is some known thing, but I couldn't find how to resolve it. Altough, I have feeling that I'm missing something...

Here are some of the errors I've got after packaging

`[ { Error: ENAMETOOLONG: name too long, readlink '/Users/babbler/Sites/el/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'
      at Error (native)
    errno: -63,
    code: 'ENAMETOOLONG',
    syscall: 'readlink',
    path: '/Users/babbler/Sites/el/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' },
  { Error: ENAMETOOLONG: name too long, readlink '/Users/babbler/Sites/el/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Frameworks/ReactiveCocoa.framework/Headers'
      at Error (native)
    errno: -63,
    code: 'ENAMETOOLONG',
    syscall: 'readlink',
    path: '/Users/babbler/Sites/el/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Frameworks/ReactiveCocoa.framework/Headers' },
  { Error: ENAMETOOLONG: name too long, readlink '/Users/babbler/Sites/el/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Frameworks/Squirrel.framework/Headers'
      at Error (native)
    errno: -63,
    code: 'ENAMETOOLONG',
    syscall: 'readlink',
    path: '/Users/babbler/Sites/el/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Frameworks/Squirrel.framework/Headers' },
  { Error: ENAMETOOLONG: name too long, readlink '/Users/babbler/Sites/el/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Resources/app/electron-packager/darwin-x64/ElectronReact-darwin-x64/Electron.app/Contents/Frameworks/Mantle.framework/Headers'`

**Comment by amilajack** [comment]
`node` and `npm` version?

**Comment by gile-babbler** [comment]
node v6.2.2
npm 3.10.2

**Comment by gile-babbler** [comment]
Looks like it's not electron-react-boilerplate issue. It's something wrong with my installation or such.
I've just tried to build [electron-api-demos](https://github.com/electron/electron-api-demos) and got the same problem...this time 3.27 GB :p
Sorry to bother.

**Comment by amilajack** [comment]
Try this, assuming that you have a clean fork of this repo and haven't made any changes:

```
npm cache clean
rm -rf node_modules
npm i
npm rb
```

**Comment by gile-babbler** [comment]
deleting cache and rebuild didn't help.
I suspect that I had some permission issues, coz I've made a mess with node modules installed globaly, some installed with sudo -s.
It was probably this http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo
I have remove all of modules and even installed fresh node and npm and now everything works great.
tnx
