### ISSUE TITLE
Building Windows package on OSX host?

### ISSUE THREAD

**Issue by billyvg** [chentsulin/electron-react-boilerplate#355]
Is it possible to build a windows package when developing/using OSX?

When I run `npm run package-all` I get this output:

```
Downloading electron-v1.3.3-linux-ia32.zip
Downloading electron-v1.3.3-linux-x64.zip
Downloading electron-v1.3.3-win32-ia32.zip
Downloading electron-v1.3.3-linux-ia32.zip
Downloading electron-v1.3.3-win32-x64.zip
[============================================>] 100.0% of 53.29 MB (2.27 MB/s)
Packaging app for platform win32 x64 using electron v1.3.3
```

But I only get packages for OSX and linux, not Windows. Is there a way to get more debug info when packaging?

**Comment by amilajack** [comment]
From my experience, not (or at least, at the moment).

**Comment by amilajack** [comment]
Try packing specifically for windows.

**Comment by amilajack** [comment]
Also what are your node and npm versions?

**Comment by billyvg** [comment]
node v5.12 and 6.4 (npm v3.10.3)

**Comment by amilajack** [comment]
Try updating your npm version. Its a bit old. Also make sure you have all native deps installed correctly.

```
npm cache clean
rm -rf node_modules
npm i
npm rb
npm run package-all
```

**Comment by billyvg** [comment]
Still no luck with npm v3.10.6 and all the steps above

**Comment by amilajack** [comment]
Windows is always a pain. Sorry man.

**Comment by billyvg** [comment]
Yeah, my windows VM is able to build for all platforms though, so guess that will have to do

**Comment by jhen0409** [comment]
@billyvg, have you followed [building-windows-apps-from-non-windows-platforms of readme](https://github.com/chentsulin/electron-react-boilerplate#building-windows-apps-from-non-windows-platforms)?

**Comment by amilajack** [comment]
Closing due to no response.
