### ISSUE TITLE
Stuck in "Waiting for update signal from WDS..."

### ISSUE THREAD

**Issue by nikentic** [chentsulin/electron-react-boilerplate#36]
I followed all the installation instructions but I can't get it to hot reload. What could I be doing wrong?

```
[HMR] Waiting for update signal from WDS...
Download the React DevTools for a better development experience: https://fb.me/react-devtools
[WDS] Disconnected!
[WDS] Hot Module Replacement enabled.
```

Running on Linux Mint.

**Comment by chentsulin** [comment]
Any errors occurred when you run your webpack dev server build?

**Comment by chentsulin** [comment]
Closing as inactive.

**Comment by mtse7en** [comment]
I get this message three times at chorome console and crash chorome.
 Chorome version : 74 , OS : Windows 64 bit.

[HMR] Waiting for update signal from WDS...
