### ISSUE TITLE
PR: Hot reload the main process

### ISSUE THREAD

**Issue by andrewjaykeller** [chentsulin/electron-react-boilerplate#360]
Making a change in the main process requires a complete web pack rebuild, causing advance main process development to crawl.

Can the main process be hot reloaded like the render is done so beautifully?

**Comment by amilajack** [comment]
This would be a good idea.

**Comment by rsaccon** [comment]
Is there any progress on this ?

Maybe just watching all the relevant files for changes, and if that happens, clear the cache ?

`delete require.cache[require.resolve(myModule)]`

here some approaches I just read about:

http://gallium9.blogspot.co.id/2012/03/nodejs-hot-code-reloading.html
or
https://kentor.me/posts/node-js-hot-reloading-development/

**Comment by ritz078** [comment]
@azizhk Can [warm-require](https://github.com/housinghq/warm-require) be used here ?

**Comment by amilajack** [comment]
@ritz078 From the readme, it says that the module isnt tested yet. Lets look for a webpack specific way of solving this

**Comment by ritz078** [comment]
It works well as we use it internally at Housing.com. Just the tests aren't written. Anyways I am fine with any solution that adds hot reloading :)

**Comment by azizhk** [comment]
While pitching [warm-require](https://github.com/housinghq/warm-require), a friend recommended [node-supervisor](https://github.com/petruisfan/node-supervisor).
It seems that it gives out of the box support, which warm-require does not.

**Comment by ritz078** [comment]
https://github.com/palmerhq/backpack may help

**Comment by amilajack** [comment]
Thanks for the recommendations! After looking through each one, I found that [petruisfan/node-supervisor](https://github.com/petruisfan/node-supervisor) sits our needs the most. Thoughts or recommendations on this?
