### ISSUE TITLE
Missing `electron-prebuilt` from dev dependencies

### ISSUE THREAD

**Issue by daaain** [chentsulin/electron-react-boilerplate#361]
The packaging process is apparently looking for `electron-prebuilt` as dev dependency when building: https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.js#L51

But it's missing from `package.json`, so the script falls back to download version 1.2.0: https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.js#L53

Should this missing dependency be added or is there something I'm not aware of?

**Comment by chentsulin** [comment]
Oh sorry, we replaced electron-prebuilt to electron in #343. #364 fixed this issue.

**Comment by Slapbox** [comment]
https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.js#L50

Reference to Electron-Prebuilt in comment there. I was wondering why I was missing electron-prebuilt as well when I read over that comment. Thanks for clearing up.
