### ISSUE TITLE
Debugging release build

### ISSUE THREAD

**Issue by cobarx** [chentsulin/electron-react-boilerplate#367]
My dev build is working fine but when I package it as an app and try and run it, I just get a blank window. Is there a way to get console output from the release builds so I can see what's gone wrong?

**Comment by dovy** [comment]
Same for me... Any suggestions?

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate/issues/286#issuecomment-233358865

**Comment by cobarx** [comment]
Thanks, that worked great.
