### ISSUE TITLE
Using dotenv to avoid env variables nightmare

### ISSUE THREAD

**Issue by dbrugne** [chentsulin/electron-react-boilerplate#372]
It seems to be complicated to deal with env variables in electron and particularly in this boilerplate.
Maybe we can simplify with [dotenv](https://www.npmjs.com/package/dotenv) (or [dotenv-safe](https://www.npmjs.com/package/dotenv-safe)).

NODE_ENV and HOT keys could be set in .env (and .env.example) and not on each command line.
It's possible to use different .env or override a particular key in code (for example set NODE_ENV=test in test helper).

Seems good idea?

**Comment by knpwrs** [comment]
There's also [`env-cmd`](https://www.npmjs.com/package/env-cmd) which uses a similar interface to `cross-env`.

**Comment by amilajack** [comment]
Setting them in package.json is a more idiomatic solution so I think it should be preferred. Also in my opinion, I think we already have enough dependencies for this project. If anything, we should be trying to get rid of some.

**Comment by amilajack** [comment]
Closing this, as it seems extraneous. Don't think most people will be messing around with .env variables initially. Users can easily add dotenv themselves.
