### ISSUE TITLE
Uncaught Exception: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by aaroncalderon** [chentsulin/electron-react-boilerplate#377]
![image](https://cloud.githubusercontent.com/assets/14810269/18292640/f3474002-7453-11e6-9b40-8089d8ec1542.png)

Only way I have been able to have the `start-hot` command to show me the interphace is by commenting out the [`installExtensions()` call line 36](https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.development.js#L36)

I do not know if being behind a corporate proxy has anything to do with the issue.

**Comment by amilajack** [comment]
Make sure you have the latest node version installed along with the latest npm version:

 ### install latest npm version
```
npm i -g npm
```

Then try this:
```console
rm -rf node_modules # Idk if this will work on powershell but just delete the node_modules folder
npm cache clean
npm i
npm run dev
```

If that doesnt work, try deleting the entire `electron-react-boilerplate` directory, re-clone it, and follow those steps

**Comment by aaroncalderon** [comment]
@amilajack I followed your instructions. But, I sitll got the same error. 

I can, however, get the guy if I use Visual Studio Code debugger with the following `launch.json`.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/main.development.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd",
            "runtimeArgs": [
                "--nolazy",
                "--enable-logging",
                "--v=0",
                "-r",
                "babel-register",
                "-r",
                "babel-polyfill"
            ],
            "env": {
                "NODE_ENV": "development",
                "HOT": 1
            },
            "console": "internalConsole",
            "sourceMaps": false,
            "outDir": null
        }
    ]
}
```

Once I get the renderer process displayed, i see the following on the console:

>c:\dev\p\electron\react-boilerplate-master/node_modules/.bin/electron.cmd --debug-brk=6210 --nolazy --enable-logging --v=0 -r babel-register -r babel-polyfill main.development.js 
>
> Failed to fetch extension, trying 4 more times
> Failed to fetch extension, trying 3 more times
> Failed to fetch extension, trying 2 more times
> Failed to fetch extension, trying 1 more times
> Failed to fetch extension, trying 0 more times
> Failed to fetch extension, trying 4 more times
> Failed to fetch extension, trying 3 more times
> Failed to fetch extension, trying 2 more times
> Failed to fetch extension, trying 1 more times
> Failed to fetch extension, trying 0 more times


I did a little more digging and the error returned from `download-chrome-extensions` is 

```
{ Error: connect ECONNREFUSED 216.58.194.110:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '216.58.194.110',
  port: 443 }

```

So, I think I may have two different issues on my hand which may be related. 

I will keep digging and report with any findings.

**Comment by amilajack** [comment]
Try this:

```console
PORT=1212 npm run dev
```

**Comment by jhen0409** [comment]
> c:\dev\p\electron\react-boilerplate-master/node_modules/.bin/electron.cmd --debug-brk=6210 --nolazy --enable-logging --v=0 -r babel-register -r babel-polyfill main.development.js
> 
> Failed to fetch extension, trying 4 more times
> Failed to fetch extension, trying 3 more times
> Failed to fetch extension, trying 2 more times
> Failed to fetch extension, trying 1 more times
> Failed to fetch extension, trying 0 more times
> Failed to fetch extension, trying 4 more times
> Failed to fetch extension, trying 3 more times
> Failed to fetch extension, trying 2 more times
> Failed to fetch extension, trying 1 more times
> Failed to fetch extension, trying 0 more times

Maybe the same with #268, it mean you can't connect to Chrome Store?

**Comment by aaroncalderon** [comment]
@amilajack I will try that when I have a chance. I know, however, that the port is not in use because I am not running any other process that is using it. But I do not see how the port may be related.

@jhen0409 I'm on windows 7 and yes; that is indeed the issue. I am behind a corp proxy and I have set `cntlm` and my `.npmrc` and environmenr variables are set to use it.

However, I have never had issues with electron trying to connect to the internet. I use electron for other projects as well.

My suspicion is that the node process that downloads the extensions is not using my proxy settings.

**Comment by amilajack** [comment]
> My suspicion is that the node process that downloads the extensions is not using my proxy settings.

That may be it. Our tests are @ 100% coverage so I dont this it is an issue with the repo.

**Comment by amilajack** [comment]
@aaroncalderon try following the [installation debugging solutions](https://github.com/chentsulin/electron-react-boilerplate/issues/400) and let me know if this works for you.

**Comment by aaroncalderon** [comment]
Let me take a look at this.

**Comment by aaroncalderon** [comment]
I'm getting the same error. 

So, I think we should close this issue since I think it is not directly related with __electron-react-boilerplate__ directly. 

I think the issue is a combinatin of the __electon-devtools-installer__ and my corp proxy not playing nice with each other.
