### ISSUE TITLE
get the electron version has a bug when package

### ISSUE THREAD

**Issue by foxundermoon** [chentsulin/electron-react-boilerplate#382]
`os:win10`

`npm:3.10.3`

`node:6.3.1`

when exec `npm list electron --dev`
```
 npm list electron --dev
electron-react-boilerplate@0.10.0 H:\workspace\electron\electron-react-boilerplate
`-- electron@1.3.5  -> H:\workspace\electron\electron-react-boilerplate\node_modules\.npminstall\electron\1.3.5\electron
```

then in package.js
```js
  DEFAULT_OPTS.version =  stdout.split('electron@')[1].replace(/\s/g, '');
```
` stdout.split('electron@')[1].replace(/\s/g, '') = '1.3.5->H:\\workspace\\electron\\electron-react-boilerplate\\node_modules\\.npminstall\\electron\\1.3.5\\electron'`

 then download url is `:https://.......mirrors/electron/1.3.5->H:\workspace\electron\electron-react-boilerplate\node_modules\.npminstall\electron\1.3.5\electron/electron-v1.3.5->H:\workspace\electron\electron-react-boilerplate\node_modules\.npminstall\electron\1.3.5\electron-win32-x64.zip`

so it always 404 not found when download electron

**Comment by amilajack** [comment]
Test again against latest node and npm versions.

Do a fresh install.

```
npm cache clean
```
Try deleting the entire project directory and all its content and do this:

```
npm rb
```

**Comment by amilajack** [comment]
Closing due to no response.
