### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by pmaxit** [chentsulin/electron-react-boilerplate#383]
Hi, I was trying to build this app ( npm install ) on MAC but it throws following error:

/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:44:12: error: 
      unknown property attribute 'class'
@property (class, readonly) BOOL supportsSecureCoding;
           ^
anybody has any idea about it ?

**Comment by jhen0409** [comment]
Maybe it's the same with https://github.com/chentsulin/electron-react-boilerplate/issues/326?

**Comment by amilajack** [comment]
Did you make any modifications to the boilerplate?

**Comment by pmaxit** [comment]
Yes, it was the same error and it got resolved after upgrading xcode as suggested. Thank you for your quick help.

**Comment by amilajack** [comment]
How did you upgrade xcode? Did you update the app or update the developer tools (`xcode-select --install` I think)?

**Comment by pmaxit** [comment]
No, simply downloaded the new version of xcode from Apple and replaced the older xcode with new one.
