### ISSUE TITLE
Packaged app doesn't behave like dev app

### ISSUE THREAD

**Issue by jefffriesen** [chentsulin/electron-react-boilerplate#384]
I created a new app based on master. Dev worked fine but once I packaged it I ran into a couple errors:

* Application logic problems showed up in the packaged app but not in dev. I had to enable the debugger in production to find the bug that never showed up while doing `npm run dev`. I didn't want to post all of the logic here because it's a lot of application code. I've got a more reproducible version that shows the problem:
* Importing bootstrap styles in the head of app.html. Like the first problem listed, this works fine in `npm run dev` mode but not after packaging. You can see what I did to recreate this problem on a clean branch of this repo: https://github.com/chentsulin/electron-react-boilerplate/compare/master...jefffriesen:packaging-test

A couple notes:
1. I tried with prune = true and false in case it was pruning out files in the node_modules that weren't `import`ed. I think there was some recent work on `electron-packager` that dealt with pruning `devDependencies`. Either way, I still had the problem.
2. This was happening before this weekend and after I pulled in the latest merges from greenskeeper this weekend (cross-env, react-router, electron-rebuild, jsdom, css-loader)

I don't know if this is related to #383 #374 #379 but like I mentioned elsewhere, I have a few apps built on a version of this boilerplate from March with none of these issues. Adding bootstrap in app.html also wasn't a problem nor did I have differences between dev and the packaged app. I'm not sure if they are all related but they are all new.

(vaguely related to this older, closed ticket: https://github.com/chentsulin/electron-react-boilerplate/issues/260#issuecomment-239632033)

**Comment by amilajack** [comment]
Did you see [this](https://github.com/chentsulin/electron-react-boilerplate/issues/344#issuecomment-240830556)

**Comment by jefffriesen** [comment]
@amilajack I hadn't see that thread. Thanks.

I tried these steps with node 6.4:
```
rm -rf node_modules
npm cache clean
npm i
npm rb
npm run package
```
That's a good list to use - I hadn't thought about `npm rb`. It didn't solve this problem though. I knew  how to show dev tools in production. This is the error I get:
```
Users/jeffers/git/forks/electron-react-boilerplate/release/darwin-x…t.app/Contents/Resources/app/node_modules/bootstrap/dist/css/bootstrap.css Failed to load resource: net::ERR_FILE_NOT_FOUND
```
I know in that thread someone mentioned this isn't really a problem for the boilerplate, but I'm not sure about that. Like I've mentioned in other recent tickets, something changed in the past six month with this boilerplate that is causing a lot of problems. For this and other tickets I have the same setup in older apps working correctly that don't work now. And I can't get them to work. There's something about the packaging and `fs` that has changed with no solution that I've come up with yet.  (#374 and #379)

**Comment by jefffriesen** [comment]
I figured out the problem. I needed to include Bootstrap in `externals` in `webpack.config.base.js`. I added a PR to clarify a bit how `externals` works. 

https://github.com/chentsulin/electron-react-boilerplate/pull/390

thanks @amilajack and @vinnymac
