### ISSUE TITLE
Any guide on defining the server side?

### ISSUE THREAD

**Issue by woniesong92** [chentsulin/electron-react-boilerplate#394]
Let's say I want to create a simple module that opens a text file, modifies the first line, and saves to a different file. It should be easy to do so with NodeJS and electron API.

Not sure where's the best place to do it though. Should I define `/app/api/TextModifier.js` and use the functions inside `/server.js`? I will appreciate any guide.

**Comment by amilajack** [comment]
You can do this inside an existing component. Say in Home.js

```js
import fs from 'fs'

fs.readSync('somefile')
``

**Comment by amilajack** [comment]
Closing due to no response 😢
