### ISSUE TITLE
Release app blank window

### ISSUE THREAD

**Issue by 0x80** [chentsulin/electron-react-boilerplate#4]
When I run the package script and launch the osx app, the window is blank. This is for the develop branch. If I do the same on the master branch there is not even a window coming up...

I'm testing this without any of my code involved.

**Comment by 0x80** [comment]
I've triggered openDevTools() on the release build and it appears the bundle file is not being found:

failed to load  file:///Users/me/tmp/electron-react-boilerplate/release/darwin/ElectronReact.app/Contents/Resources/app/dist/bundle.js

There is indeed no bundle file in the dist folder.

**Comment by chentsulin** [comment]
Now It does not  bundle in package process.

Maybe I should include exec `webpack` in `package.js`

**Comment by chentsulin** [comment]
And I will include [electron-debug](https://github.com/sindresorhus/electron-debug) when it be published to npm.

**Comment by chentsulin** [comment]
I even find out some weird behavior about `electron-packager` with `ignore` option.....some time whole app will not be included by electron-packager

**Comment by akovalyov** [comment]
@0x80 have you run ```npm run build``` before ```npm run package``` ? I have run in the same issue.
@chentsulin maybe the build task should be combined with package one?

**Comment by 0x80** [comment]
@akovalyov Thanks that looks like the problem.

Some minor things I noticed:

webpack-production.config.js should be named webpack.production.config
 ```del('release')``` in the package.js shoudl be ```del('./release')```

Too tired for a PR right now ;)

**Comment by 0x80** [comment]
Also I also noticed that the css file is not being picked up somehow

**Comment by 0x80** [comment]
It seems to me that the whole package app content is off at the moment. It includes the app folder with all the react sources for example and the webpack configs and everything.

I think you want to end up eventually with something like this:

```
.
├── app.html
├── bundle.js
├── main.css
├── node_modules
└── stats.json
```
But I haven't figure out how to get there yet. Just planting some seeds :)

**Comment by chentsulin** [comment]
This should already be fixed.

**Comment by dublinus** [comment]
I'm having the same problem (and I did do `npm run build`). How do I get the dev tools in the packaged app so I can figure out whats going on? I tried passing `NODE_ENV=development`, but that didn't seem to work.

**Comment by amilajack** [comment]
The packaged app should not contain the dev tools. Run:

```bash
npm run dev
```

**Comment by dublinus** [comment]
That gives me my app, which works correctly. But when I package it, I just get the blank page, and no dev tools to find out why.

**Comment by amilajack** [comment]
When did you fork or clone this repo?

**Comment by dublinus** [comment]
Not sure when, but I have version 0.10.0.

**Comment by amilajack** [comment]
The repo version is not updated frequently (last updated April 17). You should making a fresh clone of the repo:

If you forked the repo:
```bash
git remote add upstream https://github.com/chentsulin/electron-react-boilerplate.git
git pull upstream master
```

If you didn't change the origin:
```bash
git pull --all
```

**Comment by c446984928** [comment]
try  this :
```javascript
function createWindow () {
  mainWindow = new BrowserWindow({
    //...
  })
// use this to open dev tools manualy to debug
 mainWindow.webContents.openDevTools()
//...
}
```

**Comment by lacymorrow** [comment]
This issue is back, macos 10.14

Cant even page the example app.
