### ISSUE TITLE
How to change App icon for windows?

### ISSUE THREAD

**Issue by kishanj918** [chentsulin/electron-react-boilerplate#407]
I am bundling package from mac os . I want to change windows app's icon. I have tried following commands, but they don't seem to work. what am i supposed to do?
1) electron-packager . iconsink --all --icon "/app/img/App_icon.ico"
2) npm run package-all --icon "/app/img/App_icon.ico"

**Comment by amilajack** [comment]
I would try adding the ico file to the same location where the default icon is. Havent tried this out before. After we merge the electron-builder PR, this will become much eaiser.

**Comment by kishanj918** [comment]
@amilajack  i had tried replacing default icon. That worked for osx but no luck for windows.

**Comment by amilajack** [comment]
Update: this will be [fixed soon](https://github.com/chentsulin/electron-react-boilerplate/pull/440#issuecomment-252415761)

**Comment by amilajack** [comment]
Closing because this will be fixed in a few days.

**Comment by Ctesias** [comment]
What's the right way to do it?  `npm run package --icon "app/img/icon.ico"` isn't working for me.  

I am still seeing "Application icon is not set, default Electron icon will be used"

**Comment by amilajack** [comment]
Try this:

```bash
npm run package -- --icon "app/img/icon.ico"
```

**Comment by Ctesias** [comment]
I get an `unknown argument: icon` error when I try that way

**Comment by amilajack** [comment]
We're using electron builder to package the app. Here's electron-builder's documentation documents icons:

https://github.com/electron-userland/electron-builder#quick-setup-guide

Here's an example:
https://github.com/amilajack/popcorn-time-desktop/blob/master/package.json#L58

**Comment by Ctesias** [comment]
Oh, if I add `"icon" : "<path-to-icon>"` in the `win` param of the `build` object in `package.json` that does it.

You can close this thread, thanks for the link.

**Comment by jackmallers** [comment]
This did not work for me for some reason. I can't seem to change the dock icon or the product name. Has anything changed?

**Comment by amilajack** [comment]
This is a question about `electron-builder`. See its docs [here](https://github.com/electron-userland/electron-builder/wiki/Icons)
