### ISSUE TITLE
the start up command missing cross-env and electron

### ISSUE THREAD

**Issue by yeluolei** [chentsulin/electron-react-boilerplate#417]
I need to run the follow command to start the development.

```
npm install -g cross-env
npm install -g electron
```

no documentation for this.

**Comment by amilajack** [comment]
That is not necessary. Did you follow the installation guide? What errors did you get?

**Comment by yeluolei** [comment]
yes, I cloned this repository and then run `npm install`.  after the installation complete, I started with `npm run dev` but failed.
 
my environment is window 10 with node version v6.6.0 and npm 3.10.3.

the error message is cross-env is not an command or executable.

**Comment by amilajack** [comment]
What is the error?

**Comment by andrerpena** [comment]
@yeluolei , on Windows you have to `SET NODE_ENV=development` before the NPM install

**Comment by yeluolei** [comment]
OK，thank you. This should be the reason.😀

**Comment by amilajack** [comment]
Fixed?
