### ISSUE TITLE
run start-hot breaks chrome refresh(CTRL+R)

### ISSUE THREAD

**Issue by yinhm** [chentsulin/electron-react-boilerplate#42]
Ubuntu Linux 14.04, Chrome 45, after

```
npm run start-hot
```

then chrome will not respond to refresh(CTRL+R/F5).

Close Electron App will re-enable chrome refresh functionality.

I did not spot this in other electron app, I was wondering this may related to react-dev or react-hot-loader?

**Comment by chentsulin** [comment]
It seems a issue relate to [electron-debug](https://github.com/sindresorhus/electron-debug) and also eletron's `global-shortcut` built-in module.

**Comment by yinhm** [comment]
Thanks for the reply.

After commented:

```
require('electron-debug')();
```
in main.js, refreshing works fine.

Maybe we could remove electron-debug dependency, and make shortcuts in menu, this will not break other apps(eg: terminal, chrome).

**Comment by chentsulin** [comment]
I already send a pull request to fix the issue at `electron-debug`, let's waiting for response from the repo maintainer.

**Comment by chentsulin** [comment]
should be fixed at [0.4.2](https://github.com/chentsulin/electron-react-boilerplate/releases/tag/v0.4.2)

**Comment by yinhm** [comment]
thanks for your great work.
