### ISSUE TITLE
Possible performance impact of dynamic script injection

### ISSUE THREAD

**Issue by wyjieying** [chentsulin/electron-react-boilerplate#423]
when i run   nam run dev, and the app is running ,but it show error message like this

A Parser-blocking, cross-origin script, http://localhost:3000/dist/bundle.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

why? I use mac os 10.11.5, it cannot work,
and  i use window, it ok,
how can i do??

**Comment by amilajack** [comment]
This is not really a problem. The boilerplate app should still work.

**Comment by wyjieying** [comment]
@amilajack but why it report cross-origin  error in mac os?

**Comment by amilajack** [comment]
It is because creating inserting a script dynamically at runtime is terrible for performance. Browsers want to be able to walk the DOM tree without having to evaluate JS to insert scripts that will pull in other scripts.

**Comment by wyjieying** [comment]
@amilajack  and how to do ?

**Comment by amilajack** [comment]
The message can be ignored.

**Comment by amilajack** [comment]
https://developers.google.com/web/updates/2016/08/removing-document-write

**Comment by amilajack** [comment]
Reopening because I think this actually may have some noticeable performance.

**Comment by wyjieying** [comment]
@amilajack  thank you , solved!

**Comment by amilajack** [comment]
http://blog.dareboost.com/en/2016/09/avoid-using-document-write-scripts-injection/

Dynamic script injection will be disallowed in Chrome 54. We definitely need to migrate from this soon.

**Comment by yourfavorite** [comment]
I am already seeing errors from this using electron 1.4.3. Not sure when this happened but in my haste, I downgraded to electron 1.3.4 and my errors went away. Will have to slowly increment down in electron versions to find the latest compatible version.

I get the Parser-blocking error both in terminal and in console of electron app.

**Comment by amilajack** [comment]
Are they warnings or errors?

**Comment by yourfavorite** [comment]
Last night there were errors that I assumed were related. After downgrading electron, I did a bit more work. I just updated to the latest electron again though and now I'm just getting the Parser-blocking warning. So perhaps the error was unrelated as I cannot reproduce now.

**Comment by Ugarz** [comment]
I have this too with this repo. Downloaded about an hour ago, `npm i && npm run dev` show me 
<img width="445" alt="capture d ecran 2016-10-26 a 09 34 15" src="https://cloud.githubusercontent.com/assets/6050079/19717118/641e9cbc-9b5f-11e6-8e49-12f1ce0749cb.png">
Chrome Version 54.0.2840.71 (64-bit) on MacOs

**Comment by amilajack** [comment]
Its probably caused by something else. The first two errors are just warnings

**Comment by amilajack** [comment]
@Ugarz Did you see #400

**Comment by dustintownsend** [comment]
I replaced 
`document.write(link.outerHTML)` with `document.body.appendChild(link)`
and `document.write(script.outerHTML)` with `document.body.appendChild(script)`

The resulting output is the same and it gets rid of the errors.

**Comment by amilajack** [comment]
Made https://github.com/chentsulin/electron-react-boilerplate/pull/604 for this. Would be great if you could review it just to confirm
