### ISSUE TITLE
Suggestion: use WebpackHTMLPlugin

### ISSUE THREAD

**Issue by AlexFrazer** [chentsulin/electron-react-boilerplate#437]
Not sure if it would fit into this framework, but it might make things a little simpler.

**Comment by knpwrs** [comment]
I've tried it before. I use it for all of my web projects but I ran into limitations with resolving native / external modules when the HTML page was served by webpack as opposed to loaded directly from the file system. That said, it's been a while since I tried.

**Comment by amilajack** [comment]
@AlexFrazer I havent used this plugin before. Can you elaborate on how it could improve the project? I'm somewhat hesitant on adding new dependencies because we already have too many 😢

**Comment by amilajack** [comment]
Closing do to no response 😢
