### ISSUE TITLE
What is the purpose of setup.js file in root dir?

### ISSUE THREAD

**Issue by doortts** [chentsulin/electron-react-boilerplate#444]
First of all, thank you for all the work :)

I wonder what setup.js file does which located in root dir.

**Comment by amilajack** [comment]
It is supposed to remove the boilerplate from this project

**Comment by amilajack** [comment]
@tstringer Would be great if you could add some comments to the `setup.js` explaining what it is!

**Comment by doortts** [comment]
@amilajack thanks you! but may I ask one more thing? Would you mind explain how it be done with setup.js ?

**Comment by amilajack** [comment]
No worries! Ask away. It is being done with [one of our dependencies](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L66).

**Comment by doortts** [comment]
@amilajack Ah ha! Thanks!!! You are so kind!! : ) Have a nice day~ 

For now, I'll closed the issue.

**Comment by tstringer** [comment]
@amilajack absolutely that's a great idea! I've made a few advancements to `boiler-room-custodian` that I want to incorporate here, so you should be seeing a PR soon. 👍
