### ISSUE TITLE
PR: Automatic port collision handling

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#446]

**Comment by jhen0409** [comment]
It seems very simple if we use [get-port-cli](https://www.npmjs.com/package/get-port-cli):

```bash
$ PORT=$(get-port) npm run dev
```

I have been using it this way.
But unfortunately we cannot do it on Windows CMD :(, so may we need add some additional code.

**Comment by amilajack** [comment]
Should file an issue for this?

**Comment by amilajack** [comment]
> But unfortunately we cannot do it on Windows CMD :(,

@jhen0409 how come?
