### ISSUE TITLE
A Javascript error occured in the main process

### ISSUE THREAD

**Issue by Mutharasi** [chentsulin/electron-react-boilerplate#452]
When trying to test this sample code I got the following error. Please help me to resolve this.
![ele_react](https://cloud.githubusercontent.com/assets/17024340/19349772/76dddabc-9172-11e6-9f6d-d60202290566.PNG)

**Comment by amilajack** [comment]
Did you see this? v

**Comment by Mutharasi** [comment]
I am using the latest npm and node version. I deleted the node_modules folder and tried it again.

**Comment by amilajack** [comment]
I have update #400 . Please refer to it again.

**Comment by amilajack** [comment]
Closing due to no response
