### ISSUE TITLE
Actions VS. Action Creators

### ISSUE THREAD

**Issue by tylerlong** [chentsulin/electron-react-boilerplate#460]
Compare 

https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/actions/counter.js 

to

https://github.com/reactjs/redux/blob/master/docs/api/bindActionCreators.md

Apparently, actions in this repo are actually action creators. So it's pretty confusing.

Check the doc here for what are Action and Action Creator: http://redux.js.org/docs/Glossary.html . It will cause unnecessary confusion if you don't use the same glossary as Redux.

**Comment by chentsulin** [comment]
Official examples in redux repo also use same convention:
https://github.com/reactjs/redux/blob/master/examples/todos/src/actions/index.js

**Comment by tylerlong** [comment]
Interesting. The link I posted is also from the official doc. 

Maybe this issue belongs to Redux. Closing.
