### ISSUE TITLE
Misleading function name: mapDispatchToProps

### ISSUE THREAD

**Issue by tylerlong** [chentsulin/electron-react-boilerplate#461]
https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/containers/CounterPage.js#L13

According to the doc of [bindActionCreators](https://github.com/reactjs/redux/blob/master/docs/api/bindActionCreators.md), method name should be `mapActionCreatorsToProps`, Or `mapActionsToProps` for short. The current name is quite misleading.

**Comment by chentsulin** [comment]
`mapDispatchToProps` - receive `dispatch` and map it to `props`.

It's not about  `bindActionCreators`, just convention for `connect`'s second argument:
https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by tylerlong** [comment]
I see. Although I don't like the name, it's suggested by the official doc.
