### ISSUE TITLE
CSS file imports

### ISSUE THREAD

**Issue by pathway27** [chentsulin/electron-react-boilerplate#468]
Hi,

So i was trying to use an [external react component](http://intljusticemission.github.io/react-big-calendar/examples/index.html), but the CSS import statements don't seem to work.

``` js
import 'rc-calendar/assets/index.css';
```

Do i have to link them in the head of my index.html like the bootstrap example shown in the README?

**Comment by amilajack** [comment]
In which module/folder is the import statement in?

**Comment by pathway27** [comment]
It's in one of my components. In the components folder given by the boilerplate.

**Comment by amilajack** [comment]
I haven't worked with css imports much so I cant give you much advice on this. @chentsulin @jhen0409 thoughts?

**Comment by joncppl** [comment]
Same issue. 

```javascript
import 'bootstrap-slider/dist/css/bootstrap-slider.css';
```

The file appears to be loaded by webpack (I can see it in "Sources" in dev-tools), but the styles aren't being applied.

**Comment by joncppl** [comment]
After researching css-modules, I found out that it adds a hash to the classnames, and hence they weren't being applied. 

The workaround is to rename the css files *.global.css, and then it doesn't add the hashes so the styles work as expected. 

Another (slightly more elegant way) is to specify a different loader by prepending the css import with `!style!css!` so that it isn't processed by css-modules.

so in your case,

```javascript
import '!style!css!rc-calendar/assets/index.css';
```

should do it.

**Comment by pathway27** [comment]
Yeah, that's what i figured out just then, too!
Working quite well.

Should we add this to the README?

**Comment by amilajack** [comment]
> prepending the css import with !style!css! so that it isn't processed by css-modules.

Is there a way around this without adding `!`'s?

**Comment by jhen0409** [comment]
Why not just add the import code to `app.global.css`?

```css
@import '~rc-calendar/assets/index.css';
```

**Comment by mattwilson1024** [comment]
Thanks @jhen0409. Importing with the tilde prefix worked for me. In my case it was:

`@import '~semantic-ui-css/semantic.min.css';`

**Comment by songyuc** [comment]
Hi, @joncppl!
I tested it today, and find that "import '!style!css!rc-calendar/assets/index.css';" cannot lead to successful compiling.
