### ISSUE TITLE
size of package too big

### ISSUE THREAD

**Issue by MichaelIT** [chentsulin/electron-react-boilerplate#469]
I got a 636.7Mb package file after run `npm run package` according README document.It's possible to make it more small size?
![wechatimg4](https://cloud.githubusercontent.com/assets/5445733/19511445/d5c58a06-9619-11e6-8a73-3ad7a2fb0d41.jpeg)

**Comment by jhen0409** [comment]
For the package, ~2.3Mb is the expected result of node_modules.

It looks you have unexpected folder `.npminstall`, the node_modules of package is copy from root node_modules, and prune unnecessary dependencies. Could you check `.npminstall` is exists in root node_modules?

**Comment by MichaelIT** [comment]
yes! `.npminstall` is exists in `electron-react-boilerplate/node_modules/`.How can i ignore it when run `npm run package`?

**Comment by amilajack** [comment]
Use yarn

**Comment by MichaelIT** [comment]
@amilajack aewsome, it solved!tks a lot.

**Comment by amilajack** [comment]
🎉
