### ISSUE TITLE
Having issues rendering CSS

### ISSUE THREAD

**Issue by seanchen1991** [chentsulin/electron-react-boilerplate#47]
I replaced the included app.css file's content with my own CSS rules but they don't seem be to taking effect and I'm not sure why. Any pointers on this issue?

**Comment by seanchen1991** [comment]
Here's the error message I'm getting: 
```ERROR in ./~/css-loader?localIdentName=[path][name]---[local]---[hash:base64:5]!./~/style-loader!./~/css-loader!./app/app.css
Module build failed: CssSyntaxError: /Users/seanchen/karma/admin-refactor/node_modules/style-loader/index.js!/Users/seanchen/karma/admin-refactor/node_modules/css-loader/index.js!/Users/seanchen/karma/admin-refactor/app/app.css:1:4: Unknown word```

Really not sure how to get my CSS to render.

**Comment by chentsulin** [comment]
Can you show your css here?

Just like the message you got, I thought It cause by your css or css-loader setting.

`/Users/seanchen/karma/admin-refactor/app/app.css:1:4: Unknown word`

**Comment by seanchen1991** [comment]
I'm loading a short custom css file and a minified css file. The minified file isn't loading. Is there a setting in webpack that needs to be changed to minified css files?

**Comment by chentsulin** [comment]
Nothing different between web and electron in the way webpack treating css file. You can try to write some own rules for css.

**Comment by chentsulin** [comment]
@seanchen1991 Webpack configs was simplified in the v0.5 release. Have you figured out how to modify your loader config for css now?

**Comment by seanchen1991** [comment]
Yea I figured it out. Thanks.

**Comment by billcolumbia** [comment]
@seanchen1991 can you post what you did to fix this?
