### ISSUE TITLE
Can't open new window 

### ISSUE THREAD

**Issue by rogerfuentes** [chentsulin/electron-react-boilerplate#484]
When I try to open a new window and load the contents of /app/print.html (for example) the error occurs:

Not allowed to load the local resource: ...

`print_win = new BrowserWindow({autoHideMenuBar: true})`
`print_win.loadURL('file:///' + ${__dirname} + '/app/print.html');`
`print_win.show();`

**Comment by knpwrs** [comment]
It looks like you're concatenating and attempting to use a template string?
