### ISSUE TITLE
`'ENAMETOOLONG': syscall unlink` when packaging

### ISSUE THREAD

**Issue by Unforgiven-wanda** [chentsulin/electron-react-boilerplate#485]
Hello,
I have the base repo with no modifications whatsoever. `npm run dev` runs fine; however whenever I try to run `npm run package` the packager generates an incredibly bloated `electron-packager` folder, 6gb this time around, not to mention a huge log in the console with something like:
```
errno: -36,
    code: 'ENAMETOOLONG',
    syscall: 'unlink',
    path: **some incredibly long path here**
``` 

I've scoured the issues but have found no mention of this. What could be the issue here?
I am running on Ubuntu 16.04 packing node 6.9.1 and npm 3.10.8. 

Thank you for your time.

**Comment by amilajack** [comment]
@Unforgiven-wanda Sorry for the slow response. Have you seen #400? If none of those work, try [installing using yarn](https://github.com/chentsulin/electron-react-boilerplate/issues/469#issuecomment-254844318)

**Comment by Unforgiven-wanda** [comment]
Indeed. Yarn seems to have solved the issue for me.
Thank you.
