### ISSUE TITLE
Minify package

### ISSUE THREAD

**Issue by warka0** [chentsulin/electron-react-boilerplate#487]
Hi,

On the release folder of the darwin-x64, for example, at `ElectronReact-darwin-x64/ElectronReact.app/Contents/Resources/app/app` we can see the entire source code. 

Does anyone have a solution to minify (or uglify) the entire code when doing `npm run package` ?

Maybe i missed something  😄

**Comment by amilajack** [comment]
We've just updated to electron-builder. Can you check if you can replicate this issue?

**Comment by warka0** [comment]
Sorry for never answering to this issue. I was in a restricted country where GitHub is blocked.
Thx for the update! 👍
