### ISSUE TITLE
`npm run dev` race condition

### ISSUE THREAD

**Issue by enagy27** [chentsulin/electron-react-boilerplate#488]
Running this on OSX Sierra, npm version 3.10.9 and node version 7.0.0. After cloning and running either npm install or yarn install I'll use npm run dev, which doesn't work. Fortunately by running the two commands simultaneously I can get a dev environment working (referring to npm run hot-server and npm run start-hot), and then afterwards I can run npm run dev, but on a clean install it doesn't seem to work.

**Comment by amilajack** [comment]
That isn't necessary. What is the output of running `npm run dev`?

**Comment by enagy27** [comment]
Ok, so this might be a subtle difference that I wasn't expecting running on OSX my first time. What's happening is that there's a successful build and the electron window opens up, but I'm seeing ERR_CONNECTION_REFUSED because dist/bundle.js could not be loaded (not found). It seems that if I don't open the window until the build process completes- everything is reloaded and it's fine, otherwise reload just needs to be done manually.

**Comment by amilajack** [comment]
Right now a manual reload is required.

**Comment by amilajack** [comment]
So if I understand you correctly, the build shows an error message but when refreshing electron, everything works?

**Comment by enagy27** [comment]
Nope, there are no build errors, I'm seeing the connection refused/bundle.js missing message from inside the developer tools console.

**Comment by amilajack** [comment]
I see. I have to do the same thing locally sometimes. There's a race condition. Electron is opened before the build is complete.

Here's what we have right now: https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L21

Here's what we should have something like this:
https://github.com/amilajack/popcorn-time-desktop/blob/master/server.js#L30-L38

**Comment by enagy27** [comment]
Right, yeah, makes perfect sense. Should I close this out?

**Comment by amilajack** [comment]
Let's close this once I get around to fixing this.

**Comment by amilajack** [comment]
Made https://github.com/chentsulin/electron-react-boilerplate/pull/489

**Comment by amilajack** [comment]
Fixed
