### ISSUE TITLE
[Enhancement] Extra package.json in app folder

### ISSUE THREAD

**Issue by awsp** [chentsulin/electron-react-boilerplate#49]
First of all, thanks for this great package.

Here's the issue, let's say if I am using this boilerplate to develop my own app, where should I put my own copyright message to my app? Would that be better if the default `package.json` file only contains all NPM dependencies for necessary packages for developing, building, etc., while leaving the main entry point to another `package.json` in app folder instead? 

For instance, `package.json` would look like this, and the content of `main.js` would be in the `app` folder instead. 

##### ./package.json
```js
{
  ...
  "start": "electron app/.",
  "start-dev": "NODE_ENV=development electron app/.",
  ...
}
```

##### ./app/package.json
```
{
  "name"    : "your-app",
  "version" : "0.1.0",
  "main"    : "main.js"
}
```

In that case, it's easier to keep this boilerplate up-to-date, while it doesn't affect the app's own versioning as others develop that.

**Comment by vladfr** [comment]
Hi!

I've seen a good example for this in https://github.com/szwacz/electron-boilerplate
An interesting side-effect is that I can get native modules easier with this approach, i.e. modules installed with npm install in /app seem to work with electron. I don't really understand why.

My use-case is pouchdb with leveldb. Even if I compile the code against electron headers, it doesn't seem to be working, pouch selects idb. 
With the above boilerplate, it works, it finds and uses leveldb.

**Comment by amilajack** [comment]
This should be closed, since this is being done in https://github.com/chentsulin/electron-react-boilerplate/pull/310

**Comment by chentsulin** [comment]
Sure, `electron-builder` is in our roadmap, so eventually this will be done.
