### ISSUE TITLE
Question: Origin of logs

### ISSUE THREAD

**Issue by bernatfortet** [chentsulin/electron-react-boilerplate#490]
I just started using the boilerplate but I don't get to see the origin of my logs.
I was wondering if there's anyway to see where they come from.

![image](https://cloud.githubusercontent.com/assets/390010/19834843/44ac1f36-9e15-11e6-9261-2a5325b155cf.png)

Thanks!

**Comment by amilajack** [comment]
How can I reproduce this? I've tried logging from the `HomePage` component and it works fine:

<img width="1029" alt="screen shot 2016-10-29 at 11 50 25 pm" src="https://cloud.githubusercontent.com/assets/6374832/19834942/8f610db2-9e32-11e6-9e4f-d46964ed3bf0.png">

**Comment by bernatfortet** [comment]
I found a way to bring the reference back.

I changed this line from `webpack.config.development`
```js
devtool: 'cheap-module-eval-source-map'
```

to:
```js
devtool: 'source-map'
```

I researched a little bit and learnt that it compiles a little bit slower. And it's definitely noticeble. But now I can debug!

**Comment by amilajack** [comment]
I don't think there's a way to fix that. Its a tradeoff between accuracy and speed. The webpack docs explain this tradeoff well.
