### ISSUE TITLE
Proper usage of utils directory.

### ISSUE THREAD

**Issue by yourfavorite** [chentsulin/electron-react-boilerplate#495]
I have some helper functions that I intend to include in a file in the utils directory. Is there a way to integrate the utils folder into webpack or should I just import any utils files to components that need access to the helper functions?

**Comment by amilajack** [comment]
> import any utils files to components that need access to the helper functions?

This is what I recommend

**Comment by yourfavorite** [comment]
Thanks as always @amilajack This is what I'm currently doing. Just wanted to make sure I wasn't missing out on some other magic from this boilerplate. :D

**Comment by amilajack** [comment]
@yourfavorite if this helps, you can always reference [my project](https://github.com/amilajack/popcorn-time-desktop) that is based off this boilerplate. I have a utils directory in [app/utils](https://github.com/amilajack/popcorn-time-desktop/tree/master/app/utils). I can also move faster with that project. So for example, I added electron-builder support about a month or so before it was added to this boilerplate

**Comment by yourfavorite** [comment]
@amilajack Thanks so much! Can't wait to dig into this.
