### ISSUE TITLE
How to add React devtools

### ISSUE THREAD

**Issue by 0x80** [chentsulin/electron-react-boilerplate#5]
Hi, I am struggeling to add the react devtools. I'm hoping you have a clue. Here's a SO post I made with more details...

http://stackoverflow.com/questions/30578963/how-to-add-react-devtools-to-electron-shell

**Comment by chentsulin** [comment]
I already open a issue to electron repo for this, and finally be linked to this issue. 

https://github.com/atom/electron/issues/915

It seems some breaking change in `react-devtools`, so not working in electron now.

**Comment by 0x80** [comment]
Thanks good to know I can stop trying! :)

**Comment by chadobado** [comment]
Any updates on this?  After spending a few hours with it it seems like ```__REACT_DEVTOOLS_GLOBAL_HOOK__``` is not being injected on the created window, so react-devtools has nothing to communicate with.

**Comment by 0x80** [comment]
FYI there is a new beta devtools for React. Seems like a lot has changed. Maybe it helps...

http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html

**Comment by chentsulin** [comment]
I will look into this next week. But #31 #32 have higher priority.

PR welcome.

**Comment by chentsulin** [comment]
Waiting for next release https://github.com/electron/electron/pull/5711

**Comment by jhen0409** [comment]
Closed by #227.
