### ISSUE TITLE
build exe fails to load resources

### ISSUE THREAD

**Issue by barbalex** [chentsulin/electron-react-boilerplate#500]
My project (https://github.com/barbalex/kapla3) works in dev mode.

When I run `npm run package-win` I get this output in the console: https://gist.github.com/barbalex/801c048ba10966af11eb15fb0352fa13

It contains this error:

    ERROR in bundle.js from UglifyJs
    SyntaxError: Unexpected token: punc ()) [./~/username/index.js:23,0]

but finishes.

When I then install the app or run the exe file in `win-unpacked` I get these errors:

    file:///C:/Users/alex/AppData/Local/Programs/Kapla/1.0.0/resources/node_modules/font-awesome/css/font-awesome.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
    file:///C:/Users/alex/AppData/Local/Programs/Kapla/1.0.0/resources/dist/style.css Failed to load resource: net::ERR_FILE_NOT_FOUND
    file:///C:/Users/alex/AppData/Local/Programs/Kapla/1.0.0/resources/dist/bundle.js Failed to load resource: net::ERR_FILE_NOT_FOUND

Am I doing something wrong?

Some information:

- My project was forked from electron-react-boilerplate today
- This happens on Windows 10 and macOS Sierra
- node 7.0.0

**Comment by amilajack** [comment]
Try cloning installing from source and following step 3 in #400. If that works, we know that the issue happened in one of these commits:

<img width="721" alt="screen shot 2016-10-31 at 10 57 32 am" src="https://cloud.githubusercontent.com/assets/6374832/19865293/d790e360-9f58-11e6-88f4-d297592cd99c.png">

**Comment by barbalex** [comment]
Thanks. Did it and get this here after running `npm run dev`:

![error](https://cloud.githubusercontent.com/assets/669783/19867717/300639d6-9fa5-11e6-959e-5fcd3e14cd62.png)

**Comment by barbalex** [comment]
the missed file is definitely there

**Comment by amilajack** [comment]
@jhen0409 seems to be working on a fix for that: https://github.com/chentsulin/electron-react-boilerplate/pull/496.

**Comment by jhen0409** [comment]
> Did it and get this here after running npm run dev:

@amilajack, it looks not related to #496, maybe just haven't run `postinstall` script..

@barbalex, make sure [`postinstall` of package.json](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L18) is passed, currently `app/node_modules` folder is expected.

**Comment by amilajack** [comment]
@barbalex did you install with yarn?

**Comment by barbalex** [comment]
> make sure postinstall of package.json is passed, currently app/node_modules folder is expected.

This is the output of `npm i`:

    PS C:\Users\alex> cd kapla3
    PS C:\Users\alex\kapla3> npm i

    > Kapla@1.0.0 postinstall C:\Users\alex\kapla3
    > concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

    [0] Installing app dependencies for arch x64 to C:\Users\alex\kapla3\app
    [0]
    [1] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0
    [0] install-app-deps exited with code 0
    npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
    npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
    PS C:\Users\alex\kapla3>

So I believe postinstall runs o.k.

I believe to remember there was a problem the first time I ran `npm i`: I got error messages and later on I could see different versions of the dependencies in the two package.json files.

But I think this is o.k. now.

**Comment by barbalex** [comment]
> did you install with yarn?

At first no.

Then after getting problems I thought: try yarn.

I remember getting an error message when running `package-win` after that.
And, being a complete yarn noob I the reverted to using npm.

**Comment by amilajack** [comment]
Yarn isnt very stable with all projects at the moment. I think we should mention the readme

**Comment by amilajack** [comment]
Also can you try cloning from source, clearing npm cache, and testing again (just to be safe).

**Comment by barbalex** [comment]
o.k., I did this on Windows 10:

- clone electron-react-boilerplate to the desktop
- `npm cache clean` (as admin to have the needed rights)
- `npm i`
- `npm rb`

Then:

- `npm run dev`:

Result: runs without error

Then:

- `npm run package-win`

Result: electron-react-boilerplate.exe runs without error!

I guess I will try to port my app to this version of the boilerplate now.

**Comment by barbalex** [comment]
I now did this in my own app:

- `git pull upstream master`
- delete both node_modules folders
- `npm cache clean`
- `npm i`
- `npm rb`
- `build-sqlite3-win64` (this is needed for my app)

Then:

- `npm run dev`

Result: runs without error

Then: 

- `npm run package-win`

Result: This error occurs in the console, just as before:

    file:///C:/Users/alex/kapla3/release/win-unpacked/resources/node_modules/font-awesome/css/font-awesome.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
    file:///C:/Users/alex/kapla3/release/win-unpacked/resources/dist/style.css Failed to load resource: net::ERR_FILE_NOT_FOUND
    module.js:457 Uncaught Error: Cannot find module 'sqlite3'

**Comment by barbalex** [comment]
followed up by https://github.com/chentsulin/electron-react-boilerplate/issues/515 as the font-awesome issue was solved
