### ISSUE TITLE
how to use setup.js

### ISSUE THREAD

**Issue by FTAndy** [chentsulin/electron-react-boilerplate#506]
I see a setup.js file in the folder, how can i use it to reset the project? What command should i use?

**Comment by amilajack** [comment]
What do you mean by reset? Do you mean 'removed all the boilerplate' or 'restore it to the original version of the boilerplate'?

**Comment by FTAndy** [comment]
yes

**Comment by amilajack** [comment]
> yes

Which option?

**Comment by FTAndy** [comment]
I mean how to use the `setup.js` file, `node setup.js` absolutely not work. Need to use any tool to execte the `setup.js` file?

**Comment by amilajack** [comment]
ping @tstringer

**Comment by tstringer** [comment]
@FTAndy you don't directly consume or invoke `setup.js` in any manner. You do `npm run cleanup` in order for `boiler-room-custodian` to clean up the sample code from the boilerplate.

I hope that makes sense!

**Comment by FTAndy** [comment]
@tstringer thanks, then
