### ISSUE TITLE
Releasing for both x86 and x64

### ISSUE THREAD

**Issue by Unforgiven-wanda** [chentsulin/electron-react-boilerplate#507]
Hello,
I am trying to release for both architectures at the same time, however when passing:
`sudo yarn run package -- --asar --version=1.4.4 --ia32 --x64`

Which, according to `electron-builder` docs should give me both.
I only get the x64 version.

I would like to avoid, if possible, having to package from a 32bit machine.

Thank you.

**Comment by jhen0409** [comment]
It should work with `"package-win": "npm run build && build --win --x64 --ia32"`, because `run package -- --ia32` doesn't apply to `build`.

**Comment by amilajack** [comment]
Try running it with npm.

**Comment by Unforgiven-wanda** [comment]
> Try running it with npm.
Same thing. Still only releases the x64 version, on both Windows and Ubuntu.
Even doing `npm run package -- --ia32` still releases only x64 version.

**Comment by amilajack** [comment]
Try updating to the latest release. `package.js` was deprecated a few days ago. We use electron-builder now
