### ISSUE TITLE
Reset router path

### ISSUE THREAD

**Issue by bernatfortet** [chentsulin/electron-react-boilerplate#511]
1. I navigate to a path '/users'
2. I reload app
3. the app now loads on the path '/users' instead of the begning

How can I force the history to be reloaded?

Thanks!

**Comment by amilajack** [comment]
https://github.com/chentsulin/electron-react-boilerplate/issues/108

**Comment by bernatfortet** [comment]
@amilajack I've gone through that other thread a few times but I don't understand what is that I have to do :(

currently I'm using `browserHistory.replace('/')` on the app/index.js

This works for reseting but it's causing some problem with the `window.location`:

Default boilerplate app/index.js
<img width="762" alt="screen shot 2016-11-03 at 7 37 10 pm" src="https://cloud.githubusercontent.com/assets/390010/19995979/3f882646-a200-11e6-9ec3-039131f27bbb.png">

With `browserHistory.replace('/')` 
<img width="767" alt="screen shot 2016-11-03 at 8 00 36 pm" src="https://cloud.githubusercontent.com/assets/390010/19995980/3fb5319a-a200-11e6-967f-fc8514afb908.png">

This is causing problems when it comes to loading images


Here's how I have app/index.js setup
```js
// @flow
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { Router, browserHistory, hashHistory } from 'react-router';

import { syncHistoryWithStore } from 'react-router-redux';
import routes from './routes';
import configureStore from './store/configureStore';

browserHistory.replace('/')

const store = configureStore();
const history = syncHistoryWithStore(hashHistory, store);

render(
  <Provider store={store}>
    <Router history={history} routes={routes} />
  </Provider>,
  document.getElementById('root')
)
```

**Comment by amilajack** [comment]
@bernatfortet sorry for the late response.

I assume you're new to the react/redux community. Welcome aboard! I would recommend checking out the react/redux docs.

1. With `browserHistory.replace('/')`, you're trying to update the API browser's history without redux knowing about it. Reference the react-router docs for setting the route's default index path

2. > I've gone through that other thread a few times but I don't understand what is that I have to do :(

The discussion is about saving react's state to the disk. React's state, which is managed by redux, will be persisted to a location on the disk. When the app is reopened, the app will check the disk for the state, if it exists. If it does, that state will be used.

**Comment by bernatfortet** [comment]
Thanks, yeah I'm new to the react/redux community. And some things seem to be a little bit out of my grasp still :/

I'm going to try to solve the original problem which is that if I reload a route I want all the information to be there without having to go through the index.
Solving that would allow me to avoid the need for reseting the router path.

**Comment by amilajack** [comment]
> I'm going to try to solve the original problem which is that if I reload a route I want all the information to be there without having to go through the index.

Make sure that you are using redux. If you are, restoring the state will come easy
