### ISSUE TITLE
ERROR in Loader on npm run hot-server

### ISSUE THREAD

**Issue by barbalex** [chentsulin/electron-react-boilerplate#513]
When I run `npm run hot-server` I get this error:

    ERROR in Loader C:\Users\alex\kapla3\node_modules\url\url.js?limit=10000&mimetype=application/font-woff didn't return a function
     @ ./~/css-loader?sourceMap!./~/font-awesome/css/font-awesome.css 6:479-532

    ERROR in Loader C:\Users\alex\kapla3\node_modules\url\url.js?limit=10000&mimetype=application/font-woff didn't return a function
     @ ./~/css-loader?sourceMap!./~/font-awesome/css/font-awesome.css 6:563-615

    ERROR in Loader C:\Users\alex\kapla3\node_modules\url\url.js?limit=10000&mimetype=application/octet-stream didn't return a function
     @ ./~/css-loader?sourceMap!./~/font-awesome/css/font-awesome.css 6:645-696

    ERROR in Loader C:\Users\alex\kapla3\node_modules\url\url.js?limit=10000&mimetype=image/svg+xml didn't return a function
     @ ./~/css-loader?sourceMap!./~/font-awesome/css/font-awesome.css 6:730-781
    webpack: bundle is now VALID.

This happens in [my project](https://github.com/barbalex/kapla3) on Windows 10 and macOS Sierra but not when I create a new project with electron-react-boilerplate.

Which is not too clear to me as I based my project on electron-react-boilerplate a few days ago and have kept it updated as described [here](https://github.com/chentsulin/electron-react-boilerplate#how-to-keep-the-boilerplate-updated).

Actually: This happens since I pulled the [last changes](https://github.com/chentsulin/electron-react-boilerplate/pull/496).

**Comment by jhen0409** [comment]
```
ERROR in Loader C:\Users\alex\kapla3\node_modules\url\url.js?limit=10000&mimetype=application/font-woff didn't return a function
```

It looks webpack loaded `url` module instead of `url-loader`... but it can't reproduce on my machine.

Can you edit [webpack.config.development.js#L55-L59](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.development.js#L55-L59) (change `url` to `url-loader`), and check it works?

**Comment by barbalex** [comment]
my bad: In package.json I was missing `url-loader`. It now works unchanged.

Thanks for great help :-) and sorry for bugging you :-(
