### ISSUE TITLE
build fails to load resources

### ISSUE THREAD

**Issue by barbalex** [chentsulin/electron-react-boilerplate#515]
My project (https://github.com/barbalex/kapla3) works in dev mode.

When I run `npm run package-win` (on Windows 10) or `npm run package` (on macOS Sierra) and install the app or run the exe file in `win-unpacked` on Windows or the app file on macOS I get these errors:

    file:///C:/Users/alex/kapla3/release/win-unpacked/resources/dist/style.css Failed to load resource: net::ERR_FILE_NOT_FOUND
    module.js:457 Uncaught Error: Cannot find module 'sqlite3'

Am I doing something wrong?

Some information:

- My project was forked from electron-react-boilerplate a few days ago. I tried to keep it updated by following https://github.com/chentsulin/electron-react-boilerplate#how-to-keep-the-boilerplate-updated
- Happens on Windows 10 and macOS Sierra
- node 6.9.1

**Comment by jhen0409** [comment]
Currently we have [two package.json structure](https://github.com/chentsulin/electron-react-boilerplate#module-structure], for webpack externals, please make sure sqlite3 dependency is in app/package.json and app/node_modules.
