### ISSUE TITLE
Discussion: Fixes for Debugger/Sourcemaps

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#516]
This is a discussion about the solutions for the fixing the debugging functionality. Inspired by https://github.com/chentsulin/electron-react-boilerplate/issues/379

**See these discussions for ideas**
* https://github.com/mxstbr/react-boilerplate/issues/1087#issuecomment-252738363

**Comment by aguynamedben** [comment]
Is there a way to get sourcemaps to work correctly with this boilerplate? I'm on master (2068ea0) and if I throw an exception in the Home component I don't see it clearly pointed to...

```jsx
export default class Home extends Component<Props> {
  props: Props;

  render() {
    throw new Error('ben broke it');
    return (
      <div className={styles.container} data-tid="container">
        <h2>Home</h2>
        <Link to={routes.COUNTER}>to Counter</Link>
      </div>
    );
  }
}
```

<img width="920" alt="developer_tools_-_file____users_ben_code_electron-react-boilerplate_app_app_html_and_hello_electron_react__and_discussion__fixes_for_debugger_sourcemaps_ _issue__516_ _chentsulin_electron-react-boilerplate" src="https://user-images.githubusercontent.com/107841/44817553-918c3b80-ab9a-11e8-8325-626fdb499555.png">

In my app, there's an error happening within an anonymous function in a large class, and it's difficult to track down. I have the stack trace but the line number would be nice.

Thanks for working on this great boilerplate. Let me know if there's an avenue I can pursue to get sourcemaps working better.
