### ISSUE TITLE
Discussion: Create gitter chat

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#519]
@chentsulin  would be great for creating a gitter.im chat for this project. That would help resolve a lot of issues about how to use this project. IMO, its better than having users make a new issue for every question they have

Thoughts?

**Comment by dustintownsend** [comment]
I haven't used gitter before. Are you able to search easily? The one thing I like about issues is they are easily searchable so most questions I have can be answered with a few searches. 

I can also see the benefit to moving to something like gitter for questions and discussion. Seems like something GitHub should build in.

**Comment by chentsulin** [comment]
Ok. I think we can try it and see if it can give some helps to people.
https://gitter.im/electron-react-boilerplate/Lobby

**Comment by amilajack** [comment]
Thanks @chentsulin !
