### ISSUE TITLE
External module in node main

### ISSUE THREAD

**Issue by zapkub** [chentsulin/electron-react-boilerplate#524]
Hi,  I need to use some unsupport webpack library ( such as socket io ) with Electron main

Anyway I follow the instruction that tell me to move all those library to 

webpack.config.base as external modules 

```
 externals: [
        // put your node 3rd party libraries which can't be built with webpack here
        // (mysql, mongodb, and so on..)
        'socket.io',
        'node-xlsx'
    ] 
```
everything work fine in development
but after packaging it give me an error

![screen shot 2559-11-08 at 01 44 20](https://cloud.githubusercontent.com/assets/4373581/20070955/0c7eb212-a555-11e6-8253-986e6dd0020b.jpg)

Any step missing ?

Thank for help !

**Comment by dustintownsend** [comment]
@zapkub Do you have socket.io in the app/package.json dependencies? Or in the top-level package.json?

**Comment by zapkub** [comment]
@dustintownsend I have it only in top-level one, after I put it in app/package.json it work perfectly now ! thanks for help!

**Comment by dustintownsend** [comment]
@zapkub could add something like:
Libraries included in `externals` should be listed under `dependencies` in `./app/package.json`.

**Comment by jhen0409** [comment]
> Do we need to add this into document ? I can't find this one.

Actually it's [here](https://github.com/chentsulin/electron-react-boilerplate#module-structure), there are two sections to explain this, but title is wrong, I'll update it.

**Comment by dustintownsend** [comment]
@jhen0409 what do you think about putting a see Modules Structure link in the Externals section?

**Comment by zapkub** [comment]
I agreed with @dustintownsend or maybe update a line of comment in config ?
```
externals: [
  // put your node 3rd party libraries which can't be built with webpack here (mysql, mongodb, and so on..)
  // and also add it to app/package.json
]

```

**Comment by jhen0409** [comment]
> what do you think about putting a see Modules Structure link in the Externals section?

@dustintownsend, I agreed.

However, I think we can just recommend add dependency to `app/package.json`, for webpack externals, we can take dependencies of `app/package.json`:

```js
externals: Object.keys(require('./app/package.json').dependencies)
```

**Comment by amilajack** [comment]
Closing due to no response

**Comment by frankgo81** [comment]
> I do the same but still the external depedencies are not getting resolved in development mode. It simply says cannot find module **node-json-db** even webpack has marked it like **var jsondb = require('node-json-db')**.
> 
> The reason behind this I see is, my **app/node_modules** is not being used to resolve the modules in dev mode.

I am having the same issue, but w. mysql
