### ISSUE TITLE
better explain project files and the tools used

### ISSUE THREAD

**Issue by forman** [chentsulin/electron-react-boilerplate#530]
Thanks for this nice starting point for creating Electron/React desktop apps! I guess a number of the many users starting from this boilerplate may be electron and/or react (or even JS) beginners and are using it, because it provides a valuable preselection of tools and configurations. It would be great for such users to read about the choices made, e.g. why the project structure is like it is now, what it's individual files are used for, and why this very technology stack has been selected.

**Comment by amilajack** [comment]
Lets merge this into https://github.com/chentsulin/electron-react-boilerplate/issues/530

**Comment by forman** [comment]
But #530 is this one?!

**Comment by amilajack** [comment]
My bad. I meant #518
