### ISSUE TITLE
What is the `npm run build` for?

### ISSUE THREAD

**Issue by nikgraf** [chentsulin/electron-react-boilerplate#532]
It's not explained in the Readme. Do I need it to package my app or why do I have these separate build steps: `build-renderer` & `build-main`?

**Comment by jhen0409** [comment]
In addition to renderer, we also build [main process](https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/main.development.js) via webpack. ([config](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.electron.js))

**Comment by nikgraf** [comment]
Hmm, so should I run `npm run build` before I package or when should I use it?

**Comment by jhen0409** [comment]
> should I run npm run build before I package

If you just want package app, you don't need to run `npm run build` before. ([package script](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L20))

> when should I use it?

It should use for production test -  `npm start` and `npm run test-e2e`, it doesn't mention that in Readme. 😂
