### ISSUE TITLE
webpack devserver

### ISSUE THREAD

**Issue by vvinton** [chentsulin/electron-react-boilerplate#533]
Hi All, is it possible to start example as web app as well, or its starts desktop only? Can someone hint me how that can be enabled with current configuration?

Thank you,
Vitaliy

**Comment by amilajack** [comment]
Are you asking something along the lines of https://github.com/chentsulin/electron-react-boilerplate/issues/80

**Comment by vvinton** [comment]
amilajack, you are right. thank you for pointing on that.
