### ISSUE TITLE
publishing to mac app store

### ISSUE THREAD

**Issue by chunkiat82** [chentsulin/electron-react-boilerplate#537]
Hi, 

Can you share the settings for publishing this app to mas?

I have this setting below, care to comment?

Thanks!

```json
"build": {
    "appId": "com.foo.bar",
    "category": "public.app-category.productivity",
    "mac": {
      "target": "mas",
      "identity": "XXXXXXXX",
      "icon": "resources/icon.icns",
      "category": "public.app-category.productivity"
    }
```

**Comment by chunkiat82** [comment]
I get the following error

ERROR ITMS-90287: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.team-identifier' in 'com.foo.bar.pkg/Payload/electron-react-boilerplate.app/Contents/MacOS/electron-react-boilerplate'."

**Comment by chunkiat82** [comment]
just packing to dmg, works fine.

**Comment by amilajack** [comment]
`XXXXXXXX` is your apple certificate. You need an apple developer license to publish to app store

**Comment by chunkiat82** [comment]
@amilajack yes, I put to XXXX and com.foo.bar as examples only. 

I have managed to sign it without problems. And I have the Apple Certificate and License. This is my first Mac App but I have published iOS apps. 

Do you have more examples on the settings or documentation on the signing procedure?

I am more curious about the one particular error above when I uploaded to the store (it's not a build problem)

Thanks!

**Comment by amilajack** [comment]
I would recommend checking out the [electron-builder's docs](https://github.com/electron-userland/electron-builder/wiki/Code-Signing) for more information. I think this is an electron-builder specific issue.

**Comment by chunkiat82** [comment]
ok thanks

**Comment by chunkiat82** [comment]
@amilajack

FYI This is issue I am facing

https://github.com/electron-userland/electron-builder/issues/897

**Comment by jamesporter** [comment]
One thing I found extremely confusing is that that mas build is apparently not meant to run locally. You can do a `mas-dev` target but this will seemingly require a separate provisioning profile.

I find this Apple signing stuff is extremely confusing (and I've done iOS development for years), gave up on whole thing at least 3 times. I'm assuming very few people are actually distributing electron apps via app store given lack of issues/documentation around it. For non-App store signing was a lot more straightforward.
