### ISSUE TITLE
react-router and history api incompatibility 

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#542]
I'm getting this error in my packaged app on Windows 7 x64 at Router.js?cf42:111:

`Uncaught TypeError: Cannot read property 'getCurrentLocation' of undefined`  

The code on that line is:    

`!history.getCurrentLocation ? process.env.NODE_ENV !== 'production' ? (0, _invariant2.default)(false, 'You have provided a history object created with history v2.x or ' + 'earlier. This version of React Router is only compatible with v3 ' + 'history objects. Please upgrade to history v3.x.') : (0, _invariant2.default)(false) : void 0;`

Amila, since I suspect you'll be the first one here, thank you very much for your time in advance.

**Comment by amilajack** [comment]
Try making the following change:

https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.development.js#L18

And see what the new error messages are.

**Comment by Slapbox** [comment]
Ah actually I had already tried that. Same error unfortunately. I'm on build commit a5382241a1fe40099289c73a96b6435c0c319847.

Sorry, not sure if there's a better way to reference that.

**Comment by amilajack** [comment]
Hmm. What code do you have in `Router.js`?

**Comment by Slapbox** [comment]
Sorry I should have included that from the get go. It's very basic and mirrors the repo:

```
// @flow
import React from 'react';
import { Route, IndexRoute } from 'react-router';
import App from './containers/App';
import MyMain from './containers/MyMain';

export default (
	<Route path="/" component={App}>
		<IndexRoute component={MyMain} />
	</Route>
);

```

**Comment by amilajack** [comment]
And also what do devtools show? (line numbers, stack trace)

**Comment by Slapbox** [comment]
```
Router.js?cf42:112 - Uncaught TypeError: Cannot read property 'getCurrentLocation' of undefined
createTransitionManager	@	Router.js?cf42:112
componentWillMount	@	Router.js?cf42:119
performInitialMount	@	ReactCompositeComponent.js?cd59:350
mountComponent	@	ReactCompositeComponent.js?cd59:257
mountComponent	@	ReactReconciler.js?6bfa:47
performInitialMount	@	ReactCompositeComponent.js?cd59:370
mountComponent	@	ReactCompositeComponent.js?cd59:257
mountComponent	@	ReactReconciler.js?6bfa:47
performInitialMount	@	ReactCompositeComponent.js?cd59:370
mountComponent	@	ReactCompositeComponent.js?cd59:257
mountComponent	@	ReactReconciler.js?6bfa:47
mountComponentIntoNode	@	ReactMount.js?2f23:105
perform	@	Transaction.js?6dff:138
batchedMountComponentIntoNode	@	ReactMount.js?2f23:127
perform	@	Transaction.js?6dff:138
batchedUpdates	@	ReactDefaultBatchingStrategy.js?ef70:63
batchedUpdates	@	ReactUpdates.js?ce09:98
_renderNewRootComponent	@	ReactMount.js?2f23:321
_renderSubtreeIntoContainer	@	ReactMount.js?2f23:402
render	@	ReactMount.js?2f23:423
createProvider	@	index.js?dadc:78
(anonymous function)	@	index.js?dadc:212
(anonymous function)	@	async.js?b52e:484
nextTask	@	async.js?b52e:5195
(anonymous function)	@	async.js?b52e:5202
apply	@	async.js?b52e:41
(anonymous function)	@	async.js?b52e:76
(anonymous function)	@	async.js?b52e:988
(anonymous function)	@	storage.js?62ae:90
nextTask	@	async.js?b52e:5208
(anonymous function)	@	async.js?b52e:5202
apply	@	async.js?b52e:41
(anonymous function)	@	async.js?b52e:76
(anonymous function)	@	async.js?b52e:988
(anonymous function)	@	storage.js?62ae:73
tryToString	@	fs.js:455
readFileAfterClose	@	fs.js:442
```

![image](https://cloud.githubusercontent.com/assets/6835891/20247931/542b10f0-a9a7-11e6-8967-29f479c4ffaa.png)

As far as I can tell there's nothing wrong with my index.js where I am syncing the history with the store, and there's no issue with my configureStore.prod.js either (as far as I can see.)

**Comment by amilajack** [comment]
Seems like its related to [this](https://github.com/ReactTraining/react-router/blob/master/upgrade-guides/v2.0.0.md). We might need to provide an upgrade.

Try this: 
> Please upgrade to history v3.x

**Comment by Slapbox** [comment]
Unfortunately didn't help, but that's a nice tool to know about.

**Comment by utsavig** [comment]
I am getting same error with react-router 3.0.0. Slapbox, did you manage to fix this?

**Comment by Slapbox** [comment]
No I didn't unfortunately. It's been a major roadblock for me.

**Comment by amilajack** [comment]
I've done a fresh clone and reinstalled dependencies and can't seem to reproduce the issue. @Slapbox have you tried a fresh clone?

**Comment by chentsulin** [comment]
@Slapbox @utsavig update `react-router-redux` to `v4.0.7` should fix this.

**Comment by Slapbox** [comment]
Unfortunately that's the version I'm using and my routes and store setups are virtually identical to the versions in the repo. I have matched all my packages to the versions in the repo, and also tried the latest versions of all the packages, but the same error always.

**Comment by amilajack** [comment]
Did you try https://github.com/chentsulin/electron-react-boilerplate/issues/542#issuecomment-261794414

**Comment by chentsulin** [comment]
@Slapbox what is the version of your `node_modules/history`? `history.getCurrentLocation` only exists between `v3.0.0-0` ~ `v4.0.0-2`.


3.0.0-0
Added history.getCurrentLocation() method
https://github.com/mjackson/history/blob/master/CHANGES.md#300-0


v4.0.0-2
Removed history.getCurrentLocation()
https://github.com/mjackson/history/blob/master/CHANGES.md#v400-2

**Comment by chentsulin** [comment]
`Cannot read property 'getCurrentLocation' of undefined` error message pointed out that `history` is `undefined` in `Router`'s `props`: https://github.com/ReactTraining/react-router/blob/master/modules/Router.js#L75

You should check your passed history correctly to Router (maybe you can log history before pass it to Router):
https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/index.js#L16

**Comment by utsavig** [comment]
I managed to fix the error.  I hadn't defined "history" attribute on the <Router> tag. My Routes looked 
something like
  <Router>
    <Route path='/' component={Main}>
      <IndexRoute component={Home}/>
    </Route>
  </Router>

as soon as I defined "history" attribute error was gone.  Following is what my current code looks like and works without any errors. (I am still using react-router 3.0.0)

var ReactRouter = require('react-router');
var hashHistory = ReactRouter.hashHistory;
  <Router history={hashHistory}>
    <Route path='/' component={Main}>
      <IndexRoute component={Home}/>
    </Route>
  </Router>

**Comment by chentsulin** [comment]
Note that react-router v3 no longer use hash history as default (v2 with warning), so you must pass history in.

**Comment by Slapbox** [comment]
I was really hopeful in that solution, but unfortunately I have the same error here. The weirdest thing is that hashHistory is actually coming up defined and I'm passing it, but I still get the same results.

![image](https://cloud.githubusercontent.com/assets/6835891/20528374/f94cfe2e-b099-11e6-90a5-eae63eb8cac0.png)

**Comment by chentsulin** [comment]
It's difficult to help you if we didn't get a reproduce example here. Your app implement history in a entire different way. We pass history to router here: https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/index.js#L16-Lundefined

and link it to redux: https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/store/configureStore.development.js#L20

**Comment by Slapbox** [comment]
Thanks a lot for that info chentsulin! I'll try to implement it in a way that's in line with what you showed me above and report back if it still doesn't work in that configuration.

**Comment by Slapbox** [comment]
Okay so it turns out I was passing history that was the whole time, and it is version 3.0.0. So I restored my code to only pass history in this way and here's my code. It's slightly different, in that it passes in a saved state to configureStore, so I use functions and promises, but the structure is essentially the same. I also tried packaging a version where I don't pass in my saved state, and I get the same result.

```
// @flow
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import storage from 'electron-json-storage';
import { Router, hashHistory } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';
import axios from 'axios';

import * as appUtils from './utils/functions';
import configureStore from './store/configureStore';
import routes from './routes';
import './app.css';
var CryptoJS = require("crypto-js");

let appState;
let stateKeyPresent;
let createStore;
var history;
let userEmail;


function createStoreFunction() {
	debugger;
	console.log(hashHistory);
	createStore = configureStore(appState);
	history = syncHistoryWithStore(hashHistory, createStore);
}


function createProvider() {
	debugger;
	render(
	  <Provider store={createStore}>
	    <Router history={history} routes={routes} />
	  </Provider>,
	  document.getElementById('root')
	);
}

storage.keys(function(err, keys) {
	
	if (err) throw err;
	//	Check for 'state' key in electron-json-storage
	for (var i = 0; i < keys.length; i++) {
		if (keys[i] === 'state') {
			stateKeyPresent = keys[i];
		}
	}

	//	Parse state from json file
	storage.get('state', function(err, data) {
		appState = JSON.parse(data);
	});

	var promise = new Promise((resolve, reject) => {
		createStoreFunction();
  	resolve();
  });
	
	promise.then(function() {
		createProvider()
	});
});
```

**Comment by Slapbox** [comment]
Please consider reopening.

Based on the code I have here, I see no substantial differences from the implementation in the repo.

Even when passing in no state to the store creator as the repo version does, I get the same issues.

**Comment by amilajack** [comment]
If the [fresh clone method](https://github.com/chentsulin/electron-react-boilerplate/issues/542#issuecomment-261794414) did work for you, the problem with the code is not with the boilerplate. Our tests also end to end tests arent failing so that means that it should work on both windows and mac without any errors regarding the router.
