### ISSUE TITLE
Sound files

### ISSUE THREAD

**Issue by nlemoine** [chentsulin/electron-react-boilerplate#549]
Hi, 

I made an app with some notification sounds, basically, mp3 files played with HTML5 `Audio`. Works fine in dev (`npm run dev`) and production (`npm run build && npm run start`) mode. 
But when I package the app, files aren't found: `full/path/app/Contents/Resources/app.asar/assets/sounds/notification.mp3` 

What should I do to have these files available in package?

**Comment by nlemoine** [comment]
(I'm using the very last version of `electron-react-boilerplate`)

**Comment by jhen0409** [comment]
Try add it to [`build.files` of package.json](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L44) or `dist/`.

**Comment by nlemoine** [comment]
Thanks! It worked perfectly. 

Might be worth mentioning this in the docs for "non webpackable" files. ;)
