### ISSUE TITLE
Add: PyInstaller

### ISSUE THREAD

**Issue by aj-ptw** [chentsulin/electron-react-boilerplate#551]
All I have been building python binaries within this framework, I just rebased off this actually so the implementation would be pretty easy. Would y'all entertain a viable way to use python natively? 

AJ

**Comment by amilajack** [comment]
I cant see most of the users of this boilerplate benefiting from this at the moment. Closing for now

**Comment by aj-ptw** [comment]
Ok! Lmk if you change your mind!
