### ISSUE TITLE
Basic IPC functionality boilerplate

### ISSUE THREAD

**Issue by jefffriesen** [chentsulin/electron-react-boilerplate#555]
I would love to see an example in this boilerplate that shows IPC communication.

Running non-UI-blocking background processes are an awesome feature of Electron. Just to be clear, this is different than an async request (those don't block the UI). 

Here is an example that relies on an out-of-date library: https://github.com/smith-kyle/electron-background-process-app

**Comment by amilajack** [comment]
Thinking of adding this to the video series

**Comment by amilajack** [comment]
Added to release todo list. Lets merge this conversation into #504
