### ISSUE TITLE
Bug: Icons not loading in production

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#559]
The icons don't seem to load in production:
<img width="1032" alt="screen shot 2016-11-20 at 9 39 32 am" src="https://cloud.githubusercontent.com/assets/6374832/20464867/42f518ea-af05-11e6-906e-224811d74234.png">

@jhen0409 @dustintownsend thoughts on this? From what I see, I think this happened after https://github.com/chentsulin/electron-react-boilerplate/commit/b59ad178a79769e60a22d213e9ba6e442353d9f3

**Comment by jhen0409** [comment]
It looks #558 broken it:

![2016-11-21 2 27 32](https://cloud.githubusercontent.com/assets/3001525/20465192/8a17a4da-af92-11e6-96ba-1ba873d33d64.png)

**Comment by amilajack** [comment]
How did you open devtools in production? I tried using the previous method but it didn't work

**Comment by amilajack** [comment]
Fixed after reverting
