### ISSUE TITLE
Is the autoUpdater functional?

### ISSUE THREAD

**Issue by Unforgiven-wanda** [chentsulin/electron-react-boilerplate#562]
Hello,
I am wondering if Electron's autoUpdater would work once this app is built. I believe that it necessitates a `.nupkg` file, however once built the app only generates an `.exe` installer.

I have seen that is it mentionned in this [issue](https://github.com/chentsulin/electron-react-boilerplate/issues/504). Does that mean that at the moment it isn't available?

Thank you.

**Comment by amilajack** [comment]
It does not work out of the box yet. This is planned for an upcoming release

**Comment by datnordstrom** [comment]
Is this still in the works?

**Comment by amilajack** [comment]
No. I closed this because its already in https://github.com/chentsulin/electron-react-boilerplate/issues/504
