### ISSUE TITLE
fresh install doesn't seem to work

### ISSUE THREAD

**Issue by aequasi** [chentsulin/electron-react-boilerplate#563]
<img width="1020" alt="image 2016-11-21 at 20 01 44" src="https://cloud.githubusercontent.com/assets/896295/20510481/6bae3ac0-b025-11e6-8548-5d40797ac311.png">

I've tried two different times now.

Cloned, cd in, `npm install`, `npm run dev`, white page with console error 404ing on dist/bundle.js

```
$ node -v
v6.2.2
```

**Comment by aequasi** [comment]
Hmmm, apparently something else was running on 3000, causing it to not work.

**Comment by amilajack** [comment]
@jhen0409 I can't to find the PR that allowed for automatic port resolution. What happened to it?
