### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by Unforgiven-wanda** [chentsulin/electron-react-boilerplate#571]
Hello again,
I'm having an issue with the drag & drop functionality. Trying to drag and drop a file from my file explorer into the window does not work. Instead, the cursor becomes a `"no-drop"` one. I wasn't aware that there was such an issue when merging Electron & React. In a simple Electron app, dropping a file opens it inside the window. Searching for possible solutions hasn't yielded anything worth mentioning. I've opened this issue, but I'm not sure it is specific to this boilerplate.

Is there some way to remedy this?
Thank you.

**Comment by amilajack** [comment]
This is not specific to this boilerplate. We don't have any drag and drop functionality. That is electron and react specific

**Comment by Slapbox** [comment]
@amilajack is this still a universal issue in development? I have no issues in production, but not being able to drag and drop in development makes some things a bit difficult.

**Comment by amilajack** [comment]
Will reopen this. Open to solutions for this

**Comment by Slapbox** [comment]
@amilajack do you have any ideas about the cause of this? I'm not even sure where to look, but I'll be happy to investigate if you have anything that could point me off in the right direction.

**Comment by amilajack** [comment]
The [docs](https://electronjs.org/docs/tutorial/native-file-drag-drop) seem to say something about this. But i've never actually experience this issue before because i haven't worked with drag/drop functionality before
