### ISSUE TITLE
Components not rendered

### ISSUE THREAD

**Issue by teckays** [chentsulin/electron-react-boilerplate#575]
I have cloned the repo, followed instructions, ran the app `npm run dev`, the boilerplate app was not rendered, the only think I got was a white background. Did a `npm run cleanup` and inserted a custom tag in `/app/components/Home.js` and restarted, same result, none of the components are rendered. In debugger, the deepest node I see is `<div id="root"></div>`

- clean `git clone`
- clean `npm install`
- `npm run dev`

results in:
![Screenshot](http://image.prntscr.com/image/14831ef768524634b640e30b53e51656.png)

**Comment by amilajack** [comment]
What is the error in the conosle?

**Comment by teckays** [comment]
@amilajack ![Screenshot](http://image.prntscr.com/image/1f1b012d1fad4bf68ee4e8a0fd2b078c.png)

**Comment by teckays** [comment]
OK, I know what the error is. In another terminal I had another project running on the same port `3000`, wonder why there wasn't an `EADDRINUSE` error. Works now!
