### ISSUE TITLE
Something wrong with router

### ISSUE THREAD

**Issue by theWaR13** [chentsulin/electron-react-boilerplate#580]
Hello. I'm developing an application and i noticed that LOCATION_CHANGE called twice all the time. I tried to find a bug in my code but it seems to be ok. Then i decided to check your example app and i can see the same situation here. When you go to the counter page, LOCATION_CHANGE called 2 times. Is it electron bug or what? Thanks.

UPD. Got the problem, thanks.

**Comment by amilajack** [comment]
@theWaR13 did you resolve this?

**Comment by theWaR13** [comment]
@amilajack yes. Sorry for this issue.

**Comment by amilajack** [comment]
How did you solve it? Wondering so that I can help people who experience this issue in the future

**Comment by theWaR13** [comment]
@amilajack i don't know to be honest :) I decided to start again and my problem has gone. I guess i should use shouldComponentUpdate to prevent useless render.

**Comment by amilajack** [comment]
@theWaR13 should this be closed?

**Comment by theWaR13** [comment]
@amilajack well, i guess no. This is not the best solution. Because every time you start packaged application you should launch express. Probably there should be another solution. Anyway i said about the problem and you can close this issue if you want.

**Comment by yayolius** [comment]
@theWaR13  This is not a bug, i checked the issue, and what happens is you have 2 events, a PUSH event and a PULL event both related to LOCATION_CHANGE. 

Is just that you are telling router to change in one event and the other event is router telling you that is getting the location from the queue.

**Comment by theWaR13** [comment]
@yayolius thanks for your answer. The problem is that in componentWillMount i make a request and it's called twice. Should i use shouldComponentUpdate to prevent such behaviour?
