### ISSUE TITLE
Do not build the NSIS installer

### ISSUE THREAD

**Issue by Unforgiven-wanda** [chentsulin/electron-react-boilerplate#586]
Hello,
I would like to be able to generate my app without afterwards building the NSIS Installer. - I am using my own Squirrel Installer in my case.

Is it possible?
Thank you.

**Comment by Unforgiven-wanda** [comment]
Never mind. I found out how: in my `package.json` file
```
    "win": {
      "target": "dir"
    },
```
Good evening.

**Comment by amilajack** [comment]
Instead of creating a new issue for each issue or question you have, try using the gitter chat. We want to keep issues for legitimate confirmed issues.

**Comment by Unforgiven-wanda** [comment]
I wasn't aware there was a Gitter for this repo. Apologies.

**Comment by amilajack** [comment]
No worries. It was created rather recently
