### ISSUE TITLE
System environment variables in packaged app?

### ISSUE THREAD

**Issue by mylanconnolly** [chentsulin/electron-react-boilerplate#587]
I am pretty new at Electron so I might be missing something basic, but I wrote a module which I use to load and save files in a directory. The directory's path is dependent upon the platform (it's configuration files, so in macOS I'd want them in `$HOME/Library/Preferences/[dir]`, in Linux I'd want them in `$HOME/.config/[dir]` and in Windows I'd want them in `%USERPROFILE%\AppData\[dir]`.

This behavior works great in development, however when I package the application I get an error message that led me to do some debugging. What I found is that the error stems from `process.env` not being populated with anything at runtime (I think it's just what webpack compiled in. For reference, `process.env` looks like:

```js
{NODE_ENV: "production"}
```

When I run it in development, `process.env` is populated with all the system and user variables I'd expect, including the ones I care about most (`USERPROFILE` / `HOME`, depending on the platform).

Platform detection works as expected, just variables aren't getting populated.

Is this something I can do anything about?

Thanks, and this boilerplate has been great at helping me wrap my head around a lot of what's required to get an Electron app up and running.

**EDIT**

I think I found a neat package ([electron-settings](https://github.com/nathanbuchar/electron-settings)), which removes the initial need, but I think I am still curious about the environment variables. I might want to use them in the future, and was just curious if this is possible or not.

**Comment by amilajack** [comment]
This is very possible. I've [built an example app](https://github.com/amilajack/popcorn-time-desktop) that adds environment variables in electron. I'm using [dotenv](https://github.com/motdotla/dotenv) to load env vars. Also I would recommend checking out https://github.com/sindresorhus/electron-config

**Comment by mylanconnolly** [comment]
Thanks for the example and explanation.

It seems like the dotenv package is used to define environment variables manually (or I could set defaults) What I was hoping to accomplish is introspect the running system to some degree using environment variables set by the operating system.

I think I might need to go about that a different way, but for now I'm just going to settle on a configuration page and saving the options using the package I mentioned (though the one you specified seems to accomplish the same thing, so thanks for the additional option!).

Initially, I think my bigger problem was looking at this problem the wrong way (not really used to GUI applications, almost all of my work is in CLI stuff and servers, which I tend to prefer configuring using environment variables as much as possible).
