### ISSUE TITLE
How can I run react page in chrome, when I run : `npm run hot-server`

### ISSUE THREAD

**Issue by doulmi** [chentsulin/electron-react-boilerplate#590]
After running `npm run hot-server`, I type `localhost:3000` in chrome, but get `Cannot GET /`

Can someone help? I want to build an application can run both in electron and in navigator.

Maybe I should add `app.router('/', ...)` in server.js ? But I don't know how to do it.

**Comment by amilajack** [comment]
This boilerplate wasnt intended to be run inside chrome. See issue https://github.com/chentsulin/electron-react-boilerplate/issues/80
