### ISSUE TITLE
Remote is undefined

### ISSUE THREAD

**Issue by IgorGee** [chentsulin/electron-react-boilerplate#591]
I'm trying to use the `dialog` API. I've spent hours looking at past solutions to no avail.

I try to call upon the dialog object after this code:

```
import { remote } from 'electron'
const dialog = remote.dialog
```

This yields `TypeError: Cannot read property 'dialog' of undefined`.

I'm trying to call this from a React component.

I've also tried importing `dialog` without `remote`, but then `dialog` is `undefined`.

**Comment by Piom** [comment]
Try 
const {dialog} = require('electron').remote;

**Comment by IgorGee** [comment]
Same result

#127 Seems to be a similar issue. The only difference being that I'm importing them from a plain React component. I don't know if the APIs changed drastically from that time.

**Comment by jhen0409** [comment]
Are you run it on test? If yes, because it just got binary path by `require('electron')` ([electron-prebuilt/index.js](https://github.com/electron-userland/electron-prebuilt/blob/master/index.js)). Otherwise it's not possible on renderer process of electron I think.

**Comment by IgorGee** [comment]
@jhen0409 
Ohh yes, I am running it on a test.

Running the dev scripts worked :)
Thank you!!!

**Comment by jhen0409** [comment]
@IgorGee if you want it also work in test, please see https://github.com/chentsulin/electron-react-boilerplate/issues/573#issuecomment-263033090.

**Comment by IgorGee** [comment]
Hmm, simply replacing `mocha` with `electron-mocha` didn't solve the issue in test.

**Comment by IgorGee** [comment]
I figured it out. I have to remove the require for `jsdom-setup.js`.

**Comment by sanzhardanybayev** [comment]
Since new verions, **electron** doesn't let you to access **remote module**. In order to get access to it, you need to enable it by setting **enableRemoteModule** to **true** in **webPreferences** property when instantiating **BrowserWindow** . Here's an official solution:
```
 const mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    icon: getAssetPath('logo.png'),
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true,
    },
  });
  ````
