### ISSUE TITLE
Full source code contained in release build

### ISSUE THREAD

**Issue by huesforalice** [chentsulin/electron-react-boilerplate#592]
I'm new to electron, so I may be missing something, so please forgive me if this does not make any sense. I've check out v0.10.0, and I've found, that the release build which gets created by `npm run package` actually contains the whole repo directory including the source code in `AppBundle->Contents->Resources->app`. I feel like this can't really be intentional can it?

**Comment by Slapbox** [comment]
Could be mistaken, but I'm pretty sure that's just the way Electron is.

**Comment by amilajack** [comment]
It could be removed. I'll add this to our release 0.11.0 release in #504

**Comment by huesforalice** [comment]
Thanks. @Slapbox: The sources actually used will be contained in the 'compiled' bundle.js and are therefore somewhat obfuscated. The source code does not need to be included and most people building a non-open-source app will probably not want it to be included.

**Comment by huesforalice** [comment]
Also, before I forget, a big thanks for maintaining this and giving me an easy start in to the electron world!
