### ISSUE TITLE
PR: React Storybook Support

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#595]

**Comment by dustintownsend** [comment]
Do you mean React Storybook? 

My search found this:
https://github.com/D1plo1d/react-storyboard
http://guigrpa.github.io/storyboard/
https://github.com/storybooks/react-storybook

**Comment by amilajack** [comment]
Yea, my bad. Meant storybook 😂

**Comment by ritz078** [comment]
I don't think anything is needed from this boilerplate. If anyone wants to use it

```
npm i -g getstorybook
getstorybook
```

This will automatically add storybook in the existing repo. The user may want to use different plugins and its better to leave it on him.

Just adding in the readme should work.

**Comment by talha131** [comment]
@amilajack I added storybook support by running `getstorybook` in the root of the project. Later, when I had to display images, I added following rule to webpack configuration

```js
{
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {}
          }
        ]
      }
```

I am confused about CSS. When I add a story that involves a component which uses CSS modules of this project, storybook does not work.

What rule do I need to add to make storybook compile CSS modules?

**Comment by talha131** [comment]
I fixed the issue by adding following rule for CSS.

```js
{
        test: /\.css?$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]'
            }
          }
        ]
      }
```
