### ISSUE TITLE
Question: how to change font from Font-awesome to Roboto?

### ISSUE THREAD

**Issue by Grimones** [chentsulin/electron-react-boilerplate#596]
Hello,

was struggling all night to change the font on Roboto, but without luck.
I would appreciate any help. 
My application is this boilerplate slightly modified with material-ui

Thank you

**Comment by amilajack** [comment]
I've pushed an temporary branch to this repo as an example of how to change the font:
```bash
git clone https://github.com/chentsulin/electron-react-boilerplate.git
git checkout font-change-example
yarn # or npm
npm run dev
```
[Here's the diff](https://github.com/chentsulin/electron-react-boilerplate/commit/f949b058f1153fa7edc82ae28b1bc9acd72944fe)

**Comment by amilajack** [comment]
Closing due to no response :(
