### ISSUE TITLE
Discussion: Webpack Blocks

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#598]
I believe this package significantly simplifies webpack configurations and that we should consider it the default for the project:

https://github.com/andywer/webpack-blocks

Inspired by:
https://twitter.com/dan_abramov/status/806246431707320320

Thoughts?

**Comment by dustintownsend** [comment]
Anything that simplifies webpack configs is a good thing! 

Do you think the blocks they have already created would do everything the current webpack configs do or would custom blocks need to be created?

**Comment by amilajack** [comment]
I havent used webpack blocks yet but it seems like it can.

**Comment by chentsulin** [comment]
I'd like to wait for couple of weeks and see how people works with it. Many developers use this boilerplate on production project so we should use bleeding edge technologies carefully.

**Comment by amilajack** [comment]
@chentsulin good idea. Lets wait for a month or so. Mid-January?

**Comment by chentsulin** [comment]
It's ok. we can send a PR to open discussion at that time.

**Comment by amilajack** [comment]
It's been a while since this was last discussed. [There's a PR open which adds happypack support](https://github.com/andywer/webpack-blocks/pull/126). This will significantly improve reduce the build time of the boilerplate.
