### ISSUE TITLE
Including exe file in build electron application

### ISSUE THREAD

**Issue by csprance** [chentsulin/electron-react-boilerplate#599]
I have an exe file which is a command line interface tool. Using child-process I am sending commands to the exe and then parsing the results like this:
```

  sendCommand = (command) => {
    const execFile = require('child_process').execFile;
    //misrcon.exe -i [ip] --port [admin port] -p [admin password] --command [command] --time [exec_time] --s [schedule]

    let child = execFile(String(process.cwd() + '/app/api/misrcon.exe'),
      ['-i', this.state.ip, '--port', this.state.port, '-p', this.state.password, '--command', command],
      (error, stdout, stderr) => {
        if (error) {
          throw error
        }
        this.refs.console.log(stdout);
        this.refs.console.return();
      });


  };

```

I can get it to work just fine in dev referencing ./app/api/misrcon.exe

but when I package the app it doesn't include that exe along with the packaged files/installer.

I've been trying to figure it out searching through issues here but I'm having a hard time finding a solution.

Is there an easy way to do this that I'm missing somewhere?

**Comment by csprance** [comment]
nm I figured it out. In the root package.json
```
"build": {
   ...
    "win": {
      "extraFiles": [
        "resources/misrcon_cli.exe"
      ],
      "target": "nsis"
    }
    ...
  },

```

That will copy it to (on windows)` project-root/resources/misrcon_cli.exe`

Hopefully this can at least serve as helpful documentation to anyone else having the same problem.

**Comment by SMUEric1127** [comment]
Hi, just some add on if you have more than just an .exe file (Some .dll libraries come along with it). What I did was adding the directories to the extraResources (Assume my directory is executable).

`
"build": {
...
"extraResources": [
      "./assets/**",
      "./executable/**" 
    ],
...
}`
