### ISSUE TITLE
`Error: Cannot find module 'isomorphic-fetch` in Packaged App, works in Development

### ISSUE THREAD

**Issue by hhff** [chentsulin/electron-react-boilerplate#600]
My `webpack.config.base.js`:

```js
/**
 * Base webpack config used across other specific configs
 */

import path from 'path';
import validate from 'webpack-validator';

export default validate({
  //...snip
  externals: [
    {
      'isomorphic-fetch': {
        root: 'isomorphic-fetch',
        commonjs2: 'isomorphic-fetch',
        commonjs: 'isomorphic-fetch',
        amd: 'isomorphic-fetch'
      }
    }
  ]
});
```

When I run `npm run package` the build completes fine.  However when opening the completed packaged file, I get this error:

`Error: Cannot find module 'isomorphic-fetch'`

![image](https://cloud.githubusercontent.com/assets/2865404/20991663/a14b8220-bcad-11e6-9b7b-9cab474fd49f.png)

No issues when runing `npm run dev`.  Am I missing something?

THANKYOU!

**Comment by amilajack** [comment]
I'm using fetch in one of my apps that uses this boilerplate:

https://github.com/amilajack/popcorn-time-desktop/blob/09fa99a8f2952a0bdee3b1e881d0f4b4b098fc44/app/api/torrents/ExtraTorrentProvider.js#L4

It doesn't require any additional setup. Try removing the externals section.

**Comment by hhff** [comment]
Thanks @amilajack !  (And thankyou for the excellent Popcorn Time app!)

When I remove `isomorphic-fetch` from the `externals` section, I instead get this error when the packaged app opens:

![image](https://cloud.githubusercontent.com/assets/2865404/21018947/dcef17f8-bd3c-11e6-8efe-fdc6c62ade9b.png)

I figured this was related, as isomorphic-fetch tries to resolve `self`

**Comment by hhff** [comment]
Ah - now I've tried switching to `node-fetch`, and I'm getting:

```
ReferenceError: window is not defined
    at Object.module.exports.u.Promise
```

![image](https://cloud.githubusercontent.com/assets/2865404/21020002/a29683da-bd40-11e6-8d8e-c4a7746a5f1f.png)

**Comment by amilajack** [comment]
Try this:

```
git clone https://github.com/chentsulin/electron-react-boilerplate.git
git checkout iso-fetch-demo
yarn # or npm. yarn is recommended
npm run dev # should work
npm run package # should work
```

See https://github.com/chentsulin/electron-react-boilerplate/commit/b9c03d3fb764cb6edc8a90118fef777b4213accf for the changes

**Comment by hhff** [comment]
works great @amilajack - this issue may be from a different lib.  OK if I keep this open while I keep debugging?

**Comment by hhff** [comment]
Ok so!  Making some progress.  The issue is that I am using `fetch` from my `main.js` electron process, not the `renderer`.

If I change this line:
https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.base.js#L34

To this:
`packageMains: ['webpack', 'main', 'browser', 'web', 'browserify', ['jam', 'main']]`

It works great - but I'm guessing that order is the way it is for a reason.  Is there a better way to configure this?

**Comment by amilajack** [comment]
@hhff is there a downside to using the configuration that worked for you?

**Comment by hhff** [comment]
@amilajack - the only thing I can think of is that there are cases where I'll need to make calls from the `renderer` in the future.

Is it possible to have both versions (node & browser) of `isomorphic-fetch` in the same webpack build?

**Comment by amilajack** [comment]
Just updated the branch. It imports `isomorphic-fetch` from main process:

https://github.com/chentsulin/electron-react-boilerplate/commit/53d623cb5f228f09be096675111a7f52d6ebf43d
