### ISSUE TITLE
locals[0] does not appear to be a `module` object with Hot Module replacement API enabled

### ISSUE THREAD

**Issue by Ctesias** [chentsulin/electron-react-boilerplate#601]
Hi, 

I am using react with semantic in electron and when I put my code in this boilerplate I start getting this error:

> locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

The stack trace (posted below) leads to this line in one of my react component files:

`import {Modal, Button, Icon, Image} from 'semantic-ui-react';`

The error suggests the following:

>should disable react-transform-hmr in production by using `env` section in Babel configuration

But the link example it posts leads to a deprecated repo and pointer to another.   I'm not at all familiar with this stuff enough to know what the implications of this error are.  Should I do something to fix it or just disable it in production and call it quits?  How would I go about doing whichever is the right move?

Thanks for whatever advice you can give on the right direction to go with this.

Stack trace: 

C:\git\Configurator\node_modules\react-transform-hmr\lib\index.js:51Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
proxyReactComponents @ C:\git\Configurator\node_modules\react-transform-hmr\lib\index.js:51
(anonymous function) @ new-customer-dialog.js:3
Module._compile @ module.js:556
loader @ C:\git\Configurator\app\node_modules\babel-register\lib\node.js:144
require.extensions.(anonymous function) @ C:\git\Configurator\app\node_modules\babel-register\lib\node.js:154
Module.load @ module.js:473
tryModuleLoad @ module.js:432
Module._load @ module.js:424
Module.require @ module.js:483
require @ internal/module.js:20
(anonymous function) @ customer-select.js:3
Module._compile @ module.js:556
loader @ C:\git\Configurator\app\node_modules\babel-register\lib\node.js:144
require.extensions.(anonymous function) @ C:\git\Configurator\app\node_modules\babel-register\lib\node.js:154
Module.load @ module.js:473
tryModuleLoad @ module.js:432
Module._load @ module.js:424
Module.require @ module.js:483
require @ internal/module.js:20
(anonymous function) @ entry.js:13
n.run @ browser.min.js:3
l @ browser.min.js:3
(anonymous function) @ browser.min.js:3
s.onreadystatechange @ browser.min.js:3

**Comment by dustintownsend** [comment]
Are you trying this on a fresh boilerplate project or an existing project that is based on the boilerplate? I don't think this is an issue with the boilerplate. I cloned a fresh copy and installed semantic-ui-react and it worked.

You should look into your webpack config files. Specifically any changes you have made. Also, if you are using an older version of the boilerplate you should look at the changes made. You maybe able to do an upstream pull and merge in changes.

You should be able to disable HMR by removing the below from store/configureStore.development.js 
`  if (module.hot) {
    module.hot.accept('../reducers', () =>
      store.replaceReducer(require('../reducers'))
    );
  }`

**Comment by Ctesias** [comment]
It's not a problem with the boilerplate I don't think, I just wasn't sure who else to ask.  I could start the boilerplate without errors, but once I ported my code into it this began.

It's a project I'm porting over to the boilerplate so I can take advantage of the packaging commands and live update etc.  I pulled the latest version of the boilerplate yesterday to try it.  I use different entry files for the program so I changed the name of those files in the webpack config.  Otherwise the only thing I change are the react files in the component folder.  

I also get "Uncaught TypeError: Cannot set property 'exports' of undefined" in line one of the bundle webpack makes, not sure if related.

I appreciate the support.

**Comment by dustintownsend** [comment]
If it's a public repo I could take a look, but I don't think I can be much help with what's provided. I do think it's something with the webpack config.
Are you able to build the project? `npm run build`?

**Comment by Ctesias** [comment]
`npm run build` appears to work fine:

    C:\git\Configurator>npm run build
    
    electron-react-boilerplate@0.10.0 build C:\git\Configurator
    npm run build-main && npm run build-renderer


    electron-react-boilerplate@0.10.0 build-main C:\git\Configurator
    cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --    config webpack.config.electron.js --progress --profile --colors

    1682ms build modules
    7ms seal
    8ms optimize
    9ms hashing
    22ms create chunk assets
    2503ms additional chunk assets
    793ms optimize chunk assets
    3ms optimize assets
    15ms emit
    Hash: 6d1ff708cfd8dae83cba
    Version: webpack 1.14.0
    Time: 5051ms
            Asset     Size  Chunks             Chunk Names
        ./app/main.js   174 kB       0  [emitted]  main
        ./app/main.js.map  1.39 MB       0  [emitted]  main
       [0] multi main 40 bytes {0} [built]
       factory:0ms building:2ms = 2ms
    + 340 hidden modules

    electron-react-boilerplate@0.10.0 build-renderer C:\git\Configurator
    cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --  config webpack.config.production.js --progress --profile --colors
    
    3479ms build modules
    7ms seal
    19ms optimize
    9ms hashing
    36ms create chunk assets
    3823ms additional chunk assets
    45ms optimize chunk assets
    83ms optimize assets
    8ms emit
    Hash: 4ff87fbea1bc8b2dfcbf
    Version: webpack 1.14.0
    Time: 7526ms
            Asset       Size  Chunks             Chunk Names
        bundle.js     278 kB       0  [emitted]  main
    bundle.js.map  176 bytes       0  [emitted]  main
    ../index.html    1.54 kB          [emitted]
       [0] multi main 40 bytes {0} [built]
           factory:0ms building:1ms = 1ms
        + 483 hidden modules
    Child html-webpack-plugin for "..\index.html":
            + 3 hidden modules



However if I try to `npm package` I get an executable that installs an app that doesn't show anything.

    C:\git\Configurator>npm run package --icon "/app/img/onramp-logo-swirl.ico"
    
    > electron-react-boilerplate@0.10.0 package C:\git\Configurator
    > npm run build && build --publish never "/app/img/onramp-logo-swirl.ico"
    
    
    > electron-react-boilerplate@0.10.0 build C:\git\Configurator
    > npm run build-main && npm run build-renderer
    
    
    > electron-react-boilerplate@0.10.0 build-main C:\git\Configurator
    > cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --    config webpack.config.electron.js --progress --profile --colors
    
    1344ms build modules
    8ms seal
    8ms optimize
    7ms hashing
    19ms create chunk assets
    2305ms additional chunk assets
    783ms optimize chunk assets
    0ms optimize assets
    14ms emit
    Hash: 6d1ff708cfd8dae83cba
    Version: webpack 1.14.0
    Time: 4497ms
                Asset     Size  Chunks             Chunk Names
        ./app/main.js   174 kB       0  [emitted]  main
    ./app/main.js.map  1.39 MB       0  [emitted]  main
       [0] multi main 40 bytes {0} [built]
           factory:0ms building:2ms = 2ms
        + 340 hidden modules
    
    > electron-react-boilerplate@0.10.0 build-renderer C:\git\Configurator
    > cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --    config webpack.config.production.js --progress --profile --colors
    
    3487ms build modules
    10ms seal
    19ms optimize
    10ms hashing
    26ms create chunk assets
    3853ms additional chunk assets
    47ms optimize chunk assets
    89ms optimize assets
    7ms emit
    Hash: 4ff87fbea1bc8b2dfcbf
    Version: webpack 1.14.0
    Time: 7564ms
            Asset       Size  Chunks             Chunk Names
        bundle.js     278 kB       0  [emitted]  main
    bundle.js.map  176 bytes       0  [emitted]  main
    ../index.html    1.54 kB          [emitted]
       [0] multi main 40 bytes {0} [built]
           factory:0ms building:1ms = 1ms
        + 483 hidden modules
    Child html-webpack-plugin for "..\index.html":
            + 3 hidden modules
    Packaging for win32 x64 using electron 1.4.11 to release\win-unpacked
    ⚠️  Application icon is not set, default Electron icon will be used
    Packaging NSIS installer for arch x64
    Building NSIS installer

I've made `https://github.com/onramp/configurator` temporarily public.  If you don't mind taking a look I would be eternally grateful.  I know you guys could be blowing me off because this isn't your problem, and I tremendously appreciate the support while I get my feet wet with this stuff.

**Comment by dustintownsend** [comment]
It maybe because you are using Gulp. I think if you are going to use Gulp you have to integrate it with Webpack. Maybe this can help: https://webpack.github.io/docs/usage-with-gulp.html

If it is working when you do `npm run dev` but not when packaged it is likely because everything is not being packed into bundle.js by webpack.

**Comment by amilajack** [comment]
@Ctesias did you resole this?

**Comment by Ctesias** [comment]
No not yet.  I'm still fighting with it

**Comment by amilajack** [comment]
@Ctesias Closing because this issue seems a little outdated. Try cloning the latest version of this boilerplate and confirming if this issue persists
