### ISSUE TITLE
PR: Enhanced build configuration and optimizations

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#609]
`babel-preset-env` [officially supports electron](https://github.com/babel/babel-preset-env/releases/tag/v1.0.0) now. Adding support for it would be great.

Here's a list of all the things i'm going to try to add support for while i'm at it:
- [ ] `babel-preset-env`
- [ ] `babili`: https://github.com/boopathi/babili-webpack-plugin

**Comment by jhen0409** [comment]
Same with https://github.com/chentsulin/electron-react-boilerplate/issues/275#issuecomment-256095908, we need to add [babili](https://github.com/babel/babili) and remove webpack `UglifyJsPlugin` for support minify ES2015 code, a simple workaround is use [babili-webpack-plugin](https://github.com/boopathi/babili-webpack-plugin). Or waiting UglifyJS support.

**Comment by amilajack** [comment]
Closing, as https://github.com/chentsulin/electron-react-boilerplate/pull/622 was made
