### ISSUE TITLE
PR: Example Apps section

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#611]
I think we should follow in preact's footsteps and provide a section of example apps that use this boilerplate. It'll help users of the boilerplate steer in the right direction and give them useful hints of how to structure and extend the boilerplate.

**Comment by amilajack** [comment]
Here's preact's demo section:

https://github.com/developit/preact#demos

**Comment by m4tta** [comment]
Get some examples together and submit a pr.

**Comment by dustintownsend** [comment]
@amilajack I agree. This would have been very helpful when I first started using this. I always look for examples of implementations. Do you have a list of projects in mind? The only one I know off the top of my head is (your project) https://github.com/amilajack/popcorn-time-desktop and https://github.com/xwartz/PupaFM

If anyone knows of any other good examples that are open source please share.

**Comment by amilajack** [comment]
Eventually we might be able to add this:

https://github.com/andrewjong/electron-calendar-schedule/

**Comment by schaveyt** [comment]
Not sure how to "up vote" this request so..I would triple vote for this :-).

**Comment by schaveyt** [comment]
I am looking to move an internal team toward electron/react based app for all of our future line-of-business apps. As we are all winforms and WPF gurus but only  novice react developers...we and I am sure countless others would be forever greatful for a demo app that exercises few desktop-oriented features.

I can fork and use the pull request process to help develop the following but as a noob would ask for senior help

A simple directory searching app. Given a top level directory..the app shows the dir/file tree in a left panel, the user right clicks a folder where a context menu says Find In Files, kinda like sublime text the user specifies the string to match. Like sublime text, When commanded to search, the app recursively searches one or more files that contains the string and displays each hit in say..a table.Of course, the app should show the hits as they are found to the user (not wait til the end) and be able to cancel the search.

We are trying to exercise file system, asych processing, cancel of process nor thread, react handling of context menus and panel with tree...and table results..

Thoughts?

**Comment by amilajack** [comment]
I'm not sure if i understood your question. Are you asking the collaborators of electron-react-boilerplate (erb) to work on your app? The erb team isnt aimed towards on related projects. We can help you resolve issues you have with the boilerplate.

**Comment by schaveyt** [comment]
I share @dustintownsend sentiment that having some demo apps built with this boilerplate would have been helpful when first starting out. My previous comment is a suggestion to one of those demo apps that would cover a lot of ground and get many folks kickstarted. Just looking for a way to see a somewhat meaningful demo app that the erb team sees as a proper use of the their boilerplate.

**Comment by amilajack** [comment]
Ahhhh. Wow I was way off. Sorry for the confusion. Sure thing! What's the link to your app?

**Comment by schaveyt** [comment]
Hmm. I am thinking this might be a "300" level demo app but might need a 100 level and a 200 level. Just my thoughts :-)

**Comment by amilajack** [comment]
Yea, I definitely agree. popcorn-time-desktop also doesn't make use of that many electron specific features, like using the main process or the icon tray.

**Comment by schaveyt** [comment]
How about giving that directory search demo app a shot..if you're up for ;-)

**Comment by amilajack** [comment]
Directory traversal has more to do with node. I think we should try to display electron specific API's

**Comment by amilajack** [comment]
Working on a toy app that lets you use diff two files.

https://github.com/amilajack/contrast

May consider adding it

**Comment by amilajack** [comment]
Just found that [DBGlass](https://github.com/web-pal/DBGlass) is based off this boilerplate
