### ISSUE TITLE
Path of image on main process when in packaged app?

### ISSUE THREAD

**Issue by mkwng** [chentsulin/electron-react-boilerplate#612]
I've been banging my head against this for a while now, but I'm trying to get the absolute path to a PNG file so I can create an Electron Tray.(https://github.com/electron/electron/blob/master/docs/api/tray.md#new-trayimage)

On development, this works fine. But after packaged, the path is no longer valid and the app crashes at trying to create a Tray. This problem (getting the right path in a packaged app) seems to be solved for the renderer process (#250), but when trying to `import` files on the main process side, getting this error:
```
App threw an error during load
SyntaxError: /Library/WebServer/Documents/syft/app/server-components/iconTemplate.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 | ?
  3 | 
  4 | IHD��agAMA��
                  �a cHRMz&�����u0�`:�p��Q<bKGD�C�      pHYs

                                                            ��~�cIDAT8˝�?HUq����@D�D��(��C
```

Let me know if I'm thinking about this wrong/overlooking a simple solution. Here's where I'm running into the issue: https://github.com/mkwng/syft/blob/master/app/server-components/TrayIcon.js

And also, thank you all for your contributions!

**Comment by amilajack** [comment]
Did you see https://github.com/chentsulin/electron-react-boilerplate/issues/129 and https://github.com/chentsulin/electron-react-boilerplate/issues/250? Not sure if they're directly related but they could help. When did you clone the repo? Do you have the latest version of it?

**Comment by mkwng** [comment]
@amilajack Yup, took a look at both of those, and they're related but not the same issue.

I just cloned the latest and was able to repro by including a `test.png` in /app and trying to `import test from './test.png'` from `main.development.js`

**Comment by amilajack** [comment]
Can you create a branch in your fork so that I can test this out? That would be really helpful

**Comment by mkwng** [comment]
Is this what you mean? I just forked the main branch into my own repo: https://github.com/mkwng/electron-react-boilerplate

**Comment by jhen0409** [comment]
> On development, this works fine. But after packaged, the path is no longer valid and the app crashes

Try to add your assets dir to [allow list](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L46), it should work for packaged app.

> but when trying to import files on the main process side, getting this error:

Currently we didn‘t use `file-loader` on [main process](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.electron.js).

**Comment by mkwng** [comment]
That solved my issue.. thank you so much guys!

Closing this for now.

**Comment by rahilsondhi** [comment]
My images show up in development but not in production.

I render images like this:

```
const SIGN_IN_WITH_GOOGLE_PATH = require('../assets/images/btn_google_signin_dark_normal_web@2x.png');
<img src={SIGN_IN_WITH_GOOGLE_PATH} />
```

I tried reading through all the issues and no dice 😢 I also tried the `import` syntax but that didn't work either. Not sure what @jhen0409 was referring to about `allow list` in his comment

**Comment by arieldf** [comment]
I had the same issue. What I did to solve this was to move the loader for the images into the base config and now it works.

Let me know if this works for you. Probably there is a more correct way to do it.

**Comment by rahilsondhi** [comment]
@arieldf thanks so much, that worked!

To the maintainers, maybe the root cause of this bug lies somewhere here?
https://github.com/webpack/style-loader/issues/55

Or is it related to `__webpack_public_path__` @ http://webpack.github.io/docs/configuration.html#output-publicpath
