### ISSUE TITLE
Add `.less` support

### ISSUE THREAD

**Issue by catalinmiron** [chentsulin/electron-react-boilerplate#62]
### Need
```gherkin
As a developer
I want to use css preprocessors
So that I'll increase my productivity and DX[Developer Experience]
```

### Solution

- [x] add `less-loader` as dev dependencies
- [x] in `webpack.config.development.js` 
```javascript
{
  test: /\.less$/,
  loader: ['style-loader!css-loader!less-loader']
}
```
- [x] in `webpack.config.production.js`
```javascript
{ 
  test: /\.less$/,
  loader: ExtractTextPlugin.extract('style-loader','css-loader!less-loader')
}
```

**Comment by chentsulin** [comment]
Thanks for high quality PR here :+1: , but I doubt we should support less in this boilerplate. 

See also here, I want to keep webpack config just simple:

https://github.com/chentsulin/electron-react-boilerplate/blob/b2ddeb28b87dfa0194cd174e27afb5fefe54e68b/webpack/make-webpack-config.js#L18

I ever use sass, scss, less, stylus before and now postcss. We should not support all of those in one boilerplate and should let user make a decision themselves.

**Comment by catalinmiron** [comment]
@chentsulin fair enough :+1: 

What do you think about ExtractTextPlugin initialization, [this commit](https://github.com/catalinmiron/electron-react-boilerplate/commit/cdf221697cd71b12972fbead9a857ea6a7d81ac0), can we merge it, without `less` of course, or it's out of scope?

> Thanks for high quality PR here :+1:

It's not a problem, since this repo is a bless :godmode: :cake:

**Comment by chentsulin** [comment]
Sure, maybe open a new PR or rebase to modify on that commit, after that i will merge or cherry-pick it.

**Comment by catalinmiron** [comment]
Closing this in favour of #64 (PR: #65)
