### ISSUE TITLE
Adding aliases and root in `resolve` will not work in tests.

### ISSUE THREAD

**Issue by AlexFrazer** [chentsulin/electron-react-boilerplate#620]
### The errors:

If you add any aliases or root to the `webpack.config.base.js`, it will not function the same in a test environment, and will not resolve appropriately. The error will be something like:

```
Error: Cannot find module 'app/utils/api'
```

### How to reproduce:

Simply add a single alias or root to the `webpack.config.base.js`

```
export default {
  // ... whatever
  resolve: {
    extensions: ['', '.js', '.jsx', '.json', '.css', '.scss'],
    packageMains: ['webpack', 'browser', 'web', 'browserify', ['jam', 'main'], 'main'],
    alias: { 'app': `${__dirname}/app` },
  }
}
```

Then add this to the `webpack.config.test.js`

```
module.exports = {
  // ...
  resolve: devConfig.resolve
}
```

Use an aliased import anywhere in the application and import it in a test.

```
import 'app/utils/api';  // <- just an example.
```

Run tests.

```
$ npm run test
```

**Comment by jhen0409** [comment]
Write `resolve.alias` to [test config](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.test.js) and add [babel-plugin-webpack-aliases](https://github.com/trayio/babel-plugin-webpack-alias) to `TEST` env of `babelrc` may be a simple workaround.

#### `webpack.config.test.js`

```diff
...
module.exports = validate({
  ...
+ resolve: {
+   alias: { app: `${__dirname}/app` },
+ }
});
```

#### `.babelrc`

```diff
{
  ...
  "env": {
    ...
    "test": {
      "plugins": [
+       ["webpack-aliases", { "config": "webpack.config.test.js" }],
        ["webpack-loaders", { "config": "webpack.config.test.js", "verbose": false }]
      ]
    }
  }
}
```
