### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ThiagoFacchini** [chentsulin/electron-react-boilerplate#621]
Hi,

Couldn't find anything related to this issue,
basically I downloaded and run npm install, which failed at this point:

> concurrently "npm run flow-typed-install" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

> 

> • Found flow-bin@v0.37.0 installed. Installing libdefs compatible with this version of Flow...
[0] ERROR: Unable to find a flow project in the current dir or any of it's parents!
[0] Please run this command from within a Flow project.

> 

Any ideias?
Thanks

**Comment by ThiagoFacchini** [comment]
Extra information:
Node Version: 6.50
NPM Version: 3.10.3

**Comment by amilajack** [comment]
Try cloning instead of downloading

**Comment by jaitaiwan** [comment]
Can confirm cloning and download works. Copy from folder to another somehow doesn't.

**Comment by amilajack** [comment]
Thanks for confirming
