### ISSUE TITLE
Discussion: Multiple Windows?

### ISSUE THREAD

**Issue by dustintownsend** [chentsulin/electron-react-boilerplate#623]
How do you all handle the case of Multiple Windows in the boilerplate?

**Comment by dustintownsend** [comment]
I'm considering removing all the renderer specific code from the app folder and then create a new folder for the primary window and another folder for the secondary window.

But this really breaks away from the structure of the boilerplate, so I was curious how others have solved it. Or any ideas.

**Comment by amilajack** [comment]
Should this be closed? Doesn't seem like anyone else is doing this? How did you solve this?

**Comment by dustintownsend** [comment]
@amilajack I'm working on solving this now. I'll post what I end up doing and close this so if anyone in the future searches for it they can see one solution.

**Comment by nlemoine** [comment]
Have you checked [this issue](https://github.com/chentsulin/electron-react-boilerplate/issues/108)?

I'm also looking for a good way to handle multiple windows. Please let me know if you find out a nice way to deal with this.

**Comment by dustintownsend** [comment]
So I ended up not doing multiple windows. I think in order for it to work something like redux-electron-store needs to be set-up. @nlemoine 

What I did was instead of creating a new window I just resize the current window and reposition it to give the same effect as a new window. When the user exits that "window" it just resets the window to the original size and position. This will only work in the case that both windows don't need to be used at the same time which in my case this was true.

I think if we are able to add something like redux-electron-store in the future it will open the door for multiple window applications. Otherwise you will need to effectively have separate "apps" for each window.

**Comment by stevenfabre** [comment]
Definitely interested in this! Anyone's got a good solution to this?

**Comment by chancethecoder** [comment]
I'm in this problem too...

I think redux-electron-store is needed anyway.

**Comment by yourfavorite** [comment]
I am just diving into this same problem. My app will have three windows.

1) Main window of app.  You can create tasks and run them. Most everything happens here.
2) Window for managing settings.
3) Window for managing profiles.

My settings and profiles are both saved in a local db via nedb. Since both the settings and profiles pages will require the user to hit a SAVE button, I intend to hook into the save success action and fire off an IPC call to the main window of the app. At which point the main window will update its store for settings or profiles accordingly.

Open to thoughts on this, but if nothing else hope it helps someone else in the future.

**Comment by 1-14x0r** [comment]
I just ran into this while trying to create a splash screen to display some loading info in a progress bar. First i thought it was as simple as copying the index.html and index.js and loading it the same way... nope.

I don't think having a main entry point html page that routes to other components is a terrible way. However are there any implications to loading all these routes and their components upfront? Is there a way to load them on demand or does it really matter anyways being a desktop app?

**Comment by 1-14x0r** [comment]
Okay I wrote solution for this based off from a few days of research and experimenting.

Assume we have two windows defined in a main process, each with their own view. Lets have `window-a` call `viewA`, and `window-b` call `viewB`. 

```
windowA = new BrowserWindow(
    {
      name: 'window-a',
      width: 400, 
      height: 300,
    }
  );
  window.loadURL(
    isDev
      ? 'http://localhost:3000?viewA'
      : `file://${path.join(__dirname, '../build/index.html?viewA')}`
  );

windowB = new BrowserWindow(
    {
      name: 'window-b',
      width: 400, 
      height: 300,
    }
  );
  window.loadURL(
    isDev
      ? 'http://localhost:3000?viewB'
      : `file://${path.join(__dirname, '../build/index.html?viewB')}`
  );
```
we should use a query parameter, also known in react as a search property of the path like `?viewA` or `?viewB`

In our entry point file `index.js` we will import a new class called `ViewManager` which will handle all of the view routing and configuration. The index.js would look like this:

```
import React from 'react';
import ReactDOM from 'react-dom'
import ViewManager from './ViewManager';

ReactDOM.render(<ViewManager />, document.getElementById('root'));
```

and our `ViewManager.js` class file should look something like this:

```
import React, { Component } from 'react';
import {
  BrowserRouter as Router,
  Route
} from 'react-router-dom'
import Update from './ViewA';
import Console from './ViewB';

class ViewManager extends Component {

  static Views() {
    return {
      viewA: <ViewA/>,
      viewB: <ViewB/>
    }
  }

  static View(props) {
    let name = props.location.search.substr(1);
    let view = ViewManager.Views()[name];
    if(view == null) 
      throw new Error("View '" + name + "' is undefined");
    return view;
  }
  
  render() {
    return (
      <Router>
        <div>
          <Route path='/' component={ViewManager.View}/>
        </div>
      </Router>
    );
  }
}

export default ViewManager
```

`ViewA` and `ViewB` are just regular `React.Component` classes. The `ViewManager` will inject these components based on the routes defined by the name of the query string after `?` When no view is defined or an incorrect name is used. an exception is thrown so you know the mapping is wrong.

When you need to add another view, such as `ViewC` to your project, just import the new Component at the top of the `ViewManager` like 

```
import Update from './view/ViewC';
```
and update this array method of the `ViewManager`:

```
  static Views() {
    return {
      viewA: <ViewA/>,
      viewB: <ViewB/>,
      viewC: <ViewC/>
    }
  }
```

There currently is no way to dynamically lookup and return a react component with a string directly. You have to register the component into an object. Using a `ViewManager` class is clean, and provides a global way to access the views and associated components statically; such as : 

`ViewManager.Views()` -> returns a map of the view components
`ViewManager.View(prop)` -> a way to return the component on the name

I am sure there are some ways to extend the functionality, but this is for minimal code

GLHF;

**Comment by yourfavorite** [comment]
I'm not sure I understand the need for ViewManager? You are currently loading pages via query string when you could just use hash urls and the built in ReactRouter which would require far less code imo. What benefit does ViewManager add over this approach?

**Comment by 1-14x0r** [comment]
The view manager does use the builtin routing, but yes its true you could use #/ which worked for me in dev mode hosting live code.. When i went to package a release the url paths were not working for me with a # in the file path. IE loading page from the file:// protocol. 

I also wanted a static array to store my views in that the router selects from. I wanted a single class that manages all of my required views, and access them from ViewManager.Views.viewA. 

I do agree it might seem like overkill when you can just require the component as you needed. In my project we have hundreds of views and dozens of different windows that use a combination of views. I also needed a way to statically store the states of each of these views. 

Using a manager provided me a way to easily reuse a single view component statically, and inject it into window directly or nested into another component recursively using the built in react router. Without a manager i would either have to add the view as a global object (gets messy when you have hundreds of views) and reuse it that way. My other option would be to instantiate a new view component and inject the stored state into the constructor (which uses more memory and less responsive on complex views with large DOM)

I also found that by instantiate in a static Views() object in the ViewManager,  the components are rendered upfront and not when the router detects a url change. This usually isn't noticeable but on some of the more complex views there will be about a second white screen lag of the window while the router instantiates the new view component.

**Comment by FullstackJack** [comment]
@1-14x0r Big ups, yo.

**Comment by incizzle** [comment]
How does one redirect between components using BrowserRouter . I had this previously working with HashRouter but HashRouter does not have support for the prop Search. I was previously using ``this.props.history.push("/viewC");`` to redirect.

**Comment by incizzle** [comment]
I fixed this by creating adding a history to the router ``<Router history={history}>``. If there is a better way with props that would be nice. But this works for now.

**Comment by gautamsi** [comment]
@1-14x0r I have used same url routing approach with multiple window (before landed here). My problem is that it takes lot longer to load new window content. even after the built version.

What did you do to optimize the load time with view manager? code splitting?

**Comment by ivanjeremic** [comment]
What about loading WebViews in different routes? Can WebViews have each of then stored cookies?

**Comment by vladislavalerievich** [comment]
Thanks man. You saved me days!

**Comment by evlerr** [comment]
Yo? I'm attempting to do the same thing while also using HashRouter and it doesn't seem to work.

```
const createWindow = () => {
  mainWindow = new BrowserWindow({width: 1281, height: 800,   webPreferences: {
    nodeIntegration: true
  }});
  mainWindow.autoHideMenuBar = true;
  mainWindow.loadURL(`file://${path.join(__dirname, '../build/index.html#/dashboard')}`);
  mainWindow.webContents.openDevTools()
  mainWindow.on("closed", () => (mainWindow = null));
}```

**Comment by ZoeDreams** [comment]
> @1-14x0r I have used same url routing approach with multiple window (before landed here). My problem is that it takes lot longer (expectation would be to load in 1-2 seconds) to load new window content. even after the built version.
> 
> What did you do to optimize the load time with view manager? code splitting?

that does help, but i compile my code and minify it. I also load all of my windows compiled code front through a AppLoader class i created. This allows your ViewRouter to quickly load this cache.. Poke around in your apps data directory and local storage in the CLI to see how things are loading. 

Ill be honest, one of our projects has 5MB of compiled JS code that spawns about 5 windows with hundreds of classes and it takes <1 sec to load in dev. do you use minify and uglify?

**Comment by ZoeDreams** [comment]
> What about loading WebViews in different routes? Can WebViews have each of then stored cookies?

yes and yes. it can be very powerful check out https://www.npmjs.com/package/electron-cookies

but if your using persistent data check out NeDB or LokiJS way more secure and faster then cookies. GL;HF

**Comment by ZoeDreams** [comment]
> HashRouter

check your URL, looks invalid with a #/

`window.loadURL(
    isDev
      ? 'http://localhost:3000?viewB'
      : `file://${path.join(__dirname, '../build/index.html?viewB')}`
  );`

**Comment by PeterHarlan** [comment]
> Okay I wrote solution for this based off from a few days of research and experimenting.
> 
> Assume we have two windows defined in a main process, each with their own view. Lets have `window-a` call `viewA`, and `window-b` call `viewB`.
> 
> ```
> windowA = new BrowserWindow(
>     {
>       name: 'window-a',
>       width: 400, 
>       height: 300,
>     }
>   );
>   window.loadURL(
>     isDev
>       ? 'http://localhost:3000?viewA'
>       : `file://${path.join(__dirname, '../build/index.html?viewA')}`
>   );
> 
> windowB = new BrowserWindow(
>     {
>       name: 'window-b',
>       width: 400, 
>       height: 300,
>     }
>   );
>   window.loadURL(
>     isDev
>       ? 'http://localhost:3000?viewB'
>       : `file://${path.join(__dirname, '../build/index.html?viewB')}`
>   );
> ```
> 
> we should use a query parameter, also known in react as a search property of the path like `?viewA` or `?viewB`
> 
> In our entry point file `index.js` we will import a new class called `ViewManager` which will handle all of the view routing and configuration. The index.js would look like this:
> 
> ```
> import React from 'react';
> import ReactDOM from 'react-dom'
> import ViewManager from './ViewManager';
> 
> ReactDOM.render(<ViewManager />, document.getElementById('root'));
> ```
> 
> and our `ViewManager.js` class file should look something like this:
> 
> ```
> import React, { Component } from 'react';
> import {
>   BrowserRouter as Router,
>   Route
> } from 'react-router-dom'
> import Update from './ViewA';
> import Console from './ViewB';
> 
> class ViewManager extends Component {
> 
>   static Views() {
>     return {
>       viewA: <ViewA/>,
>       viewB: <ViewB/>
>     }
>   }
> 
>   static View(props) {
>     let name = props.location.search.substr(1);
>     let view = ViewManager.Views()[name];
>     if(view == null) 
>       throw new Error("View '" + name + "' is undefined");
>     return view;
>   }
>   
>   render() {
>     return (
>       <Router>
>         <div>
>           <Route path='/' component={ViewManager.View}/>
>         </div>
>       </Router>
>     );
>   }
> }
> 
> export default ViewManager
> ```
> 
> `ViewA` and `ViewB` are just regular `React.Component` classes. The `ViewManager` will inject these components based on the routes defined by the name of the query string after `?` When no view is defined or an incorrect name is used. an exception is thrown so you know the mapping is wrong.
> 
> When you need to add another view, such as `ViewC` to your project, just import the new Component at the top of the `ViewManager` like
> 
> ```
> import Update from './view/ViewC';
> ```
> 
> and update this array method of the `ViewManager`:
> 
> ```
>   static Views() {
>     return {
>       viewA: <ViewA/>,
>       viewB: <ViewB/>,
>       viewC: <ViewC/>
>     }
>   }
> ```
> 
> There currently is no way to dynamically lookup and return a react component with a string directly. You have to register the component into an object. Using a `ViewManager` class is clean, and provides a global way to access the views and associated components statically; such as :
> 
> `ViewManager.Views()` -> returns a map of the view components
> `ViewManager.View(prop)` -> a way to return the component on the name
> 
> I am sure there are some ways to extend the functionality, but this is for minimal code
> 
> GLHF;
> 
> => https://medium.com/@1t4x0r/multiple-electron-windows-using-a-view-manager-and-react-js-6d8b1e209faf

Good work! 
You can also import `useLocation` from `react-router-dom` instead of passing with `props`. 
For instance, I use the following function to parse the URL query. 
`function useQuery() {
    return new URLSearchParams(useLocation().search);
  }`

I can then access more than one params of the query by using the following code (Assuming I am using standard URL query syntax that has been encoded e.g. http://localhost:3000?key1=val1&key2=val2).
`let query = useQuery();`
`query.get("key1"); # Returns the value at key1`
`query.get("key2"); # Returns the value at key2`
`let x = query.get("key3"); # x is undefined`

I then can write 
` x ? console.log("x has a value") : console.log("x is null or undefined or false")`

**Comment by ZoeDreams** [comment]
good looks:) yes useLocation is a more pragmatic and extensible approach, however has more overhead. I actually recently switched to this when i needed to pass in a flag for rendering 3d in one of my windows. This flag was determined by a setting in the main process so i bubbled it as a url param in this router..

**Comment by akbar-animaker** [comment]
@ZoeDreams i seen your suggestion the way to handle multiple windows... in that case how can i use parent window redux state value in child one?

**Comment by leandroasilva** [comment]
>  Console from './Vi

Hello, how are you.
I did exactly as you said in the tutorial, but my application, when opening the second view in a new window, an error occurs saying that
`Uncaught ReferenceError: require is not defined` and in debug, it points the error exactly to the` export default` of the screen in question.

do you know how to solve?

**Comment by ZoeDreams** [comment]
> > Console from './Vi
> 
> Hello, how are you.
> I did exactly as you said in the tutorial, but my application, when opening the second view in a new window, an error occurs saying that
> `Uncaught ReferenceError: require is not defined` and in debug, it points the error exactly to the` export default` of the screen in question.
> 
> do you know how to solve?

the renderer uses ECMA 6+ require is ECMA v5. consider using export statements in your renderer code.

**Comment by xlinbsd** [comment]
Hi, I'm successfully using this HashRouter config but only on Linux and MacOS.
On Windows, the printPreviewWindow content is blank and no error is produced.

Why, I'm wondering.
Any Idea here ?

##### index.js
```js
import React from "react"

import ReactDOM from "react-dom"
import App from "./App.js"
import PrintPreview from "./PrintPreview.js"
// import * as serviceWorker from "./serviceWorker"
import { HashRouter, Route } from "react-router-dom"

ReactDOM.render(
    <React.StrictMode>
        <HashRouter>
            <div>
                <Route exact path="/">
                    <App />
                </Route>
                <Route exact sensitive path="/printPreview">
                    <PrintPreview />
                </Route>
            </div>
        </HashRouter>
    </React.StrictMode>,
    document.getElementById("root")
)

```


Building on Linux. I never had a problem of different behavior under Win until now.

##### electron.js
```js
[...]
mainWindow.loadURL(
        isDev
            ? "http://localhost:3000"
            : `file://${path.join(__dirname, "../build/index.html")}`
    )
[...]
printPreviewWindow.loadURL(
        isDev
            ? "http://localhost:3000/#/printPreview"
            : `file://${path.join(
                  __dirname,
                  "../build/index.html#/printPreview"
              )}`
    )
[...]
```

**Comment by xlinbsd** [comment]
I found out the relative path constructor is not well understood on Windows.

Replacing 

``file://${path.join(
                  __dirname,
                  "../build/index.html#/printPreview"
              )}``

with

`file://${__dirname}/index.html#/printPreview`

And voilà HashRouter is working like a charm on every platform

**Comment by gautamsi** [comment]
is this HashRouter working fast for you, long time ago when I used this, it was very slow in opening new window.

**Comment by xlinbsd** [comment]
Yes, it is pretty fast, under 1s in dev. I'm using the v6 of react-router, quite lighter than the previous release too.

**Comment by gautamsi** [comment]
is there support for dynamic import so that my very large main page is not loaded just to mount a slick light dialog box?

**Comment by xlinbsd** [comment]
@gautamsi Route to the dialog component on "/" then and your main when needed.

**Comment by gautamsi** [comment]
I will try that, thanks

**Comment by ZoeDreams** [comment]
> I found out the relative path constructor is not well understood on Windows.
> 
> Replacing
> 
> `file://${path.join( __dirname, "../build/index.html#/printPreview" )}`
> 
> with
> 
> `file://${__dirname}/index.html#/printPreview`
> 
> And voilà HashRouter is working like a charm on every platform

Thank you. Yes, i haven't tested this on windows since around the time that i originally wrote this stuff. That sounds like a bug in  the Path module within your windows environment. Good troubleshooting, i am happy you figured it out.

**Comment by hi2u** [comment]
Does anyone know of any example github repos that demonstrate opening a new window when clicking something?  I've spent a couple of days on this, and I don't seem to be getting anywhere.

I want to be able to click buttons inside my React components that will open routes/components in new windows.  i.e. I don't just want a bunch of windows to open by default when starting the app.

I've tried examples from a bunch of different sources, but no idea what is out of date or different in the current version of electron-react-boilerplate.  I've seen lots of mentions of `Router.tsx`, which I don't have.  [So I've just assumed I can add those changes into `App.tsx` here?](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/src/renderer/App.tsx#L45-L49)

I can't remember which source material/stackoverflow question led me to: https://electron-react-boilerplate.js.org/docs/native-modules/#renderer-process-native-modules - but one of the things I've tried is the webpack.config edits mentioned on that page.  But confused about how simply opening a new window even relates to "native modules" or "remote content" to begin with.  Did I need to make these edits?  These changes seem to prevent me from viewing  `http://localhost:1212/` in my browser, it just always shows a blank page, so I can't even figure out how to test my routes there before trying to access them inside electron.

**Comment by whoisryosuke** [comment]
[This query param method works well](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/623#issuecomment-333750155) to create multiple windows using a single render -- **but** I was only able to get the query params using `global.location.search`. 

You can see [the related issue on StackOverflow here.](https://stackoverflow.com/questions/38335004/how-to-pass-parameters-from-main-process-to-render-processes-in-electron/38401579#38401579)

**Comment by nlemoine** [comment]
Anyone tried https://github.com/pvrobays/electron-multi-monitor?

**Comment by NxRoot** [comment]
### Check out this updated example.
It allows bundles to be managed correctly without any overhead
[https://github.com/NxRoot/electron-multiple-windows](https://github.com/NxRoot/electron-multiple-windows)

**Comment by SaadiSidali** [comment]
I wanted to show 2 windows at the same time but this solution doesn't help, I made my own solution but it requires a minor config:
first you create a new file inside the `renderer ` with the `tsx` extension and you make whatever page you want to make. I made a `child.tsx` and here's my page :
```tsx
import React from "react";
import { createRoot } from "react-dom/client";
import "./App.css";

const container = document.getElementById("root")!;
const root = createRoot(container);
// @ts-ignore
root.render(
  <div
    style={{
      color: "black",
      background: "red",
    }}
  >
    hi
  </div>
);
```
after that you go to `.erb/configs/webpack.config.renderer.dev.ts` and look for the `entry` objects, now you will import your react files and name them according to the window you want to render for example I named mine app for the main app and child for the child window:
```ts
 entry: {
    w1: `webpack-dev-server/client?http://localhost:${port}/dist`,
    w2: "webpack/hot/only-dev-server",
    app: {
      import: path.join(webpackPaths.srcRendererPath, "index.tsx"),
    },
    child: {
      import: path.join(webpackPaths.srcRendererPath, "child.tsx"),
    },
  },
```
note: `entry` was an array before.

you also need to modify the `output` object so that webpack packs your js in seperate files 
```ts
output: {
    path: webpackPaths.distRendererPath,
    publicPath: "/",
    filename: "[name].renderer.dev.js",
    library: {
      type: "umd",
    },
  },
```
then you scroll down to the plugins section and edit the `new HtmlWebpackPlugin` for the main app, and also make a copy for the child app like so:
```ts
new HtmlWebpackPlugin({
      chunks: ["app"],
      filename: path.join("index.html"),
      template: path.join(webpackPaths.srcRendererPath, "index.ejs"),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      isBrowser: false,
      env: process.env.NODE_ENV,
      isDevelopment: process.env.NODE_ENV !== "production",
      nodeModules: webpackPaths.appNodeModulesPath,
    }),

    new HtmlWebpackPlugin({
      chunks: ["child"],
      filename: path.join("child.html"),
      template: path.join(webpackPaths.srcRendererPath, "index.ejs"),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      isBrowser: false,
      env: process.env.NODE_ENV,
      isDevelopment: process.env.NODE_ENV !== "production",
      nodeModules: webpackPaths.appNodeModulesPath,
    }),
```
now when you start the app it should work in dev mode and we need to make similar modification in production mode
go to `.erb/configs/webpack.config.renderer.prod.ts`
edit the `entry` object:
```ts
 entry: {
    app: path.join(webpackPaths.srcRendererPath, "index.tsx"),
    child: path.join(webpackPaths.srcRendererPath, "child.tsx"),
  },
```
and the `output` object:
```ts
output: {
    path: webpackPaths.distRendererPath,
    publicPath: "./",
    filename: "[name].renderer.js",
    library: {
      type: "umd",
    },
  },
```
scroll down to the plugins section: 
```ts
new HtmlWebpackPlugin({
      chunks: ["app"],
      filename: "index.html",
      template: path.join(webpackPaths.srcRendererPath, "index.ejs"),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      isBrowser: false,
      isDevelopment: process.env.NODE_ENV !== "production",
    }),
    new HtmlWebpackPlugin({
      chunks: ["child"],
      filename: "child.html",
      template: path.join(webpackPaths.srcRendererPath, "index.ejs"),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      isBrowser: false,
      isDevelopment: process.env.NODE_ENV !== "production",
    }),
```

note: if you are using css in your project or a css framework like tailwind you need to add `[name]` in your `MiniCssExtractPlugin` for both dev and production like so:
```ts
new MiniCssExtractPlugin({
      filename: "[name].style.css",
    }),
```

**Comment by gdbroman** [comment]
Exquisite explanation @SaadiSidali, this worked perfectly, thank you.

**Comment by moussa32** [comment]
Thank you @SaadiSidali but i got error when i am trying to build the project
![image](https://user-images.githubusercontent.com/25851117/222983736-f409a008-5c1d-49af-b21a-42460e3553da.png)

**Comment by mokhtarHamdoune** [comment]
For me I used **HashRouter** and  I add a Route inside it called /card-only 
then in electron.js, I add the following:
```javascript 
const SecondScreen = new BrowserWindow({
    width: 800,
    height: 600,
    minWidth: 800,
    minHeight: 600,
    icon: path.join(__dirname, "icon.ico"),
    webPreferences: {
      nodeIntegration: true, // Enable Node integration
      preload: path.join(__dirname, "preload.js"),
    },
  });

let secondScreeUrl =
    process.env.node_env === "Development"
      ? process.env.ELECTRON_START_URL + "#/card-only"
      : `file://${path.join(__dirname, "../build/index.html#card-only")}`;

  SecondScreen.loadURL(secondScreeUrl);
````

**Comment by gurkanozer2609** [comment]
I sent path from my createWindow function. And listen that on App.tsx. Then just navigate that path.

main.ts:
```
export const createSettingsWindow = (data:string):void =>{
  // Create the browser window.
  const settingsWindow = new BrowserWindow({
    width: 900,
    height: 670,
    minWidth:420,
    minHeight:520,
    show: false,
    // frame:false,
    // titleBarStyle:'hidden',
    center:true,
    title:'Pool Control',
    autoHideMenuBar: true,
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
      contextIsolation: true
    }
  })

  settingsWindow.on('ready-to-show', () => {
    settingsWindow.show()
    settingsWindow.webContents.send('fromMain', data);
  })
  settingsWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  // HMR for renderer base on electron-vite cli.
  // Load the remote URL for development or the local html file for production.
  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    settingsWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    settingsWindow.loadFile(join(__dirname, '../renderer/index.html')
  )
  }
  settingsWindow.webContents.openDevTools() 

}
```
and App.tsx:

const App = (): => {
  const navigate = useNavigate();
  useEffect(() => {
    window.api.receive('fromMain', (data) => {
      navigate(data)
    })
  }, [])
  return (
    <Routes>
      <Route path="/" element={<StartScreen />} />
      <Route path="/settings" element={<SettingsScreen />} />
    </Routes>
  )
}

export default App
