### ISSUE TITLE
'Module not found: Error' when packaging

### ISSUE THREAD

**Issue by doortts** [chentsulin/electron-react-boilerplate#627]
When I packaging, The following error occurs.

```
yarn run package
...
...
ERROR in ./~/get-cursor-position/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./build/Release/pos in /xxx/xxx/~~~/node_modules/get-cursor-position
 @ ./~/get-cursor-position/index.js 1:11-41

ERROR in ./~/iconv/lib/iconv.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Debug/iconv.node in /xxx/xxx/~~~/node_modules/iconv/lib
 @ ./~/iconv/lib/iconv.js 29:13-49
```

get-cursor-position/index.js line 1:
```javascript
var pos  = require('./build/Release/pos');
var tty  = require('tty');
```

What I examined...

```sh
ls ./build/Release

drwxr-xr-x  3 user  staff   102B 12 20 18:35 obj.target
-rwxr-xr-x  1 user  staff    11K 12 20 18:35 pos.node
```

./~/iconv/lib/iconv.js 29:13-49

```javascript
...
catch (e) {
  bindings = require('../build/Debug/iconv.node');
}
...
```

and..

```sh
-rw-r--r--  1 user  staff    13K 12 20 18:35 Makefile
drwxr-xr-x  5 user  staff   170B 12 20 18:35 Release
-rw-r--r--  1 user  staff   113B 12 20 18:35 binding.Makefile
-rw-r--r--  1 user  staff   4.5K 12 20 18:35 config.gypi
-rwxr-xr-x  1 user  staff    23K 12 20 18:35 gyp-mac-tool
-rw-r--r--  1 user  staff   5.7K 12 20 18:35 iconv.target.mk
```

there is no Debug directory.

I don't know what's the problem.
Is there any clue?

**Comment by amilajack** [comment]
Does a fresh clone of the project work for you?

**Comment by doortts** [comment]
@amilajack Sadly it didn't work.

I think you can reproduce it following steps.


```
yarn add xml-stream
```

Add following code at first line of  main.development.js

``
import xmlStream from 'xml-stream';
...
``
![image](https://cloud.githubusercontent.com/assets/520523/21378974/d5b3235c-c78d-11e6-9fb0-942a638b519d.png)


then run package
```
yarn run package
```

ps
This is my running system..

![image](https://cloud.githubusercontent.com/assets/520523/21378988/efeeb15a-c78d-11e6-85d9-17494a6ef76e.png)

**Comment by amilajack** [comment]
What was the issue with the fresh clone? Lets start there. that way, we know if the issue is related to the project or not.

**Comment by doortts** [comment]
@amilajack Yes! I tested it with new clone. 

I started.. 

```
git clone --depth 1 https://github.com/chentsulin/electron-react-boilerplate.git

cd electron-react-boilerplate

yarn add xml-stream

```
...

and then next works are as I wrote above.

**Comment by jhen0409** [comment]
Add `get-cursor-position` and `iconv` to dependencies of `app/package.json`, because they are native modules (See [README.md#module-structure](https://github.com/chentsulin/electron-react-boilerplate#module-structure)), or just add `xml-stream`.

**Comment by doortts** [comment]
@jhen0409 You are right! It is resolved. Thank you for your the correct resolution. 
@amilajack Thanks!!
