### ISSUE TITLE
Error in using React-Konva

### ISSUE THREAD

**Issue by StefanWerW** [chentsulin/electron-react-boilerplate#639]
I am trying to use [react-konva](https://github.com/lavrton/react-konva) but somehow is not working.
I installed `react-konva` and `konva` directly on './app/package.json'

Error on console:
> Uncaught TypeError: Cannot read property 'getPooled' of null

Apparently the error is coming from [this line of code](https://github.com/lavrton/react-konva/blob/a117d9106862e3cecdb0c45df3b13f9ad0bb2c65/src/react-konva.js#L270)

Am I doing something wrong here? Could it be a problem caused by two 'package.json' structure? Should I install the packages differently?

Thanks

**Comment by flyingant** [comment]
You probably need to do some changes on you webpack config file.

**Comment by amilajack** [comment]
Closing due to no response

**Comment by StefanWerW** [comment]
@flyingant Thanks, but your answer was a little vague. I still dont know what is causing the error and how to fix it. Any clue what should i change in webpack config?


------------------------------------------
@amilajack Sorry for the delay, is it possible to reopen this issue. Still not resolved. Thanks

**Comment by flyingant** [comment]
My solution is add the canvas as external to the webpack config file.

`...

 externals: [
         'canvas'
 ]

...
`

Hope it helps. 
@StefanWerW

**Comment by StefanWerW** [comment]
@flyingant Thanks, but I still a little lost here.
### Externals
I thought that any dependency on the './app/package.json' was automatcly add as externals for webpack.
`webpack.config.base.js`:
```js
import { dependencies as externals } from './app/package.json';

...

    externals: Object.keys(externals || {})
```

### canvas
As far as I am concerned, the `canvas` package dependency is only required for the `konva` package when using in a node environment. I thought in electron it was as if we were using in a browser. 

Hence, there is a project, [Opensprint Electron](https://github.com/opensprints/opensprints-electron/), that is a old fork from this repo (single package.json structure still), and uses `konva` and `react-konva` successfully and without the need of the `canvas` dependency, and without adding externals to webpack.

I wasn't able to pinpoint what is essentially different from their package to mine in therms of config, except for the single package.json structure, but it should be the same as us npm installing on the root './package.json'

Any thoughts? 😄

**Comment by flyingant** [comment]
Not sure if we had the same file structure. I noticed that you installed `react-konva` and `konva`  on `./app/package.json` but not on the root directory. Perhaps you should install them on `./package.json`.

If still not working. could you please paste you config files and package.json here?
@StefanWerW

**Comment by flyingant** [comment]
BTW, the `canvas` is a dependency of the 'react-konva' and I'm pretty sure it works well on both node environment and browser.
@StefanWerW

**Comment by StefanWerW** [comment]
I know that `canvas` is a dependency of `konva` but only on the node env. From[ the words](https://github.com/konvajs/konva/issues/146#issuecomment-213901676) of the `konva` dev:

> I am using Konva with webpack. It works well. What exactly is not working? canvas and jsdom are described in package.json to be skipped in browser env.

How it should be skipped I not so sure. Apparently `"browser": {
    "canvas": false,
    "jsdom": false
  }` on package.json suggest that somehow 😕 .


---------------------------------------------

Now, I finally made it work somehow, but I don't fully understand the magic behind. I installed `konva` and `react-konva` in the root pacake.json, and also put this on webpack.config.development.js:
```js
  plugins: [
    // for react-konva
    new webpack.IgnorePlugin(/canvas$/),
    new webpack.IgnorePlugin(/jsdom$/),
    ...
```
In [this issue](https://github.com/konvajs/konva/issues/146) the `konva` dev suggest this should not be required. But is the only way I get to make it work. Still the question, is this ok? Or is a dirty fix? Will it work on the production, since it's only on the dev config file?

Thanks 😄

**Comment by amilajack** [comment]
@StefanWerW did you resolve this issue?

**Comment by StefanWerW** [comment]
@amilajack Partially. The issue is resolved by doing something that I'm not sure is clean and correct to do. It seems a little dirty. But I think you can close this issue. Thank you :smile:

**Comment by bianbiandashen** [comment]
...
