### ISSUE TITLE
Dynamic Linking error happens only in packaged app

### ISSUE THREAD

**Issue by lironzua** [chentsulin/electron-react-boilerplate#644]
I'm getting this error after running an OSX packaged app:

Uncaught Error: Dynamic Linking Error: dlopen(/Users/......./release/mac/electron-react-boilerplate.app/Contents/Resources/app.asar/node_modules/argon2-ffi/build/Release/argon2.dylib, 2): no suitable image found.

This isn't happening while running the code in development mode

How can I resolve this?

**Comment by amilajack** [comment]
Solving this kind of issue will take a while to fix. Make sure that the dylib files are in production. I solved this by writing a small script that moves dylibs to a dist folder when packaging.

**Comment by lironzua** [comment]
Thanks for the answer! can u please elaborate more on that? 
If u can share the script that would be wonderful

**Comment by amilajack** [comment]
[Here's](https://github.com/amilajack/popcorn-time-desktop/blob/master/postinstall.js) the script for that. [These lines](https://github.com/amilajack/popcorn-time-desktop/blob/master/postinstall.js#L36-L47) are all you need to pay attention to

**Comment by lironzua** [comment]
Thanks!

**Comment by rfedericoni** [comment]
Hi, I have the same problem and to see the script would be very useful but the link it doesn't exist anymore.. can you help me?
