### ISSUE TITLE
Cant run npm run dev. Give me a ENONT FILE error

### ISSUE THREAD

**Issue by golinmarq** [chentsulin/electron-react-boilerplate#655]
I clone this repo, then "yarn it" and then run `npm run dev` as documentation said, but I still get the following error 

    fs.js:557
      return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                     ^
    
    Error: ENOENT: no such file or directory, open '/Users/myuser/Documents/Github/r-e-bp/node_modules/electron/path.txt'
        at Object.fs.openSync (fs.js:557:18)
        at Object.fs.readFileSync (fs.js:467:33)
        at Object.<anonymous> (/Users/myuser/Documents/Github/r-e-bp/node_modules/electron/index.js:4:42)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)

What could be this error?

**Comment by amilajack** [comment]
See #400

**Comment by golinmarq** [comment]
Thanks @amilajack ! I already did that but, I get a new error now. I'm really frustated

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /var/folders/gy/6046zxfx2gjc8qnx3ksbzr2c0000gn/T/npm-30684-36d1eed9/registry.npmjs.org/flow-bin/-/flow-bin-0.37.4.tgz
```

**Comment by amilajack** [comment]
Make sure you're using latest npm. If that doesn't work, use `yarn`:

```
npm i -g yarn
yarn # <-- this is yarn's npm install
```

**Comment by golinmarq** [comment]
In fact I've tried with Yarn and NPM but it doesn't work with any of these. I follow the instructions in #400. 

Right now, after analyze my first error I see that the path.txt was not created. I delete the node_modules/electron and then run `npm install electron` but, the `node install.js` part is taking too much time (15 min and counting). What can it be?

**Comment by amilajack** [comment]
I'm guessing you're on windows. Is that true?

**Comment by golinmarq** [comment]
@amilajack no, I using macOS Sierra with node v7.2.1, npm  v3.10.9 and yarn v0.17.10

I got this from yarn-debug-log
```
Trace: 
  Error: EACCES: permission denied, unlink '/Users/myUser/Documents/Github/r-e-bp/node_modules/.bin/_mocha'
```

**Comment by amilajack** [comment]
How did you install `npm` and `node?`

**Comment by golinmarq** [comment]
Using Homebrew like 
```
brew update
brew install node
brew link node
```

**Comment by amilajack** [comment]
Try this:
```
sudo chown -R $USER:$GROUP ~/.npm
```

**Comment by golinmarq** [comment]
I still get the `An unexpected error occurred: "EACCES: permission denied`

**Comment by amilajack** [comment]
Try these solutions: https://docs.npmjs.com/getting-started/fixing-npm-permissions

Also bear with me here. This isnt an issue with this project. Its an issue with your installation of npm.

**Comment by golinmarq** [comment]
I fix it using sudo, but the `node install.js` is taking too much time

**Comment by amilajack** [comment]
That's a very abnormal issue. I would try removing all traces of npm and reinstall it (not with brew).

**Comment by amilajack** [comment]
Try installing with `npm` instead of `yarn`

**Comment by golinmarq** [comment]
@amilajack indeed, it works with npm and fails with yarn. Probably is an error with yarn packages
