### ISSUE TITLE
how not to open chrome devtools in production

### ISSUE THREAD

**Issue by barbalex** [chentsulin/electron-react-boilerplate#659]
this must be the dumbest question ever but I have not found any way to get the production app not to have devtools opened when starting up.

What am I missing?

Help is much appreciated.

**Comment by barbalex** [comment]
Sorry, it really was the dumbest question ever: I now found the code where I myself permanently turned on devtools... :-)

    mainWindow.openDevTools()

**Comment by ballPointPenguin** [comment]
This helped me figure out how to run devTools in production. Thanks :)

**Comment by barbalex** [comment]
:-)
