### ISSUE TITLE
PR: Webpack 2 Migration

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#660]
Webpack 2 was released today. When it becomes more stable and plugin support for it improves, we should migrate to it

**Comment by AlexFrazer** [comment]
I am working on adding it to my application, which is based on this boilerplate. Can provide PR if needed

**Comment by amilajack** [comment]
@AlexFrazer that would be great!

**Comment by psamim** [comment]
@AlexFrazer Is you PR ready?

**Comment by AlexFrazer** [comment]
@psamim , I do have it working locally, yes.
I will put in the PR tomorrow, there were some relatively major changes, such as completely removing the `server.js` file from the base (no longer necessary in webpack 2)

**Comment by AlexFrazer** [comment]
https://github.com/chentsulin/electron-react-boilerplate/pull/769

PR Open
