### ISSUE TITLE
"Cannot call a class as a function" in production mode on Windows

### ISSUE THREAD

**Issue by NikitaKoval** [chentsulin/electron-react-boilerplate#669]
# Versions
OS: Windows 10 x64
Boilerplate: 0.10.0 (10e6a73d228b2e400ecff8529ff85da5529edc36)

# Steps to reproduce
1. Clone repo
2. Install dependencies
3. Run `npm run package-win` and start the app or `npm run build && npm start`

# Actual result
![capture](https://cloud.githubusercontent.com/assets/5259652/22189325/159cd338-e146-11e6-9f37-82aa88313fcf.PNG)

I fixed the error by replacement `BabiliPlugin` to `UglifyJsPlugin` in webpack config and added `es2015` to presets in `.babelrc`

**Comment by amilajack** [comment]
Just to confirm this isnt an installation issue, try the following.

```
npm i -g yarn
git clone https://github.com/chentsulin/electron-react-boilerplate.git
cd electron-react-boilerplate
yarn
yarn run dev
```

**Comment by NikitaKoval** [comment]
@amilajack Thanks. When i use yarn it works in production mode too. I believe the problem is in npm. It is not boilerplate issue.
