### ISSUE TITLE
Default app doesn't work correctly on Windows 8.1?

### ISSUE THREAD

**Issue by gbmhunter** [chentsulin/electron-react-boilerplate#67]
`npm install` and `npm run hot-server` work fine, but `npm run start-hot` gives me the following error:

![image](https://cloud.githubusercontent.com/assets/2396869/10752621/cdf5a9d0-7cef-11e5-8772-dcde6de8ecb5.png)

**Comment by gbmhunter** [comment]
Note that putting `electron .` at the start of the `start-hot` script fixes this error, but then electron loads up an empty screen (I believe it is meant to show a home page?).

**Comment by catalinmiron** [comment]
@gbmhunter can you do the following:

```bash
set HOT=1 & NODE_ENV=development electron .
```
or 
```bash
set HOT=1 & NODE_ENV=development & electron .
```

or if this is not working for you, a quick win is to modify [this](https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.js#L21-L25) with 

```javascript
if (process.env.NODE_ENV === 'development') {
  mainWindow.loadUrl('file://' + __dirname + '/app/hot-dev-app.html');
} else {
  mainWindow.loadUrl('file://' + __dirname + '/app/app.html');
}
```
and run `set NODE_ENV=development electron .`

In this way, the `html` file loading in main, when `NODE_ENV=development` is `hot-dev-app.html`

**Comment by gbmhunter** [comment]
Thanks for the help.

I tweaked what you mentioned above and managed to get it working with:
`start-hot": "set HOT=1 & set NODE_ENV=development & electron .`

**Comment by catalinmiron** [comment]
@gbmhunter great!
