### ISSUE TITLE
Redux Form - React Hot Loader v3

### ISSUE THREAD

**Issue by arieldf** [chentsulin/electron-react-boilerplate#701]
Hi @chentsulin 

Thanks a lot for this boilerplate.

I have implemented Redux Form in my app (v6) which requires med to upgrade to React Hot Loader v3. I have followed your example (https://github.com/chentsulin/electron-react-boilerplate/pull/421/commits/bc41473c69c2cf335dbb95f2efd96956d07e469a) exactly, but HMR does not work for me - I get this error:

process-update.js:81 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js:89 [HMR]

Do you have any idea of what can be wrong?

Best regards
Ariel

**Comment by amilajack** [comment]
ping @jhen0409

**Comment by jhen0409** [comment]
I haven't yet to use RHL v3 because some [issues](https://github.com/gaearon/react-hot-loader/issues). @arieldf I might to try at the weekend.

**Comment by amilajack** [comment]
This was done in https://github.com/chentsulin/electron-react-boilerplate/pull/769
