### ISSUE TITLE
Using @Radium with transform-decorators-legacy fails after package

### ISSUE THREAD

**Issue by Cipher-geek-Studios** [chentsulin/electron-react-boilerplate#706]
Hello guys,

I'm using `radium` to style the react components. I have called it and used it as `export default Radium(component)`. But when package the app it is showing  an error `Uncaught Error: Cannot find module 'react'` .

I don't see this error in `dev mode`. But if i install `react` in app dir this issue is cleared but whenever i use refs in components. It is showing an error that refs can only be used in master component. 

plz help me out.

**Comment by amilajack** [comment]
try to see if you can reproduce this with the latest release.  This may have to do with the two-package.json structure.
