### ISSUE TITLE
command not found: install-app-deps

### ISSUE THREAD

**Issue by Jamlee** [chentsulin/electron-react-boilerplate#726]
## the problem
````
> electron-react-boilerplate@0.10.0 postinstall /home/jamlee/test/paas-installer
> concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

[0] zsh:1: command not found: install-app-deps
[0] install-app-deps exited with code 127
[1] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0
````
## my env
npm ERR! Linux 4.9.8-1-ARCH
npm ERR! argv "/home/jamlee/.nvm/versions/node/v6.3.0/bin/node" "/home/jamlee/.nvm/versions/node/v6.3.0/bin/npm" "run" "postinstall"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5

## How to reslove the problem？
i change it to： `  "postinstall": "concurrently \"./node_modules/.bin/install-app-deps \" \"node node_modules/fbjs-scripts/node/check-dev-engines.js package.json\"",
    `

**Comment by amilajack** [comment]
Try installing with npm instead of yarn
