### ISSUE TITLE
Using npm > 3 will cause packaging to miss dependencies

### ISSUE THREAD

**Issue by rbkreisberg** [chentsulin/electron-react-boilerplate#73]
Using this logic for gathering npm modules to ignore does not work correctly for npm versions greater than 3. I tried this with npm 3.4.0.
```
var devDeps = Object.keys(require('./package.json').devDependencies);
var DEFAULT_OPTS = {
   ....,
  ignore: [
   ....,
  ].concat(devDeps.map(function(name) { return '/node_modules/' + name + '($|/)'; }))
};
```
https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.js#L26

With npm > 3, there are child dependencies of top-level production dependencies in the node_modules folder.  (```async``` may be listed in devDependencies and is also a child dependency of a project like ```request```)

The necessary dependency is not bundled by ```electron-packager```.

I've tried a few approaches, but I don't have a solution for this, yet.

Thanks for the great work on this poject.

**Comment by rbkreisberg** [comment]
It looks like the same thing can happen with npm 2.  When the devDependency version of async is close enough to the child dep of a production dependency, that linked dep is lost.

**Comment by jhen0409** [comment]
In my work project, I using a new folder to build (including package.json), and run `npm i --production` reinstall dependencies, it seems to solved this problem, @chentsulin you think? Or do we use webpack in main script? :D

**Comment by chentsulin** [comment]
Maybe we can give electron-packager's [opts](https://github.com/maxogden/electron-packager#opts) `prune` a try and see whether it works on npm@3 or not.

**Comment by rbkreisberg** [comment]
@jhen0409 How do you run the build without the devDependencies present in the project?  Does this mean that electron-packager and the other build tools are being pulled into the compiled app?

**Comment by rbkreisberg** [comment]
I tried the following:

added npm as a devDependency
``` npm install npm --save-dev```

Identify production only (or dev only) dependencies using the following
 ```
npm.load({json:true, parseable: true, production: true}, function(err) {
      npm.ls([], function(err, data, lite) {
         console.log(data);
          console.log(lite);
       });
});
```
but either this is broken or the parameters are wrong.

**Comment by jhen0409** [comment]
@rbkreisberg no, I just create new a child folder (copy package.json to it, use `--production` to `install` or copy node_modules then `prune`), so build is work on parent folder, but it only packaging for node_modules of the child folder.

**Comment by jhen0409** [comment]
@chentsulin electron-packager's `prune` it works! @rbkreisberg you can try in [this](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.js#L88).

**Comment by rbkreisberg** [comment]
@jhen0409 @chentsulin thanks.  I used prune for a while and took it out after rebasing to a more recent version of electron-react-boilerplate.  Adding it back in solved my issue!
