### ISSUE TITLE
How to log errors in main and render process to a file?

### ISSUE THREAD

**Issue by talha131** [chentsulin/electron-react-boilerplate#731]
Thank you team for developing this awesome boilerplate and continuing active development on it. I cannot thank you enough for giving me a head start. 

I have a question. How can I log errors that are generated in main process and render process to a file, such that it works in development and production package both?

Besides, `console.error()`, it would be great if I can log warnings and errors that are thrown into Developer Tools Console, like this

<img width="718" alt="screen shot 2017-02-12 at 00 24 05" src="https://cloud.githubusercontent.com/assets/1094724/22856740/aa518d7a-f0b9-11e6-80a2-d88949b31419.png">

**Comment by amilajack** [comment]
See:

**Comment by talha131** [comment]
@amilajack If I understand correctly, other issues are focused on debugging. All I want is to generate a log file, which should have output of not just `Console.error()` but also `Console.log()`, `Console.info()`.

Nodejs docs has an example of using a file for collecting logs. See [this link](https://nodejs.org/api/console.html#console_new_console_stdout_stderr).

```js
const output = fs.createWriteStream('./stdout.log');
const errorOutput = fs.createWriteStream('./stderr.log');
// custom simple logger
const logger = new Console(output, errorOutput);
// use it like console
const count = 5;
logger.log('count: %d', count);
// in stdout.log: count 5
```

What I don't understand is how to make sure this will work in production package, and to make render and main process write to the same file.

**Comment by amilajack** [comment]
`console.log` doesn't log to the regular console in dev tools. I logs to a server that you would need to run. It is discussed in the vscode issue

**Comment by talha131** [comment]
Forgive my ignorance. But I had my code littered with `console.log()`. The `console.log` always appeared in the Dev Tools during development. The `console.log` defined in the main process, appeared in the terminal where I kick started electron using `npm run start-hot`.

> `console.log` doesn't log to the regular console in dev tools.

Are you saying in *production*, `console.log` doesn't log to the regular console in dev tools?

**Comment by amilajack** [comment]
> Are you saying in production, console.log doesn't log to the regular console in dev tools?

I'm actually not sure about that. I haven't tried that before. I just know that this project hasn't yet added support for development on the main thread.

**Comment by talha131** [comment]
> I'm actually not sure about that.

Ok, just an FYI. I run database queries on main process. It has bunch of `console.error()` and `console.log()`. It has always printed on the terminal from where I launched `start-hot`.

**Comment by amilajack** [comment]
What about when you run `npm run dev`?

**Comment by talha131** [comment]
Same output. All `console` statements are working.

**Comment by amilajack** [comment]
Interesting. Last time i tried this it didn't work.

**Comment by amilajack** [comment]
@talha131 did you find a solution for this?
