### ISSUE TITLE
PR/Docs: Editor setup guide for vscode

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#732]
I've been trying out vscode and I found it to be really nice for node development. Its much faster than atom and it has great support flow flow's type inspection.

If you have any suggestions for any recommended plugins, please feel free to contribute to this discussion!

**Comment by schaveyt** [comment]
Vs code has been a joy to work with. I recommend:

- vscode icons
- eslint
- mssql
- git history
- hopscotch theme
- atom one dark theme
- XML tools

**Comment by amilajack** [comment]
Links please! :)

**Comment by amilajack** [comment]
- [eslint](https://github.com/Microsoft/vscode-eslint)
- [flow](https://github.com/flowtype/flow-for-vscode)
- [editorconfig](https://github.com/editorconfig/editorconfig-vscode)

**Comment by chariot6** [comment]
- [Jest](https://github.com/orta/vscode-jest)
- [GitLens](https://github.com/eamodio/vscode-gitlens)
