### ISSUE TITLE
Error: Cannot find module 'express' in product environment

### ISSUE THREAD

**Issue by hl-a-k** [chentsulin/electron-react-boilerplate#744]
I need a express server in my app.
I move the express dependence from devDependencies to dependencies,
After execute:
    npm run package
 I still got an Error: Cannot find module 'express' in product environment

**Comment by hl-a-k** [comment]
I deleted my node_modules folder,and run "npm install" again,problem was solved

**Comment by amilajack** [comment]
Closing because you apparently resolved this issue
