### ISSUE TITLE
Types error in VS Code

### ISSUE THREAD

**Issue by utv** [chentsulin/electron-react-boilerplate#749]
I do install following extensions:
- ESLint
- EditorConfig
- Babel ES6/ES7

Here is my types error.
![type-error](https://cloud.githubusercontent.com/assets/2507485/22942634/28226256-f29f-11e6-9a4f-44308a643980.png)

Thank you.

**Comment by amilajack** [comment]
Leaving this closed until more information is provided. I don't know what the issue is here because i don't use vscode extensively.

**Comment by utv** [comment]
I figured it out.
1. Install "Flow Language Support" extension for vs code.
2. Set workspace preference with "javascript.validate.enable": false.
