### ISSUE TITLE
Question about running in dev

### ISSUE THREAD

**Issue by johnryan** [chentsulin/electron-react-boilerplate#757]
Is it expected that when running the app in dev mode it doesn't use any of the config from the package.json (productName, but more importantly url schemes i've set up). It is included correctly when i run package but it seems to be just running inside the Electron.app when i do `npm run dev`

**Comment by dustintownsend** [comment]
Yes this is expected. Development is running on a pre-built version of Electron. For more details: https://github.com/electron-userland/electron-prebuilt
