### ISSUE TITLE
Live reload does not work with adding new state to a component

### ISSUE THREAD

**Issue by utv** [chentsulin/electron-react-boilerplate#759]
Hello,

I try adding new state to a component and save, but it does not get updated.
I am not sure this is known limitation or not because I don't see it mentioned in the doc.

Thank you.

**Comment by dustintownsend** [comment]
@utv more details would be needed. But if you are referring to the initial Redux state then that is correct it shouldn't update the initial state on a hot reload.

**Comment by utv** [comment]
It is a state of a component, I don't do Redux.
I don't use it for a while so I don't remember the detail.

Thank you very much for your response.
