### ISSUE TITLE
How to make webpack supply environment variables to app.html?

### ISSUE THREAD

**Issue by rahilsondhi** [chentsulin/electron-react-boilerplate#760]
I want to add a `<script>` tag to the bottom of index.html that references an ENV var. Any tips on how to do that in development and production?

In dev, I have

```
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
      API_HOST: JSON.stringify(config.API_HOST),
      MIXPANEL_TOKEN: JSON.stringify(config.MIXPANEL_TOKEN),
      WEB_HOST: JSON.stringify(config.WEB_HOST),
    }),
```

which means I can access those env vars in my React component files, but they seem unavailable in app.html.

**Comment by amilajack** [comment]
The `DefinePlugin` replaces text. [See here](https://webpack.js.org/plugins/define-plugin/). I believe your `app.html` file is not processed by webpack. I would recommend keeping js logic isolated from your `app.html`. Its better to keep all your js in modules and import those modules via a script source instead of inline'd script tags

**Comment by rahilsondhi** [comment]
Thanks for the quick response @amilajack!

I was going to play around with the `options` configuration @ https://github.com/jantimon/html-webpack-plugin, but I wasn't sure how to configure that in development vs production, and I ended up finding a pre-made component that enables and configures Intercom for me https://github.com/nhagen/react-intercom, so I'm good for now 😃

**Comment by fangzhzh** [comment]
@rahilsondhi Hi, I have some problems to integrate intercom in eletron ^2.0.0 the old way(inline script tags). Does react-intercom with well with it?

**Comment by rahilsondhi** [comment]
Not sure, I'm not using 2.0.
