### ISSUE TITLE
Error when I run the cleanup script

### ISSUE THREAD

**Issue by Zac-Garby** [chentsulin/electron-react-boilerplate#764]
When I run _npm run cleanup_, there's an error in _/node_modules/boiler-room-custodian/app/modules/file-ops.js_, on line 51, saying that you can't use let, const, function or class outside strict mode. When I fix this, the same thing happens in a number of other places in the file.

**Comment by amilajack** [comment]
ping @tstringer

**Comment by tstringer** [comment]
@amilajack @Zac-Garby thanks for the heads up, looking into this.

**Comment by tstringer** [comment]
@Zac-Garby I am unable to reproduce this error. Here are the steps I took:

1. `git clone https://github.com/chentsulin/electron-react-boilerplate.git`
2. `cd electron-react-boilerplate`
3. Verify the sample app is working correctly: `npm run dev`
4. Run cleanup: `npm run cleanup`
5. Run the cleaned app: `npm run dev`

Looking at the console, I see no errors. This applies as well to the terminal. Successful build, successful run. If my repro steps are incorrect, can you please provide me with your repro steps to raise this error?

It's also worth noting that there are components (regex) in `boiler-room-custodian` that are designed to search through the files. Therefore, the best experience to "clean" the app is to run it with no custom code modifications. If you have modified the sample app, you run the risk of causing errant matches, or eliminating necessary matches.

**Comment by Zac-Garby** [comment]
@tstringer That's weird.

This is what I just tried:

 1. `git clone https://github.com/chentsulin/electron-react-boilerplate.git my-app`
 2. `cd my-app/`
 3. `npm install` - I tried first not doing this, like in your example, but then it wouldn't even run.
 3. `npm run dev` - The app opened, working perfectly.
 4. `npm run cleanup` - I've added an image of my terminal to show the output.

<img width="907" alt="screen shot 2017-02-20 at 16 14 53" src="https://cloud.githubusercontent.com/assets/19708658/23133079/b9a90c2e-f787-11e6-8dc3-aeab8de07471.png">

The _SyntaxError_ happens almost instantly after I use `npm run cleanup`.

I don't know if you're using macOS, but is it possible that that's the problem?

**Comment by Zac-Garby** [comment]
Also, I tried fixing all the syntax errors in _file-ops.js_ (There were about 5?) Once I'd done this, `npm run cleanup` worked without any errors.

**Comment by tstringer** [comment]
@Zac-Garby yeah I definitely did `npm install` as well, sorry for omitting that in my repro attempt 😅 

So I just ran your steps, still no repro. My only thought here is you're perhaps using an old cached version of `boiler-room-custodian`? While in the `my-app` directory, run `npm ls boiler-room-custodian`. What's the output?

**Comment by Zac-Garby** [comment]
$ npm ls boiler-room-custodian
    electron-react-boilerplate@0.10.0 /Users/zacgarby/Desktop/my-app
    └── boiler-room-custodian@0.6.1

**Comment by tstringer** [comment]
Ah, looking at the specific error I bet this has to do with the node version. You're running node 4.4.7. Is that a constraint for you?

**Comment by Zac-Garby** [comment]
It's not a constraint, no.

I've now updated node and it works! Thanks!
