### ISSUE TITLE
Which version to use? Latest release or master branch?

### ISSUE THREAD

**Issue by seanbuscay** [chentsulin/electron-react-boilerplate#765]
Hello. 

I look forward to trying your boilerplate. 

I noticed there are a lot of commits since the last tagged release from April last year. 

Do you recommend I use your master branch or your latest tagged release?

Thanks much.

**Comment by amilajack** [comment]
Master updates much faster. We still need to update all the documentation to reflect the changes since the last release before pushing the new release. I would recommend master for now
