### ISSUE TITLE
Cleanup script leaves the repository in a non working state.

### ISSUE THREAD

**Issue by KelSolaar** [chentsulin/electron-react-boilerplate#766]
After running `npm run cleanup` on 6a0c7f3a75208aae71bece34ef7cccac9bfb8ceb I end up with files partially written:

*Home.js*
```javascript
// @flow
import React, { Component } from 'react';
import { Link } from 'react-router';
import styles from './Home.css';
```

I then reset the repo: `git reset --hard HEAD`, run `npm run cleanup` again:

*Home.js*
```javascript
// @flow
import React, { Component } from 'react';
import { Link } from 'react-router';
import styles from './Home.css';


export default class Home extends Component {
  render() {
    return (
```

The file ends up in a different state pretty much all the time.

**Comment by amilajack** [comment]
@tstringer

**Comment by amilajack** [comment]
@KelSolaar There's been a lot of bugs related with the cleanup script. I think we should move towards a more elegant solution like that of create-react-app.

For now, I don't recommend using it. There isn't a really good solution for this right now

**Comment by tstringer** [comment]
Sorry for the delay on this one. @KelSolaar have you modified the underlying code prior to running the cleanup? The configuration is meant to match certain strings, as well as line numbers. Or was this a fresh install with no modified code?

**Comment by KelSolaar** [comment]
@tstringer : Yeah it was from fresh HEAD, I haven't tried recently though!
