### ISSUE TITLE
getting PostCSS to work

### ISSUE THREAD

**Issue by ballPointPenguin** [chentsulin/electron-react-boilerplate#767]
I noticed postcss was removed [here](https://github.com/chentsulin/electron-react-boilerplate/commit/481841784e6ded9f02f28012a30ef717d6b38808#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
I am having trouble bringing it back in and getting plugins to load properly.
Specifically I am trying to use https://github.com/react-toolbox/react-toolbox
which requires postcss-loader as well as the postcss-cssnext plugin.

Has anybody done this or something like it and can provide any insight? I can provide more details if anyone is interested. Thank you.

**Comment by psamim** [comment]
I am trying to do the same exact thing and had no luck. I asked about webpack 1 config file here: 

https://github.com/react-toolbox/react-toolbox/issues/1186#issuecomment-281103857

Would be happy to tell if you were successful.

**Comment by psamim** [comment]
There is a webpack 2 config file in https://github.com/react-toolbox/react-toolbox-example , but this boilerpate has not yet migrated to webpack2, discussion at https://github.com/chentsulin/electron-react-boilerplate/issues/660

**Comment by ballPointPenguin** [comment]
I got this working after a week of picking things apart and trial & error.
https://github.com/codex-digital/electron-react-boilerplate
let me know if you have questions or suggestions.

**Comment by ptilli** [comment]
@ballPointPenguin this doesn't seem to work with when used with the latest boilerplate with webpack 3 / node 7. Variables just won't get converted to static values. Any idea what might be the exact problem?

**Comment by ballPointPenguin** [comment]
unfortunately @ptilli I am no longer using this library and don't have anything meaningful to contribute to solving this problem right now.

**Comment by ptilli** [comment]
@ballPointPenguin no problem. Couldn't figure out the problem in a reasonable time, so I downgraded my boilerplate to your version. I'll manage with that, thanks for sharing it :)
