### ISSUE TITLE
Clone of master on 2017-02-22 is not working

### ISSUE THREAD

**Issue by walknwind** [chentsulin/electron-react-boilerplate#770]
Hi! Just cloned, did:

```
npm install
npm run hot-server
npm run start-hot   # separate tab, after above 'compiled successfully'
```

And I see a blank electron window with JS debug console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

node version is v7.4.0
npm version is 4.0.5

Might I be missing something?

**Comment by amilajack** [comment]
What OS are you on? Did you install with yarn or npm?
