### ISSUE TITLE
Passing data to React from Electron's open-url & open-file

### ISSUE THREAD

**Issue by dovinmu** [chentsulin/electron-react-boilerplate#771]
I'm trying to pass data from an Electron event handler for opening a file or URL (https://github.com/electron/electron/blob/master/docs/api/app.md#event-open-file-macos) into the React project. I'm handling the event in main.development.js, and need it to trigger a new view in React. Is there an accepted best practice for doing this?

**Comment by talha131** [comment]
Try this

1. Send data from `main.js` to renderer (your React App) using IPC. [ipcMain](http://electron.atom.io/docs/api/ipc-main/)
1. [ipcRenderer](http://electron.atom.io/docs/api/ipc-renderer/) will receive this data.
1. The ipcRenderer can then dispatch a redux action that updates the redux store.
1. The update in redux store is then passed down as a props new value.
1. On recieving the props, your React component can display a new view

**Comment by dovinmu** [comment]
Awesome, thanks. Didn't know about the IPCs.

**Comment by Ferigit** [comment]
hi @talha131 , would you please provide me with a link or small example of how can I update redux store with the data got from ipcmain of mani.js? I mean, I send data to react component but I can not handle how and where to dispatch a redux action to update the redux store.

**Comment by sediq-khan** [comment]
@dovinmu  Were you able to get the message from ipcMain in your react? Here is what I am stuck with. From ipcMain I am propagating an event...and in the react I would like to get that event and display a component depending on the event that came from ipcMain. Any idea? I understand @talha131 's pseudo code, but I could not write react/electron code for that.
