### ISSUE TITLE
How to use mainWindow in another file

### ISSUE THREAD

**Issue by LarsJansen-Ultraware** [chentsulin/electron-react-boilerplate#772]
Hello,

Maybe it's because I just started with the boilerplate in combination with react-desktop, but how can I change the mainWindow from within a component or container?

My goal is to maximize the window when the maximize button gets clicked.

Thanks in advance.

Kind regards,
Lars Jansen

**Comment by amilajack** [comment]
What do you mean by change? Can you please be more specific with your question. That way its easier for me to help you 😃

**Comment by LarsJansen-Ultraware** [comment]
Well, I would like to maximize and minimize the mainWindow with the controls on the Window component of react-desktop. So basically I would like to alter the mainWindow from within app/components/AppWindow.js.

This file exports the AppWindow class which extends Component.
```js
export default class AppWindow extends Component { ...
```

**Comment by Slapbox** [comment]
If I'm understanding correctly, you're looking for the ipcRender system in the main process. It can let you communicate between the Main and Render processes.

**Comment by amilajack** [comment]
@LarsJansen-Ultraware did you find a working solution?
