### ISSUE TITLE
stage-0 seems unstable. Move it down to stage-2?

### ISSUE THREAD

**Issue by AlexFrazer** [chentsulin/electron-react-boilerplate#773]

**Comment by amilajack** [comment]
Agreed. PR would be welcome!

**Comment by luigiplr** [comment]
I would argue that `stage-3` would be a safer bet.

In `stage-2` the semantics of a proposed feature may still change (e.g. decorators). Whereas in `stage-3` you can feel more secure knowing that the spec is complete & will be integrated in all browsers unless a critical issue comes up.

Further Reading:

- https://tc39.github.io/process-document/
- https://babeljs.io/docs/plugins/preset-stage-3/
- https://babeljs.io/docs/plugins/preset-stage-2/

**Comment by amilajack** [comment]
I agree with stage-3

**Comment by amilajack** [comment]
Closing as the PR for this is in progress
