### ISSUE TITLE
Add new build options to electron-builder

### ISSUE THREAD

**Issue by indapublic** [chentsulin/electron-react-boilerplate#777]
If I will change `target` from `nsis` to `portable` packaging will fault with exception:

> Using electron-builder.yml configuration file
> No native production dependencies
> Error: Unknown target: portable

`Portable` is correct target from [here](https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-target)

**Comment by jhen0409** [comment]
[It just a day ago in electron-builder](https://github.com/electron-userland/electron-builder/commit/6292855cc5e0210a617b0b0ae0ab73f3c1682315), we should upgrade it to `^14.4.0`.

**Comment by jhen0409** [comment]
@chentsulin, greenkeeper is disabled on this repo?

**Comment by amilajack** [comment]
I can PR for this. Not sure when but hopefully within a week or so. Migrated in a toy app that i was working on:

https://github.com/amilajack/contrast

Requires that we 
- [ ] Update the readme to reflect the new requirements of electron-builder
- [ ] Fix our config options which have been deprecated

**Comment by amilajack** [comment]
Fixed this
