### ISSUE TITLE
Error when use auth0-lock

### ISSUE THREAD

**Issue by 3ch3r46** [chentsulin/electron-react-boilerplate#778]
I have an error when i integrating with auth0.
the error appear below:

> WARNING in ./~/formidable/lib/incoming_form.js
> Critical dependencies:
> 1:43-50 require function is used in a way in which dependencies cannot be statically extracted
>  @ ./~/formidable/lib/incoming_form.js 1:43-50
> 
> WARNING in ./~/formidable/lib/file.js
> Critical dependencies:
> 1:43-50 require function is used in a way in which dependencies cannot be statically extracted
>  @ ./~/formidable/lib/file.js 1:43-50
> 
> WARNING in ./~/formidable/lib/json_parser.js
> Critical dependencies:
> 1:43-50 require function is used in a way in which dependencies cannot be statically extracted
>  @ ./~/formidable/lib/json_parser.js 1:43-50
> 
> WARNING in ./~/formidable/lib/querystring_parser.js
> Critical dependencies:
> 1:43-50 require function is used in a way in which dependencies cannot be statically extracted
>  @ ./~/formidable/lib/querystring_parser.js 1:43-50

What the solution for fixing this error?

**Comment by amilajack** [comment]
Those are warnings, not errors. The boilerplate should still work for you.

**Comment by 3ch3r46** [comment]
but in the electron console log, error appear with "Uncaught TypeError: require is not a function       incoming_form.js:3"

**Comment by amilajack** [comment]
Please log the entire stack trace here.

**Comment by 3ch3r46** [comment]
this is the log:

> incoming_form.js:3Uncaught TypeError: require is not a function(anonymous function) @ incoming_form.js:3__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ index.js:1__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ index.js:7__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ request-builder.js:2__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ index.js:3__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ index.js:1__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ web_api.js:5__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ core.js:13__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ index.js:5__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ AuthService.js:1__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ routes.js:4__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ index.js:6__webpack_require__ @ bootstrap 5a5f497…:555fn @ bootstrap 5a5f497…:86(anonymous function) @ bootstrap 5a5f497…:578__webpack_require__ @ bootstrap 5a5f497…:555(anonymous function) @ bootstrap 5a5f497…:578(anonymous function) @ bootstrap 5a5f497…:578
> client.js?207a:67[HMR] connected

and the error is in here:

> if (global.GENTLY) require = GENTLY.hijack(require);
> 
> var crypto = require('crypto');

**Comment by amilajack** [comment]
I would recommend looking into webpack and node-gently integration. This issue isnt with this project so i'm closing this but we should still continue the discussion
