### ISSUE TITLE
Dependencies in two package.json structure

### ISSUE THREAD

**Issue by ajbeaven** [chentsulin/electron-react-boilerplate#780]
This issue was originally posted [here](https://github.com/electron-userland/electron-builder/issues/1309).

At the end of [this (electron-builder) document](https://github.com/electron-userland/electron-builder/blob/master/docs/Two%20package.json%20Structure.md), it is stated:

> If you use the two-package.json project structure, you'll only have your devDependencies in your development package.json and your dependencies in your app package.json.

Looking through [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json), it seems that this advice isn't followed and the project `package.json` file includes a list of dependencies as well as devDependencies.

Judging by the @develar's response, I'm guessing this is understood to be a deviation from what is expected though I haven't come across any issues that could be attributed to this (yet). Sure enough, when I use the same approach as this project does, the node_modules folder inside app.asar is empty but the app correctly functions. Where are the dependencies stored if not here?

**Comment by jhen0409** [comment]
We are using webpack, so the dependencies can be ignored in `app/package.json` (they are bundled into a js file), unless it's a native module or for other reasons. We are still separated `dependencies` and `devDependencies` in `package.json` as a distinction between their use.

**Comment by ajbeaven** [comment]
Ahh, of course - that makes sense. Thanks for the explanation!
