### ISSUE TITLE
Will you plan to support typescript in the future

### ISSUE THREAD

**Issue by wangyueming** [chentsulin/electron-react-boilerplate#781]
I tried to set up typescript and failed. I am not good at webpack. Now I use tsc to compile typescript to js file manually. So will you plan to support typescript in the future?

**Comment by akozhemiakin** [comment]
For now this project uses Flow, which is kind of less intrusive alternative to typescript.
But I think that it should not be a problem to you to use https://github.com/s-panferov/awesome-typescript-loader to handle your ts files.

**Comment by amilajack** [comment]
@wangyueming did that solution work for you?

**Comment by wangyueming** [comment]
Thanks. I will use Flow.

**Comment by amilajack** [comment]
@wangyueming its not necessary. You should be able to use typescript with this project with relative ease. Did you try setting it up?

**Comment by wangyueming** [comment]
I set up typescript in webpack.config.base.js by adding lines below in loaders
```
    , {
      test: /\.tsx?$/,
      loaders: ['babel', 'ts-loader'],
      exclude: /node_modules/
    }

```
and changing line to below in resolve/extensions
`    extensions: ['', '.ts', '.tsx', '.js', '.jsx', '.json'],
`

It works with the drawback of live editing becomes slow and edited code is not replaced in chrome debug source view.

**Comment by amilajack** [comment]
I believe when we get happypack and DLL integration, this shouldn't be an issue for you anymore
