### ISSUE TITLE
[Question]: Best way to clean repository after initializing new project?

### ISSUE THREAD

**Issue by lightningboss** [chentsulin/electron-react-boilerplate#782]
I am very happy with electron-react-boilerplate, it's easy to use and in my opinion it's great to just run `npm run dev` and start working. Thank you very much!

Recently I was looking at my repo and looked at ~750 commits. I like to only have commits in my repo that actually are made by me or for this repo (basically to separate that). Therefore I was wondering what's the best way of getting rid of them?
The simplest solution would be to just delete `.git`. But this would mean giving up updates using a remote (if that's what you want).
Then I looked at the approach `create-react-app` was taking: Abstracting things away and updating itself as an npm-package. It basically get's out of the way concerning version control.
I think this is not what we want here, but having a mechanism that enables you to update `react-electron-boilerplate` would be very nice.

Are there any ideas concerning this and would this be something for the future?

**Comment by amilajack** [comment]
In my mind, migrating to a 'npm package' upgrade method will probably require a significant amount of refactoring. Not sure if we're going to be going in this direction anytime soon, but i definitely agree that it makes upgrading a lot simpler. Maybe this is something we can consider a while from now.

**Comment by talha131** [comment]
> Recently I was looking at my repo and looked at ~750 commits.

What if you do `git fetch --depth 1 git@github.com:chentsulin/electron-react-boilerplate.git`?

**Comment by lightningboss** [comment]
That could actually be something to put in the readme, right? Because right now it promotes cloning the full repository.

**Comment by amilajack** [comment]
Fixed this :)

**Comment by mariotacke** [comment]
Would absolutely love this as well. Have you given this any more thought since? Seems to be a lot of work but having create-react-app + this boilerplate would make for an amazing dev story.
