### ISSUE TITLE
Intellisense Errors in VS Code

### ISSUE THREAD

**Issue by Xetrics** [chentsulin/electron-react-boilerplate#784]
I get errors in files such as app/reducers/counter.js, as seen here:
![](http://pix.toile-libre.org/upload/original/1488412808.png)

These are fixed by renaming the files to .ts, but this breaks the application. Setting the file language also throws the errors.

**Comment by Xetrics** [comment]
temporary workaround 

`.vscode/settings.json`
```
{
    "javascript.validate.enable": false
}
```

**Comment by amilajack** [comment]
I made a PR to reflect these changes. Would be great if you could review it

https://github.com/chentsulin/electron-react-boilerplate/pull/789
