### ISSUE TITLE
React-bootstrap is not working

### ISSUE THREAD

**Issue by AvijitDutta95** [chentsulin/electron-react-boilerplate#787]
I am trying to make carousel for homepage after cleanup this project, but react-bootstrap is not working and i am unable to debug this problem and also make a navbar for my homepage using normal html and css its also not working.

**Comment by dustintownsend** [comment]
Check out this section on the readme https://github.com/chentsulin/electron-react-boilerplate#css-modules

**Comment by amilajack** [comment]
@AvijitDutta95 Did you resolve this? If you did, let's close this

**Comment by AvijitDutta95** [comment]
Yes, problem solved. Thanks for your help

**Comment by Aashir1** [comment]
> Yes, problem solved. Thanks for your help

want to use react-bootstrap how did you resolved it ?
