### ISSUE TITLE
How to pull upstream changes without screwing up yarn.lock completely?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#792]
Any advice on this? I haven't pulled since I started using Yarn because it causes complete disasters.

**Comment by amilajack** [comment]
I haven't found a solution to this. I just
```
rm yarn.lock
yarn
```
and hope everything works. There hasn't been a situation where that hasn't worked for me. But it seems like a hack. Don't know a better solution

**Comment by Slapbox** [comment]
Thanks @amilajack.

I'm not really clear on your workaround. Are you removing the `yarn.lock` you pull down and then reinstalling from your prior `yarn.lock`?

I think I'm misunderstanding because that would leave the `yarn.lock` with out of date packages, right?

**Comment by amilajack** [comment]
`yarn` will create a `yarn.lock` file if one does not exist. It will create it based on your current package.json

**Comment by Slapbox** [comment]
Got it. Thanks a lot! I'll give that a shot.

Seeing as I don't think there is a better solution right now, I think we can probably close the issue.
