### ISSUE TITLE
Question: Using Electron-Notifications package with Boilerplate

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#793]
I'm trying to use [the Electron-Notifications](https://github.com/blainesch/electron-notifications) package. This package  has it's own main process and when packaged for production it searches for the file within `app.asar`: `/assets/notification.html`

I have tried using the following to import it into the final packaged product:

  ```
  new HtmlWebpackPlugin({
      filename: '../assets/notification.html',
      template: 'node_modules/electron-notifications/lib/assets/notification.html',
      inject: false
```

I can't find any advice out there on how to use a node_module with its own main process. The module works perfectly in development, but I cannot figure out for my life how to package it. I have tried to get advice elsewhere before eventually writing this. If anyone has any insight into what changes would need to be made, I would really appreciate anything you can let me know.

Thank you very much.

**Comment by amilajack** [comment]
Is the source for this application viewable? It would be helpful if we can reproduce what you're experiencing.

**Comment by Slapbox** [comment]
Sure I can put together a repo to demonstrate the issue. I'll do it as soon as I can. Thanks very much @amilajack for your willingness to help me understand the nature of the issue.

**Comment by Slapbox** [comment]
I've put together a repo to demonstrate the issue. You can view the repo here: https://github.com/Slapbox/electron-notification-demo

You can download just the contents of https://github.com/Slapbox/electron-notification-demo/tree/master/release/win-unpacked and run ElectronReact.exe. The application will create a notification window on startup. Developer tools should be available for both the main application and for the `Electron-Notifications` window that is created.

The notification is generated in the Home.js file around line 9. It should last for an hour before closing.

If you need to generate another notification window you can do so with `notifier('reminders');` in the console.

Thanks very much for taking a look @amilajack.

**Comment by amilajack** [comment]
@Slapbox Sorry for the late response. I'll look into this either tmrw or over the weekend

**Comment by Slapbox** [comment]
Hey man don't be sorry. I appreciate you taking a look at all very much!

**Comment by Slapbox** [comment]
Figured it out in a sudden stroke of insight. I didn't realize/remember that there is a two package.json structure, and/or I didn't understand the relevance of this many months ago when I began.

Moving my dependency for `electron-notifications` to the `/app/package.json` resolved the issue entirely I believe.
