### ISSUE TITLE
how write a file in osx 

### ISSUE THREAD

**Issue by hl-a-k** [chentsulin/electron-react-boilerplate#794]
I would like write a file in osx,
but the code
`var fs = require('fs')`
`fs.writeFile('xxxxxx','hee')`

cause a `permission denied` error

**Comment by amilajack** [comment]
Try writing it to your desktop or some other place that you know you have permission to

**Comment by amilajack** [comment]
```js
const fs = require('fs')
fs.writeFileSync('/Users/foo/Desktop', 'foo')
```

**Comment by amilajack** [comment]
Closing this because it isnt a question about the boilerplate itself but lets continue the discussion

**Comment by hl-a-k** [comment]
Thanks amilajack,
I found I have permission by this way:
`let home = require('os').homedir()`
` storage: '${home}/Library/Account/account.db'`
