### ISSUE TITLE
Packaged app doesn't work with electron-log

### ISSUE THREAD

**Issue by johnryan** [chentsulin/electron-react-boilerplate#797]
I was trying to use https://github.com/megahertz/electron-log as recommended in the electron-boilerplate repo. However it seems like the required process.env variables aren't present in the packaged app (but they are when running npm run dev). 

The only flag that is present is `process.env.NODE_ENV` when accessing from the `main.development.js` file. Is this an expected behavior or is this a bug? I imagine I could write the values at startup but it seems like if they are already added in `development` it should also work in `production`. Thoughts?

**Comment by amilajack** [comment]
Where did you see the recommendation of https://github.com/megahertz/electron-log?

**Comment by johnryan** [comment]
@amilajack oh, i'm sorry that was a typo, it is recommended in the *electron-boilerplate* repo in the auto update section. However, it works when building https://github.com/iffy/electron-updater-example using standard electron-builder so I thought it must be affected by something with electron-boilerplate

**Comment by amilajack** [comment]
I believe ENV variables are stripped out by webpack at compile time. @dustintownsend can you confirm this?

**Comment by dustintownsend** [comment]
Yes Webpack will replace the `if (process.env.NODE_ENV==='development')` flags with `if (false)` and then everything in that block is removed as dead code.

Here are a couple things to look into (I haven't tried these so don't know if they work):
- https://github.com/babel/babili/tree/master/packages/babel-plugin-transform-inline-environment-variables
- https://github.com/babel/babili/tree/master/packages/babel-plugin-transform-node-env-inline

That second link, I think, would allow you to create a `package-dev` script that can transform the `if NODE_ENV is development` into `if (true)`, so it won't be removed by webpack.

For example:
Update the `.babelrc` to use this plugin then update the main package.json:
```
"build-main-dev": "cross-env NODE_ENV=development node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.electron.js --progress --profile --colors",
"build-renderer-dev": "cross-env NODE_ENV=development node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.production.js --progress --profile --colors",
"build": "npm run build-main-dev && npm run build-renderer-dev",
"package-dev": "npm run build-dev && build --publish never"
```
I didn't test any of that, but just to give you an idea of something to try.

**Comment by johnryan** [comment]
@dustintownsend Thanks for the info, the part I was more confused about was the ENV variables that aren't inline. For instance when accessing `process.env.HOME` in a debug build it is set to `/Users/johnryan/`. In production though it is undefined (same for a number of other ENV vars). 

I was just trying to figure out what is different between `npm run dev` and `npm run package` that causes all those other vars to be missing

**Comment by dustintownsend** [comment]
@johnryan I don't use any env vars outside of `process.env.NODE_ENV` and `process.platform`.

I'm not sure if it is Webpack pulling them out or maybe the environment is different after it is packaged up, so that is why it is undefined. 

With that being said I think it is best to avoid using env vars for things like getting the users home directory. In that case you should use the Electron API. 
```js
const { app } = 'electron';
const homeDir = app.getPath('home'); // will return user's home directory
```
See the [Electron Docs](https://electron.atom.io/docs/api/app/#appgetpathname) for more details on that.

**Comment by amilajack** [comment]
@johnryan Look through this discussion:

https://github.com/chentsulin/electron-react-boilerplate/issues/455

**Comment by johnryan** [comment]
@dustintownsend Totally agree, I think I will use the electron api's to make this work for my use case thanks. 

@amilajack Seems like WebPack is doing something with the packaged app to change the behavior (though still not sure specifically what is causing the env variables to be gone in the prod build). 

In any case thanks for the help, i'll take dustin's advice and update this ticket if I find any other relevant information.
