### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by na-ji** [chentsulin/electron-react-boilerplate#803]
Hello !

When I run the command `npm run test` I get this output: 
```
> electron-react-boilerplate@0.10.0 test /home/naji/www/electron-react-boilerplate
> cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 jest "(\\|/)test(\\|/)(?!.*e2e\.spec\.js).+\.spec\.js"

No tests found
  106 files checked.
  testPathDirs: /home/naji/www/electron-react-boilerplate - 106 matches
  testPathIgnorePatterns: /node_modules/ - 106 matches
  testRegex: (/__tests__/.*|(\.|/)(test|spec))\.jsx?$ - 5 matches
  testPathPattern: "(\|/)test(\|/)(?!.*e2e\.spec\.js).+\.spec\.js" - 0 matches
```
But when I replace the escaped double quotes `\"` with simple quotes in the command definition, I am able to run the tests.
I am currently developing on Linux Mint. But in appveyor (and probably windows), the simple quotes create errors. 
So should I have two commands, one with simple quotes for linux and one with double quotes for windows, or do you know a solution to this no tests found problem ?

Thanks !

**Comment by amilajack** [comment]
I believe this is related to https://github.com/chentsulin/electron-react-boilerplate/pull/774/. Will look into this. Thanks for reporting this!

**Comment by amilajack** [comment]
@na-ji Please try cloning this fork and confirming if this works for you:

```
git clone https://github.com/akozhemiakin/electron-react-boilerplate.git
cd electron-react-boilerplate
git checkout fix-tests
npm i
npm t
```

**Comment by na-ji** [comment]
Good idea to run Jest with node ! Now it is working like a charm :+1: 
Thank you for your help @amilajack!

**Comment by amilajack** [comment]
@na-ji thank @akozhemiakin for this 😄

**Comment by na-ji** [comment]
Ok so thanks @akozhemiakin ! :)
