### ISSUE TITLE
throw err while click inspect element

### ISSUE THREAD

**Issue by jasminecjc** [chentsulin/electron-react-boilerplate#805]
I can run npm run dev, and it's ok,no errors, but if i click inspect element ,it throw errors like below

![qq 20170313151133](https://cloud.githubusercontent.com/assets/13568376/23844805/66dcfb6c-07ff-11e7-9fd6-aa6eeef9995c.png)

I never made any changes in menu.js or in other files btw

**Comment by amilajack** [comment]
I cant seem to reproduce this error. Do you have the latest commit of the boilerplate? Try installing with yarn. If those dont work, try step 3 of #400

**Comment by jhen0409** [comment]
I think [this line](https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/menu.js#L38) got the wrong `this`, it should use arrow function, I'll fix it.
