### ISSUE TITLE
How to properly include bootstrap's css in electron app? 

### ISSUE THREAD

**Issue by ilmam** [chentsulin/electron-react-boilerplate#806]
I want to add twitter bootstrap's css. So I installed it like this:
`npm install bootstrap`

And included in the index.html like this:
`<link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">`

When I run: npm start from terminal it works fine. However when I try to build it using electron-packager like this:
`npm run build`

I get a native mac app "myApp.app", but when I open it, I don't see the styles.

The only files in the application aside from node_modules and package.json are: main.js and index.html and both are in the root dir.

Is there anything else I need to do to include the css properly?

**Comment by dustintownsend** [comment]
The boilerplate uses CSS Modules.
See https://github.com/chentsulin/electron-react-boilerplate#css-modules

**Comment by amilajack** [comment]
Also I believe what you want is `npm install bootstrap --save`.

**Comment by ilmam** [comment]
@amilajack yes it turned out that the problem was with --save option. Thanks, I', really beginner here and I was trying my heads first node/electron application.

**Comment by amilajack** [comment]
@ilmam No worries! Welcome to the Node and Electron ecosystem! Feel free to ask questions in the gitter chat. [I'm thinking of making a free video tutorial series](https://github.com/chentsulin/electron-react-boilerplate/issues/518) for this boilerplate. Its intended for people who have little to no experience with node but have experience with javascript/es6/7. I highly recommend going through [js-stack-from-scratch](https://github.com/verekia/js-stack-from-scratch). Every one of those technologies except for bootstrap is used in this project.

**Comment by ilmam** [comment]
@amilajack great idea! thanks for the support.

**Comment by Andrres017** [comment]
Hi, everyone.
I have a problem when calling jquery.js and boostrap.js I do not know if it has to be called any other way.
![image](https://user-images.githubusercontent.com/29790087/49409565-3042ae00-f72f-11e8-9d03-61228f5d45a4.png)
![image](https://user-images.githubusercontent.com/29790087/49409574-3c2e7000-f72f-11e8-90e5-e0e36b39db6e.png)

**Comment by MJB-Khorasani** [comment]
**try this: **

in the html file (index.html): do this 
` <script>window.$ = require('jquery')</script> `
 or do this imports in external js file.

i think that you need to work with somthing like webpack for advance & better experience.
