### ISSUE TITLE
serialport does not work in production.

### ISSUE THREAD

**Issue by wangyueming** [chentsulin/electron-react-boilerplate#807]
I require serialport in main process, it works in development environment. But it does not work after I package it with "npm run package" on mac.

I attach a picture here. Please look at it.

I checked the app.asar. The serialport.node really does not exist. Can Anybody help? Thanks in advance. 

[
<img width="418" alt="2017-03-13 10 27 34" src="https://cloud.githubusercontent.com/assets/10303419/23858703/494d41aa-083c-11e7-98e6-8fc180f832cd.png">
](url)

**Comment by amilajack** [comment]
Try using [node-loader](https://github.com/webpack-contrib/node-loader)

**Comment by wangyueming** [comment]
I installed node-loader and added lines below to webpack.config.base.js:
```
    }, {
      test: /\.node$/,
      use: 'node-loader'
    }]
   ...
    extensions: ['.js', '.jsx', '.json', '.node'],

```

In development environment:
If I import it in this way:
`import SerialPort from 'serialport.node';
`
There will be an error below:
```
App threw an error during load
Error: Cannot find module 'serialport.node'
    at Module._resolveFilename (module.js:455:15)

```

If I import it in this way:
`import SerialPort from '../../node_modules/serialport/build/Release/serialport.node';
`
There will be an error when I do "new SerialPort"
![2017-03-14 10 15 54](https://cloud.githubusercontent.com/assets/10303419/23904740/ebc6a6a2-0903-11e7-951e-3b6faa35277b.png)

In both cases after I package it with "npm run package" on mac and checked the app.asar, the serialport.node still does not exist, and the program can not start.

**Comment by dustintownsend** [comment]
Try to import like this... `import { SerialPort } from....`

**Comment by wangyueming** [comment]
If I use `import SerialPort from '../../node_modules/serialport/build/Release/serialport.node';`, I can do `SerialPort.list()`, I can not do `new SerialPort()`.

If I user `import { SerialPort } from '../../node_modules/serialport/build/Release/serialport.node';`, I even can not do `SerialPort.list()`, the error is shown below
![2017-03-15 10 16 17](https://cloud.githubusercontent.com/assets/10303419/23930672/c93eda68-0968-11e7-94f6-bb07afc49583.png)

**Comment by amilajack** [comment]
I believe the library you are using requires the `serialport.node` file so you dont have to do this in your own code. You should be able to do something like
```js
import serialPort from 'serialport`
```
and everything should just work. I dont know what the name of the package is by the way but I'm assuming that it is 'serialport'

**Comment by amilajack** [comment]
@wangyueming also seem my comments on a related issue: https://github.com/chentsulin/electron-react-boilerplate/issues/812#issuecomment-286641953

**Comment by wangyueming** [comment]
I succeeded by installing serialport in ${root}/app/node_modules rather than  ${root}/node_modules. And also see your comment to #812. Thanks.

**Comment by wangyueming** [comment]
And my questions are 
1. Need I to install the native module both to app/node_modules and node_modules? I succeeded by installing only to app/node_modules.
2. I found all the directories and files under app/node_modules will be packed in app.asar, are the required JavaScript files also bundled to app/dist/bundle.js? So they are duplicated in app.asar if yes, right?

**Comment by amilajack** [comment]
@wangyueming yes, both are correct. Also make sure to rebuild the `app/package.json`. Here's some examples:

https://github.com/amilajack/contrast/blob/master/app/package.json#L13
https://github.com/chentsulin/electron-react-boilerplate/issues/812#issuecomment-286658673

**Comment by Slapbox** [comment]
@amilajack node_modules packed within the `/app/` folder should also be installed to the top level `node_modules`? Is that correct?

**Comment by Slapbox** [comment]
Yes that is indeed correct. It works like magic.

**Comment by Madaovo** [comment]
I also got that problem,thanks
