### ISSUE TITLE
Migrate to react-router v4 and utilize code-splitting at the routing level

### ISSUE THREAD

**Issue by AlexFrazer** [chentsulin/electron-react-boilerplate#808]
Looks like react router 4 was officially released:
https://mobile.twitter.com/ReactJSTraining/status/840405844072124416

We can use the asynchronous component loading to manage code splitting.

I can handle this one if need be.

**Comment by dustintownsend** [comment]
@AlexFrazer looks like React-Router-Redux 5 is still in beta https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

Are there any other dependencies that might be impacted by this?

I think a PR for this would be great, so we can start testing it!

**Comment by Elyx0** [comment]
Putting that here as it might help for the boilerplate migration:
- `IndexRoute` is now gone: https://github.com/ReactTraining/react-router/issues/4732 looking at replacement either with `<Switch>` or `exact` prop for `path`

- `Router` should be imported as `BrowserRouter as Router` from `react-router-dom` : https://github.com/ReactTraining/react-router/issues/4477

- `listen` function will throw from `react-router-redux` as it now requires `createBrowserHistory` from `history` : https://github.com/reactjs/react-router-redux/issues/348 (They might add it back to the repo though)
