### ISSUE TITLE
PR/Docs: Typescript guide

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#809]
Although we don't support typescript, the types of this project should be 100% compatible with typescript. I think we should use flow as the default and at least provide the documentation for setting up the project with typescript.

Inspired by:
https://githubengineering.com/how-four-native-developers-wrote-an-electron-app/
https://slack.engineering/typescript-at-slack-a81307fa288d

**Comment by wangyueming** [comment]
I found a good tutorial to set up typescript.
http://blog.tomduncalf.com/posts/setting-up-typescript-and-react/

**Comment by fandy** [comment]
Any updates on the timeline of this? I've had a lot of issues type checking React props with Flow, but none with TS. It'd be great to have a fork of this or at least some docs on the README on how to do it.

**Comment by amilajack** [comment]
@fandy I haven't found a way to get TS working nicely with ESLint. Any suggestions?

**Comment by fandy** [comment]
Not sure - what issues are you running into?

/cc @chentsulin can you help us here? :)

**Comment by wilomgfx** [comment]
Id love that as well!

**Comment by wilomgfx** [comment]
@amilajack  just use TSLINT.

**Comment by amilajack** [comment]
@wilomgfx is there a way to integration with our current eslint rules?

**Comment by wilomgfx** [comment]
yes its the samething, but just use this https://www.npmjs.com/package/tslint-config-airbnb for the base airbnb rules.

**Comment by wilomgfx** [comment]
Did you figure out how to get typescript going with this ? I prefer typescript over flow :p

**Comment by amilajack** [comment]
I'll try this again later this week. I'll make a fork and post the link here when I finish

**Comment by amilajack** [comment]
Doing some work on that in [this repo](https://github.com/amilajack/erb-typescript-example)

**Comment by BafS** [comment]
Nice, thanks for your efforts ! Is it stable enough to switch from flow to typescript ?

**Comment by fandy** [comment]
Thanks @amilajack! Is that PR close to finished or are you blocked on anything?

**Comment by amilajack** [comment]
@fandy which PR are you referring to?

**Comment by BafS** [comment]
He was probably talking about the other repo.

**Comment by fandy** [comment]
@amilajack https://github.com/chentsulin/electron-react-boilerplate/issues/968 or https://github.com/amilajack/erb-typescript-example

**Comment by amilajack** [comment]
@fandy Did some work on the typescript example today. Check it out and let me know what you think.

**Comment by fandy** [comment]
I checked out `erb-typescript-example` and it looks good for the most part. Do we still need the `yarn ts` command if we're using Webpack? Awesome work!

**Comment by amilajack** [comment]
I actually couldn't get webpack to work with typescript. awesome-typescript-loader prevents webpack from starting if there are any type errors, which isn't ideal.

**Comment by ManuKle** [comment]
Is there still interest?
I just moved from flow to typescript, so I could create a fork and maybe type up some kind of migration guide if you want.

**Comment by RussGlover** [comment]
@ManuKle Do you have a sparknotes of what you did for the migration? I'm trying to move to typescript following https://github.com/amilajack/erb-typescript-example but am having some issues.

**Comment by amilajack** [comment]
@RussGlover what issues are you having?

**Comment by RussGlover** [comment]
I'm getting a runtime type error in one of my core dependencies. With the config in your example dependencies should run the same as in the flow setup correct?

**Comment by ManuKle** [comment]
In case anyone is still interested, I just added a working typescript repo based on the most recent release [here](https://github.com/ManuKle/electron-react-typescript-boilerplate).

**Comment by talha131** [comment]
@ManuKle That's awesome. 👍  I have added your repo to [Wiki-Notable Forks](https://github.com/chentsulin/electron-react-boilerplate/wiki/Notable-Forks). It would be so great if TS boilerplate stays up to date with the upstream.

**Comment by ManuKle** [comment]
I'll try my best 👍

**Comment by Almenon** [comment]
If anyone is interested in a example of a project using @ManuKle's boilerplate, I just switched [arepl-react](https://github.com/Almenon/AREPL-react) over to it.

**Comment by amilajack** [comment]
this is now possible because babel 7 was released and it now has typescript support 🎉

**Comment by muhajirframe** [comment]
woah,
How do we implement this @amilajack ?

**Comment by amilajack** [comment]
[Working on the repo here](https://github.com/amilajack/erb-typescript-example). It doesn't work yet. @vikr01 and I are working on this now

**Comment by talha131** [comment]
@amilajack Can we make an erb organization on Github and place all erb related repositories inside it? Like your TS repo or serial port sample example etc. This will make those repositories easier to find.
