### ISSUE TITLE
Error running npm run start-hot on Windows

### ISSUE THREAD

**Issue by dukedougal** [chentsulin/electron-react-boilerplate#81]
C:\Users\x\devel\electron-react-boilerplate> npm run start-hot

> electron-react-boilerplate@0.7.0-beta start-hot C:\Users\x\devel\electron-react-boilerplate
> HOT=1 NODE_ENV=development electron .

'HOT' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-hot"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.7.0-beta start-hot: `HOT=1 NODE_ENV=development electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.7.0-beta start-hot script 'HOT=1 NODE_ENV=development electron .'.
npm ERR! This is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     HOT=1 NODE_ENV=development electron .
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\x\devel\electron-react-boilerplate\npm-debug.log
PS C:\Users\x\devel\electron-react-boilerplate>

**Comment by guigmaster** [comment]
when run on Windows use set HOT=1 && set  NODE_ENV=development && electron .

**Comment by chentsulin** [comment]
You must use different env variable syntax as what @guigmaster mentioned or use a unix-like command line tool for Windows .

**Comment by dukedougal** [comment]
Is there a way for the script to be made cross platform?

**Comment by jhen0409** [comment]
Maybe we can use [better-npm-run](https://www.npmjs.com/package/better-npm-run) to solve this problem, it seems to be the easiest solution. @chentsulin you think?

**Comment by chentsulin** [comment]
It seems there isn' t a graceful solution here..

Maybe we can just implement a exec script:

http://stackoverflow.com/a/32993213/3012290
https://github.com/benoror/angular-formly/commit/b039b1b990ef137ab0b7242d3c31a2e96077a018

**Comment by iDuuck** [comment]
I think `better-npm-run` is working for this as solution. It uses the `spawn` method of `child_process` and there you can set the `env` option. Should work on Windows I think.

I will do a pull request and then someone need to check on windows (I am using a mac).

**Comment by chentsulin** [comment]
Close via #100
