### ISSUE TITLE
"require function is used in a way in which dependencies cannot be statically extracted"

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#832]
I'm not sure this is an issue on the boilerplate side, but I have seen a lot of posts on the web saying this is a webpack configuration issue.

The error I'm getting is `require function is used in a way in which dependencies cannot be statically extracted`

I get the error from [formidable](https://www.npmjs.com/package/formidable) which is relied on by Auth0.

Any ideas? It's reproducible in a fresh copy of the boilerplate.

**Comment by amilajack** [comment]
Try using the new dynamic requires with webpack:

https://github.com/airbnb/babel-plugin-dynamic-import-webpack
http://2ality.com/2017/01/import-operator.html

```js
import('some-module')
  .then(module => {
    module.foo()
  })
```

**Comment by Slapbox** [comment]
I managed to get it working with: `new webpack.DefinePlugin({ "global.GENTLY": false }),`

I have no idea the implications of doing this.

**Comment by amilajack** [comment]
Probably has to do with https://github.com/felixge/node-gently. I would recommend using dynamic imports tho

**Comment by Slapbox** [comment]
Could you clarify which module `'some-module'` would be in this context, and what `module.foo()` would be also?

Because I'm not directly running the dependency, formidable, I'm not sure how I would go about this.

**Comment by amilajack** [comment]
Look through the links in this comment: https://github.com/chentsulin/electron-react-boilerplate/issues/832#issuecomment-287568603. They explain what `import()` is and how to use it

**Comment by brandonmp** [comment]
@amilajack I understand your reluctance to look at this issue, but I think there's a problem here more unique to this boilerplate than you're thinking. I've been researching this for a few hours and could really use your input if you have a moment.

The problem OP is highlighting [is an issue in](https://github.com/felixge/node-formidable/issues/337) `node-formidable`. There's an expression in the top of one their files that reads:

```
if (global.GENTLY) require = GENTLY.hijack(require);
```

The standard fix is to set `GENTLY=false`, which avoids `require` being overwritten

In your boilerplate, however, some plugin or webpack setting is changing this line to this:

```
var require;if (global.GENTLY) require = GENTLY.hijack(require);
```

This overwrites global `require` & breaks the module, which is not something the end user can fix. 

If anything I think this is a bug in whatever is changing the expression, but I can't figure out what's doing it.

Do you have any ideas what might be declaring this var? 

I thought it was [class prop transform](https://babeljs.io/docs/plugins/transform-class-properties/), but it looks like class prop transform also happens in `stage-0` and maybe the `env` preset, so i'm not clear how to remove/isolate it w/o removing basically the entire babel config.

**Comment by Slapbox** [comment]
I can't speak to the accuracy of what @brandonmp posted, but I know that I ran into the problem trying to implement Auth0. I imagine Auth0 would get a lot of complaints about their package not working, but I don't see any reports of this problem there https://github.com/auth0/auth0.js

I also don't see the issue with this project demoing Auth0 in Electron: https://github.com/darkyen/pkce-demos

Again, I can't speak to the source of the problem. This is just some circumstantial evidence that suggests @brandonmp may be correct.

**Comment by brandonmp** [comment]
if anyone's having the same sorts of troubles @Slapbox  & i are describing w/ auth0, a quick-fix is to just require the minified script from the CDN in a <script> tag.

I prefer to have my dependencies bundled, but for now it's good enough

**Comment by AlexCatch** [comment]
I'm getting 'require is not a function' when trying to use auth0

**Comment by SevenSinS02** [comment]
@AlexCatch , @gazzer82.
You'd probably have to add an alias as well. I was getting the same error with superagent and the fix mentioned was to use an alias as well. Have a look at this comment. Something similar should work for auth0 as well.
[https://github.com/felixge/node-formidable/issues/337#issuecomment-264337905](url)

**Comment by patrykkrawczyk** [comment]
I've created a repository with node-auth0 already bundled for anyone to use in their own project to avoid any issues with formidable and similar errors.
https://github.com/patrykkrawczyk/node-auth0-bundle

Just get the `node-auth0-bundle.js` file from the `dist` directory, place it in your project and reference it with import/require statements as such:

```
import { ManagementClient } from './libs/node-auth0-bundle'
import { AuthenticationClient } from './libs/node-auth0-bundle'
```
