### ISSUE TITLE
Clean up script problems

### ISSUE THREAD

**Issue by Miyan0** [chentsulin/electron-react-boilerplate#837]
Thanks for the great work guys.

It looks like the cleanup script is broken...

Here's the steps I've done:

1. fork the  electron-react-boilerplate repo
2. clone my fork
3. yarn install
4. npm run dev

All works except I get a flow-runtime warning.

5. npm run cleanup
6. npm run dev

Now, 2 files are messed up by the cleanup script:

configureStore.development.js is truncated:
```

import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import { hashHistory } from 'react-router';
import { routerMiddleware, push } from 'react-router-redux';
import createLogger from 'redux-logger';
import rootReducer from '../reducers';




const actionCreators = {

  push,
};

const logger = createLogger({
  level: 'info',
  collapsed: true
});

const router = routerMiddleware(hashHistory);

// If Redux DevTools Extension is installed use it, otherwise use Redux compose
/* eslint-disable no-underscore-dangle */
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
```

and so is route.js:

```
// @flow
import React from 'react';
import { Route, IndexRoute } from 'react-router';
import App from './containers/App';
import HomePage from './containers/HomePage';


export default (
  <Route path="/" component={App}>
```

I'm on Windows 10 btw.

**Comment by Miyan0** [comment]
Not sure what's going on because I've done more tests (cloning and cleanup) and some files are still broken but it's not consistent. Sometimes Home.js gets truncated and not routes.js. Also files are not truncated at on the same line every time...

**Comment by amilajack** [comment]
Will remove cleanup script in the near future
