### ISSUE TITLE
Suggestions for injecting environment variables

### ISSUE THREAD

**Issue by johnryan** [chentsulin/electron-react-boilerplate#851]
I'm trying to get url variables injected using webpack like:

```
new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
      'process.env.BASE_URL': JSON.stringify('somesite.com')
})
```

then in some config.js
```
export const BASE_URL = process.env.BASE_URL
```

but when running the boilerplate in dev i see that these variables aren't set. 

Interestingly even modifying the NODE_ENV in `webpack.config.development` from 'development' -> 'something_else' has no effect on the `process.env.NODE_ENV`...it still stays as 'development'. 

Any idea where these process.env variables are coming from / why the DefinePlugin is having no effect?

**Comment by amilajack** [comment]
I couldn't reproduce this issue when using the latest version of the boilerplate.

Here's what I did:
1. Added the following to the `weback.config.development`
```js
'process.env.SOME': JSON.stringify('some')
```
2. Logged from `App.js`
```js
console.log(process.env.SOME);
```

**Comment by johnryan** [comment]
@amilajack interesting, it seems to work in App.js but not if you check in `main.development.js`. In there it's `undefined`

**Comment by amilajack** [comment]
I think `main.development.js` is compiled when `npm run build` is run. Try running `npm run build` first

**Comment by johnryan** [comment]
I think that is the issue, when using the hot start env variables can only be passed in via the `package.json`
