### ISSUE TITLE
Unable to run '$ npm run start-hot' on Centos7

### ISSUE THREAD

**Issue by jecsanders** [chentsulin/electron-react-boilerplate#852]
Hi All,

I am having an issue getting the Electron Boiler Plate working on my **64bit Centos7 distro**. I have this framework working perfectly on OS Sierra and Windows 10 and I love it. I am just trying to get **your demo counter working** available on git working for now.

On my Linux machine I was set my the environment with the following steps on a **clean reinstalled and fully up to date Centos7 operating system**:

**1) I installed both nodejs 7.7.4 and npm 4.1.2 (most recent available versions of each) successfully using curl and yum.
2) I installed git version 1.8.3.1 using yum. 
3) Next I executed the following two commands from the documentation. They both ran successfully
   i. $ git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git my-new-project-name
   ii. $ cd my-new-project-name && npm install 
4) Finally I ran npm run dev which failed with the following error**

**Also when I attempt to run it the alternative way shown in your documentation with the **'$ npm run hot-server'** and **'$ npm run start-hot'** run simultaneously, the  **'$ npm run hot-server'** command compiles perfectly fine. It is the  **'$ npm run start-hot'** command that generates an identical error.

Here is my **npm run dev** command (I tried it as Sudo as well) Output:

**===============================================================================**

> electron-react-boilerplate@0.10.0 dev /home/user/Desktop/AppDev/my-new-project-name
> cross-env START_HOT=1 npm run hot-server

> electron-react-boilerplate@0.10.0 hot-server /home/user/Desktop/AppDev/my-new-project-name
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config ./webpack.config.development.js

Project is running at http://localhost:3000/webpack-dev-server/
webpack output is served from http://localhost:3000/dist
Content not from webpack is served from /home/user/Desktop/AppDev/my-new-project-name/dist
404s will fallback to /index.html

> electron-react-boilerplate@0.10.0 start-hot /home/user/Desktop/AppDev/my-new-project-name
> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development

/home/user/Desktop/AppDev/my-new-project-name/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "start-hot"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-react-boilerplate@0.10.0 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.10.0 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Desktop/AppDev/my-new-project-name/npm-debug.log

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "hot-server"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 hot-server: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config ./webpack.config.development.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.10.0 hot-server script 'cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config ./webpack.config.development.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config ./webpack.config.development.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Desktop/AppDev/my-new-project-name/npm-debug.log

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "dev"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 dev: `cross-env START_HOT=1 npm run hot-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.10.0 dev script 'cross-env START_HOT=1 npm run hot-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env START_HOT=1 npm run hot-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Desktop/AppDev/my-new-project-name/npm-debug.log

**=============================================================================**

I appreciate any help I can receive. Thank you for taking the time to read this and let me know if this is an issue that can be fixed from my end, or if I need to wait for you guys to come up with a solution. 

I also attached the my-new-project-name/npm-debug.log file as requested in the error output.

Best Regards and Thanks Again.

jecsanders

[npm-debug-log.txt](https://github.com/chentsulin/electron-react-boilerplate/files/869782/npm-debug-log.txt)

**Comment by Slapbox** [comment]
If you copy the script out and run it directly rather than via NPM, does that work?

**Comment by jecsanders** [comment]
Yeah it does appear to be an issue with cross-env. I tried installing it with NPM and it is still now working.

**Comment by Slapbox** [comment]
You installed `cross-env` as a global with the `-g` flag, right?

And you're still getting the exact same error when you run `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development` directly?
