### ISSUE TITLE
Application bundle.js error after babel process

### ISSUE THREAD

**Issue by MatusSkerlik** [chentsulin/electron-react-boilerplate#861]
When i run project in "developing" mode everything works as it should.
`npm run dev`
But when i bundle code into Electron and run application, i am getting error in /app/dist/bundle.js
`npm run package`

Syntax error: Invalid regular expression: missing /

my repository  [rep]( https://github.com/MatusSkerlik/Prezior)
Compilation of source code is made by babel-pollyfill
OSX 10.12.3, node v6.9.2, npm 4.2.0

**Comment by amilajack** [comment]
Cant access your repo. It may be bc its private. What is the full stack trace? 3 of #400 and install with yarn.

**Comment by MatusSkerlik** [comment]
Sorry for that link, it works now.

**Comment by MatusSkerlik** [comment]
It is fixed. But thank you all. The problem was in BabiliPlugin from 'babili-webpack-plugin' in webpack configuration.

[https://github.com/babel/babel/issues/5564](https://github.com/babel/babel/issues/5564)
