### ISSUE TITLE
Provide Documentation for Removing Redux

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#862]
Providing a path for users who don't use redux is something I've been wanting to do for a while. Redux increases the barrier to using this boilerplate -- especially for those who are new to front-end or the react ecosystem. Also I'm sure there are many consumers of the boilerplate that  [may not even need redux](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367).

@jefffriesen Would be great if you could help out here. If I recall correctly, you stripped out redux and replaced it with mobx, correct?

**Inspiration:**
> Theres the Electron-react-boilerplate that in my opinion is not a boilerplate because the entire app is wrapped around redux (meaning if you don’t know redux or don’t want redux it’s actually sort of difficult to remove).

from the article [building-an-electron-app-with-react-auth0-hmr-sass](https://labs.redantler.com/building-an-electron-app-with-react-auth0-hmr-sass-a5dfed260763)

**Comment by Slapbox** [comment]
I love Redux, but was just wondering about this today.

**Comment by Slapbox** [comment]
Also want to mention, best boilerplate for Electron I have come across by far, even if it does have Redux wrapped in (which I appreciate about it)

Plus @amilajack, no one could be so helpful as you have been to myself and I'm sure many others. Thanks to the devs and maintainers.

**Comment by amilajack** [comment]
@Slapbox thanks for the kind words ❤️

**Comment by Helw150** [comment]
@amilajack Did this documentation ever happen? I'd love to pop redux out of the boilerplate.

I love a lot of the features, but am doing a very small project which definitely does not need redux and my fellow developers are just learning react now, so I don't want to throw redux on them now as well.

**Comment by amilajack** [comment]
> Did this documentation ever happen?

It didn't happen yet
