### ISSUE TITLE
Avoid silent failure when port 3000 is already in use

### ISSUE THREAD

**Issue by caillou** [chentsulin/electron-react-boilerplate#868]
Running `npm run dev` when port 3000 is in use by another process fails silently.

There is no information in the cli about a problem going on. The `BrowserWindow` opens and tries to fetch `http://localhost:3000/dist/bundle.js`. Im my case port 3000 return a `404`.

I took my quite a while to figure out what was going on.

Ideally `npm run dev` should fallback on another free port.

Having `npm run dev` fail with an error would be ok too.

**Comment by amilajack** [comment]
To avoid this, you can override the port:
```
PORT=1212 npm run dev
```

**Comment by caillou** [comment]
@amilajack thanks for the hint. I found that out myself.

This ticket is more about informing the developers about the problem, rather than a way to hot-fix it once the problem happened.

The thing is that it took me a bit over an hour to realise that `localhost:3000` was served from another server.

Here is what I would have expected is:

```
$ npm run dev

Error: listen EADDRINUSE :::3000
```

**Comment by amilajack** [comment]
I think changing the default port might be a solution to this
