### ISSUE TITLE
Docs: Add 'Features' Section to README

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#873]

**Comment by KamesCG** [comment]
Are you needing help with this task?

**Comment by amilajack** [comment]
@KamesCG yup! Would be great if you could PR for this. Ideally, it could resemble [react-boilerplate's features section](https://github.com/react-boilerplate/react-boilerplate#features)

**Comment by amilajack** [comment]
Would also be great if you could help out with https://github.com/chentsulin/electron-react-boilerplate/issues/919

**Comment by KamesCG** [comment]
I'll start with the features section this evening.

Working on Dashboard/Nightmare app this week, so I can start to work on #919 as I push changes to my personal repository.

**Comment by KamesCG** [comment]
I was thinking about doing a screencast/gif.

However, the current build has a depreciation warning. Should we fix any warnings before screencasts of the features?

```
(node:23552) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/babel-loader/lib/index.js:104:35)
    at LOADER_EXECUTION (/Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/kamescg/Documents/Projects/ElectronReact/code/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**Comment by amilajack** [comment]
I think it should be fine. Also you should see this discussion about the [video tutorial series](https://github.com/chentsulin/electron-react-boilerplate/issues/518)

**Comment by KamesCG** [comment]
Bueno - I'll go ahead and continue with the features section than.

Happy to assist with screencasts. Anything in particular? I can start with some of the basics.

**Comment by amilajack** [comment]
One thing I've been wanting to work on for a while is [a complementary website to the app](https://github.com/chentsulin/electron-react-boilerplate/issues/800). Unfortunately I'm short on time because maintaining this boilerplate and other projects takes a lot of time. @shahzeb1 is working on this as well. I have to work on an initial design so that contributors can get started. I can invite you to the site's repo if you're interested

**Comment by KamesCG** [comment]
Haha what did I get myself into... JK I think this is an awesome project :)

You are needing help with mockups? I do a lot of Photoshop UI design. I can help kickoff the initial layout if that's needed? I have pretty structured Photoshop mockups and try and match DOM and Component group, so easy to share and build upon.

![screen shot 2017-04-23 at 10 13 28 am](https://cloud.githubusercontent.com/assets/3408362/25315655/8884151a-280d-11e7-9253-799dc4a7b803.png)

**Comment by amilajack** [comment]
I've also worked with mockups before with sketch. I what will take the most time is probably implementing the front-end side of the site. [Here's the repo](https://github.com/amilajack/electron-react-boilerplate-site/) if you're interested. I just forked react-boilerplate, which I think is a really nice foundation for a scalable front-end

**Comment by KamesCG** [comment]
I really like the React Boilerplate site too.

Sure, add me and I can start contributing. I imagine we'll start by taking out all the references to React Boilerplate and "react-boilerplate"?

**Comment by KamesCG** [comment]
Started writing features this morning. Maybe some help editing and starting the last one "Performant - Route-Based Code Splitting"?

<dl>
  <dt>Faster Build Times: Webpack DLL</dt>
  <dd>
    Quickly test production code with lighting fast build times via Webpack DLL + Electron Packager. Tracking a bug in production? Enable production debugging, compile application 1-2 minutes (quick stretch) and get back to work.
  </dd>
  <dt>Hot Reloading: React Hot Loader 3</dt>
  <dd>
		Instantly add components, import modules and start developing applications 1,000,000's of nanoseconds faster. Electron React Boilerplate is a "Javascript Factory 🏭" for developers/designs serious about getting things done.
	</dd>
  <dt>Modern Tooling and Stack: ESlint, Flow, Jest, React, Redux</dt>
  <dd>
    Start writing code that matters and less time importing, configuring and reasoning about the lower depths of the Javascript. The Electron React Boilerplate has all modern the infrastructure in place, so whether day 1 or 3 months into the project our code always has your code's back.
  </dd>
  <dt>SCSS Styling</dt>
  <dd>
		Out-of-the-box support for CSS and SCSS imports for easy compartmentalization of UI. Plus, Webpack includes the compiled CSS directly into the exported bundle.js, minimizing run-time requests even further.
	</dd>
  <dt>Performant - Route-Based Code Splitting</dt>
	<dd></dd>
</dl>

**Comment by amilajack** [comment]
Love it! Also I forgot to mention that you should add asar to the 'Performant - Route-Based Code Splitting' section

**Comment by KamesCG** [comment]
Cool - I'll keep working on it, fix spelling errors, polish and submit the PR.

**Comment by amilajack** [comment]
@KamesCG Would love to help you merge in this PR. What's the status of it?

**Comment by KamesCG** [comment]
I'll finish the writing today and submit the PR.

**Comment by amilajack** [comment]
@KamesCG I can help out with this now. Have a lot of free time on my hands these days because its summer

**Comment by KamesCG** [comment]
@amilajack I'm literally finishing my first production Electron React Boilerplate application for a client today/weekened

I pulled a forked repo to my local computer and started making changes to the README. Need to finish polishing the content and submit the pull request.

It will happen shortly I promise.... That being said, we should totally reconnect and get a game plan for this summer. I still really want to contribute meaningful documentation the boilerplate. I've been playing with the latest version and even updated the project, so I could use the new react-router and others.

I noticed there was a request to document how to electron-redux too. I started implementing sagas can contribute too that conversation as well.

**Comment by amilajack** [comment]
@KamesCG Great! What's a good way to contact you?

**Comment by KamesCG** [comment]
@amilajack Email me at kamescg at [gmail.com]

**Comment by johanetox** [comment]
@KamesCG take a look at this rapo I'm making for my company liftit, sagas implemented and many other things, still work to finish but it is based on this scaffolding :)
