### ISSUE TITLE
Use of "const" in strict mode

### ISSUE THREAD

**Issue by awmartin** [chentsulin/electron-react-boilerplate#88]
This error occurs on a new install, after cloning the repo, running `npm install`, and running `npm run hot-server`.

server.js doesn't seem to be a true JavaScript file, regardless of the .js extension. In addition to the error below, there is a CoffeeScript-like closure using => and string interpolation using backticks. All of these prevent `npm run hot-server` from running. Is there a dependency not installed with `npm install`?

```
/Users/awmartin/Dropbox/Playground/electron-react-boilerplate/server.js:4
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

[npm-debug.log.txt](https://github.com/chentsulin/electron-react-boilerplate/files/52974/npm-debug.log.txt)

**Comment by chentsulin** [comment]
Which node version you are using? Now required node >=4.
https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L104

**Comment by awmartin** [comment]
That was it. Perhaps some documentation in the README or an error if the version doesn't match would help? Thanks.

**Comment by chentsulin** [comment]
Maybe  we can use https://github.com/facebook/fbjs/blob/master/scripts/node/check-dev-engines.js and postinstall to improve this https://github.com/facebook/react/blob/master/package.json#L53
