### ISSUE TITLE
PR: Better Migration Path

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#883]
Merging from the boilerplate seems hacky. We need a more elegant solution for this.

Solutions:
- [ ] Adding a `CHANGELOG`
- [ ] Push versioned releases consistently
- [ ] Create a 'Upgrade Guide' wiki (similar to that of [Laravel's](https://laravel.com/docs/5.4/upgrade))

**Comment by Slapbox** [comment]
This latest merge has been brutal for me.

The last time I merged can't have been more than 3 weeks ago. Assuming no bugs are introduced, it's basically a half day effort minimum even if the last time I merged was just a week earlier.

Currently I'm dead in the water from a bug though =( (#933)
