### ISSUE TITLE
.sass files not recognized for vendor DLL

### ISSUE THREAD

**Issue by ByronKos** [chentsulin/electron-react-boilerplate#891]
```
ERROR in ./~/bulma/bulma.sass
Module parse failed: ~\node_modules\bulma\bulma.sass Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
| /*! bulma.io v0.4.0 | MIT License | github.com/jgthms/bulma */
| @charset "utf-8"
|
| @import "sass/utilities/_all"
 @ dll vendor
```

Error occurs when running `npm run build-dll`.

For dependency:
```
"dependencies" :{
      "bulma": "^0.4.0",
}
```

**Comment by ByronKos** [comment]
Solution was to add it to:
` .filter(dependency => dependency !== 'font-awesome' && dependency !== 'bulma'),`

**Comment by amilajack** [comment]
Going to add a more elegant solution [to this](https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json#L167)

**Comment by amilajack** [comment]
Can you please test out https://github.com/chentsulin/electron-react-boilerplate/pull/894 to see if it resolves your issue? Thanks!

**Comment by ByronKos** [comment]
https://github.com/chentsulin/electron-react-boilerplate/pull/894/files#diff-b3ddea04db352cffeddf3b3d8cdf9737R23 fixes the problem, however a case for `.sass` files should be added inside of `webpack.config.renderer.dev.js`

```
{
        test: /^((?!\.global).)*\.sass/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]',
            }
          },
          {
            loader: 'sass-loader'
          }
        ]
      },

```

Bulma was removed from the filter:
`.filter(dependency => dependency !== 'font-awesome'),`

Commenting out .filter results in an error
```
ERROR in dll vendor
Module not found: Error: Can't resolve 'font-awesome' in '{project_root}'
 @ dll vendor
```

**Comment by amilajack** [comment]
This is expected. If you look at font-awesome's package.json, there isn't a main field. npm doesn't know what to import from there.

**Comment by ByronKos** [comment]
@amilajack To answer your question, the issue still persists with those changes when applied to my project.
You can check out [my project here](https://github.com/ByronKos/SE300-Journal). Adding a test case for `.sass` files  to  the module located at `webpack.config.renderer.dev.js` with the aforementioned code resolves the issue.
