### ISSUE TITLE
Pulling upstream leads to conflicts in every file in flow-typed folder

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#892]
Even if I remove flow-typed from my project prior to the pull, I get merge conflicts in every file. Any ideas?

**Comment by amilajack** [comment]
Lets merge this into https://github.com/chentsulin/electron-react-boilerplate/issues/883 to avoid duplication

**Comment by Slapbox** [comment]
I agree it is a subset, but I am not clear on if this would cause any issues? If I'm not using flow, can I delete those files without harm?

**Comment by amilajack** [comment]
@Slapbox you can. Just run `npm run flow-typed` or `yarn flow-typed`. Actually the flow types of this project are usually not that that up to date. I would recommend doing this after you clone the boilerplate. They annoying thing is that you'll see a bunch of diffs and will have to commit them. There's no way to ensure that everyone who clones the app has the same flow definitions so committing them is somewhat of requirement now.

**Comment by Slapbox** [comment]
Thanks as always for explaining @amilajack
