### ISSUE TITLE
Main process and webpack config

### ISSUE THREAD

**Issue by eric-burel** [chentsulin/electron-react-boilerplate#895]
Hi,

I have some trouble figuring out how Webpack and Babel are related to the main process.
The webpack config does not seem to be taken into account in the main process, so for example `ts-loader` won't work.

In the present case, webpack `resolve.modules` is ignored in the main process, so `import Foo from 'components/Foo' `works in all `app/` files apart from `menu.js` and `main.development.js`. 
This can lead to some small (but annoying) issues, for example I have been using a lot of utilities throughout my code, by I can't load them in the  `menu.js`.
Also Flow and eslint seem to have some issues with custom modules, they tend to trigger false 'module unresolved' alarms.

Did I misunderstood something about the expected behaviour of Webpack ? As I understand, I might not be an easy problem to solve, since Electron build its main using `babel`, and then only build the app with webpack. Am I right ?

**Comment by amilajack** [comment]
All the webpack configs use babel. They inherit from the base config. Both main and renderer processes use babel and webpack. 

You are right about webpack not being able to resolve anything outside of `menu.js`. This boilerplate wasn't initially designed to allow for leveraging the main process. This is about to change soon. For now, use the renderer for your app code

For the flow/eslint configuration issues, you will need to change the config files. Some quick googling should help you find the right config.

**Comment by eric-burel** [comment]
Thanks for this quick answer. And do you have any idea about how to fix this for the `menu.js` ? 
The quick fix is to rewrite all my imports, but I am seeking for really scalable solutions, even if they are complex.
I am working on a project where most of the goal is to actually structure and configurate the application, so I would rather avoid dirty fixes, even if it means more work.

**Comment by amilajack** [comment]
To give you a very good answer, I would need to mess around with the main process myself. I haven't done much of this yet. For now, using the renderer process should work fine.

**Comment by eric-burel** [comment]
Hi, actually I am on my way to solve this.

This is simply an inconsistency between prod and dev. In production, you wrote a `webpack.config.electron.js`.

The issue is that it is simply no development equivalent. However, there are a lot of use cases when webpack would be necessary in development too (module resolution, some special imports, and reuse of code common to the renderer and the main).

My workaround is as follow:

1. Create a  `webpack.config.electron.development.js` based on the existing one (I simply change the env to development instead of production). 
2. Modify the `npm run start-hot` script to build the `main.development.es5`using webpack file, then run it.

Scripts look like this:
```json
# a new script to build the main process entry in development mode
 "build-main-development": "cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.electron.development.js --progress --profile --colors",
# and we trigger this script on start-hot
"start-hot": "build-main-development && cross-env HOT=1 NODE_ENV=development electron ./app/main.development.es5",
```
And here is the webpack config `webpack.config.electron.development.js`, that is a very small tweak of the existing one (changes are commented):
```js

/**
 * Build config for electron 'Main Process' file
 */

import webpack from 'webpack';
import merge from 'webpack-merge';
import BabiliPlugin from 'babili-webpack-plugin';
import baseConfig from './webpack.config.base';

export default merge(baseConfig, {
  devtool: 'source-map',
  entry: ['babel-polyfill', './app/main.development'],
  output: {
    path: __dirname,
// HERE I changed the filename to avoid conflict
    filename: './app/main.development.es5.js'
  },

  plugins: [
    new BabiliPlugin(),
    new webpack.DefinePlugin({
// HERE I changed the env.
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ],
  target: 'electron-main',
  node: {
    __dirname: false,
    __filename: false
  },
});

```

**Comment by amilajack** [comment]
Merge in the current boilerplate. You're making references to an older version of the boilerplate which I am no longer familiar with.

**Comment by eric-burel** [comment]
Hi, I lack the time but yes, as soon as I have some free time I'll PR this.

To put it in a nutshell, in the last version you got a `webpack.config.main.prod.js`. We simply need a development equivalent so that our main process is always built using webpack, thus making both environments consistant.

**Comment by amilajack** [comment]
For now that is out of the scope of the boilerplate. Not sure how much I can help on this. Take a look at [this](https://github.com/chentsulin/electron-react-boilerplate/blob/hot-reload-main-process/webpack.config.main.dev.js).
