### ISSUE TITLE
initialState not working

### ISSUE THREAD

**Issue by iDuuck** [chentsulin/electron-react-boilerplate#90]
Hey,
I just googled me through the ES6 + React stuff. To set the `initialState` I just tried using the constructor of the Component like so:
```es6
constructor(props) {
    super(props);
    this.state = { focused: false };
  }
```
And also tried:
```es6
constructor(props) {
    super(props);
    this.setState({ focused: false });
  }
```

Even if I put a simple `console.log` into the `constructor` it is not working and the constructor isn't called. What's the matter with this?

**Comment by chentsulin** [comment]
First one should works:

```js
constructor(props) {
    super(props);
    this.state = { focused: false };
}
```

Maybe you stay on the different page or you edit the file after component mounted?

**Comment by iDuuck** [comment]
So, the page is the right one. But I am curious: I am `log`ing the `this.state` object before the return value in the `render` method. Right in front of the `render` method there is the `constructor`. But it is not working though.

**Comment by iDuuck** [comment]
Sorry: And if I am `log`ing the `this.state` object in the `constructor` it is not `log`ed in the console neither.

**Comment by iDuuck** [comment]
Wow, ok. That was quite easy.

A simple `CMD+R` helped me fix this.

**Comment by chentsulin** [comment]
Yes, You should refresh after component already be mounted. : )
