### ISSUE TITLE
.node file webpackMissingModule

### ISSUE THREAD

**Issue by hengkx** [chentsulin/electron-react-boilerplate#900]
Uncaught Error: Cannot find module "."
    at webpackMissingModule (windowsPtyAgent.js:5)
    at eval (windowsPtyAgent.js:5)
    at Object../node_modules/node-pty/lib/windowsPtyAgent.js (vendor.dll.js:8681)
    at __webpack_require__ (vendor.dll.js:21)
    at eval (windowsTerminal.js:14)
    at Object../node_modules/node-pty/lib/windowsTerminal.js (vendor.dll.js:8689)
    at __webpack_require__ (vendor.dll.js:21)
    at eval (index.js:6)
    at Object../node_modules/node-pty/lib/index.js (vendor.dll.js:8649)
    at __webpack_require__ (vendor.dll.js:21)

**Comment by hengkx** [comment]
webpack.config.base.js 
`export default {
  module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          cacheDirectory: true
        }
      }
    },
    {
      test: /\.node$/,
      use: 'node-loader'
    }]
  },

  output: {
    path: path.join(__dirname, 'app'),
    filename: 'bundle.js',
    // https://github.com/webpack/webpack/issues/1114
    libraryTarget: 'commonjs2'
  },

  /**
   * Determine the array of extensions that should be used to resolve modules.
   */
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.node'],
    modules: [
      path.join(__dirname, 'app'),
      'node_modules',
    ],
  },

  plugins: [
    new webpack.NamedModulesPlugin(),
  ],

  externals: Object.keys(externals || {})
};
`

**Comment by hengkx** [comment]
rebuild electron  resolve!

**Comment by amilajack** [comment]
What were the steps you took to resolve this?

**Comment by hengkx** [comment]
I use  [node-pty](https://github.com/Tyriar/node-pty) ,need [electron-rebuild](https://github.com/electron/electron-rebuild) recompiler

**Comment by amilajack** [comment]
How did you install node-pty? Globally or locally? Why was it required?

**Comment by hengkx** [comment]
locally install,I use node-pty node because I want to embed the terminal, multiply platform

**Comment by hengkx** [comment]
![image](https://cloud.githubusercontent.com/assets/8358236/24786850/1d90247e-1b97-11e7-8ca4-c25d08cfb675.png)

**Comment by Seanmclem** [comment]
How? How did you install node-pty? I get a webpack error on install

**Comment by uwemneku** [comment]
Thanks, guys these comments are really helpful.
If anyone else is having issues with node-pty after trying the suggestions here and like me, you hit the wall of ```Cannot read property 'spawn' of undefined';``` 

This issue was I was using
```js
   import pty as "node-pty"
```
this solved the issue for me
```js
   import * as pty as "node-pty"
```

Helpful link https://github.com/microsoft/node-pty/issues/531
