### ISSUE TITLE
Import image in main.development.js result in error

### ISSUE THREAD

**Issue by anthonyraymond** [chentsulin/electron-react-boilerplate#906]
For some reasons, adding

### how to reproduce
Add this line to `app/main.development.js`

```javascript
import icon from '../resources/icon.png';
```

Then start dev server `npm run dev`

### What happens
```text
Uncaught Exception:
SyntaxError: D:/Users/raymo/workspace/electron-react-boilerplate/resources/icon.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 | 
  3 | 
```

### Some infos
Windows 10
npm : 3.10.10 (i don't think this is related to node or npm version)
node: 6.9.4 (i don't think this is related to node or npm version)
electron-react-boilerplate: last version from `master` branch.

Adding `import icon from '../resources/icon.png';` to a component or wherever in the app does work as expected.

**Comment by amilajack** [comment]
Importing images into the main process isnt a very common practice. I would recommend trying to import it in the renderer process if that is possible. The webpack config for the main process is very different than that of the renderer process

**Comment by anthonyraymond** [comment]
@amilajack I don't really have another choice, i need the icon to create a `Tray`, with a `NativeImage`.
because i think i can't use `new Tray('../resources/icon.png')` it will work on dev but not when packaged :/

**Comment by amilajack** [comment]
[Try adding these lines](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.prod.js#L130-L134) to the `webpack.config.main.render.js` config

**Comment by anthonyraymond** [comment]
`webpack.config.main.render.js` does not exists in repository. did you mean `webpack.config.main.prod.js` ?

**Comment by amilajack** [comment]
Yea, my bad

**Comment by anthonyraymond** [comment]
Same error.

**Comment by amilajack** [comment]
You have to build the main process again with `npm run build-main`

**Comment by anthonyraymond** [comment]
Still the same error :/

**Comment by amilajack** [comment]
I don't have much time to look into this until this weekend. I would recommend looking into the renderer production webpack config and copying over webpack rules into the main production webpack config.

**Comment by anthonyraymond** [comment]
Ok, i'll try that. Thanks ;)

**Comment by Slapbox** [comment]
**webpack.config.base.js**

Add this to your   module: { rules: [ ] }

```
   { 
        test: /\.(?:ico|gif|png|jpg|jpeg|webp)$/, 
        use: 'url-loader' 
    }
```

**main.development.js**

Add anywhere: `const myIcon= \`${__dirname}\\includes\\myIcon.png\`;`

**Comment by anthonyraymond** [comment]
@Slapbox ok, this would do the trick to get the image path, but it won't work in packaged app.

**Comment by Slapbox** [comment]
Why not? I use it and it works. At least confirmed for a `.ico` file in Webpack 2 and for `.png` in Webpack 1. Should still work now though.

**Comment by Slapbox** [comment]
To use in a packaged app, I believe all you have to do is create the `includes` folder at the top level of your project, then add `"includes/"` to your `"files: [ ]"` array in your top level `package.json`

It's been a long time since I set this part up, so if it doesn't work, let me know and I'll dig deeper.

**Comment by anthonyraymond** [comment]
Ok...
After testing all possible config i found one which does work:

**/package.json**
Add `"includes/"` to `"files: []`.

**/app/includes** (notice the **app**, not at the top level)
Add `icon.png` to `app/includes/`

**/app/main.development.js**

    new Tray(`${__dirname}\\includes\\icon.png`);

<br />
<br />
And it works... but it makes no sense to me, it would have make sense if i added `"app/includes/` to `package.json`, but with it, it does not work.

If you do understand why it work that way i'll be interested to know why.

Thanks

**Comment by Slapbox** [comment]
Crap sorry. I see now `/includes` should always have been at the `app` level. Sorry for leading you astray there. I'm glad to see you got it working.

You're most welcome. I'm glad to be able to help someone else after @amilajack has spent what must be hours helping me out.

I'm interested to know, why import the images? What benefit does that method have if you get it working? What can you do that you can't do with the method outlined above?

**Comment by anthonyraymond** [comment]
No problem, your answer actually make me understand a lot of thing about the project architecture and webpack ^^.

To answer you about image imports, i'm mostly a `Java` guy, and it kind of *bother* me to include a depency this way, with no checking at *compile* time.
So if i decide to move or rename or even delete an image in few month i won't know that my app won't start, event if it does build.

**Comment by amilajack** [comment]
Just to confirm, was this resolved?

**Comment by Slapbox** [comment]
I definitely know a number of times I have built I have found I screwed something up like that even though it builds fine.

I think you could probably do something with environmental variables in the `webpack.configs` to cause it to exit the build process if the file is not found.  I'm not familiar with Java though and I'm speaking outside the range of my knowledge on Webpack now though, so I could be very wrong.

**Comment by anthonyraymond** [comment]
@amilajack kind of, Slapbox did provide a workaround, but `import icon from './whatever.png'` does not work.
