### ISSUE TITLE
Building for the web?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#912]
I was just wondering what major obstacles one would face in creating from this project, a version of their application for use in a traditional browser (assuming no use of Electron specific packages.)

The build target would need to be changed if I'm not mistaken, but I'm sure that's only the starting point. Are there other things that immediately come to mind?

I'm interested in pursuing this, but would like to get a high level idea of what would be involved before embarking on that.

**Comment by amilajack** [comment]
lets merge this into https://github.com/chentsulin/electron-react-boilerplate/issues/80

**Comment by Slapbox** [comment]
Ah whoops. Did try to find any possible duplicates, but there are quite a many issues now.

**Comment by amilajack** [comment]
No worries. The issue was actually closed before. That's most likely why you didn't find it.
