### ISSUE TITLE
PR: Folder structure refactor

### ISSUE THREAD

**Issue by ansumanshah** [chentsulin/electron-react-boilerplate#919]
Proposal for changes in folder structure (if possible)
1. Can we move all the webpack config files to one webpack folder?
2. Move all the flow, mocks, dll, and webpack folders under config
3. Move resources and img under assets

Would be happy to submit a PR

**Comment by amilajack** [comment]
the `flow-typed` directory was removed recently. I think the folder should be called `webpack` to be more explicit. Other than that, 👌 Would love a PR for this

**Comment by ansumanshah** [comment]
so I was suggesting a structure same as react-boilerplate with the `internals` folders they have, is that what you have in mind as well?

**Comment by ansumanshah** [comment]
Can we do away with the `img` folder as well please, It was confusing from me when I started

**Comment by ansumanshah** [comment]
I am also proposing to do away with the config files we have for stylelint, eslint and babel to either move them to `package.json`, webpack or create config files/folder for them in the internals folder.

P.S would love to work on the site we are planning as well, can we move both the repos to a separate org?

**Comment by amilajack** [comment]
> Can we do away with the img folder as well please, It was confusing from me when I started

Yup! I was actually thinking the same
