### ISSUE TITLE
Add localization to boilerplate

### ISSUE THREAD

**Issue by terhuerne** [chentsulin/electron-react-boilerplate#925]
I think in most common cases at a point in your project you want to be able to roll out your application for multiple languages. With i18next we have a standard and also a react connector to do so. It would be great to have it build right into the boilerplate.

**Comment by amilajack** [comment]
Would love a PR for this :smile

**Comment by terhuerne** [comment]
I'll see what I can do. ;)

**Comment by offaxis** [comment]
Hi,

I integrate react-intl in my app ! Maybe i can help !
