### ISSUE TITLE
Error while running npm run test with sqlite3 package

### ISSUE THREAD

**Issue by othke** [chentsulin/electron-react-boilerplate#926]
Hi, 
I am running with an issue with `npm run test` and a package installed in app/node_modules.
I am using sqlite3 in my app and this module is listed in the app/package.json
[app/package.json](https://gist.github.com/othke/b7d0b22395a726082edbdb762e3e9389)

I add this module in the second package.json as recommended.
[2 package.json](https://github.com/chentsulin/electron-react-boilerplate#module-structure)
For this module works I need to rebuild it with  `npm run postinstall`

For simple test, I create app/db.js
[app/db.js](https://gist.github.com/othke/2ed16a73ea677a93f91000849d29b7c5)

I Call this function in app/main.development.js
[app/main.development.js](https://gist.github.com/othke/553308120fa4cf819d7e5784f5b55456)
When I run `npm run dev` a sqlite file is created in the TEMP directory.

**Now I would like to run a test.**
I wrote a simple test in test.
[test/db.spec.js](https://gist.github.com/othke/46eb168462b18020795115525455382a)

When I run `npm run test` I get this Error
>  FAIL  test\db.spec.js
  ● Test suite failed to run

    Cannot find module '../package' from 'node-pre-gyp.js'

      at Resolver.resolveModule (node_modules\jest-resolve\build\index.js:169:17)
      at Object.<anonymous> (app\node_modules\sqlite3\node_modules\node-pre-gyp\lib\node-pre-gyp.js:60:17)

I understand that the node version running the test is not the same as the node version running electron. Am I wrong ?
Is there a way to workaround this issue ?

Thanks

**Comment by amilajack** [comment]
Using the renderer process to load expensive code isn't a good idea in general. You'd generally want to do this in the renderer process. I would recommend moving your import statements outside of the `main.development.js` module

**Comment by amilajack** [comment]
See [this example](https://github.com/amilajack/erb-sqlite-example).

**Comment by othke** [comment]
Hi @amilajack,
I am not sure this is my issue. I just tried to say that electron need to rebuild the sqlite3 package to works with `npm run dev`. But if the package are build for electron then the `npm run test` does not work because `test` use node.js and not electron.

**Comment by amilajack** [comment]
I see. Can you fork my example repo and show me exactly what you mean by editing your fork? An example would really help

**Comment by y1feng200156** [comment]
step1:
`cd app\node_modules\sqlite3\`

setp2:
`npm update`

**Comment by othke** [comment]
Hi @amilajack ,
I fork your [repo](https://github.com/othke/erb-sqlite-example) and reproduce the issue.
I put the db operation into a function and add a simple unit test. The issue append when running the test.

`yarn test`

>  FAIL  test/db/db.spec.js
  ● Test suite failed to run

    Cannot find module '../package' from 'node-pre-gyp.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js:60:17)

**Comment by amilajack** [comment]
Great! Thanks for this. I'll look into this over.

**Comment by amilajack** [comment]
I looked into this issue and it seems to be an issue with `jest-resolve`. It seems like jest tries to resolve the `../package` path:

```js
inherits(Run, EE);
exports.Run = Run;
var proto = Run.prototype;

/**
 * Export the contents of the package.json.
 */

proto.package = require('../package');
```

**Comment by phra** [comment]
@amilajack i have this problem with a fresh install of latest jest and ts-jest in a not-electron env. 😕

**Comment by amilajack** [comment]
@phra what is the version of `node-pre-gyp` that you have?

**Comment by amilajack** [comment]
Closing because i dont think this is issue is related to the boilerplate. Let me know if you think this should be reopened

**Comment by Nauss** [comment]
I tried the example and after fixing the ```require('../package.json')``` I get this error:
```
Cannot find module '[...]electron-react-boilerplate\app\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node' from 'sqlite3.js'
```
I came here because I get the exact same problem with my own nodejs addon.
In both cases the *.node file exists and the path in the error is correct.
What's wrong here ?

**Comment by Nauss** [comment]
This [feature](https://github.com/facebook/jest/issues/3698) if ever added, would probably solve the problem.
