### ISSUE TITLE
PR: Add prettier support/integration

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#927]

**Comment by amilajack** [comment]
Closing this because prettier and eslint integration and consistency is off

**Comment by loopmode** [comment]
@amilajack Actually, today it seems to be working together nicely once ESLint is configured accordingly.

This is all to make it work: https://github.com/loopmode/electron-react-boilerplate/commit/72bfdec6d1f4e360849cc6df4c3382da29638c7c

This is the result after `npm run lint-fix`: https://github.com/loopmode/electron-react-boilerplate/commit/78e38c02f43faecec35454090dee2d32d038a8fb (80 chars/row)

However, I guess when using prettier, one should clean up the ESLint setup, e.g. drop `eslint-formatter-pretty`. I've no idea whether currently, double work is done as in maybe first `eslint-formatter-pretty` does its thing, then comes `prettier` and does its thing, making the first step obsolete...?
