### ISSUE TITLE
Load firebase script

### ISSUE THREAD

**Issue by erick2014** [chentsulin/electron-react-boilerplate#930]
Hi guys thanks for this awesome startert kit, I've using it for a couple of weeks, and works pretty well. I was wondering how can I load firebase script?

*Right now what I am doing is this:

At app.html, I Added the following code
http://prntscr.com/eyhaft

But Sometimes I'm getting this error, and I got a blank page
http://prntscr.com/eyha0z

*I also tried editing index.js file and included this line:

`import firebase from 'firebaseLibrary/firebaseLibrary';`

which is the library downloaded from the cdn

But I got this error: 
http://prntscr.com/eyhuwd

I'm not sure if loading the script in this way is breaking my compiler, thx in advance

**Comment by amilajack** [comment]
Please upload screenshots using GitHub's markdown. It supports drag/drop functionality. Makes reviewing this easier

**Comment by erick2014** [comment]
Well at the end I've decided to install firebase from npm, and looks like working, but I'm having trouble with the compiler

**Comment by amilajack** [comment]
Please open a new issue for this. That makes it easier for me to keep track of issues
