### ISSUE TITLE
In Packaged Application: Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#935]
```
Uncaught (in promise) TypeError: Cannot read property 'dispatch' of undefined
    at ConnectedRouter._this.handleLocationChange (ConnectedRouter.js:26)
    at ConnectedRouter.componentWillMount (ConnectedRouter.js:41)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:351)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:371)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:371)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)

```
```

ConnectedRouter._this.handleLocationChange	@	ConnectedRouter.js:26
componentWillMount	@	ConnectedRouter.js:41
performInitialMount	@	ReactCompositeComponent.js:351
mountComponent	@	ReactCompositeComponent.js:258
mountComponent	@	ReactReconciler.js:46
performInitialMount	@	ReactCompositeComponent.js:371
mountComponent	@	ReactCompositeComponent.js:258
mountComponent	@	ReactReconciler.js:46
performInitialMount	@	ReactCompositeComponent.js:371
mountComponent	@	ReactCompositeComponent.js:258
mountComponent	@	ReactReconciler.js:46
performInitialMount	@	ReactCompositeComponent.js:371
mountComponent	@	ReactCompositeComponent.js:258
mountComponent	@	ReactReconciler.js:46
performInitialMount	@	ReactCompositeComponent.js:371
mountComponent	@	ReactCompositeComponent.js:258
mountComponent	@	ReactReconciler.js:46
mountComponentIntoNode	@	ReactMount.js:104
perform	@	Transaction.js:140
batchedMountComponentIntoNode	@	ReactMount.js:126
perform	@	Transaction.js:140
batchedUpdates	@	ReactDefaultBatchingStrategy.js:62
batchedUpdates	@	ReactUpdates.js:97
_renderNewRootComponent	@	ReactMount.js:320
_renderSubtreeIntoContainer	@	ReactMount.js:401
render	@	ReactMount.js:422
createStoreFunction	@	index.js:28
module.exports../app/index.js.getStoredState.then	@	index.js:239
```

![image](https://cloud.githubusercontent.com/assets/6835891/25288304/e705e11c-2692-11e7-9fe1-3e31cc38da2f.png)

**Comment by amilajack** [comment]
What is the source code that is making the call to `this.store.dispatch` (if you can disclose this)? That will make debugging a lot easier. Also we bumped [`react-router-redux` and other dependencies](https://github.com/chentsulin/electron-react-boilerplate/commit/6941f419719138a53d7c1d6ded349adb308a63f9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R194). May have something to do with this.

**Comment by Slapbox** [comment]
I upgraded all of my packages to those used in the current version of the boilerplate. Below is my `index.js`. Let me know if there are any other files you need to see and I'll share whatever I can.

**Index.js**
```
import _ from 'lodash';
// @flow
import React from 'react';
import { Provider } from 'react-redux';
import { render } from 'react-dom';
import storage from 'electron-json-storage';
import { AppContainer } from 'react-hot-loader';
import Root from './containers/Root';
import { configureStore, history } from './store/configureStore';
import './app.global.css';


let myState;
let stateKeyPresent;
let store;

function createStoreFunction() {
	store = configureStore(myState);
	render(
	  <AppContainer>
	    <Root store={store} history={history} />
	  </AppContainer>,
	  document.getElementById('root')
	);

	if (module.hot) {
	  module.hot.accept('./containers/Root', () => {
	    const NextRoot = require('./containers/Root'); // eslint-disable-line global-require
	    render(
	      <AppContainer>
	        <NextRoot store={store} history={history} />
	      </AppContainer>,
	      document.getElementById('root')
	    );
	  });
	}
}


storage.keys((err, keys) => {
	if (err) throw err;

	for (let i = 0; i < keys.length; i++) {
		if (keys[i] === 'state') {
			stateKeyPresent = keys[i];
		}
	};
});

let getStoredState = new Promise(function(resolve,reject) {
	storage.get('state', (err, data) => {
		if (!stateKeyPresent) {
			myState = {};
			resolve();
		} else if (data) {
			myState = JSON.parse(data);
			resolve();
		} else {
			myState = {};
			resolve();
		}
	});
});

getStoredState.then(() => {
	createStoreFunction();
});
```

**Comment by Slapbox** [comment]
Any thoughts on this one? I forgot all about this error until I just went to package thinking I had finally worked out all my issues.

**Comment by Slapbox** [comment]
Whoops definitely didn't mean to close this one. It's plaguing me.

I tried building the vanilla boilerplate and inspecting what values `_this.store.dispatch` has at runtime there, but it will not display a value on mouseover, so I'm not sure what it should be, only that mine is undefined.

**Comment by anthonyraymond** [comment]
This is more a question than an answer.

As far a i understand you are saving and restoring the `state` of your application. But don't populating the `state.router` in this way breaks the system?
I means, you are inserting value for the router in the initialState of the application, is it supposed to work?

What happens if you remove the `router` key from the state?

**Comment by Slapbox** [comment]
I'm not sure the answers to these questions unfortunately. I know it worked in 0.11.0 and doesn't in 0.11.1.

I'll report back later today when I can poke around some more.

**Comment by Slapbox** [comment]
Okay until looking at my code I wasn't 100% following the later part of your comment.

The `initialState` in my case is not loading a routing state, only an array of objects used in the application and some options. The rest of the portions of my state are discarded when exiting, and then created anew when restarting the application.

**Comment by Slapbox** [comment]
So upon further examination, it looks like this is #850 rearing it's ugly head again!

This was somehow resolved for me in 0.11.0, but reintroduced in 0.11.1. I have reviewed all the changes and cannot fathom why this could be the case.

**Comment by Slapbox** [comment]
Specifically, history is defined in `root.js`, but `store` is not now.

**Comment by Slapbox** [comment]
The most "elegant" fix for this is to define `store` in your `index.js` instead as `global.store`, and to reference it the same way in your `root.js`

Alternatively see #850 for a solution not using global variables.

@amilajack if you have any idea why this occurs, I'd be interested figure out, but I'm going to close it now as there are now 2 workarounds available to anyone else facing this.
