### ISSUE TITLE
npm run flow-typed fails on npm install

### ISSUE THREAD

**Issue by JohnBain** [chentsulin/electron-react-boilerplate#936]
Don't know what this means, but it happened when I tried npm install. I'm running OSX El Capitan. My Node and NPM are up-to-date.

`[1] WARNING in ./~/ajv/lib/async.js
[1] 96:20-33 Critical dependency: the request of a dependency is an expression
[1] 
[1] WARNING in ./~/ajv/lib/async.js
[1] 119:15-28 Critical dependency: the request of a dependency is an expression
[1] 
[1] WARNING in ./~/ajv/lib/compile/index.js
[1] 13:21-34 Critical dependency: the request of a dependency is an expression
[0]   • babel-plugin-flow-runtime@^0.10.0
[0]     └> flow-typed/npm/babel-plugin-flow-runtime_vx.x.x.js
[0]   • node-sass@^4.5.2
[0]     └> flow-typed/npm/node-sass_vx.x.x.js
[0]   • electron@^1.6.5
[0]     └> flow-typed/npm/electron_vx.x.x.js
[0] 
[0] !! No flow@v0.44.2-compatible libdefs found in flow-typed for the above untyped dependencies !!
[0] 
[0] I've generated `any`-typed stubs for these packages, but consider submitting 
[0] libdefs for them to https://github.com/flowtype/flow-typed/
[0] 
[1] npm run build-dll exited with code 0
[0] npm
[0]  ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! electron-react-boilerplate@0.11.0 flow-typed: `flow-typed install --overwrite`
[0] npm ERR!
[0]  Exit status 1
`

`
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run flow-typed" "npm run build-dll" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
`

**Comment by amilajack** [comment]
Does it work if you `rm -rf flow-typed` first?

**Comment by Slapbox** [comment]
It does (at least for me), but it seems like in this version it is trying to rebuild the contents of the flow-typed folder when I add new packages, and fails unless I manually remove it again. I am not 100% sure about this yet.

**Comment by MarkDavidGoddard** [comment]
Running into this issue too.   Reseting to this commit seems to eliminate the issue.  https://github.com/chentsulin/electron-react-boilerplate/commit/2b0f7606bb06397e87078bb4f00c357efc778e65

**Comment by amilajack** [comment]
@JohnBain @MarkDavidGoddard would be great if you could test out [this PR](https://github.com/chentsulin/electron-react-boilerplate/pull/940) with npm to see if this was resolved

**Comment by MarkDavidGoddard** [comment]
Still failing for me.  I get the following error if I run 'npm run flow-typed':

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'flow-typed' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'preflow-typed', 'flow-typed', 'postflow-typed' ]
5 info lifecycle electron-react-boilerplate@0.11.0~preflow-typed: electron-react-boilerplate@0.11.0
6 silly lifecycle electron-react-boilerplate@0.11.0~preflow-typed: no script for preflow-typed, continuing
7 info lifecycle electron-react-boilerplate@0.11.0~flow-typed: electron-react-boilerplate@0.11.0
8 verbose lifecycle electron-react-boilerplate@0.11.0~flow-typed: unsafe-perm in lifecycle true
9 verbose lifecycle electron-react-boilerplate@0.11.0~flow-typed: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mark/electron-react-test/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/mark/go/bin
10 verbose lifecycle electron-react-boilerplate@0.11.0~flow-typed: CWD: /Users/mark/electron-react-test
11 silly lifecycle electron-react-boilerplate@0.11.0~flow-typed: Args: [ '-c', 'rm -rf flow-typed && flow-typed install --overwrite' ]
12 silly lifecycle electron-react-boilerplate@0.11.0~flow-typed: Returned: code: 1  signal: null
13 info lifecycle electron-react-boilerplate@0.11.0~flow-typed: Failed to exec flow-typed script
14 verbose stack Error: electron-react-boilerplate@0.11.0 flow-typed: `rm -rf flow-typed && flow-typed install --overwrite`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-react-boilerplate@0.11.0
16 verbose cwd /Users/mark/electron-react-test
17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "flow-typed"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error electron-react-boilerplate@0.11.0 flow-typed: `rm -rf flow-typed && flow-typed install --overwrite`
23 error Exit status 1
24 error Failed at the electron-react-boilerplate@0.11.0 flow-typed script 'rm -rf flow-typed && flow-typed install --overwrite'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the electron-react-boilerplate package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     rm -rf flow-typed && flow-typed install --overwrite
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs electron-react-boilerplate
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls electron-react-boilerplate
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by MarkDavidGoddard** [comment]
If I install flow-typed globally, then the `flow-typed install --overwrite` works fine, but the `npm run flow-typed` still fails.

**Comment by MarkDavidGoddard** [comment]
This seems to be the root cause of this issue: https://github.com/flowtype/flow-typed/issues/795.  If you add add `|| true` to the command, it will fix it. `"flow-typed": "rm -rf flow-typed && flow-typed install --overwrite || true",`

**Comment by amilajack** [comment]
Fixed this in dev-master
