### ISSUE TITLE
Error calling Sqlite3. Wrong package.json path in node_module sqlite3

### ISSUE THREAD

**Issue by rahmatkruniawan** [chentsulin/electron-react-boilerplate#937]
I just install sqlite3 via npm when i call 

> var sqlite3 = require('sqlite3').verbose();

and got this error below.

> `Uncaught Error: package.json does not exist at D:\package.json
>     at Object.exports.find (pre-binding.js:17)
>     at Object.eval (sqlite3.js:3)
>     at eval (sqlite3.js:190)
>     at Object../node_modules/sqlite3/lib/sqlite3.js (vendor.dll.js:7300)
>     at __webpack_require__ (vendor.dll.js:21)
>     at Object.26 (sqlite3.js from dll-reference vendor:1)
>     at __webpack_require__ (bootstrap 92c9347…:657)
>     at fn (bootstrap 92c9347…:85)
>     at Object../app/components/Home.js (Home.js:5)
>     at __webpack_require__ (bootstrap 92c9347…:657)

in file sqlite3.js under node_modules directory. They execute this

> var binding_path = binary.find(path.resolve(__dirname,'./../package.json'));

**Comment by amilajack** [comment]
Try checking out [this commit](https://github.com/chentsulin/electron-react-boilerplate/commit/2b0f7606bb06397e87078bb4f00c357efc778e65). Native deps were broken in a recent release:

**Comment by amilajack** [comment]
Lets merge this into https://github.com/chentsulin/electron-react-boilerplate/issues/933

**Comment by devgeektech** [comment]
what's the solution for this?

**Comment by rahmatkruniawan** [comment]
@devgeektech  use yarn + http://cmder.net/ (if u on windows )

**Comment by devgeektech** [comment]
Thanks for reply @rahmatkruniawan but i am using linux
getting following error while installing sqlite3 module in my app  
pre-binding.js:17 Uncaught Error: package.json does not exist at /package.json

**Comment by rahmatkruniawan** [comment]
@devk] maybe u can share your error message

**Comment by devgeektech** [comment]
That's what it is binding error while webpack building the code from node module sqlite3
"pre-binding.js:17 Uncaught Error: package.json does not exist at /package.json"

**Comment by rahmatkruniawan** [comment]
@devgeektech 
Is this the first time you run boileplate ? 
If no , just clone this repo agan and run it. See the different
