### ISSUE TITLE
Add local eslint to package.json

### ISSUE THREAD

**Issue by iDuuck** [chentsulin/electron-react-boilerplate#94]
Every time I start a new project with this boilerplate I am getting the error in Atom, that I have no local `eslint` installed.

How about adding this as local dependency?

**Comment by chentsulin** [comment]
We already have a local dev eslint installed: https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L61

**Comment by iDuuck** [comment]
Sorry, my fault. I just had not installed the dependencies from `package.json`. Now it works.
