### ISSUE TITLE
Rename 'main.development.js'

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#942]
The module `main.development.js` has a misleading name because its filename suggests that it is used in development while it is actually used in production as well. Maybe renaming this to `main.js` and building `main.dev.js` and `main.prod.js` modules from it would make more sense

**Comment by KamesCG** [comment]
I think that makes sense - I'm literally working on that file right now, so I can enable debugging on the production package.

A distinguished naming convention for development and production entry points would be nice.

On that note, there isn't a setting I'm missing to enable Chrome DevTools in production am I? We handle that ourselves in the menu.js file?

**Comment by amilajack** [comment]
Release `v0.11.1` adds support for debugging the production build. You can try it out by checking out the `dev-master` branch. Also I'm looking for testers of this branch. Would be great if you could test it out

**Comment by KamesCG** [comment]
I'll be sure to test it tomorrow. Anything specific I should try and break?

**Comment by amilajack** [comment]
Merged this into `v0.11.2`
