### ISSUE TITLE
OSX Renames the first menu item "Electron" no matter what is in menu.js

### ISSUE THREAD

**Issue by aphillipo** [chentsulin/electron-react-boilerplate#943]
For example, on OSX the Menu item is changed to 'My Application Name' as below the menu still says 'Electron'.

I've been searching for ages to find the answer and it's maybe something to do with an Info.plist file somewhere?  That's the best I've found!

```javascript
buildDarwinTemplate() {
    const subMenuAbout = {
      label: 'My Application Name',
      submenu: [
        { label: 'About ElectronReact', selector: 'orderFrontStandardAboutPanel:' },
        { type: 'separator' },
        { label: 'Services', submenu: [] },
        { type: 'separator' },
        { label: 'Hide ElectronReact', accelerator: 'Command+H', selector: 'hide:' },
        { label: 'Hide Others', accelerator: 'Command+Shift+H', selector: 'hideOtherApplications:' },
        { label: 'Show All', selector: 'unhideAllApplications:' },
        { type: 'separator' },
        { label: 'Quit', accelerator: 'Command+Q', click: () => { app.quit(); } }
      ]
    };
    ....
```

I'm probably missing something really obvious!

**Comment by aphillipo** [comment]
Actually the compiled version works perfectly so no worries about the dev version.  Please close; I will leave it open just in case you have anything to add here.

**Comment by cantino** [comment]
I ran into this as well. Might be worth noting in menu.js so it doesn't confuse the next person.
