### ISSUE TITLE
Refused to execute inline script because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#946]
Just upgraded to v0.11.1

![image](https://cloud.githubusercontent.com/assets/6835891/25317862/7df7e5bc-284f-11e7-92cc-e3d5e6c4b036.png)

I'm using Node version 7.7.3.

I tried adding 

```
 webPreferences: {
      zoomFactor: 1,
      allowRunningInsecureContent: true,
      nodeIntegration: true,
    }
```

to my Electron window options, but no difference. At least 2 of the errors are thrown Thoughts about what may cause this?

I had two additional errors from `ImmutableJS formatter` and `React Perf` tools extensions, but I disabled those. I am left with the above.

**Callstack:**
```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-7zh4+o3FkHE/wZ5mo01ZvE2qnuSyXVVAhGUGCIX+iW4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
1277								@	VM98 pagewrap.bundle.js:3
__webpack_require__	@	VM98 pagewrap.bundle.js:3
0										@	VM98 pagewrap.bundle.js:3
__webpack_require__	@	VM98 pagewrap.bundle.js:3
(anonymous)					@	VM98 pagewrap.bundle.js:3
(anonymous)					@	VM98 pagewrap.bundle.js:3
runContentScript		@	C:\Projects\Recollectr\node_modules\electron\dist\resources\electron.asar\renderer\content-scripts-…:23
onceWrapper					@	events.js:290
emitNone						@	events.js:91
emit								@	events.js:185
```

**Comment by amilajack** [comment]
This may have been caused by an incorrect merge. We no longer use express to serve content during development. Some files you may want to check are `./app/app.html` and `devServer` section of `webpack.config.renderer.dev.js`. Make sure that these are exactly the same as the boilerplate.

**Comment by Slapbox** [comment]
Will do thanks @amilajack. I  just added some additional (poorly formatted despite trying) info. I will report back soon.

**Comment by amilajack** [comment]
You also may want to look at this commit: https://github.com/chentsulin/electron-react-boilerplate/pull/941/commits/d9bb26c241b3125cfe3d1bf239708881691e4316

**Comment by Slapbox** [comment]
My `webpack.config.renderer.dev.js` has a huge number of differences, so I am sure that this is the source of my issues.

**Comment by amilajack** [comment]
You only have to pay attention to how the files are served. The `devServer` section should be the only thing you have to look at

**Comment by Slapbox** [comment]
It looks like the only difference I have is that my app.html has an additional div above the `<root>`:

`<div id="titlebar"></div>`

That couldn't be a problem, right?

After resolving the several differences in `webpack.config.renderer.dev.js` I unfortunately have the same error still.

**Comment by amilajack** [comment]
What does your `./app/routes.js` look like?

**Comment by Slapbox** [comment]
```
/* eslint flowtype-errors/show-errors: 0 */
import React from 'react';
import { HashRouter as Router } from 'react-router-dom';
import { Switch, Route } from 'react-router';
import App from './containers/App';
import myAppMain from './containers/myAppMain';

export default () => (
  <Router>
    <App>
      <Switch>
        <Route path="/" component={myAppMain} />
      </Switch>
    </App>
  </Router>
);
```

**Comment by amilajack** [comment]
What do your `app/main.development.js`, webpack renderer dev config, and app.html look like? (if you don't mind sharing. Would make debugging a lot easier)

**Comment by Slapbox** [comment]
In my `main.development.js` I was incorrectly still using:

```
const url = (process.env.NODE_ENV === 'development')
    ? `http://localhost:${process.env.PORT || 1212}/dist/app.html`
    : `file://${__dirname}/dist/app.html`;
  mainWindow.loadURL(url);
```

Thanks as always for all your help @amilajack

**Comment by b4dnewz** [comment]
@Slapbox how did you solved exactly? I'm using electron-vue but it has the same configuration:
```
const winURL = process.env.NODE_ENV === 'development'
  ? `http://localhost:9080`
  : `file://${__dirname}/index.html`
```
and I get the same error but I don't understand why

**Comment by Slapbox** [comment]
@b4dnewz Sorry it's been a long while and I don't recall the details of this issue. I'm pretty sure I just had to update/remove the incorrect code shown in my last comment.

Is your boilerplate code up to date? In both my working config and the master branch it looks like you no longer need to set the url that way an instead just use:

`  mainWindow.loadURL(`file://${__dirname}/app.html`);`

Are you having the exact same error messages I had? I really can't remember much, but I can try to help.

**Comment by b4dnewz** [comment]
@Slapbox I've ended by doing this:
```js
let authUrl = this.auth0.buildAuthorizeUrl(options)
let authWindow = new BrowserWindow({
      width: 800,
      height: 600,
      frame: true,
      resizable: false,
      autoHideMenuBar: true
})

authWindow.loadURL(authUrl)
authWindow.on('close', () => {
      authWindow = null
}, false)

// some code

authWindow.webContents.on('did-get-redirect-request', (event, oldUrl, url) => {
      let urlObject = URL.parse(url)
      let queryParams = qs.parse(urlObject.query)

      // Close new window instance
      if (queryParams.code || queryParams.error) {
        authWindow.destroy()
      }

      if (queryParams.code) {
        this.handleAuthorizationResponse(queryParams.code)
      }
})
```

which use another electron BrowserWindow (as popup) because I had troubles with the redirect from external browser to electron app

maybe is not the best solution but right now it's working and I can keep coding :)

**Comment by Slapbox** [comment]
As long as it works and doesn't affect user experience, it's all good.

You should see the workaround I had to implement for this one: https://github.com/chentsulin/electron-react-boilerplate/issues/850#issuecomment-294236663
