### ISSUE TITLE
some question with arcgis

### ISSUE THREAD

**Issue by Tanjh1996** [chentsulin/electron-react-boilerplate#948]
I clone your project 's config and use with React-ArcGIS , it has some errors shows that 'path muse be a string', I just use the simplest example of the arcgis. I feel  confused that it run the same react code  normally without electron but with error only in electron.

**Comment by KamesCG** [comment]
Are you getting "requirement can't be an expression error" from Webpack?

Can you post example code?

**Comment by Tanjh1996** [comment]
The arcgis api is AMD. 
I load the arcgis api 
```
import { dojoRequire } from 'esri-loader';
    dojoRequire(['esri/Map', 'esri/views/MapView'], (Map, MapView) => { 
      new MapView({
        container: this.mapContainer,
        map: new Map({basemap: 'topo'})
      })
    });
```
It has an error that "the path must be a string". I thnk that it may have a conflict between node's require and AMD's require.Because I use a project without electron it can run normally .So how can i use it normally with AMD's module.Can you give a example?Thanks.

**Comment by Tanjh1996** [comment]
argis-loader has fixerd this problem
