### ISSUE TITLE
background-image from resources

### ISSUE THREAD

**Issue by motakbiri** [chentsulin/electron-react-boilerplate#951]
Hi,
when I set background image in css for a section  from resources folder it is not appear. (it seems the renderer looking for it in dist folder, how I can add my images to dist folder or add to bundle?)

Thanks for your good boilerplate and Support :)

**Comment by amilajack** [comment]
The `resources` directory is actually intended to be more for build assets. I would recommend adding a `./app/img` folder. [See this project](https://github.com/amilajack/popcorn-time-desktop/tree/master/app/images) as an example.
