### ISSUE TITLE
Error when generating windows installer on mac os

### ISSUE THREAD

**Issue by erick2014** [chentsulin/electron-react-boilerplate#953]
NODE: v6.9.1
NPM: 3.10.8
yarn: 0.23.2
mac os: El Capitan

I got an error when I run: npm run package-win command, I have pulled the latest changes from the starter kit, both using npm and yarn.

<img src="http://i64.tinypic.com/2q3zxqg.png" border="0" alt="Image and video hosting by TinyPic">

I also tried to compile with node 6.10.2 version

**Comment by domierosina** [comment]
Are you running Wine? I have the same issue, it is telling me to install Wine, have not tried that solution yet. Packaged it on a Windows and it worked fine, just getting a blank home screen.

**Comment by erick2014** [comment]
Well it is kinda weird, what I did was to run these commands:

npm run build
./node_modules/.bin/build --win --x64

And it created the windows installer, but I discover that the problem was a react component within my app, so I have to comment that component, then I was able to create the build again running: 

npm run package-win

By the way, I also updated the starter kit to the latest version

**Comment by erick2014** [comment]
@domierosina yes I had to install wine in my machine to generate the installer for windows

**Comment by erick2014** [comment]
Well it is kinda weird, what I did was to run these commands:

npm run build
./node_modules/.bin/build --win --x64

And it created the windows installer, but I discover that the problem was a react component within my app, so I have to comment that component, then I was able to create the build again running: 

npm run package-win

By the way, I also updated the starter kit to the latest version

**Comment by amilajack** [comment]
@domierosina In `v0.11.1`, you can easily debug the production build with devtools using:

```
DEBUG_PROD=true npm run build
```

**Comment by erick2014** [comment]
O: @domierosina I didnt know that thx for sharing it :)

**Comment by amilajack** [comment]
@erick2014 did you resolve this?
