### ISSUE TITLE
How do I switch out flow for typescript?

### ISSUE THREAD

**Issue by pfftdammitchris** [chentsulin/electron-react-boilerplate#957]
I have tried to read tutorials on how to use typescript for electron and react, but they don't explain it in the context of electron-react-boilerplate because the files and codes are structured differently plus they don't show how to replace electron/react/flow with typescript--- only explains adding typescript to electron/react.

I followed this guide: https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

The order is use typescript -> babel -> webpack > bundle.js right?
Which entry point should typescript use to start transpiling? And what should I use for output (tsx-to-js) file to?

**Comment by amilajack** [comment]
In your `tsconig.json`, try adding `"externalTranspiler": "babel"`. Also see https://github.com/chentsulin/electron-react-boilerplate/issues/809. We don't have a guide yet. I'll probably create a fork of the boilerplate using typescript instead of flow

**Comment by amilajack** [comment]
Doing some work on that in [this repo](https://github.com/amilajack/erb-typescript-example)

**Comment by amilajack** [comment]
Will do this in https://github.com/chentsulin/electron-react-boilerplate/issues/968
