### ISSUE TITLE
PR: lint-styles-fix

### ISSUE THREAD

**Issue by digitronics** [chentsulin/electron-react-boilerplate#959]
Just an idea, but theres a `lint-fix` so I figured it might be a good idea to have a `lint-styles-fix`, been doing some digging and found [stylefmt](https://github.com/morishitter/stylefmt) that works pretty well.

`"lint-styles-fix": "stylefmt -r app/*.css app/components/*.css",`

**Comment by amilajack** [comment]
@digitronics would love if you could PR for this!
