### ISSUE TITLE
Windows package from electron cannot be found

### ISSUE THREAD

**Issue by Tanjh1996** [chentsulin/electron-react-boilerplate#961]
```
Downloading tmp-6752-0-electron-v1.6.6-win32-x64.zip
Error: connect ETIMEDOUT 54.231.48.240:443
Error: connect ETIMEDOUT 54.231.48.240:443
    at Object.exports._errnoException (util.js:1018:11)
```

i run npm run package ,it show this error. Is it my network problem?I try serval times but not solve the problem.But i have download the electron-v1.6.6-win32-x64.zip from the web separately.How can i use my electron-v1.6.6-win32-x64.zip to avoid this error？Thank you.

**Comment by amilajack** [comment]
This is most likely a network problem. Our tests are at 100% coverage and `npm run package` is one of the scripts

**Comment by amilajack** [comment]
Might have to do with this:

https://github.com/electron/electron/issues/9321

**Comment by Tanjh1996** [comment]
@amilajack  Thamks,but if i have download the electron-v1.6.6-win32-x64.zip from the web separately, can i have other methods to deal with it?

**Comment by amilajack** [comment]
@Tanjh1996 I dont think there's an easy way of doing that. You'll probably have to edit some of the source code of electron-builder. I'm not really sure. Haven't tried this before.

**Comment by Tanjh1996** [comment]
@chentsulin  妳好，我是中國大陸的壹名開發者。在npm run package的時候遇到了如下的問題。我想可能是大陸的網絡問題，我掛了vpn也同樣是這個問題。
```
Downloading tmp-6752-0-electron-v1.6.6-win32-x64.zip
Error: connect ETIMEDOUT 54.231.48.240:443
Error: connect ETIMEDOUT 54.231.48.240:443
    at Object.exports._errnoException (util.js:1018:11)
```
如果我單獨從網上下了這個這個包的話，有辦法解決這個打包的時候的網絡問題嗎

**Comment by chentsulin** [comment]
I don't have much time dive into the details, but it seems that there is an option could avoid downloading from the network. @Tanjh1996 Maybe you can try out.  

https://github.com/electron-userland/electron-builder/blob/8c79f605401a7f50726254dba68fc889f76afcde/packages/electron-builder/src/packager/dirPackager.ts#L48-L60

**Comment by Tanjh1996** [comment]
@chentsulin  Thanks.It is net's problem.I have solve this error when i change other vpn
