### ISSUE TITLE
BUG: Windows build fails on postinstall (node install.js)

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#964]
The error happens only on windows on the postinstall event of electron. It occurs when postinstall runs `node install.js`

This is actually an issue with electron and not with this boilerplate but I'm opening this to make it easier for others to find this issue. [Here's the issue in the electron repo](https://github.com/electron/electron/issues/9321).

**Comment by csprance** [comment]
Looks like they found a workaround here 

https://github.com/electron/electron/issues/9323#issuecomment-298205377

**Comment by amilajack** [comment]
Closing this because a solution was found in https://github.com/electron/electron/issues/9323#issuecomment-298287399
