### ISSUE TITLE
Cannot use typeface-roboto front (from npm)

### ISSUE THREAD

**Issue by rsaccon** [chentsulin/electron-react-boilerplate#966]
For a material-ui project I want to use roboto fonts. I am aware on how to hack the app.global.css for loading them from a CDN, but because this a electron app and not a website, it want to self-host them, with npm [typeface-roboto](https://www.npmjs.com/package/typeface-roboto), to be served from webpack. But it doesnt work. The following happens:

the error console outputs 404 errors such as:

`GET file:///Users/username/kelor-electron-react-boilerplate/app/0d7e71f2b5cc1ddab837f72e1fe52f3f.woff2 net::ERR_FILE_NOT_FOUND`

however the file exists, at a slightly different location:

`/Users/username/kelor-electron-react-boilerplate/app/dist/0d7e71f2b5cc1ddab837f72e1fe52f3f.woff2`

the relevant entry at dist/styles.css is:

`/* roboto-700normal - latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 700;
  src: url(../dist/128879da78c6c8eb4e2c07fa3732cea7.eot); /* IE9 Compat Modes */
  src:
    local('Roboto Bold '),
    local('Roboto-Bold'),
    url(../dist/128879da78c6c8eb4e2c07fa3732cea7.eot?#iefix) format('embedded-opentype'), 
    url(../dist/0d7e71f2b5cc1ddab837f72e1fe52f3f.woff2) format('woff2'), 
    url(../dist/525d5b452809b3172a2a34e26d9db546.woff) format('woff'), 
    url(../dist/7f57c4c0f3b44acbe338d7ff6d6ee5b1.svg#roboto) format('svg'); /* Legacy iOS */
}` 

Do I need to configure anything for webpack to make this work ? 

I npm uninstalled font-awesome, however I noticed, that webpack.config.renderer.dev.dll.js also contains some reference to font-awesome:
`...
entry: {
    vendor: [
      'babel-polyfill',
      ...Object.keys(dependencies)
    ]
    .filter(dependency => dependency !== 'font-awesome'),
  },
...`

I tried to replace `font-awesome` with `typeface-roboto`, but the errors continued.

Also it is not clear to me where font-awesome was imported (or how it is made to work with webpack), for `typeface-roboto` I just added to index.js:

`import 'typeface-roboto'; // eslint-disable-line`

**Comment by amilajack** [comment]
> I tried to replace font-awesome with typeface-roboto, but the errors continued.

Import typeface-roboto from any css file

**Comment by amilajack** [comment]
See this example https://github.com/chentsulin/electron-react-boilerplate#css-modules

**Comment by rsaccon** [comment]
Oh yes, that was it! Problem solved. @amilajack, thanks a lot. Just added to app.global.css:

`@import '~typeface-roboto';`

and changed in  [webpack.config.renderer.dev.dll.js#L166](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.dev.dll.js#L166) `font-awesome` to `typeface-roboto`

**Comment by mtompkins** [comment]
Can you advise how to update [webpack.config.renderer.dev.dll.js#L166](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.renderer.dev.dll.js#L166) if you don't want to remove `font-awesome`

**Comment by jackdh** [comment]
Hey @rsaccon I'm having the same issue as you are. I've attempted to add the import to app.global.css however it is still not working.

Also your link to webpack.config.renderer.dev.dll.js is no longer pointing to what I think it was originally?
