### ISSUE TITLE
Building on osx failed

### ISSUE THREAD

**Issue by motakbiri** [chentsulin/electron-react-boilerplate#967]
this is my log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rehyhoon-restaurant-app@0.0.1~prebuild: rehyhoon-restaurant-app@0.0.1
6 silly lifecycle rehyhoon-restaurant-app@0.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle rehyhoon-restaurant-app@0.0.1~build: rehyhoon-restaurant-app@0.0.1
8 verbose lifecycle rehyhoon-restaurant-app@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle rehyhoon-restaurant-app@0.0.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mohammadtakbiri/Workspace/Reyhoon/restaurant-app/node_modules/.bin:/Users/mohammadtakbiri/Applications/anaconda/bin:/Users/mohammadtakbiri/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mohammadtakbiri/Library/Android/sdk/platform-tools:/Users/mohammadtakbiri/Library/Android/sdk/tools
10 verbose lifecycle rehyhoon-restaurant-app@0.0.1~build: CWD: /Users/mohammadtakbiri/Workspace/Reyhoon/restaurant-app
11 silly lifecycle rehyhoon-restaurant-app@0.0.1~build: Args: [ '-c',
11 silly lifecycle   'concurrently "npm run build-main" "npm run build-renderer"' ]
12 silly lifecycle rehyhoon-restaurant-app@0.0.1~build: Returned: code: 1  signal: null
13 info lifecycle rehyhoon-restaurant-app@0.0.1~build: Failed to exec build script
14 verbose stack Error: rehyhoon-restaurant-app@0.0.1 build: `concurrently "npm run build-main" "npm run build-renderer"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid rehyhoon-restaurant-app@0.0.1
16 verbose cwd /Users/mohammadtakbiri/Workspace/Reyhoon/restaurant-app
17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error rehyhoon-restaurant-app@0.0.1 build: `concurrently "npm run build-main" "npm run build-renderer"`
23 error Exit status 1
24 error Failed at the rehyhoon-restaurant-app@0.0.1 build script 'concurrently "npm run build-main" "npm run build-renderer"'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the rehyhoon-restaurant-app package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     concurrently "npm run build-main" "npm run build-renderer"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs rehyhoon-restaurant-app
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls rehyhoon-restaurant-app
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by amilajack** [comment]
What were you trying to do? What cli command did you use? etc.

**Comment by motakbiri** [comment]
npm run build

**Comment by amilajack** [comment]
@motakbiri npm/yarn, node versions?

**Comment by motakbiri** [comment]
npm : 42.0 , node : 7.9.0

**Comment by Nomeasmo** [comment]
same problem here. BTW log shows the versions

**Comment by motakbiri** [comment]
yarn run buid result :
`17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "build-renderer"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error rehyhoon-restaurant-app@0.0.1 build-renderer: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors`
23 error Exit status 2
24 error Failed at the rehyhoon-restaurant-app@0.0.1 build-renderer script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the rehyhoon-restaurant-app package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs rehyhoon-restaurant-app
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls rehyhoon-restaurant-app
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]`

**Comment by amilajack** [comment]
Try running `npm run build-main` and `npm run build-renderer` separately and tell me the output of which one fails

**Comment by motakbiri** [comment]
`npm run build-renderer` failed and output attached,
[2017-05-01T17_46_52_995Z-debug.txt](https://github.com/chentsulin/electron-react-boilerplate/files/968389/2017-05-01T17_46_52_995Z-debug.txt)

**Comment by erick2014** [comment]
@motakbiri  I'm not sure if this helps but I'm using node v6.9.1 and npm 3.10.8, mac os capitan and I am able to run the  `npm run build` command, with out errors, also be aware to check your react components, I had a similar error I found that I was declaring a component in this way:

```
import React from 'react';
export default class myDialog extends React.Component 
```

then I have to change that to :

```
import React, { Component } from 'react';
export default class myDialog extends Component 
```
After that I was able to compile with out errors, hope this helps!!

**Comment by crakjie** [comment]
I still have this probleme even when all my `import React from 'react';` was changed to `import React, { Component } from 'react';`

**Comment by amilajack** [comment]
@crakjie interesting. What does your `babelrc` look like?

**Comment by crakjie** [comment]
I found the error, I'm not able to correct this but it seems the `import ffbinaries from 'ffbinaries'` make some mess with electron-builder. The shown error is the same as above but not sure the cose is the same.

**Comment by amilajack** [comment]
@crakjie how did you fix it?

**Comment by crakjie** [comment]
@amilajack As I said I was not able to resolve this except by removing the import.
I think there maybe things in external dependencies that don't work with webpacking.
And which make the above stack trace when calling the builder-render cmd.
