### ISSUE TITLE
DOCS: Add documentation guides

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#968]
List of guides to write:

- [ ] Provide migration path to typescript
- [ ] Removing flow
- [ ] Removing redux
- [ ] Integrating electron-redux
- [ ] [Integration](https://github.com/dherman/neon-electron-hello) [with rust](https://github.com/dherman/electron-build-env)

**Comment by aendrew** [comment]
Considering it seems this issue has stalled a bit, some suggestions:

* I use both Flow and TS a lot and I can't really see a clear migration path; I'd recommend somebody forking it for TypeScript and then that being linked in the README.
* I might be willing to do the "removing Flow" guide, it's not too involved.
* If you want to remove Redux, I'd simply recommend people use a different boilerplate. Part of the benefit of using this specific boilerplate is its deep Redux integration. 
* Honestly the integration with electron-redux guide is the most crucial. I've written a fair bit of Electron, React _and_ Redux, and I'm honestly not at all sure how to integrate electron-redux given the particular build style of this boilerplate looks quite a lot different from electron-redux's provided example app.
* I don't have the faintest clue how or why you'd integrate with Rust so I won't comment on the last point.

Just my two.
