### ISSUE TITLE
flow-typed script breaks Windows support

### ISSUE THREAD

**Issue by klofi** [chentsulin/electron-react-boilerplate#973]
`"flow-typed": "rm -rf flow-typed/npm && flow-typed install --overwrite || true",`
The rm -rf command does not exist on Windows, this script breaks boilerplate on Windows when executing npm install. Can be replaced with https://www.npmjs.com/package/rimraf package like this:

`"flow-typed": "rimraf flow-typed/npm && flow-typed install --overwrite || true",`

**Comment by talha131** [comment]
Alternatively, user can install Git for Windows (which he would need for cloning this boilerplate) that adds `rm` to the path.

**Comment by klofi** [comment]
Git for Windows did not  add `rm` to path for me (Command Prompt). I can use it in Git Bash and PowerShell though. The rimraf package should work in anyone's environment...

**Comment by amilajack** [comment]
@kubijo Not sure why I didn't fix this earlier. Just made a PR for this. Thanks!
