### ISSUE TITLE
Required module not found 

### ISSUE THREAD

**Issue by nodkrot** [chentsulin/electron-react-boilerplate#981]
Im getting this linting error after I install `material-ui` and import it in the component.

**Comment by amilajack** [comment]
Dont have enough info to help you. Please provide stack trace. How are you installing it?

**Comment by anthonyraymond** [comment]
Yep, we need some more information.

Show your **two** `packages.json`, and how did you install those package (yarn or npm).

**Comment by nodkrot** [comment]
I just ran `npm install material-ui -S` in project root. so it added the package to top most packages.json. Dont have the project currently
