### ISSUE TITLE
How to remove css-modules ?

### ISSUE THREAD

**Issue by sovanjana** [chentsulin/electron-react-boilerplate#984]
Basically I want to use normal CSS stylesheets with bootstrap for my project  but i'm not able to use custom styles and bootstrap at the same time means i 'm not able to use more than one className in a single place like `<div className="row custom-style"></div>`. Either help me how to use both at same time or please help me to get rid of css-modules.

**Comment by amilajack** [comment]
Import bootstrap and your custom styles from the `app.global.css`, similar to how font awesome is

**Comment by amilajack** [comment]
I also just made [another repo](https://github.com/amilajack/erb-bootstrap-example) specifically for exemplifying using sass and bootstrap. You should definitely check that out. See [this commit](https://github.com/amilajack/erb-bootstrap-example/commit/d44f0ef3496c41dae0b02586ec2157a963edc71a) to see all the useful changes.
