### ISSUE TITLE
asarUnpack ignored?

### ISSUE THREAD

**Issue by mtompkins** [chentsulin/electron-react-boilerplate#989]
Hi - looking at the boilerplate once more and had a question / possible issue:

Understanding that it is desired to have the inner `package.json` handle modules that would be treated as external dependencies, I've come across what is perhaps an edge case...

With [node-notifier](https://github.com/mikaelbr/node-notifier), to use the module with `electron-builder` it is required (for Windows):
- Extract `SnoreToast.exe` because you can't execute exe's in an asar package
- Set
```  
node: {
  __filename: true,
  __dirname: true
}
```
`node-notifier` needs the mappings to be OS agnostic and that is an issue with the structure (at least in my testing). When adding `node-notifier` to the inner `package.json` the directory is correct extracted but the links fail as expected.

When moving `node-notifier` to the outer `package.json` and trying to leverage `asarUnpack` nothing is extracted. More test seem to show that `asarUnpack` is in fact ignored in totality?

To reproduce, you should be able to clone the default boilerplate, add an `asarUnpack` to any node_module and you should see nothing unpacked from the asar (unless of course I'm missing something).

**Comment by amilajack** [comment]
I'll test this out in the coming week.

**Comment by amilajack** [comment]
@mtompkins did you resolve this?

**Comment by mtompkins** [comment]
Hi @amilajack ... I was not able to resolve this, I was not able to successfully use asarUnpack.

**Comment by Cherviakov** [comment]
asarUnpack is certainly not ignored, manually added two .jar files and they start to appear in asar.app.unpacked/node_modules

**Comment by aj-ptw** [comment]
I'm having trouble with it too

**Comment by yourfavorite** [comment]
Was there ever a solution for using node-notifier with this boilerplate? I tried setting __dirname and __filename to true as mentioned in the node-notifier docs for webpack usage but that of course breaks all kinds of other things in the app. Hoping for a solution that works for both Windows and Mac.

**Comment by Yutiy** [comment]
I'm having trouble with it too，How to deal with it？

**Comment by Lilleri** [comment]
there is still the issue at the moment

**Comment by ytlma** [comment]
there is still the issue at the moment
