### ISSUE TITLE
importing minimized js does not work in production environment

### ISSUE THREAD

**Issue by wangyueming** [chentsulin/electron-react-boilerplate#991]
I use canvas.js. It is not a npm module, I put it under app directory and import it with code below:
`  require('../../third/canvasjs/canvasjs.min');
`

But some functions like zooming do not work in production environment.

I fixed it as a work around by importing canvasjs in the way below

```
if (process.env.NODE_ENV === 'development') {
  require('../../third/canvasjs/canvasjs.min');
} else {
  require('../../third/canvasjs/canvasjs');
}

```

I don't why this issue happens when the webpack makes bundle with canvasjs.min.js, while it is okay canvasjs.js.

**Comment by amilajack** [comment]
Try using webpack's entry points.
