### ISSUE TITLE
Jest .only not working

### ISSUE THREAD

**Issue by tbarho** [chentsulin/electron-react-boilerplate#992]
I can't seem to get `.only` working in describe or it blocks on the latest version... anyone else having this problem?

**Comment by amilajack** [comment]
How is it not working? Does it seem to be ignoring the `.only` tests?

**Comment by tbarho** [comment]
It runs all the tests in the suite no matter what.  The only way I can isolate tests is using `./node_modules/.bin/jest "[suite]"`

**Comment by armand1m** [comment]
having this same issue :/ is just runs like there is no `.only` in any part of your tests.

**Comment by pkearney13** [comment]
Same here issue here.

**Comment by FuzzySockets** [comment]
I'm having the same issue.

**Comment by xtrembaker** [comment]
+1

**Comment by ericpoon** [comment]
+1

**Comment by julestruong** [comment]
still nothing ? @tbarho

**Comment by OlegLindvin** [comment]
Seeing as you are using Jest its an intended behaviour since it runs tests in parallel. 
You can read more about this https://github.com/facebook/jest/issues/4414.
