### ISSUE TITLE
Instructions for generating icons

### ISSUE THREAD

**Issue by Ahrengot** [chentsulin/electron-react-boilerplate#993]
Hey there,

This starter has been a great help for the last electron app I've built, and the docs have been very helpful except in one area: How do I manage and create all the different icon sizes? Is that a manual process? I was looking at https://github.com/chentsulin/electron-react-boilerplate/issues/407 and it seems there used to be some commands to do this, but I don't see any of them in package.json today.

A paragraph or two in the readme about the various icons, the file formats (.png vs. .ico vs. .icns) would be really helpful.

**Comment by mtompkins** [comment]
I struggled with this myself, so I'll share what finally worked for me. Do note that there may be some unneeded duplication of files but I haven't had an opportunity to "refactor" and confirm what I can remove.

Also what caused me significant grief was caching on windows. Even after properly configuring everything Windows 8.1 continued to show the default Electron icon "for a while". I'm unsure what finally allowed it to render correctly. 

With that all out of the way:

Online tool for creating assets: https://iconverticons.com/online/

Windows has a requirement of the image being at least 512x512 if I recall.
I used a multimage file for that OS.

`package.json`

    ...
    "win": {
      "icon": "app/assets/icons/win/icon.ico",
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "installerIcon": "icon.ico",
      "installerHeaderIcon": "icon.ico",
      "deleteAppDataOnUninstall": true
    },
    "linux": {
      "icon": "app/assets/icons/png",
      "target": [
        "deb",
        "AppImage"
      ]
    },
    ...
`main.dev.js`

    ...
    const seticons = (process.platform === 'linux') ? './assets/icons/logo.png' : './assets/icons/logo.ico';
    ...
    mainWindow = new BrowserWindow({
        ...
        icon: path.join(__dirname, seticons),
        ...
     });

![screenshot from 2017-05-17 17-40-08](https://cloud.githubusercontent.com/assets/4105910/26177556/0b473dce-3b28-11e7-817d-202a14852259.png)

HTH

**Comment by amilajack** [comment]
@Ahrengot did you resolve this?

**Comment by GarkGarcia** [comment]
Hey, I'd like to know how could I set the icon of my windows application if it has no `BrowserWindow`s. For example, I have a very simple app which only involves a dialog box:

```js
const exec = require('child_process').exec,
      electron = require('electron'),
      {app, dialog} = electron,

app.on('ready', () => {
        dialog.showOpenDialog(
            {
                title: 'Select a directory',
                defaultPath: process.cwd(),
                buttonLabel: 'Select',
                properties: ['openDirectory']
            }, (responce) => {
                if (responce != undefined && responce[0] != process.cwd()) {
                    process.stdout.write(responce[0]);
                    app.quit();
                } else {
                    process.stdout.write('false');
                    app.quit();
                }
            }
        );
});
```
How could I change the taskbar's icon of such app?

**Comment by pavlobu** [comment]
this script helped me to generate .icns from on source 1024x1024 png image:

https://github.com/jamf/icns-Creator
