### ISSUE TITLE
IDEA: Post-clone welcome script

### ISSUE THREAD

**Issue by amilajack** [chentsulin/electron-react-boilerplate#999]
Would be nice if we could have some kind of script that could welcome the user and help them get set up after cloning the project.

**Comment by erick2014** [comment]
@amilajack like a command line script? to set up your files in the structure?

**Comment by amilajack** [comment]
It's just a simple script saying how to use the project (how to install, setup, etc)

**Comment by erick2014** [comment]
@amilajack but the script is going to be triggered from the command line, or from the web app?

**Comment by amilajack** [comment]
From the command line
